LIEF: Library to Instrument Executable Formats: LIEF::dwarf::types::Typedef Class Reference
LIEF::dwarf::types::Typedef Class Reference
This class represents a DW_TAG_typedef type.
#include <Typedef.hpp>
Public Member Functions
template<typename... Args, typename = typename std:: enable_if<std::is_constructible<Type, Args&&...>::value>::type>
Typedef (Args &&... args)
Typedef (const Typedef &)=delete
Typedef & operator= (const Typedef &)=delete
Typedef (Typedef &&) noexcept=default
Typedef & operator= (Typedef &&) noexcept=default
const Type * underlying_type () const
The type aliased by this typedef.
const Type * operator-> () const
const Type & operator* () const
~Typedef () override
Public Member Functions inherited from LIEF::dwarf::Type
Type (std::unique_ptr< details::Type > impl)
Type (details::Type &impl)
Type (const Type &)=delete
Type & operator= (const Type &)=delete
Type (Type &&) noexcept
Type & operator= (Type &&) noexcept
virtual ~Type ()
KIND kind () const
bool is_unspecified () const
Whether this type is a DW_TAG_unspecified_type.
result< std::string > name () const
Return the type's name using either DW_AT_name or DW_AT_picture_string (if any).
result< uint64_t > size () const
Return the size of the type or an error if it can't be computed.
debug_location_t location () const
Return the debug location where this type is defined.
std::unique_ptr< Scope > scope () const
Return the scope in which this type is defined.
std::string to_decl (const DeclOpt &opt=DeclOpt()) const
Generates a C/C++ definition for this type.
template<class T>
const T * as () const
Static Public Member Functions
static bool classof (const Type *type)
Static Public Member Functions inherited from LIEF::dwarf::Type
static std::unique_ptr< Type > create (std::unique_ptr< details::Type > impl)
Additional Inherited Members
Public Types inherited from LIEF::dwarf::Type
enum class KIND {
UNKNOWN = 0 , UNSPECIFIED , BASE , CONST_KIND ,
CLASS , ARRAY , POINTER , STRUCT ,
UNION , TYPEDEF , REF , SET_TYPE ,
STRING , SUBROUTINE , POINTER_MEMBER , PACKED ,
FILE , THROWN , VOLATILE , RESTRICT ,
INTERFACE , SHARED , RVALREF , TEMPLATE_ALIAS ,
COARRAY , DYNAMIC , ATOMIC , IMMUTABLE ,
ENUM
}
Detailed Description
This class represents a DW_TAG_typedef type.
Constructor & Destructor Documentation
Typedef() [1/3]
template<typename... Args, typename = typename std:: enable_if<std::is_constructible<Type, Args&&...>::value>::type> LIEF::dwarf::types::Typedef::Typedef (Args &&... args) inline
References LIEF::dwarf::Type::Type().
Referenced by operator=(), operator=(), Typedef(), and Typedef().
Typedef() [2/3]
LIEF::dwarf::types::Typedef::Typedef (const Typedef &) delete
References Typedef().
Typedef() [3/3]
LIEF::dwarf::types::Typedef::Typedef (Typedef &&) default noexcept
References Typedef().
~Typedef()
LIEF::dwarf::types::Typedef::~Typedef () override
Member Function Documentation
classof()
bool LIEF::dwarf::types::Typedef::classof (const Type * type) inline static
References LIEF::dwarf::Type::kind(), LIEF::dwarf::Type::Type(), and LIEF::dwarf::Type::TYPEDEF.
operator*()
const Type & LIEF::dwarf::types::Typedef::operator* () const inline
References LIEF_LIFETIMEBOUND, LIEF::dwarf::Type::Type(), and underlying_type().
operator->()
const Type * LIEF::dwarf::types::Typedef::operator-> () const inline
References LIEF_LIFETIMEBOUND, LIEF::dwarf::Type::Type(), and underlying_type().
operator=() [1/2]
Typedef & LIEF::dwarf::types::Typedef::operator= (const Typedef &) delete
References Typedef().
operator=() [2/2]
Typedef & LIEF::dwarf::types::Typedef::operator= (Typedef &&) default noexcept
References Typedef().
underlying_type()
const Type * LIEF::dwarf::types::Typedef::underlying_type () const
The type aliased by this typedef.
References LIEF_LIFETIMEBOUND, LIEF::dwarf::Type::Type(), and underlying_type().
Referenced by operator*(), operator->(), and underlying_type().
The documentation for this class was generated from the following file:
Typedef.hpp