LIEF: Library to Instrument Executable Formats: LIEF::COFF::Parser Class Reference
LIEF::COFF::Parser Class Reference
#include <Parser.hpp>
Public Types
using SymSecMap = std::vector<SymSec>
<=> std::unordered_multimap<section index, Symbol*>
Public Member Functions
~Parser ()
Static Public Member Functions
static std::unique_ptr< Binary > parse (std::unique_ptr< BinaryStream > stream, const ParserConfig &config=ParserConfig::default_conf())
Parse the COFF binary referenced by the stream argument with the given config.
static std::unique_ptr< Binary > parse (const std::string &file, const ParserConfig &config=ParserConfig::default_conf())
Parse the COFF binary pointed by the file argument with the given config.
Member Typedef Documentation
SymSecMap
using LIEF::COFF::Parser::SymSecMap = std::vector<SymSec>
<=> std::unordered_multimap<section index, Symbol*>
Constructor & Destructor Documentation
~Parser()
LIEF::COFF::Parser::~Parser ()
Member Function Documentation
parse() [1/2]
std::unique_ptr< Binary > LIEF::COFF::Parser::parse (const std::string & file, const ParserConfig & config = ParserConfig::default_conf()) inline static
Parse the COFF binary pointed by the file argument with the given config.
References LIEF::COFF::ParserConfig::default_conf(), LIEF::VectorStream::from_file(), and parse().
parse() [2/2]
std::unique_ptr< Binary > LIEF::COFF::Parser::parse (std::unique_ptr< BinaryStream > stream, const ParserConfig & config = ParserConfig::default_conf()) static
Parse the COFF binary referenced by the stream argument with the given config.
References LIEF::COFF::ParserConfig::default_conf().
Referenced by parse().
The documentation for this class was generated from the following file:
COFF/Parser.hpp