LIEF: Library to Instrument Executable Formats: LIEF::VectorStream Class Reference
LIEF::VectorStream Class Reference
#include <VectorStream.hpp>
Public Member Functions
VectorStream (std::vector< uint8_t > data)
VectorStream ()=delete
VectorStream (const VectorStream &)=delete
VectorStream & operator= (const VectorStream &)=delete
VectorStream (VectorStream &&other) noexcept=default
VectorStream & operator= (VectorStream &&other) noexcept=default
uint64_t size () const override
const std::vector< uint8_t > & content () const
std::vector< uint8_t > && move_content ()
const uint8_t * p () const override
const uint8_t * start () const override
const uint8_t * end () const override
std::unique_ptr< SpanStream > slice (uint32_t offset, size_t size) const
std::unique_ptr< SpanStream > slice (uint32_t offset) const
virtual uint8_t * p ()
virtual uint8_t * end ()
virtual uint8_t * start ()
Public Member Functions inherited from LIEF::BinaryStream
BinaryStream (STREAM_TYPE type)
virtual ~BinaryStream ()=default
STREAM_TYPE type () const
result< uint64_t > read_uleb128 (size_t *size=nullptr) const
result< uint64_t > read_sleb128 (size_t *size=nullptr) const
result< int64_t > read_dwarf_encoded (uint8_t encoding) const
result< std::string > read_string (size_t maxsize=~static_cast< size_t >(0)) const
result< std::string > peek_string (size_t maxsize=~static_cast< size_t >(0)) const
result< std::string > peek_string_at (size_t offset, size_t maxsize=~static_cast< size_t >(0)) const
result< std::u16string > read_u16string () const
result< std::u16string > peek_u16string () const
result< std::string > read_mutf8 (size_t maxsize=~static_cast< size_t >(0)) const
result< std::u16string > read_u16string (size_t length) const
result< std::u16string > peek_u16string (size_t length) const
result< std::u16string > peek_u16string_at (size_t offset, size_t length) const
virtual ok_error_t peek_data (std::vector< uint8_t > &container, uint64_t offset, uint64_t size, uint64_t virtual_address=0)
virtual ok_error_t read_data (std::vector< uint8_t > &container, uint64_t size)
ok_error_t read_data (std::vector< uint8_t > &container)
template<class T>
ok_error_t read_objects (std::vector< T > &container, uint64_t count)
template<class T>
ok_error_t peek_objects (std::vector< T > &container, uint64_t count)
template<class T>
ok_error_t peek_objects_at (uint64_t offset, std::vector< T > &container, uint64_t count)
void setpos (size_t pos) const
const BinaryStream & increment_pos (size_t value) const
void decrement_pos (size_t value) const
size_t pos () const
operator bool () const
template<class T>
const T * read_array (size_t size) const
template<class T, size_t N>
ok_error_t peek_array (std::array< T, N > &dst) const
template<class T, size_t N>
ok_error_t read_array (std::array< T, N > &dst) const
template<class T>
result< T > peek () const
template<class T>
result< T > peek (size_t offset) const
template<class T>
const T * peek_array (size_t size) const
template<class T>
const T * peek_array (size_t offset, size_t size) const
template<class T>
result< T > read () const
template<typename T>
bool can_read () const
template<typename T>
bool can_read (size_t offset) const
bool can_read (int64_t offset, int64_t size) const
size_t align (size_t align_on) const
void set_endian_swap (bool swap)
bool should_swap () const
virtual ok_error_t peek_in (void *dst, uint64_t offset, uint64_t size, uint64_t virtual_address=0) const
Static Public Member Functions
static result< VectorStream > from_file (const std::string &file)
static bool classof (const BinaryStream &stream)
Static Public Member Functions inherited from LIEF::BinaryStream
template<class T>
static bool is_all_zero (const T &buffer)
Additional Inherited Members
Public Types inherited from LIEF::BinaryStream
enum class STREAM_TYPE {
UNKNOWN = 0 , VECTOR , MEMORY , SPAN ,
FILE , ELF_DATA_HANDLER
}
Constructor & Destructor Documentation
VectorStream() [1/4]
LIEF::VectorStream::VectorStream (std::vector< uint8_t > data) inline
References LIEF::BinaryStream::BinaryStream(), and size().
Referenced by operator=(), operator=(), VectorStream(), and VectorStream().
VectorStream() [2/4]
LIEF::VectorStream::VectorStream () delete
VectorStream() [3/4]
LIEF::VectorStream::VectorStream (const VectorStream &) delete
References VectorStream().
VectorStream() [4/4]
LIEF::VectorStream::VectorStream (VectorStream && other) default noexcept
References VectorStream().
Member Function Documentation
classof()
bool LIEF::VectorStream::classof (const BinaryStream & stream) inline static
References LIEF::BinaryStream::BinaryStream(), LIEF::BinaryStream::type(), and LIEF::BinaryStream::VECTOR.
content()
const std::vector< uint8_t > & LIEF::VectorStream::content () const inline
end() [1/2]
virtual uint8_t * LIEF::BinaryStream::end () inline virtual
Reimplemented from LIEF::BinaryStream.
end() [2/2]
const uint8_t * LIEF::VectorStream::end () const inline override virtual
Reimplemented from LIEF::BinaryStream.
from_file()
result< VectorStream > LIEF::VectorStream::from_file (const std::string & file) static
Referenced by LIEF::COFF::Parser::parse().
move_content()
std::vector< uint8_t > && LIEF::VectorStream::move_content () inline
operator=() [1/2]
VectorStream & LIEF::VectorStream::operator= (const VectorStream &) delete
References VectorStream().
operator=() [2/2]
VectorStream & LIEF::VectorStream::operator= (VectorStream && other) default noexcept
References VectorStream().
p() [1/2]
virtual uint8_t * LIEF::BinaryStream::p () inline virtual
Reimplemented from LIEF::BinaryStream.
p() [2/2]
const uint8_t * LIEF::VectorStream::p () const inline override virtual
Reimplemented from LIEF::BinaryStream.
References LIEF::BinaryStream::pos().
size()
uint64_t LIEF::VectorStream::size () const inline override virtual
Implements LIEF::BinaryStream.
Referenced by slice(), and VectorStream().
slice() [1/2]
std::unique_ptr< SpanStream > LIEF::VectorStream::slice (uint32_t offset) const
slice() [2/2]
std::unique_ptr< SpanStream > LIEF::VectorStream::slice (uint32_t offset, size_t size) const
References size().
start() [1/2]
virtual uint8_t * LIEF::BinaryStream::start () inline virtual
Reimplemented from LIEF::BinaryStream.
start() [2/2]
const uint8_t * LIEF::VectorStream::start () const inline override virtual
Reimplemented from LIEF::BinaryStream.
The documentation for this class was generated from the following file:
VectorStream.hpp