LIEF: Library to Instrument Executable Formats: LIEF::PE::DynamicRelocationV2 Class Reference
LIEF::PE::DynamicRelocationV2 Class Reference
This class represents a dynamic relocation (IMAGE_DYNAMIC_RELOCATION64_V2 or IMAGE_DYNAMIC_RELOCATION32_V2).
#include <DynamicRelocationV2.hpp>
Public Member Functions
DynamicRelocationV2 ()
DynamicRelocationV2 (const DynamicRelocationV2 &)=default
DynamicRelocationV2 & operator= (const DynamicRelocationV2 &)=default
DynamicRelocationV2 (DynamicRelocationV2 &&)=default
DynamicRelocationV2 & operator= (DynamicRelocationV2 &&)=default
std::unique_ptr< DynamicRelocation > clone () const override
std::string to_string () const override
~DynamicRelocationV2 () override=default
Public Member Functions inherited from LIEF::PE::DynamicRelocation
DynamicRelocation ()=delete
DynamicRelocation (uint32_t version)
DynamicRelocation (const DynamicRelocation &)
DynamicRelocation & operator= (const DynamicRelocation &)
DynamicRelocation (DynamicRelocation &&)
DynamicRelocation & operator= (DynamicRelocation &&)
uint32_t version () const
Version of the structure.
uint64_t symbol () const
Symbol address. Some values have a special meaning (c.f. IMAGE_DYNAMIC_RELOCATION) and define how fixups are encoded.
const DynamicFixup * fixups () const
DynamicFixup * fixups ()
Return fixups information, where the interpretation may depend on the symbol's value.
DynamicRelocation & symbol (uint64_t value)
DynamicRelocation & fixups (std::unique_ptr< DynamicFixup > F)
template<class T>
T * as ()
template<class T>
const T * as () const
virtual ~DynamicRelocation ()
Static Public Member Functions
static bool classof (const DynamicRelocation *reloc)
Additional Inherited Members
Public Types inherited from LIEF::PE::DynamicRelocation
enum IMAGE_DYNAMIC_RELOCATION {
RELOCATION_GUARD_RF_PROLOGUE = 1 , RELOCATION_GUARD_RF_EPILOGUE = 2 , RELOCATION_GUARD_IMPORT_CONTROL_TRANSFER = 3 , RELOCATION_GUARD_INDIR_CONTROL_TRANSFER = 4 ,
RELOCATION_GUARD_SWITCHTABLE_BRANCH = 5 , RELOCATION_ARM64X = 6 , RELOCATION_FUNCTION_OVERRIDE = 7 , RELOCATION_ARM64_KERNEL_IMPORT_CALL_TRANSFER = 8 ,
_RELOC_LAST_ENTRY
}
Special symbol values as defined in link.exe - GetDVRTSpecialSymbolName.
Detailed Description
This class represents a dynamic relocation (IMAGE_DYNAMIC_RELOCATION64_V2 or IMAGE_DYNAMIC_RELOCATION32_V2).
Constructor & Destructor Documentation
DynamicRelocationV2() [1/3]
LIEF::PE::DynamicRelocationV2::DynamicRelocationV2 () inline
References LIEF::PE::DynamicRelocation::DynamicRelocation().
Referenced by clone(), DynamicRelocationV2(), DynamicRelocationV2(), operator=(), and operator=().
DynamicRelocationV2() [2/3]
LIEF::PE::DynamicRelocationV2::DynamicRelocationV2 (const DynamicRelocationV2 &) default
References DynamicRelocationV2().
DynamicRelocationV2() [3/3]
LIEF::PE::DynamicRelocationV2::DynamicRelocationV2 (DynamicRelocationV2 &&) default
References DynamicRelocationV2().
~DynamicRelocationV2()
LIEF::PE::DynamicRelocationV2::~DynamicRelocationV2 () override default
References LIEF_LOCAL.
Member Function Documentation
classof()
bool LIEF::PE::DynamicRelocationV2::classof (const DynamicRelocation * reloc) inline static
References LIEF::PE::DynamicRelocation::DynamicRelocation(), and LIEF::PE::DynamicRelocation::version().
clone()
std::unique_ptr< DynamicRelocation > LIEF::PE::DynamicRelocationV2::clone () const inline override virtual
Implements LIEF::PE::DynamicRelocation.
References DynamicRelocationV2().
operator=() [1/2]
DynamicRelocationV2 & LIEF::PE::DynamicRelocationV2::operator= (const DynamicRelocationV2 &) default
References DynamicRelocationV2().
operator=() [2/2]
DynamicRelocationV2 & LIEF::PE::DynamicRelocationV2::operator= (DynamicRelocationV2 &&) default
References DynamicRelocationV2().
to_string()
std::string LIEF::PE::DynamicRelocationV2::to_string () const override virtual
Implements LIEF::PE::DynamicRelocation.
The documentation for this class was generated from the following file:
DynamicRelocationV2.hpp