LIEF: Library to Instrument Executable Formats: LIEF::PE::unwind_x64::Spare Class Reference
LIEF::PE::unwind_x64::Spare Class Reference
#include <UnwindCodeX64.hpp>
Public Member Functions
Spare ()
std::string to_string () const override
Pretty representation.
~Spare () override=default
Public Member Functions inherited from LIEF::PE::unwind_x64::Code
Code ()=delete
Code (const Code &)=default
Code & operator= (const Code &)=default
Code (Code &&)=default
Code & operator= (Code &&)=default
virtual ~Code ()=default
Code (OPCODE opcode, uint32_t pos)
Code (OPCODE opcode)
OPCODE opcode () const
The original opcode.
uint32_t position () const
Offset in the prolog.
Static Public Member Functions
static bool classof (const Code *code)
Additional Inherited Members
Public Types inherited from LIEF::PE::unwind_x64::Code
using OPCODE = RuntimeFunctionX64::UNWIND_OPCODES
using REG = RuntimeFunctionX64::UNWIND_REG
Constructor & Destructor Documentation
Spare()
LIEF::PE::unwind_x64::Spare::Spare () inline
References LIEF::PE::unwind_x64::Code::Code().
~Spare()
LIEF::PE::unwind_x64::Spare::~Spare () override default
Member Function Documentation
classof()
bool LIEF::PE::unwind_x64::Spare::classof (const Code * code) inline static
References LIEF::PE::unwind_x64::Code::Code(), and LIEF::PE::unwind_x64::Code::opcode().
to_string()
std::string LIEF::PE::unwind_x64::Spare::to_string () const inline override virtual
Pretty representation.
Reimplemented from LIEF::PE::unwind_x64::Code.
The documentation for this class was generated from the following file:
UnwindCodeX64.hpp