LIEF: Library to Instrument Executable Formats: LIEF::runtime::Module::Iterator Class Reference
LIEF::runtime::Module::Iterator Class Reference final
#include <Module.hpp>
Public Types
using implementation = details::ModuleIt
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, Module, std::ptrdiff_t, const Module *, const Module & >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Public Member Functions
Iterator ()
Iterator (const Iterator &)
Iterator & operator= (const Iterator &)
Iterator (Iterator &&) noexcept
Iterator & operator= (Iterator &&) noexcept
Iterator (std::unique_ptr< details::ModuleIt > impl)
~Iterator ()
Iterator & operator++ ()
const Module & operator* () const
const Module * operator-> () const
std::unique_ptr< Module > yield ()
Transfer ownership of the module at the current position to the caller. Returns nullptr if the iterator is past-the-end.
DerivedT operator++ (int)
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, Module, std::ptrdiff_t, const Module *, const Module & >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Member Typedef Documentation
implementation
using LIEF::runtime::Module::Iterator::implementation = details::ModuleIt
Constructor & Destructor Documentation
Iterator() [1/4]
LIEF::runtime::Module::Iterator::Iterator ()
References LIEF_API.
Referenced by Iterator(), Iterator(), Iterator(), operator!=, operator++(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/4]
LIEF::runtime::Module::Iterator::Iterator (const Iterator &)
References Iterator(), and LIEF_API.
Iterator() [3/4]
LIEF::runtime::Module::Iterator::Iterator (Iterator &&) noexcept
References Iterator(), and LIEF_API.
Iterator() [4/4]
LIEF::runtime::Module::Iterator::Iterator (std::unique_ptr< details::ModuleIt > impl)
References Iterator(), and LIEF_API.
~Iterator()
LIEF::runtime::Module::Iterator::~Iterator ()
References Iterator(), and LIEF_API.
Member Function Documentation
operator*()
const Module & LIEF::runtime::Module::Iterator::operator* () const
References LIEF_API, LIEF_LIFETIMEBOUND, and LIEF::runtime::Module::Module().
operator++() [1/2]
Iterator & LIEF::runtime::Module::Iterator::operator++ ()
References Iterator(), and LIEF_API.
operator++() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator++ (int) inline
operator->()
const Module * LIEF::runtime::Module::Iterator::operator-> () const
References LIEF_API, LIEF_LIFETIMEBOUND, and LIEF::runtime::Module::Module().
operator=() [1/2]
Iterator & LIEF::runtime::Module::Iterator::operator= (const Iterator &)
References Iterator(), and LIEF_API.
operator=() [2/2]
Iterator & LIEF::runtime::Module::Iterator::operator= (Iterator &&) noexcept
References Iterator(), and LIEF_API.
yield()
std::unique_ptr< Module > LIEF::runtime::Module::Iterator::yield ()
Transfer ownership of the module at the current position to the caller. Returns nullptr if the iterator is past-the-end.
References LIEF_API, LIEF::runtime::Module::Module(), and yield().
Referenced by yield().
The documentation for this class was generated from the following file:
Module.hpp