LIEF: Library to Instrument Executable Formats: LIEF::PE::Factory Class Reference
LIEF::PE::Factory Class Reference
This factory is used to create PE from scratch.
#include <Factory.hpp>
Public Member Functions
Factory (const Factory &)=delete
Factory & operator= (const Factory &)=delete
Factory (Factory &&)
Factory & operator= (Factory &&)
Factory & add_section (const Section &section)
Factory & set_arch (Header::MACHINE_TYPES arch)
Factory & set_entrypoint (uint64_t ep)
std::unique_ptr< Binary > get ()
bool is_32bit () const
bool is_64bit () const
uint32_t section_align () const
uint32_t file_align () const
~Factory ()
Static Public Member Functions
static std::unique_ptr< Factory > create (PE_TYPE type)
Initiate the factory to construct a PE which the given type.
Detailed Description
This factory is used to create PE from scratch.
Constructor & Destructor Documentation
Factory() [1/2]
LIEF::PE::Factory::Factory (const Factory &) delete
References Factory().
Referenced by add_section(), Factory(), Factory(), operator=(), operator=(), set_arch(), set_entrypoint(), and ~Factory().
Factory() [2/2]
LIEF::PE::Factory::Factory (Factory &&)
References Factory().
~Factory()
LIEF::PE::Factory::~Factory ()
References Factory().
Member Function Documentation
add_section()
Factory & LIEF::PE::Factory::add_section (const Section & section) inline
References Factory().
create()
std::unique_ptr< Factory > LIEF::PE::Factory::create (PE_TYPE type) static
Initiate the factory to construct a PE which the given type.
file_align()
uint32_t LIEF::PE::Factory::file_align () const inline
get()
std::unique_ptr< Binary > LIEF::PE::Factory::get () inline
is_32bit()
bool LIEF::PE::Factory::is_32bit () const inline
References LIEF::PE::PE32.
is_64bit()
bool LIEF::PE::Factory::is_64bit () const inline
References LIEF::PE::PE32_PLUS.
operator=() [1/2]
Factory & LIEF::PE::Factory::operator= (const Factory &) delete
References Factory().
operator=() [2/2]
Factory & LIEF::PE::Factory::operator= (Factory &&)
References Factory().
section_align()
uint32_t LIEF::PE::Factory::section_align () const inline
set_arch()
Factory & LIEF::PE::Factory::set_arch (Header::MACHINE_TYPES arch) inline
References Factory().
set_entrypoint()
Factory & LIEF::PE::Factory::set_entrypoint (uint64_t ep) inline
References Factory().
The documentation for this class was generated from the following file:
Factory.hpp