LIEF: Library to Instrument Executable Formats: LIEF::PE::CHPEMetadataARM64 Class Reference
LIEF::PE::CHPEMetadataARM64 Class Reference
This class represents ARM64-specific metadata used in CHPE (Compatible Hybrid PE) binaries, particularly for hybrid architectures like ARM64EC and ARM64X.
#include <MetadataARM64.hpp>
Classes
struct range_entry_t
Structure that describes architecture-specific ranges.
struct redirection_entry_t
Structure that describes a redirection.
struct code_range_entry_point_t
Mirror of IMAGE_ARM64EC_CODE_RANGE_ENTRY_POINT: Represents a mapping between code range and its entry point.
Public Types
using range_entries_t = std::vector<range_entry_t>
using it_range_entries = ref_iterator<range_entries_t&>
using it_const_range_entries = const_ref_iterator<const range_entries_t&>
using redirection_entries_t = std::vector<redirection_entry_t>
using it_redirection_entries = ref_iterator<redirection_entries_t&>
using it_const_redirection_entries = const_ref_iterator<const redirection_entries_t&>
using code_range_entry_point_entries = std::vector<code_range_entry_point_t>
using it_code_range_entry_point = ref_iterator<code_range_entry_point_entries&>
using it_const_code_range_entry_point = const_ref_iterator<const code_range_entry_point_entries&>
Public Types inherited from LIEF::PE::CHPEMetadata
enum class KIND { UNKNOWN = 0 , ARM64 , X86 }
Discriminator for the subclasses.
Public Member Functions
CHPEMetadataARM64 (uint32_t version)
CHPEMetadataARM64 (const CHPEMetadataARM64 &)=default
CHPEMetadataARM64 & operator= (const CHPEMetadataARM64 &)=default
CHPEMetadataARM64 (CHPEMetadataARM64 &&)=default
CHPEMetadataARM64 & operator= (CHPEMetadataARM64 &&)=default
std::unique_ptr< CHPEMetadata > clone () const override
uint32_t code_map () const
RVA to the array that describes architecture-specific ranges.
uint32_t code_map_count () const
Number of entries in the code map.
uint32_t code_ranges_to_entrypoints () const
uint32_t redirection_metadata () const
uint32_t os_arm64x_dispatch_call_no_redirect () const
uint32_t os_arm64x_dispatch_ret () const
uint32_t os_arm64x_dispatch_call () const
uint32_t os_arm64x_dispatch_icall () const
uint32_t os_arm64x_dispatch_icall_cfg () const
uint32_t alternate_entry_point () const
uint32_t auxiliary_iat () const
uint32_t code_ranges_to_entry_points_count () const
uint32_t redirection_metadata_count () const
uint32_t get_x64_information_function_pointer () const
uint32_t set_x64_information_function_pointer () const
uint32_t extra_rfe_table () const
RVA to this architecture-specific exception table.
uint32_t extra_rfe_table_size () const
architecture-specific exception table size
uint32_t os_arm64x_dispatch_fptr () const
uint32_t auxiliary_iat_copy () const
uint32_t auxiliary_delay_import () const
uint32_t auxiliary_delay_import_copy () const
uint32_t bitfield_info () const
it_range_entries code_ranges ()
it_const_range_entries code_ranges () const
it_redirection_entries redirections ()
it_const_redirection_entries redirections () const
it_code_range_entry_point code_range_entry_point ()
it_const_code_range_entry_point code_range_entry_point () const
CHPEMetadataARM64 & code_map (uint32_t value)
CHPEMetadataARM64 & code_map_count (uint32_t value)
CHPEMetadataARM64 & code_ranges_to_entrypoints (uint32_t value)
CHPEMetadataARM64 & redirection_metadata (uint32_t value)
CHPEMetadataARM64 & os_arm64x_dispatch_call_no_redirect (uint32_t value)
CHPEMetadataARM64 & os_arm64x_dispatch_ret (uint32_t value)
CHPEMetadataARM64 & os_arm64x_dispatch_call (uint32_t value)
CHPEMetadataARM64 & os_arm64x_dispatch_icall (uint32_t value)
CHPEMetadataARM64 & os_arm64x_dispatch_icall_cfg (uint32_t value)
CHPEMetadataARM64 & alternate_entry_point (uint32_t value)
CHPEMetadataARM64 & auxiliary_iat (uint32_t value)
CHPEMetadataARM64 & code_ranges_to_entry_points_count (uint32_t value)
CHPEMetadataARM64 & redirection_metadata_count (uint32_t value)
CHPEMetadataARM64 & get_x64_information_function_pointer (uint32_t value)
CHPEMetadataARM64 & set_x64_information_function_pointer (uint32_t value)
CHPEMetadataARM64 & extra_rfe_table (uint32_t value)
CHPEMetadataARM64 & extra_rfe_table_size (uint32_t value)
CHPEMetadataARM64 & os_arm64x_dispatch_fptr (uint32_t value)
CHPEMetadataARM64 & auxiliary_iat_copy (uint32_t value)
CHPEMetadataARM64 & auxiliary_delay_import (uint32_t value)
CHPEMetadataARM64 & auxiliary_delay_import_copy (uint32_t value)
CHPEMetadataARM64 & bitfield_info (uint32_t value)
std::string to_string () const override
~CHPEMetadataARM64 () override=default
Public Member Functions inherited from LIEF::PE::CHPEMetadata
CHPEMetadata ()=default
CHPEMetadata (KIND kind, uint32_t version)
CHPEMetadata (const CHPEMetadata &)=default
CHPEMetadata & operator= (const CHPEMetadata &)=default
CHPEMetadata (CHPEMetadata &&)=default
CHPEMetadata & operator= (CHPEMetadata &&)=default
KIND kind () const
Determine the type of the concrete implementation.
uint32_t version () const
Version of the structure.
template<class T>
T * as ()
template<class T>
const T * as () const
virtual ~CHPEMetadata ()=default
Static Public Member Functions
static std::unique_ptr< CHPEMetadataARM64 > parse (Parser &ctx, BinaryStream &stream, uint32_t version)
static ok_error_t parse_code_map (Parser &ctx, CHPEMetadataARM64 &metadata)
static ok_error_t parse_redirections (Parser &ctx, CHPEMetadataARM64 &metadata)
static ok_error_t parse_code_ranges_to_entry_points (Parser &ctx, CHPEMetadataARM64 &metadata)
static bool classof (const CHPEMetadata *meta)
Static Public Member Functions inherited from LIEF::PE::CHPEMetadata
static std::unique_ptr< CHPEMetadata > parse (Parser &ctx, BinaryStream &stream)
Detailed Description
This class represents ARM64-specific metadata used in CHPE (Compatible Hybrid PE) binaries, particularly for hybrid architectures like ARM64EC and ARM64X.
It extends the CHPEMetadata base class and provides access to metadata describing code ranges, redirections, entry points, and other hybrid-specific information relevant for binary analysis or instrumentation.
Member Typedef Documentation
code_range_entry_point_entries
using LIEF::PE::CHPEMetadataARM64::code_range_entry_point_entries = std::vector<code_range_entry_point_t>
it_code_range_entry_point
using LIEF::PE::CHPEMetadataARM64::it_code_range_entry_point = ref_iterator<code_range_entry_point_entries&>
it_const_code_range_entry_point
using LIEF::PE::CHPEMetadataARM64::it_const_code_range_entry_point = const_ref_iterator<const code_range_entry_point_entries&>
it_const_range_entries
using LIEF::PE::CHPEMetadataARM64::it_const_range_entries = const_ref_iterator<const range_entries_t&>
it_const_redirection_entries
using LIEF::PE::CHPEMetadataARM64::it_const_redirection_entries = const_ref_iterator<const redirection_entries_t&>
it_range_entries
using LIEF::PE::CHPEMetadataARM64::it_range_entries = ref_iterator<range_entries_t&>
it_redirection_entries
using LIEF::PE::CHPEMetadataARM64::it_redirection_entries = ref_iterator<redirection_entries_t&>
range_entries_t
using LIEF::PE::CHPEMetadataARM64::range_entries_t = std::vector<range_entry_t>
redirection_entries_t
using LIEF::PE::CHPEMetadataARM64::redirection_entries_t = std::vector<redirection_entry_t>
Constructor & Destructor Documentation
CHPEMetadataARM64() [1/3]
LIEF::PE::CHPEMetadataARM64::CHPEMetadataARM64 (uint32_t version) inline
References LIEF::PE::CHPEMetadata::CHPEMetadata(), and LIEF::PE::CHPEMetadata::version().
Referenced by alternate_entry_point(), auxiliary_delay_import(), auxiliary_delay_import_copy(), auxiliary_iat(), auxiliary_iat_copy(), bitfield_info(), CHPEMetadataARM64(), CHPEMetadataARM64(), clone(), code_map(), code_map_count(), code_ranges_to_entry_points_count(), code_ranges_to_entrypoints(), extra_rfe_table(), extra_rfe_table_size(), get_x64_information_function_pointer(), operator=(), operator=(), os_arm64x_dispatch_call(), os_arm64x_dispatch_call_no_redirect(), os_arm64x_dispatch_fptr(), os_arm64x_dispatch_icall(), os_arm64x_dispatch_icall_cfg(), os_arm64x_dispatch_ret(), parse_code_map(), parse_code_ranges_to_entry_points(), parse_redirections(), redirection_metadata(), redirection_metadata_count(), and set_x64_information_function_pointer().
CHPEMetadataARM64() [2/3]
LIEF::PE::CHPEMetadataARM64::CHPEMetadataARM64 (const CHPEMetadataARM64 &) default
References CHPEMetadataARM64().
CHPEMetadataARM64() [3/3]
LIEF::PE::CHPEMetadataARM64::CHPEMetadataARM64 (CHPEMetadataARM64 &&) default
References CHPEMetadataARM64().
~CHPEMetadataARM64()
LIEF::PE::CHPEMetadataARM64::~CHPEMetadataARM64 () override default
Member Function Documentation
alternate_entry_point() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::alternate_entry_point () const inline
alternate_entry_point() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::alternate_entry_point (uint32_t value) inline
References CHPEMetadataARM64().
auxiliary_delay_import() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::auxiliary_delay_import () const inline
auxiliary_delay_import() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::auxiliary_delay_import (uint32_t value) inline
References CHPEMetadataARM64().
auxiliary_delay_import_copy() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::auxiliary_delay_import_copy () const inline
auxiliary_delay_import_copy() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::auxiliary_delay_import_copy (uint32_t value) inline
References CHPEMetadataARM64().
auxiliary_iat() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::auxiliary_iat () const inline
auxiliary_iat() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::auxiliary_iat (uint32_t value) inline
References CHPEMetadataARM64().
auxiliary_iat_copy() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::auxiliary_iat_copy () const inline
auxiliary_iat_copy() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::auxiliary_iat_copy (uint32_t value) inline
References CHPEMetadataARM64().
bitfield_info() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::bitfield_info () const inline
bitfield_info() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::bitfield_info (uint32_t value) inline
References CHPEMetadataARM64().
classof()
bool LIEF::PE::CHPEMetadataARM64::classof (const CHPEMetadata * meta) inline static
References LIEF::PE::CHPEMetadata::ARM64, LIEF::PE::CHPEMetadata::CHPEMetadata(), and LIEF::PE::CHPEMetadata::kind().
clone()
std::unique_ptr< CHPEMetadata > LIEF::PE::CHPEMetadataARM64::clone () const inline override virtual
Reimplemented from LIEF::PE::CHPEMetadata.
References CHPEMetadataARM64().
code_map() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::code_map () const inline
RVA to the array that describes architecture-specific ranges.
code_map() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::code_map (uint32_t value) inline
References CHPEMetadataARM64().
code_map_count() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::code_map_count () const inline
Number of entries in the code map.
code_map_count() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::code_map_count (uint32_t value) inline
References CHPEMetadataARM64().
code_range_entry_point() [1/2]
it_code_range_entry_point LIEF::PE::CHPEMetadataARM64::code_range_entry_point () inline
code_range_entry_point() [2/2]
it_const_code_range_entry_point LIEF::PE::CHPEMetadataARM64::code_range_entry_point () const inline
code_ranges() [1/2]
it_range_entries LIEF::PE::CHPEMetadataARM64::code_ranges () inline
code_ranges() [2/2]
it_const_range_entries LIEF::PE::CHPEMetadataARM64::code_ranges () const inline
code_ranges_to_entry_points_count() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::code_ranges_to_entry_points_count () const inline
code_ranges_to_entry_points_count() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::code_ranges_to_entry_points_count (uint32_t value) inline
References CHPEMetadataARM64().
code_ranges_to_entrypoints() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::code_ranges_to_entrypoints () const inline
code_ranges_to_entrypoints() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::code_ranges_to_entrypoints (uint32_t value) inline
References CHPEMetadataARM64().
extra_rfe_table() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::extra_rfe_table () const inline
RVA to this architecture-specific exception table.
extra_rfe_table() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::extra_rfe_table (uint32_t value) inline
References CHPEMetadataARM64().
extra_rfe_table_size() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::extra_rfe_table_size () const inline
architecture-specific exception table size
extra_rfe_table_size() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::extra_rfe_table_size (uint32_t value) inline
References CHPEMetadataARM64().
get_x64_information_function_pointer() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::get_x64_information_function_pointer () const inline
get_x64_information_function_pointer() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::get_x64_information_function_pointer (uint32_t value) inline
References CHPEMetadataARM64().
operator=() [1/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::operator= (CHPEMetadataARM64 &&) default
References CHPEMetadataARM64().
operator=() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::operator= (const CHPEMetadataARM64 &) default
References CHPEMetadataARM64().
os_arm64x_dispatch_call() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_call () const inline
os_arm64x_dispatch_call() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_call (uint32_t value) inline
References CHPEMetadataARM64().
os_arm64x_dispatch_call_no_redirect() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_call_no_redirect () const inline
os_arm64x_dispatch_call_no_redirect() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_call_no_redirect (uint32_t value) inline
References CHPEMetadataARM64().
os_arm64x_dispatch_fptr() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_fptr () const inline
os_arm64x_dispatch_fptr() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_fptr (uint32_t value) inline
References CHPEMetadataARM64().
os_arm64x_dispatch_icall() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_icall () const inline
os_arm64x_dispatch_icall() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_icall (uint32_t value) inline
References CHPEMetadataARM64().
os_arm64x_dispatch_icall_cfg() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_icall_cfg () const inline
os_arm64x_dispatch_icall_cfg() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_icall_cfg (uint32_t value) inline
References CHPEMetadataARM64().
os_arm64x_dispatch_ret() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_ret () const inline
os_arm64x_dispatch_ret() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::os_arm64x_dispatch_ret (uint32_t value) inline
References CHPEMetadataARM64().
parse()
std::unique_ptr< CHPEMetadataARM64 > LIEF::PE::CHPEMetadataARM64::parse (Parser & ctx, BinaryStream & stream, uint32_t version) static
References LIEF::PE::CHPEMetadata::version().
parse_code_map()
ok_error_t LIEF::PE::CHPEMetadataARM64::parse_code_map (Parser & ctx, CHPEMetadataARM64 & metadata) static
References CHPEMetadataARM64().
parse_code_ranges_to_entry_points()
ok_error_t LIEF::PE::CHPEMetadataARM64::parse_code_ranges_to_entry_points (Parser & ctx, CHPEMetadataARM64 & metadata) static
References CHPEMetadataARM64().
parse_redirections()
ok_error_t LIEF::PE::CHPEMetadataARM64::parse_redirections (Parser & ctx, CHPEMetadataARM64 & metadata) static
References CHPEMetadataARM64().
redirection_metadata() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::redirection_metadata () const inline
redirection_metadata() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::redirection_metadata (uint32_t value) inline
References CHPEMetadataARM64().
redirection_metadata_count() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::redirection_metadata_count () const inline
redirection_metadata_count() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::redirection_metadata_count (uint32_t value) inline
References CHPEMetadataARM64().
redirections() [1/2]
it_redirection_entries LIEF::PE::CHPEMetadataARM64::redirections () inline
redirections() [2/2]
it_const_redirection_entries LIEF::PE::CHPEMetadataARM64::redirections () const inline
set_x64_information_function_pointer() [1/2]
uint32_t LIEF::PE::CHPEMetadataARM64::set_x64_information_function_pointer () const inline
set_x64_information_function_pointer() [2/2]
CHPEMetadataARM64 & LIEF::PE::CHPEMetadataARM64::set_x64_information_function_pointer (uint32_t value) inline
References CHPEMetadataARM64().
to_string()
std::string LIEF::PE::CHPEMetadataARM64::to_string () const override virtual
Reimplemented from LIEF::PE::CHPEMetadata.
The documentation for this class was generated from the following file:
MetadataARM64.hpp