LIEF: Library to Instrument Executable Formats: LIEF::PE::Attribute Class Reference
LIEF::PE::Attribute Class Reference abstract
Interface over PKCS #7 attribute.
#include <Attribute.hpp>
Public Types
enum class TYPE {
UNKNOWN = 0 , CONTENT_TYPE , GENERIC_TYPE , SIGNING_CERTIFICATE_V2 ,
SPC_SP_OPUS_INFO , SPC_RELAXED_PE_MARKER_CHECK , MS_COUNTER_SIGN , MS_SPC_NESTED_SIGN ,
MS_SPC_STATEMENT_TYPE , MS_PLATFORM_MANIFEST_BINARY_ID , PKCS9_AT_SEQUENCE_NUMBER , PKCS9_COUNTER_SIGNATURE ,
PKCS9_MESSAGE_DIGEST , PKCS9_SIGNING_TIME
}
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Public Member Functions
Attribute ()=delete
Attribute (const Attribute &)=default
Attribute & operator= (const Attribute &)=default
virtual std::unique_ptr< Attribute > clone () const =0
virtual TYPE type () const
Concrete type of the attribute.
virtual std::string print () const =0
Print information about the underlying attribute.
void accept (Visitor &visitor) const override
~Attribute () override=default
template<class T>
const T * cast () const
template<class T>
T * cast ()
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Detailed Description
Interface over PKCS #7 attribute.
Member Enumeration Documentation
TYPE
enum class LIEF::PE::Attribute::TYPE strong
Enumerator
UNKNOWN
CONTENT_TYPE
GENERIC_TYPE
SIGNING_CERTIFICATE_V2
SPC_SP_OPUS_INFO
SPC_RELAXED_PE_MARKER_CHECK
MS_COUNTER_SIGN
MS_SPC_NESTED_SIGN
MS_SPC_STATEMENT_TYPE
MS_PLATFORM_MANIFEST_BINARY_ID
PKCS9_AT_SEQUENCE_NUMBER
PKCS9_COUNTER_SIGNATURE
PKCS9_MESSAGE_DIGEST
PKCS9_SIGNING_TIME
Constructor & Destructor Documentation
Attribute() [1/2]
LIEF::PE::Attribute::Attribute () delete
Referenced by Attribute(), cast(), LIEF::PE::ContentType::classof(), LIEF::PE::GenericType::classof(), LIEF::PE::MsCounterSign::classof(), LIEF::PE::MsManifestBinaryID::classof(), LIEF::PE::MsSpcNestedSignature::classof(), LIEF::PE::MsSpcStatementType::classof(), LIEF::PE::PKCS9AtSequenceNumber::classof(), LIEF::PE::PKCS9CounterSignature::classof(), LIEF::PE::PKCS9MessageDigest::classof(), LIEF::PE::PKCS9SigningTime::classof(), LIEF::PE::SigningCertificateV2::classof(), LIEF::PE::SpcRelaxedPeMarkerCheck::classof(), LIEF::PE::SpcSpOpusInfo::classof(), LIEF::PE::ContentType::ContentType(), LIEF::PE::ContentType::ContentType(), LIEF::PE::GenericType::GenericType(), LIEF::PE::GenericType::GenericType(), LIEF::PE::MsCounterSign::MsCounterSign(), LIEF::PE::MsManifestBinaryID::MsManifestBinaryID(), LIEF::PE::MsSpcNestedSignature::MsSpcNestedSignature(), LIEF::PE::MsSpcStatementType::MsSpcStatementType(), operator<<, operator=(), LIEF::PE::PKCS9AtSequenceNumber::PKCS9AtSequenceNumber(), LIEF::PE::PKCS9CounterSignature::PKCS9CounterSignature(), LIEF::PE::PKCS9MessageDigest::PKCS9MessageDigest(), LIEF::PE::PKCS9SigningTime::PKCS9SigningTime(), LIEF::PE::SigningCertificateV2::SigningCertificateV2(), LIEF::PE::SpcRelaxedPeMarkerCheck::SpcRelaxedPeMarkerCheck(), and LIEF::PE::SpcSpOpusInfo::SpcSpOpusInfo().
Attribute() [2/2]
LIEF::PE::Attribute::Attribute (const Attribute &) default
References Attribute().
~Attribute()
LIEF::PE::Attribute::~Attribute () override default
References LIEF_API.
Member Function Documentation
accept()
void LIEF::PE::Attribute::accept (Visitor & visitor) const override virtual
Implements LIEF::Object.
Reimplemented in LIEF::PE::ContentType, LIEF::PE::GenericType, LIEF::PE::MsCounterSign, LIEF::PE::MsManifestBinaryID, LIEF::PE::MsSpcNestedSignature, LIEF::PE::MsSpcStatementType, LIEF::PE::PKCS9AtSequenceNumber, LIEF::PE::PKCS9CounterSignature, LIEF::PE::PKCS9MessageDigest, LIEF::PE::PKCS9SigningTime, LIEF::PE::SigningCertificateV2, LIEF::PE::SpcRelaxedPeMarkerCheck, and LIEF::PE::SpcSpOpusInfo.
cast() [1/2]
template<class T> T * LIEF::PE::Attribute::cast () inline
References Attribute(), and LIEF::PE::T.
cast() [2/2]
template<class T> const T * LIEF::PE::Attribute::cast () const inline
References LIEF::PE::T.
clone()
virtual std::unique_ptr< Attribute > LIEF::PE::Attribute::clone () const pure virtual
Implemented in LIEF::PE::ContentType, LIEF::PE::GenericType, LIEF::PE::MsCounterSign, LIEF::PE::MsManifestBinaryID, LIEF::PE::MsSpcNestedSignature, LIEF::PE::MsSpcStatementType, LIEF::PE::PKCS9AtSequenceNumber, LIEF::PE::PKCS9CounterSignature, LIEF::PE::PKCS9MessageDigest, LIEF::PE::PKCS9SigningTime, LIEF::PE::SigningCertificateV2, LIEF::PE::SpcRelaxedPeMarkerCheck, and LIEF::PE::SpcSpOpusInfo.
operator=()
Attribute & LIEF::PE::Attribute::operator= (const Attribute &) default
References Attribute().
print()
virtual std::string LIEF::PE::Attribute::print () const pure virtual
Print information about the underlying attribute.
Implemented in LIEF::PE::ContentType, LIEF::PE::GenericType, LIEF::PE::MsCounterSign, LIEF::PE::MsManifestBinaryID, LIEF::PE::MsSpcNestedSignature, LIEF::PE::MsSpcStatementType, LIEF::PE::PKCS9AtSequenceNumber, LIEF::PE::PKCS9CounterSignature, LIEF::PE::PKCS9MessageDigest, LIEF::PE::PKCS9SigningTime, LIEF::PE::SigningCertificateV2, LIEF::PE::SpcRelaxedPeMarkerCheck, and LIEF::PE::SpcSpOpusInfo.
Referenced by operator<<.
type()
virtual TYPE LIEF::PE::Attribute::type () const inline virtual
Concrete type of the attribute.
Referenced by LIEF::PE::ContentType::classof(), LIEF::PE::GenericType::classof(), LIEF::PE::MsCounterSign::classof(), LIEF::PE::MsManifestBinaryID::classof(), LIEF::PE::MsSpcNestedSignature::classof(), LIEF::PE::MsSpcStatementType::classof(), LIEF::PE::PKCS9AtSequenceNumber::classof(), LIEF::PE::PKCS9CounterSignature::classof(), LIEF::PE::PKCS9MessageDigest::classof(), LIEF::PE::PKCS9SigningTime::classof(), LIEF::PE::SigningCertificateV2::classof(), LIEF::PE::SpcRelaxedPeMarkerCheck::classof(), and LIEF::PE::SpcSpOpusInfo::classof().
The documentation for this class was generated from the following file:
PE/signature/Attribute.hpp