LIEF: Library to Instrument Executable Formats: LIEF::dwarf::types::File Class Reference
LIEF::dwarf::types::File Class Reference
This class represents a DW_TAG_file_type.
#include <File.hpp>
Public Member Functions
template<typename... Args, typename = typename std:: enable_if<std::is_constructible<Type, Args&&...>::value>::type>
File (Args &&... args)
File (const File &)=delete
File & operator= (const File &)=delete
File (File &&) noexcept=default
File & operator= (File &&) noexcept=default
~File () override
Public Member Functions inherited from LIEF::dwarf::Type
Type (std::unique_ptr< details::Type > impl)
Type (details::Type &impl)
Type (const Type &)=delete
Type & operator= (const Type &)=delete
Type (Type &&) noexcept
Type & operator= (Type &&) noexcept
virtual ~Type ()
KIND kind () const
bool is_unspecified () const
Whether this type is a DW_TAG_unspecified_type.
result< std::string > name () const
Return the type's name using either DW_AT_name or DW_AT_picture_string (if any).
result< uint64_t > size () const
Return the size of the type or an error if it can't be computed.
debug_location_t location () const
Return the debug location where this type is defined.
std::unique_ptr< Scope > scope () const
Return the scope in which this type is defined.
std::string to_decl (const DeclOpt &opt=DeclOpt()) const
Generates a C/C++ definition for this type.
template<class T>
const T * as () const
Static Public Member Functions
static bool classof (const Type *type)
Static Public Member Functions inherited from LIEF::dwarf::Type
static std::unique_ptr< Type > create (std::unique_ptr< details::Type > impl)
Additional Inherited Members
Public Types inherited from LIEF::dwarf::Type
enum class KIND {
UNKNOWN = 0 , UNSPECIFIED , BASE , CONST_KIND ,
CLASS , ARRAY , POINTER , STRUCT ,
UNION , TYPEDEF , REF , SET_TYPE ,
STRING , SUBROUTINE , POINTER_MEMBER , PACKED ,
FILE , THROWN , VOLATILE , RESTRICT ,
INTERFACE , SHARED , RVALREF , TEMPLATE_ALIAS ,
COARRAY , DYNAMIC , ATOMIC , IMMUTABLE ,
ENUM
}
Detailed Description
This class represents a DW_TAG_file_type.
Constructor & Destructor Documentation
File() [1/3]
template<typename... Args, typename = typename std:: enable_if<std::is_constructible<Type, Args&&...>::value>::type> LIEF::dwarf::types::File::File (Args &&... args) inline
References LIEF::dwarf::Type::Type().
Referenced by File(), File(), operator=(), and operator=().
File() [2/3]
LIEF::dwarf::types::File::File (const File &) delete
References File().
File() [3/3]
LIEF::dwarf::types::File::File (File &&) default noexcept
References File().
~File()
LIEF::dwarf::types::File::~File () override
Member Function Documentation
classof()
bool LIEF::dwarf::types::File::classof (const Type * type) inline static
References classof(), LIEF::dwarf::Type::FILE, and LIEF::dwarf::Type::Type().
Referenced by classof().
operator=() [1/2]
File & LIEF::dwarf::types::File::operator= (const File &) delete
References File().
operator=() [2/2]
File & LIEF::dwarf::types::File::operator= (File &&) default noexcept
References File().
The documentation for this class was generated from the following file:
DWARF/types/File.hpp