LIEF: Library to Instrument Executable Formats: LIEF::COFF::String Class Reference
LIEF::COFF::String Class Reference
This class represents a string located in the COFF string table.
#include <String.hpp>
Public Member Functions
String ()=default
String (uint32_t offset, std::string str)
String (const String &)=default
String & operator= (const String &)=default
String (String &&)=default
String & operator= (String &&)=default
~String ()=default
const std::string & str () const
The actual string.
uint32_t offset () const
The offset of this string the in the COFF string table. This offset includes the first 4-bytes that holds the table size.
String & str (std::string str)
String & offset (uint32_t value)
Detailed Description
This class represents a string located in the COFF string table.
Some of these strings can be used for section names that are greater than 8 bytes. See: LIEF::PE::Section::coff_string()
Reference: https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#coff-string-table
Constructor & Destructor Documentation
String() [1/4]
LIEF::COFF::String::String () default
Referenced by offset(), operator<<, operator=(), operator=(), str(), String(), and String().
String() [2/4]
LIEF::COFF::String::String (uint32_t offset, std::string str) inline
References offset(), and str().
String() [3/4]
LIEF::COFF::String::String (const String &) default
References String().
String() [4/4]
LIEF::COFF::String::String (String &&) default
References String().
~String()
LIEF::COFF::String::~String () default
Member Function Documentation
offset() [1/2]
uint32_t LIEF::COFF::String::offset () const inline
The offset of this string the in the COFF string table. This offset includes the first 4-bytes that holds the table size.
Referenced by String().
offset() [2/2]
String & LIEF::COFF::String::offset (uint32_t value) inline
References String().
operator=() [1/2]
String & LIEF::COFF::String::operator= (const String &) default
References String().
operator=() [2/2]
String & LIEF::COFF::String::operator= (String &&) default
References String().
str() [1/2]
const std::string & LIEF::COFF::String::str () const inline
The actual string.
Referenced by operator<<, str(), and String().
str() [2/2]
String & LIEF::COFF::String::str (std::string str) inline
References str(), and String().
The documentation for this class was generated from the following file:
String.hpp