LIEF: Library to Instrument Executable Formats: LIEF::runtime::android::Property Class Reference
LIEF::runtime::android::Property Class Reference
This class represents an Android property such as ro.boot.hardware.
#include <Property.hpp>
Public Member Functions
Property ()=default
Property (std::string name, std::string value, uint32_t serial)
Property (const Property &)=default
Property & operator= (const Property &)=default
Property (Property &&) noexcept=default
Property & operator= (Property &&) noexcept=default
~Property ()=default
const std::string & name () const
Name of the property (e.g. ro.boot.hardware).
const std::string & value () const
Value associated with the property.
uint32_t serial () const
Serial number of the property.
std::string to_string () const
Pretty representation of the property.
Static Public Member Functions
static Property create_from (const prop_info &pi)
Detailed Description
This class represents an Android property such as ro.boot.hardware.
Constructor & Destructor Documentation
Property() [1/4]
LIEF::runtime::android::Property::Property () default
Referenced by create_from(), operator<<, operator=(), operator=(), Property(), Property(), and ~Property().
Property() [2/4]
LIEF::runtime::android::Property::Property (std::string name, std::string value, uint32_t serial) inline
References name(), serial(), and value().
Property() [3/4]
LIEF::runtime::android::Property::Property (const Property &) default
References Property().
Property() [4/4]
LIEF::runtime::android::Property::Property (Property &&) default noexcept
References Property().
~Property()
LIEF::runtime::android::Property::~Property () default
References Property().
Member Function Documentation
create_from()
Property LIEF::runtime::android::Property::create_from (const prop_info & pi) static
References Property().
name()
const std::string & LIEF::runtime::android::Property::name () const inline
Name of the property (e.g. ro.boot.hardware).
References LIEF_LIFETIMEBOUND, and name().
Referenced by name(), and Property().
operator=() [1/2]
Property & LIEF::runtime::android::Property::operator= (const Property &) default
References Property().
operator=() [2/2]
Property & LIEF::runtime::android::Property::operator= (Property &&) default noexcept
References Property().
serial()
uint32_t LIEF::runtime::android::Property::serial () const inline
Serial number of the property.
It is incremented each time the property is updated and can therefore be used to detect changes.
Referenced by Property().
to_string()
std::string LIEF::runtime::android::Property::to_string () const
Pretty representation of the property.
Referenced by operator<<.
value()
const std::string & LIEF::runtime::android::Property::value () const inline
Value associated with the property.
References LIEF_LIFETIMEBOUND.
Referenced by Property().
The documentation for this class was generated from the following file:
runtime/android/Property.hpp