LIEF: Library to Instrument Executable Formats: LIEF::PE::CHPEMetadataX86 Class Reference
LIEF::PE::CHPEMetadataX86 Class Reference
This class represents hybrid metadata for X86.
#include <MetadataX86.hpp>
Public Member Functions
CHPEMetadataX86 (uint32_t version)
CHPEMetadataX86 (const CHPEMetadataX86 &)=default
CHPEMetadataX86 & operator= (const CHPEMetadataX86 &)=default
CHPEMetadataX86 (CHPEMetadataX86 &&)=default
CHPEMetadataX86 & operator= (CHPEMetadataX86 &&)=default
std::unique_ptr< CHPEMetadata > clone () const override
uint32_t chpe_code_address_range_offset () const
uint32_t chpe_code_address_range_count () const
uint32_t wowa64_exception_handler_function_pointer () const
uint32_t wowa64_dispatch_call_function_pointer () const
uint32_t wowa64_dispatch_indirect_call_function_pointer () const
uint32_t wowa64_dispatch_indirect_call_cfg_function_pointer () const
uint32_t wowa64_dispatch_ret_function_pointer () const
uint32_t wowa64_dispatch_ret_leaf_function_pointer () const
uint32_t wowa64_dispatch_jump_function_pointer () const
optional< uint32_t > compiler_iat_pointer () const
optional< uint32_t > wowa64_rdtsc_function_pointer () const
CHPEMetadataX86 & chpe_code_address_range_offset (uint32_t value)
CHPEMetadataX86 & chpe_code_address_range_count (uint32_t value)
CHPEMetadataX86 & wowa64_exception_handler_function_pointer (uint32_t value)
CHPEMetadataX86 & wowa64_dispatch_call_function_pointer (uint32_t value)
CHPEMetadataX86 & wowa64_dispatch_indirect_call_function_pointer (uint32_t value)
CHPEMetadataX86 & wowa64_dispatch_indirect_call_cfg_function_pointer (uint32_t value)
CHPEMetadataX86 & wowa64_dispatch_ret_function_pointer (uint32_t value)
CHPEMetadataX86 & wowa64_dispatch_ret_leaf_function_pointer (uint32_t value)
CHPEMetadataX86 & wowa64_dispatch_jump_function_pointer (uint32_t value)
CHPEMetadataX86 & compiler_iat_pointer (uint32_t value)
CHPEMetadataX86 & wowa64_rdtsc_function_pointer (uint32_t value)
std::string to_string () const override
~CHPEMetadataX86 () override=default
Public Member Functions inherited from LIEF::PE::CHPEMetadata
CHPEMetadata ()=default
CHPEMetadata (KIND kind, uint32_t version)
CHPEMetadata (const CHPEMetadata &)=default
CHPEMetadata & operator= (const CHPEMetadata &)=default
CHPEMetadata (CHPEMetadata &&)=default
CHPEMetadata & operator= (CHPEMetadata &&)=default
KIND kind () const
Determine the type of the concrete implementation.
uint32_t version () const
Version of the structure.
template<class T>
T * as ()
template<class T>
const T * as () const
virtual ~CHPEMetadata ()=default
Static Public Member Functions
static std::unique_ptr< CHPEMetadataX86 > parse (Parser &ctx, BinaryStream &stream, uint32_t version)
static bool classof (const CHPEMetadata *meta)
Static Public Member Functions inherited from LIEF::PE::CHPEMetadata
static std::unique_ptr< CHPEMetadata > parse (Parser &ctx, BinaryStream &stream)
Additional Inherited Members
Public Types inherited from LIEF::PE::CHPEMetadata
enum class KIND { UNKNOWN = 0 , ARM64 , X86 }
Discriminator for the subclasses.
Detailed Description
This class represents hybrid metadata for X86.
Constructor & Destructor Documentation
CHPEMetadataX86() [1/3]
LIEF::PE::CHPEMetadataX86::CHPEMetadataX86 (uint32_t version) inline
References LIEF::PE::CHPEMetadata::CHPEMetadata(), and LIEF::PE::CHPEMetadata::version().
Referenced by chpe_code_address_range_count(), chpe_code_address_range_offset(), CHPEMetadataX86(), CHPEMetadataX86(), clone(), compiler_iat_pointer(), operator=(), operator=(), wowa64_dispatch_call_function_pointer(), wowa64_dispatch_indirect_call_cfg_function_pointer(), wowa64_dispatch_indirect_call_function_pointer(), wowa64_dispatch_jump_function_pointer(), wowa64_dispatch_ret_function_pointer(), wowa64_dispatch_ret_leaf_function_pointer(), wowa64_exception_handler_function_pointer(), and wowa64_rdtsc_function_pointer().
CHPEMetadataX86() [2/3]
LIEF::PE::CHPEMetadataX86::CHPEMetadataX86 (const CHPEMetadataX86 &) default
References CHPEMetadataX86().
CHPEMetadataX86() [3/3]
LIEF::PE::CHPEMetadataX86::CHPEMetadataX86 (CHPEMetadataX86 &&) default
References CHPEMetadataX86().
~CHPEMetadataX86()
LIEF::PE::CHPEMetadataX86::~CHPEMetadataX86 () override default
Member Function Documentation
chpe_code_address_range_count() [1/2]
uint32_t LIEF::PE::CHPEMetadataX86::chpe_code_address_range_count () const inline
chpe_code_address_range_count() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::chpe_code_address_range_count (uint32_t value) inline
References CHPEMetadataX86().
chpe_code_address_range_offset() [1/2]
uint32_t LIEF::PE::CHPEMetadataX86::chpe_code_address_range_offset () const inline
chpe_code_address_range_offset() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::chpe_code_address_range_offset (uint32_t value) inline
References CHPEMetadataX86().
classof()
bool LIEF::PE::CHPEMetadataX86::classof (const CHPEMetadata * meta) inline static
References LIEF::PE::CHPEMetadata::CHPEMetadata(), LIEF::PE::CHPEMetadata::kind(), and LIEF::PE::CHPEMetadata::X86.
clone()
std::unique_ptr< CHPEMetadata > LIEF::PE::CHPEMetadataX86::clone () const inline override virtual
Reimplemented from LIEF::PE::CHPEMetadata.
References CHPEMetadataX86().
compiler_iat_pointer() [1/2]
optional< uint32_t > LIEF::PE::CHPEMetadataX86::compiler_iat_pointer () const inline
compiler_iat_pointer() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::compiler_iat_pointer (uint32_t value) inline
References CHPEMetadataX86().
operator=() [1/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::operator= (CHPEMetadataX86 &&) default
References CHPEMetadataX86().
operator=() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::operator= (const CHPEMetadataX86 &) default
References CHPEMetadataX86().
parse()
std::unique_ptr< CHPEMetadataX86 > LIEF::PE::CHPEMetadataX86::parse (Parser & ctx, BinaryStream & stream, uint32_t version) static
References LIEF::PE::CHPEMetadata::version().
to_string()
std::string LIEF::PE::CHPEMetadataX86::to_string () const override virtual
Reimplemented from LIEF::PE::CHPEMetadata.
wowa64_dispatch_call_function_pointer() [1/2]
uint32_t LIEF::PE::CHPEMetadataX86::wowa64_dispatch_call_function_pointer () const inline
wowa64_dispatch_call_function_pointer() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::wowa64_dispatch_call_function_pointer (uint32_t value) inline
References CHPEMetadataX86().
wowa64_dispatch_indirect_call_cfg_function_pointer() [1/2]
uint32_t LIEF::PE::CHPEMetadataX86::wowa64_dispatch_indirect_call_cfg_function_pointer () const inline
wowa64_dispatch_indirect_call_cfg_function_pointer() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::wowa64_dispatch_indirect_call_cfg_function_pointer (uint32_t value) inline
References CHPEMetadataX86().
wowa64_dispatch_indirect_call_function_pointer() [1/2]
uint32_t LIEF::PE::CHPEMetadataX86::wowa64_dispatch_indirect_call_function_pointer () const inline
wowa64_dispatch_indirect_call_function_pointer() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::wowa64_dispatch_indirect_call_function_pointer (uint32_t value) inline
References CHPEMetadataX86().
wowa64_dispatch_jump_function_pointer() [1/2]
uint32_t LIEF::PE::CHPEMetadataX86::wowa64_dispatch_jump_function_pointer () const inline
wowa64_dispatch_jump_function_pointer() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::wowa64_dispatch_jump_function_pointer (uint32_t value) inline
References CHPEMetadataX86().
wowa64_dispatch_ret_function_pointer() [1/2]
uint32_t LIEF::PE::CHPEMetadataX86::wowa64_dispatch_ret_function_pointer () const inline
wowa64_dispatch_ret_function_pointer() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::wowa64_dispatch_ret_function_pointer (uint32_t value) inline
References CHPEMetadataX86().
wowa64_dispatch_ret_leaf_function_pointer() [1/2]
uint32_t LIEF::PE::CHPEMetadataX86::wowa64_dispatch_ret_leaf_function_pointer () const inline
wowa64_dispatch_ret_leaf_function_pointer() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::wowa64_dispatch_ret_leaf_function_pointer (uint32_t value) inline
References CHPEMetadataX86().
wowa64_exception_handler_function_pointer() [1/2]
uint32_t LIEF::PE::CHPEMetadataX86::wowa64_exception_handler_function_pointer () const inline
wowa64_exception_handler_function_pointer() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::wowa64_exception_handler_function_pointer (uint32_t value) inline
References CHPEMetadataX86().
wowa64_rdtsc_function_pointer() [1/2]
optional< uint32_t > LIEF::PE::CHPEMetadataX86::wowa64_rdtsc_function_pointer () const inline
wowa64_rdtsc_function_pointer() [2/2]
CHPEMetadataX86 & LIEF::PE::CHPEMetadataX86::wowa64_rdtsc_function_pointer (uint32_t value) inline
References CHPEMetadataX86().
The documentation for this class was generated from the following file:
MetadataX86.hpp