LIEF: Library to Instrument Executable Formats: LIEF::assembly::riscv::Operand Class Reference
LIEF::assembly::riscv::Operand Class Reference
This class represents an operand for a RISC-V instruction.
#include <Operand.hpp>
Classes
class Iterator
Forward iterator that lazily disassembles riscv Operand.
Public Member Functions
std::string to_string () const
Pretty representation of the operand.
template<class T>
const T * as () const
This function can be used to down cast an Operand instance:
virtual ~Operand ()
Detailed Description
This class represents an operand for a RISC-V instruction.
Constructor & Destructor Documentation
~Operand()
virtual LIEF::assembly::riscv::Operand::~Operand () virtual
References LIEF_LOCAL.
Member Function Documentation
as()
template<class T> const T * LIEF::assembly::riscv::Operand::as () const inline
This function can be used to down cast an Operand instance:
std::unique_ptr<assembly::riscv::Operand> op = ...;
if (const auto* imm = inst->as<assembly::riscv::operands::Immediate>()) {
  const int64_t value = imm->value();
}
References as().
Referenced by as().
to_string()
std::string LIEF::assembly::riscv::Operand::to_string () const
Pretty representation of the operand.
References to_string().
Referenced by operator<<, and to_string().
The documentation for this class was generated from the following file:
riscv/Operand.hpp