LIEF: Library to Instrument Executable Formats: LIEF::PE::FunctionOverrideInfo Class Reference
LIEF::PE::FunctionOverrideInfo Class Reference
#include <FunctionOverrideInfo.hpp>
Public Types
using relocations_t = std::vector<std::unique_ptr<Relocation>>
using it_relocations = ref_iterator<relocations_t&, Relocation*>
using it_const_relocations = const_ref_iterator<const relocations_t&, const Relocation*>
Public Member Functions
FunctionOverrideInfo ()=default
FunctionOverrideInfo (uint32_t original_rva, uint32_t bdd_offset, uint32_t base_reloc_size)
FunctionOverrideInfo (const FunctionOverrideInfo &)
FunctionOverrideInfo & operator= (const FunctionOverrideInfo &)
FunctionOverrideInfo (FunctionOverrideInfo &&)
FunctionOverrideInfo & operator= (FunctionOverrideInfo &&)
std::string to_string () const
uint32_t original_rva () const
RVA of the original function.
uint32_t bdd_offset () const
Offset into the BDD region.
uint32_t rva_size () const
Size in bytes taken by RVAs.
uint32_t base_reloc_size () const
Size in bytes taken by BaseRelocs.
const std::vector< uint32_t > & functions_rva () const
it_relocations relocations ()
it_const_relocations relocations () const
FunctionOverrideInfo & original_rva (uint32_t value)
FunctionOverrideInfo & bdd_offset (uint32_t value)
FunctionOverrideInfo & base_reloc_size (uint32_t value)
FunctionOverrideInfo & overriding_funcs (std::vector< uint32_t > funcs)
~FunctionOverrideInfo ()
Member Typedef Documentation
it_const_relocations
using LIEF::PE::FunctionOverrideInfo::it_const_relocations = const_ref_iterator<const relocations_t&, const Relocation*>
it_relocations
using LIEF::PE::FunctionOverrideInfo::it_relocations = ref_iterator<relocations_t&, Relocation*>
relocations_t
using LIEF::PE::FunctionOverrideInfo::relocations_t = std::vector<std::unique_ptr<Relocation>>
Constructor & Destructor Documentation
FunctionOverrideInfo() [1/4]
LIEF::PE::FunctionOverrideInfo::FunctionOverrideInfo () default
Referenced by base_reloc_size(), bdd_offset(), FunctionOverrideInfo(), FunctionOverrideInfo(), operator<<, operator=(), operator=(), original_rva(), and overriding_funcs().
FunctionOverrideInfo() [2/4]
LIEF::PE::FunctionOverrideInfo::FunctionOverrideInfo (uint32_t original_rva, uint32_t bdd_offset, uint32_t base_reloc_size)
References base_reloc_size(), bdd_offset(), and original_rva().
FunctionOverrideInfo() [3/4]
LIEF::PE::FunctionOverrideInfo::FunctionOverrideInfo (const FunctionOverrideInfo &)
References FunctionOverrideInfo().
FunctionOverrideInfo() [4/4]
LIEF::PE::FunctionOverrideInfo::FunctionOverrideInfo (FunctionOverrideInfo &&)
References FunctionOverrideInfo().
~FunctionOverrideInfo()
LIEF::PE::FunctionOverrideInfo::~FunctionOverrideInfo ()
References LIEF_LOCAL.
Member Function Documentation
base_reloc_size() [1/2]
uint32_t LIEF::PE::FunctionOverrideInfo::base_reloc_size () const inline
Size in bytes taken by BaseRelocs.
Referenced by FunctionOverrideInfo().
base_reloc_size() [2/2]
FunctionOverrideInfo & LIEF::PE::FunctionOverrideInfo::base_reloc_size (uint32_t value) inline
References FunctionOverrideInfo().
bdd_offset() [1/2]
uint32_t LIEF::PE::FunctionOverrideInfo::bdd_offset () const inline
Offset into the BDD region.
Referenced by FunctionOverrideInfo().
bdd_offset() [2/2]
FunctionOverrideInfo & LIEF::PE::FunctionOverrideInfo::bdd_offset (uint32_t value) inline
References FunctionOverrideInfo().
functions_rva()
const std::vector< uint32_t > & LIEF::PE::FunctionOverrideInfo::functions_rva () const inline
operator=() [1/2]
FunctionOverrideInfo & LIEF::PE::FunctionOverrideInfo::operator= (const FunctionOverrideInfo &)
References FunctionOverrideInfo().
operator=() [2/2]
FunctionOverrideInfo & LIEF::PE::FunctionOverrideInfo::operator= (FunctionOverrideInfo &&)
References FunctionOverrideInfo().
original_rva() [1/2]
uint32_t LIEF::PE::FunctionOverrideInfo::original_rva () const inline
RVA of the original function.
Referenced by FunctionOverrideInfo().
original_rva() [2/2]
FunctionOverrideInfo & LIEF::PE::FunctionOverrideInfo::original_rva (uint32_t value) inline
References FunctionOverrideInfo().
overriding_funcs()
FunctionOverrideInfo & LIEF::PE::FunctionOverrideInfo::overriding_funcs (std::vector< uint32_t > funcs) inline
References FunctionOverrideInfo().
relocations() [1/2]
it_relocations LIEF::PE::FunctionOverrideInfo::relocations () inline
relocations() [2/2]
it_const_relocations LIEF::PE::FunctionOverrideInfo::relocations () const inline
rva_size()
uint32_t LIEF::PE::FunctionOverrideInfo::rva_size () const inline
Size in bytes taken by RVAs.
to_string()
std::string LIEF::PE::FunctionOverrideInfo::to_string () const
The documentation for this class was generated from the following file:
FunctionOverrideInfo.hpp