LIEF: Library to Instrument Executable Formats: LIEF::logging::Scoped Class Reference
LIEF::logging::Scoped Class Reference
#include <logging.hpp>
Public Member Functions
Scoped (const Scoped &)=delete
Scoped & operator= (const Scoped &)=delete
Scoped (Scoped &&)=delete
Scoped & operator= (Scoped &&)=delete
Scoped (LEVEL level)
const Scoped & set_level (LEVEL lvl) const
~Scoped ()
Constructor & Destructor Documentation
Scoped() [1/3]
LIEF::logging::Scoped::Scoped (const Scoped &) delete
References Scoped().
Referenced by operator=(), operator=(), Scoped(), Scoped(), and set_level().
Scoped() [2/3]
LIEF::logging::Scoped::Scoped (Scoped &&) delete
References Scoped().
Scoped() [3/3]
LIEF::logging::Scoped::Scoped (LEVEL level) inline explicit
References LIEF::logging::get_level(), and set_level().
~Scoped()
LIEF::logging::Scoped::~Scoped () inline
References set_level().
Member Function Documentation
operator=() [1/2]
Scoped & LIEF::logging::Scoped::operator= (const Scoped &) delete
References Scoped().
operator=() [2/2]
Scoped & LIEF::logging::Scoped::operator= (Scoped &&) delete
References Scoped().
set_level()
const Scoped & LIEF::logging::Scoped::set_level (LEVEL lvl) const inline
References Scoped(), and LIEF::logging::set_level().
Referenced by Scoped(), and ~Scoped().
The documentation for this class was generated from the following file:
logging.hpp