LIEF: Library to Instrument Executable Formats: LIEF::PE::ExceptionInfo Class Reference
LIEF::PE::ExceptionInfo Class Reference abstract
This class is the base class for any exception or runtime function entry.
#include <ExceptionInfo.hpp>
Public Types
enum class ARCH { UNKNOWN = 0 , ARM64 , X86_64 }
Arch discriminator for the subclasses.
Public Member Functions
ExceptionInfo ()=delete
ExceptionInfo (const ExceptionInfo &)=default
ExceptionInfo & operator= (const ExceptionInfo &)=default
ExceptionInfo (ExceptionInfo &&)=default
ExceptionInfo & operator= (ExceptionInfo &&)=default
virtual std::unique_ptr< ExceptionInfo > clone () const =0
ExceptionInfo (ARCH arch, uint64_t rva)
ExceptionInfo (ARCH arch)
ARCH arch () const
Target architecture of this exception.
uint32_t rva_start () const
Function start address.
uint64_t offset () const
Offset in the binary where the raw exception information associated with this entry is defined.
virtual std::string to_string () const =0
virtual ~ExceptionInfo ()=default
template<class T>
T * as ()
Helper to downcast an ExceptionInfo into a concrete implementation.
template<class T>
const T * as () const
Static Public Member Functions
static std::unique_ptr< ExceptionInfo > parse (Parser &ctx, BinaryStream &strm)
static std::unique_ptr< ExceptionInfo > parse (Parser &ctx, BinaryStream &strm, Header::MACHINE_TYPES arch)
Detailed Description
This class is the base class for any exception or runtime function entry.
Member Enumeration Documentation
ARCH
enum class LIEF::PE::ExceptionInfo::ARCH strong
Arch discriminator for the subclasses.
Enumerator
UNKNOWN
ARM64
X86_64
Constructor & Destructor Documentation
ExceptionInfo() [1/5]
LIEF::PE::ExceptionInfo::ExceptionInfo () delete
Referenced by as(), LIEF::PE::RuntimeFunctionAArch64::classof(), LIEF::PE::RuntimeFunctionX64::classof(), LIEF::PE::unwind_aarch64::PackedFunction::classof(), LIEF::PE::unwind_aarch64::UnpackedFunction::classof(), ExceptionInfo(), ExceptionInfo(), ExceptionInfo(), operator<<, operator=(), operator=(), LIEF::PE::RuntimeFunctionAArch64::RuntimeFunctionAArch64(), and LIEF::PE::RuntimeFunctionX64::RuntimeFunctionX64().
ExceptionInfo() [2/5]
LIEF::PE::ExceptionInfo::ExceptionInfo (const ExceptionInfo &) default
References ExceptionInfo().
ExceptionInfo() [3/5]
LIEF::PE::ExceptionInfo::ExceptionInfo (ExceptionInfo &&) default
References ExceptionInfo().
ExceptionInfo() [4/5]
LIEF::PE::ExceptionInfo::ExceptionInfo (ARCH arch, uint64_t rva) inline
References arch().
ExceptionInfo() [5/5]
LIEF::PE::ExceptionInfo::ExceptionInfo (ARCH arch) inline
References arch(), and ExceptionInfo().
~ExceptionInfo()
virtual LIEF::PE::ExceptionInfo::~ExceptionInfo () virtual default
Member Function Documentation
arch()
ARCH LIEF::PE::ExceptionInfo::arch () const inline
Target architecture of this exception.
Referenced by ExceptionInfo(), ExceptionInfo(), and parse().
as() [1/2]
template<class T> T * LIEF::PE::ExceptionInfo::as () inline
Helper to downcast an ExceptionInfo into a concrete implementation.
References LIEF::PE::T.
Referenced by as().
as() [2/2]
template<class T> const T * LIEF::PE::ExceptionInfo::as () const inline
References as(), ExceptionInfo(), and LIEF::PE::T.
clone()
virtual std::unique_ptr< ExceptionInfo > LIEF::PE::ExceptionInfo::clone () const pure virtual
Implemented in LIEF::PE::RuntimeFunctionAArch64, LIEF::PE::RuntimeFunctionX64, LIEF::PE::unwind_aarch64::PackedFunction, and LIEF::PE::unwind_aarch64::UnpackedFunction.
offset()
uint64_t LIEF::PE::ExceptionInfo::offset () const inline
Offset in the binary where the raw exception information associated with this entry is defined.
operator=() [1/2]
ExceptionInfo & LIEF::PE::ExceptionInfo::operator= (const ExceptionInfo &) default
References ExceptionInfo().
operator=() [2/2]
ExceptionInfo & LIEF::PE::ExceptionInfo::operator= (ExceptionInfo &&) default
References ExceptionInfo().
parse() [1/2]
std::unique_ptr< ExceptionInfo > LIEF::PE::ExceptionInfo::parse (Parser & ctx, BinaryStream & strm) static
parse() [2/2]
std::unique_ptr< ExceptionInfo > LIEF::PE::ExceptionInfo::parse (Parser & ctx, BinaryStream & strm, Header::MACHINE_TYPES arch) static
References arch().
rva_start()
uint32_t LIEF::PE::ExceptionInfo::rva_start () const inline
Function start address.
Referenced by LIEF::PE::RuntimeFunctionX64::RuntimeFunctionX64(), LIEF::PE::RuntimeFunctionAArch64::rva_end(), and LIEF::PE::RuntimeFunctionX64::size().
to_string()
virtual std::string LIEF::PE::ExceptionInfo::to_string () const pure virtual
Implemented in LIEF::PE::RuntimeFunctionAArch64, LIEF::PE::RuntimeFunctionX64, LIEF::PE::unwind_aarch64::PackedFunction, and LIEF::PE::unwind_aarch64::UnpackedFunction.
The documentation for this class was generated from the following file:
ExceptionInfo.hpp