LIEF: Library to Instrument Executable Formats: LIEF::ART::File Class Reference
LIEF::ART::File Class Reference
#include <File.hpp>
Public Member Functions
File & operator= (const File &copy)=delete
File (const File &copy)=delete
const Header & header () const
Header & header ()
void accept (Visitor &visitor) const override
~File () override
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Additional Inherited Members
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Constructor & Destructor Documentation
File()
LIEF::ART::File::File (const File & copy) delete
References File().
Referenced by File(), operator<<, and operator=().
~File()
LIEF::ART::File::~File () override
Member Function Documentation
accept()
void LIEF::ART::File::accept (Visitor & visitor) const override virtual
Implements LIEF::Object.
header() [1/2]
Header & LIEF::ART::File::header ()
header() [2/2]
const Header & LIEF::ART::File::header () const
operator=()
File & LIEF::ART::File::operator= (const File & copy) delete
References File().
The documentation for this class was generated from the following file:
ART/File.hpp