LIEF: Library to Instrument Executable Formats: LIEF::assembly::x86::Operand::Iterator Class Reference
LIEF::assembly::x86::Operand::Iterator Class Reference final
Forward iterator that outputs x86 Operand as std::unique_ptr
#include <Operand.hpp>
Public Types
using implementation = details::OperandIt
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, std::unique_ptr< Operand >, std::ptrdiff_t, Operand *, std::unique_ptr< Operand > >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Public Member Functions
Iterator ()
Iterator (std::unique_ptr< details::OperandIt > impl)
Iterator (const Iterator &)
Iterator & operator= (const Iterator &)
Iterator (Iterator &&) noexcept
Iterator & operator= (Iterator &&) noexcept
~Iterator ()
Iterator & operator++ ()
std::unique_ptr< Operand > operator* () const
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, std::unique_ptr< Operand >, std::ptrdiff_t, Operand *, std::unique_ptr< Operand > >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Detailed Description
Forward iterator that outputs x86 Operand as std::unique_ptr
Member Typedef Documentation
implementation
using LIEF::assembly::x86::Operand::Iterator::implementation = details::OperandIt
Constructor & Destructor Documentation
Iterator() [1/4]
LIEF::assembly::x86::Operand::Iterator::Iterator ()
References LIEF_API.
Referenced by Iterator(), Iterator(), operator!=, operator++(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/4]
LIEF::assembly::x86::Operand::Iterator::Iterator (std::unique_ptr< details::OperandIt > impl)
References LIEF_API.
Iterator() [3/4]
LIEF::assembly::x86::Operand::Iterator::Iterator (const Iterator &)
References Iterator(), and LIEF_API.
Iterator() [4/4]
LIEF::assembly::x86::Operand::Iterator::Iterator (Iterator &&) noexcept
References Iterator(), and LIEF_API.
~Iterator()
LIEF::assembly::x86::Operand::Iterator::~Iterator ()
References Iterator(), and LIEF_API.
Member Function Documentation
operator*()
std::unique_ptr< Operand > LIEF::assembly::x86::Operand::Iterator::operator* () const
References LIEF_API.
operator++()
Iterator & LIEF::assembly::x86::Operand::Iterator::operator++ ()
References Iterator(), and LIEF_API.
operator=() [1/2]
Iterator & LIEF::assembly::x86::Operand::Iterator::operator= (const Iterator &)
References Iterator(), and LIEF_API.
operator=() [2/2]
Iterator & LIEF::assembly::x86::Operand::Iterator::operator= (Iterator &&) noexcept
References Iterator(), and LIEF_API.
The documentation for this class was generated from the following file:
x86/Operand.hpp