LIEF: Library to Instrument Executable Formats: LIEF::ELF::Parser Class Reference
LIEF::ELF::Parser Class Reference
Class which parses and transforms an ELF file into a ELF::Binary object.
#include <Parser.hpp>
Public Types
enum ELF_TYPE { ELF_UNKNOWN , ELF32 , ELF64 }
Public Member Functions
Parser & operator= (const Parser &)=delete
Parser (const Parser &)=delete
~Parser () override
Static Public Member Functions
static std::unique_ptr< Binary > parse (const std::string &file, const ParserConfig &conf=ParserConfig::all())
Parse an ELF file and return a LIEF::ELF::Binary object.
static std::unique_ptr< Binary > parse (const std::vector< uint8_t > &data, const ParserConfig &conf=ParserConfig::all())
Parse the given raw data as an ELF binary and return a LIEF::ELF::Binary object.
static std::unique_ptr< Binary > parse (std::unique_ptr< BinaryStream > stream, const ParserConfig &conf=ParserConfig::all())
Parse the ELF binary from the given stream and return a LIEF::ELF::Binary object.
Static Public Member Functions inherited from LIEF::Parser
static std::unique_ptr< Binary > parse (const std::string &filename)
Construct an LIEF::Binary from the given filename.
static std::unique_ptr< Binary > parse (const std::vector< uint8_t > &raw)
Construct an LIEF::Binary from the given raw data.
static std::unique_ptr< Binary > parse (std::unique_ptr< BinaryStream > stream)
Construct an LIEF::Binary from the given stream.
Static Public Attributes
static constexpr uint32_t NB_MAX_SYMBOLS = 1000000
static constexpr uint32_t DELTA_NB_SYMBOLS = 3000
static constexpr uint32_t NB_MAX_BUCKETS = NB_MAX_SYMBOLS
static constexpr uint32_t NB_MAX_CHAINS = 1000000
static constexpr uint32_t NB_MAX_SEGMENTS = 10000
static constexpr uint32_t NB_MAX_RELOCATIONS = 3000000
static constexpr uint32_t NB_MAX_DYNAMIC_ENTRIES = 1000
static constexpr uint32_t MAX_SEGMENT_SIZE = 3_GB
Detailed Description
Class which parses and transforms an ELF file into a ELF::Binary object.
Member Enumeration Documentation
ELF_TYPE
enum LIEF::ELF::Parser::ELF_TYPE
Enumerator
ELF_UNKNOWN
ELF32
ELF64
Constructor & Destructor Documentation
Parser()
LIEF::ELF::Parser::Parser (const Parser &) delete
References OAT::Parser.
~Parser()
LIEF::ELF::Parser::~Parser () override virtual
Reimplemented from LIEF::Parser.
References LIEF_LOCAL, and OAT::Parser.
Member Function Documentation
operator=()
Parser & LIEF::ELF::Parser::operator= (const Parser &) delete
References OAT::Parser.
parse() [1/3]
std::unique_ptr< Binary > LIEF::ELF::Parser::parse (const std::string & file, const ParserConfig & conf = ParserConfig::all()) static
Parse an ELF file and return a LIEF::ELF::Binary object.
For weird binaries (e.g. sectionless) you can choose which method to use for counting dynamic symbols
Parameters
[in] file Path to the ELF binary
[in] conf Optional configuration for the parser
Returns
LIEF::ELF::Binary as a unique_ptr
References LIEF::ELF::ParserConfig::all().
parse() [2/3]
std::unique_ptr< Binary > LIEF::ELF::Parser::parse (const std::vector< uint8_t > & data, const ParserConfig & conf = ParserConfig::all()) static
Parse the given raw data as an ELF binary and return a LIEF::ELF::Binary object.
For weird binaries (e.g. sectionless) you can choose which method use to count dynamic symbols
Parameters
[in] data Raw ELF as a std::vector of uint8_t
[in] conf Optional configuration for the parser
Returns
LIEF::ELF::Binary
References LIEF::ELF::ParserConfig::all().
parse() [3/3]
std::unique_ptr< Binary > LIEF::ELF::Parser::parse (std::unique_ptr< BinaryStream > stream, const ParserConfig & conf = ParserConfig::all()) static
Parse the ELF binary from the given stream and return a LIEF::ELF::Binary object.
For weird binaries (e.g. sectionless) you can choose which method use to count dynamic symbols
Parameters
[in] stream The stream which wraps the ELF binary
[in] conf Optional configuration for the parser
Returns
LIEF::ELF::Binary
References LIEF::ELF::ParserConfig::all().
Member Data Documentation
DELTA_NB_SYMBOLS
uint32_t LIEF::ELF::Parser::DELTA_NB_SYMBOLS = 3000 static constexpr
MAX_SEGMENT_SIZE
uint32_t LIEF::ELF::Parser::MAX_SEGMENT_SIZE = 3_GB static constexpr
NB_MAX_BUCKETS
uint32_t LIEF::ELF::Parser::NB_MAX_BUCKETS = NB_MAX_SYMBOLS static constexpr
NB_MAX_CHAINS
uint32_t LIEF::ELF::Parser::NB_MAX_CHAINS = 1000000 static constexpr
NB_MAX_DYNAMIC_ENTRIES
uint32_t LIEF::ELF::Parser::NB_MAX_DYNAMIC_ENTRIES = 1000 static constexpr
NB_MAX_RELOCATIONS
uint32_t LIEF::ELF::Parser::NB_MAX_RELOCATIONS = 3000000 static constexpr
NB_MAX_SEGMENTS
uint32_t LIEF::ELF::Parser::NB_MAX_SEGMENTS = 10000 static constexpr
NB_MAX_SYMBOLS
uint32_t LIEF::ELF::Parser::NB_MAX_SYMBOLS = 1000000 static constexpr
The documentation for this class was generated from the following file:
ELF/Parser.hpp