LIEF: Library to Instrument Executable Formats: LIEF::ELF::SymbolVersionAux Class Reference
LIEF::ELF::SymbolVersionAux Class Reference
Class which represents an Auxiliary Symbol version.
#include <SymbolVersionAux.hpp>
Public Member Functions
SymbolVersionAux (std::string name)
SymbolVersionAux ()=default
~SymbolVersionAux () override=default
SymbolVersionAux & operator= (const SymbolVersionAux &)=default
SymbolVersionAux (const SymbolVersionAux &)=default
const std::string & name () const
Symbol's aux name (e.g. GLIBC_2.2.5).
void name (std::string name)
void accept (Visitor &visitor) const override
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Additional Inherited Members
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Detailed Description
Class which represents an Auxiliary Symbol version.
Constructor & Destructor Documentation
SymbolVersionAux() [1/3]
LIEF::ELF::SymbolVersionAux::SymbolVersionAux (std::string name) inline
References name().
Referenced by operator<<, operator=(), and SymbolVersionAux().
SymbolVersionAux() [2/3]
LIEF::ELF::SymbolVersionAux::SymbolVersionAux () default
~SymbolVersionAux()
LIEF::ELF::SymbolVersionAux::~SymbolVersionAux () override default
SymbolVersionAux() [3/3]
LIEF::ELF::SymbolVersionAux::SymbolVersionAux (const SymbolVersionAux &) default
References SymbolVersionAux().
Member Function Documentation
accept()
void LIEF::ELF::SymbolVersionAux::accept (Visitor & visitor) const override virtual
Implements LIEF::Object.
Reimplemented in LIEF::ELF::SymbolVersionAuxRequirement.
References LIEF_API.
name() [1/2]
const std::string & LIEF::ELF::SymbolVersionAux::name () const inline
Symbol's aux name (e.g. GLIBC_2.2.5).
Referenced by name(), operator<<, and SymbolVersionAux().
name() [2/2]
void LIEF::ELF::SymbolVersionAux::name (std::string name) inline
References name().
operator=()
SymbolVersionAux & LIEF::ELF::SymbolVersionAux::operator= (const SymbolVersionAux &) default
References SymbolVersionAux().
The documentation for this class was generated from the following file:
SymbolVersionAux.hpp