LIEF: Library to Instrument Executable Formats: LIEF::MachO::LazyLoadDylibInfo::Fixup Class Reference
LIEF::MachO::LazyLoadDylibInfo::Fixup Class Reference
A single lazy-binding fixup decoded from the chain referenced by chain_start_image_offset and decoded according to pointer_format.
#include <LazyLoadDylibInfo.hpp>
Public Member Functions
Fixup ()=default
Fixup (uint64_t address, uint32_t ordinal, std::string symbol, bool is_auth)
Fixup (const Fixup &)=default
Fixup & operator= (const Fixup &)=default
Fixup (Fixup &&) noexcept=default
Fixup & operator= (Fixup &&) noexcept=default
~Fixup ()=default
uint64_t address () const
Virtual address of the slot bound by this fixup.
void address (uint64_t value)
uint32_t ordinal () const
Index of the bound symbol in the symbols table of LazyLoadDylibInfo.
const std::string & symbol () const
Name of the bound symbol, resolved from ordinal() (empty if the ordinal is out of the symbols() range).
bool is_auth () const
Whether the bound pointer is authenticated (arm64e PAC).
std::string to_string () const
Detailed Description
A single lazy-binding fixup decoded from the chain referenced by chain_start_image_offset and decoded according to pointer_format.
Constructor & Destructor Documentation
Fixup() [1/4]
LIEF::MachO::LazyLoadDylibInfo::Fixup::Fixup () default
Referenced by Fixup(), Fixup(), operator<<, operator=(), operator=(), and ~Fixup().
Fixup() [2/4]
LIEF::MachO::LazyLoadDylibInfo::Fixup::Fixup (uint64_t address, uint32_t ordinal, std::string symbol, bool is_auth) inline
References address(), is_auth(), ordinal(), and symbol().
Fixup() [3/4]
LIEF::MachO::LazyLoadDylibInfo::Fixup::Fixup (const Fixup &) default
References Fixup().
Fixup() [4/4]
LIEF::MachO::LazyLoadDylibInfo::Fixup::Fixup (Fixup &&) default noexcept
References Fixup().
~Fixup()
LIEF::MachO::LazyLoadDylibInfo::Fixup::~Fixup () default
References Fixup().
Member Function Documentation
address() [1/2]
uint64_t LIEF::MachO::LazyLoadDylibInfo::Fixup::address () const inline
Virtual address of the slot bound by this fixup.
References address().
Referenced by address(), and Fixup().
address() [2/2]
void LIEF::MachO::LazyLoadDylibInfo::Fixup::address (uint64_t value) inline
is_auth()
bool LIEF::MachO::LazyLoadDylibInfo::Fixup::is_auth () const inline
Whether the bound pointer is authenticated (arm64e PAC).
Referenced by Fixup().
operator=() [1/2]
Fixup & LIEF::MachO::LazyLoadDylibInfo::Fixup::operator= (const Fixup &) default
References Fixup().
operator=() [2/2]
Fixup & LIEF::MachO::LazyLoadDylibInfo::Fixup::operator= (Fixup &&) default noexcept
References Fixup().
ordinal()
uint32_t LIEF::MachO::LazyLoadDylibInfo::Fixup::ordinal () const inline
Index of the bound symbol in the symbols table of LazyLoadDylibInfo.
Referenced by Fixup().
symbol()
const std::string & LIEF::MachO::LazyLoadDylibInfo::Fixup::symbol () const inline
Name of the bound symbol, resolved from ordinal() (empty if the ordinal is out of the symbols() range).
References LIEF_LIFETIMEBOUND.
Referenced by Fixup().
to_string()
std::string LIEF::MachO::LazyLoadDylibInfo::Fixup::to_string () const
Referenced by operator<<.
The documentation for this class was generated from the following file:
LazyLoadDylibInfo.hpp