LIEF: Library to Instrument Executable Formats: LIEF::COFF::BigObjHeader Class Reference
LIEF::COFF::BigObjHeader Class Reference
This class represents the header for a COFF object compiled with /bigobj support (i.e. the number of sections can exceed 65536).
#include <BigObjHeader.hpp>
Public Member Functions
BigObjHeader ()
BigObjHeader & operator= (const BigObjHeader &)=default
BigObjHeader (const BigObjHeader &)=default
BigObjHeader & operator= (BigObjHeader &&)=default
BigObjHeader (BigObjHeader &&)=default
std::unique_ptr< Header > clone () const override
uint16_t version () const
The version of this header which must be >= 2.
span< const uint8_t > uuid () const
Originally named ClassID, this uuid should match: {D1BAA1C7-BAEE-4ba9-AF20-FAF66AA4DCB8}.
uint32_t sizeof_data () const
Size of data that follows the header.
uint32_t flags () const
1 means that it contains metadata
uint32_t metadata_size () const
Size of CLR metadata.
uint32_t metadata_offset () const
Offset of CLR metadata.
void version (uint16_t value)
void sizeof_data (uint32_t value)
void flags (uint32_t value)
void metadata_size (uint32_t value)
void metadata_offset (uint32_t value)
~BigObjHeader () override=default
std::string to_string () const override
Public Member Functions inherited from LIEF::COFF::Header
Header ()=default
Header (KIND kind)
Header & operator= (const Header &)=default
Header (const Header &)=default
Header & operator= (Header &&)=default
Header (Header &&)=default
KIND kind () const
The type of this header: whether it is regular or using the /bigobj format.
MACHINE_TYPES machine () const
The machine type targeted by this COFF.
uint32_t nb_sections () const
The number of sections.
uint32_t pointerto_symbol_table () const
Offset of the symbols table.
uint32_t nb_symbols () const
Number of symbols (including auxiliary symbols).
uint32_t timedatestamp () const
Timestamp when the COFF has been generated.
void machine (MACHINE_TYPES machine)
void nb_sections (uint32_t value)
void pointerto_symbol_table (uint32_t value)
void nb_symbols (uint32_t value)
void timedatestamp (uint32_t value)
template<class T>
const T * as () const
virtual ~Header ()=default
Static Public Member Functions
static std::unique_ptr< BigObjHeader > create (BinaryStream &stream)
static bool classof (const Header *header)
Static Public Member Functions inherited from LIEF::COFF::Header
static std::unique_ptr< Header > create (BinaryStream &stream)
Create a header from the given stream.
static std::unique_ptr< Header > create (BinaryStream &stream, KIND kind)
Static Public Attributes
static constexpr auto UUID_SZ = 16
Additional Inherited Members
Public Types inherited from LIEF::COFF::Header
enum class KIND { UNKNOWN = 0 , REGULAR , BIGOBJ }
using MACHINE_TYPES = LIEF::PE::Header::MACHINE_TYPES
The different architectures (mirrored from PE).
Detailed Description
This class represents the header for a COFF object compiled with /bigobj support (i.e. the number of sections can exceed 65536).
The raw definition of the bigobj header is located in winnt.h and named ANON_OBJECT_HEADER_BIGOBJ
Constructor & Destructor Documentation
BigObjHeader() [1/3]
LIEF::COFF::BigObjHeader::BigObjHeader () inline
References LIEF::COFF::Header::Header().
Referenced by BigObjHeader(), BigObjHeader(), clone(), operator=(), and operator=().
BigObjHeader() [2/3]
LIEF::COFF::BigObjHeader::BigObjHeader (const BigObjHeader &) default
References BigObjHeader().
BigObjHeader() [3/3]
LIEF::COFF::BigObjHeader::BigObjHeader (BigObjHeader &&) default
References BigObjHeader().
~BigObjHeader()
LIEF::COFF::BigObjHeader::~BigObjHeader () override default
Member Function Documentation
classof()
bool LIEF::COFF::BigObjHeader::classof (const Header * header) inline static
References LIEF::COFF::Header::BIGOBJ, LIEF::COFF::Header::Header(), and LIEF::COFF::Header::kind().
clone()
std::unique_ptr< Header > LIEF::COFF::BigObjHeader::clone () const inline override virtual
Implements LIEF::COFF::Header.
References BigObjHeader().
create()
std::unique_ptr< BigObjHeader > LIEF::COFF::BigObjHeader::create (BinaryStream & stream) static
flags() [1/2]
uint32_t LIEF::COFF::BigObjHeader::flags () const inline
1 means that it contains metadata
flags() [2/2]
void LIEF::COFF::BigObjHeader::flags (uint32_t value) inline
metadata_offset() [1/2]
uint32_t LIEF::COFF::BigObjHeader::metadata_offset () const inline
Offset of CLR metadata.
metadata_offset() [2/2]
void LIEF::COFF::BigObjHeader::metadata_offset (uint32_t value) inline
metadata_size() [1/2]
uint32_t LIEF::COFF::BigObjHeader::metadata_size () const inline
Size of CLR metadata.
metadata_size() [2/2]
void LIEF::COFF::BigObjHeader::metadata_size (uint32_t value) inline
operator=() [1/2]
BigObjHeader & LIEF::COFF::BigObjHeader::operator= (BigObjHeader &&) default
References BigObjHeader().
operator=() [2/2]
BigObjHeader & LIEF::COFF::BigObjHeader::operator= (const BigObjHeader &) default
References BigObjHeader().
sizeof_data() [1/2]
uint32_t LIEF::COFF::BigObjHeader::sizeof_data () const inline
Size of data that follows the header.
sizeof_data() [2/2]
void LIEF::COFF::BigObjHeader::sizeof_data (uint32_t value) inline
to_string()
std::string LIEF::COFF::BigObjHeader::to_string () const override virtual
Reimplemented from LIEF::COFF::Header.
uuid()
span< const uint8_t > LIEF::COFF::BigObjHeader::uuid () const inline
Originally named ClassID, this uuid should match: {D1BAA1C7-BAEE-4ba9-AF20-FAF66AA4DCB8}.
version() [1/2]
uint16_t LIEF::COFF::BigObjHeader::version () const inline
The version of this header which must be >= 2.
version() [2/2]
void LIEF::COFF::BigObjHeader::version (uint16_t value) inline
Member Data Documentation
UUID_SZ
auto LIEF::COFF::BigObjHeader::UUID_SZ = 16 static constexpr
The documentation for this class was generated from the following file:
BigObjHeader.hpp