LIEF: Library to Instrument Executable Formats: LIEF::objc::Class::Iterator Class Reference
LIEF::objc::Class::Iterator Class Reference final
#include <Class.hpp>
Public Types
using implementation = details::ClassIt
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::bidirectional_iterator_tag, Class, std::ptrdiff_t, const Class *, const Class & >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Public Member Functions
Iterator ()
Iterator (std::unique_ptr< details::ClassIt > impl)
Iterator (const Iterator &)
Iterator & operator= (const Iterator &)
Iterator (Iterator &&) noexcept
Iterator & operator= (Iterator &&) noexcept
~Iterator ()
Iterator & operator++ ()
Iterator & operator-- ()
const Class & operator* () const
const Class * operator-> () const
std::unique_ptr< Class > yield ()
Transfer ownership of the class at the current position to the caller. Returns nullptr if the iterator is past-the-end.
DerivedT operator++ (int)
DerivedT operator-- (int)
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::bidirectional_iterator_tag, Class, std::ptrdiff_t, const Class *, const Class & >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Member Typedef Documentation
implementation
using LIEF::objc::Class::Iterator::implementation = details::ClassIt
Constructor & Destructor Documentation
Iterator() [1/4]
LIEF::objc::Class::Iterator::Iterator ()
References LIEF_API.
Referenced by Iterator(), Iterator(), operator!=, operator++(), operator--(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/4]
LIEF::objc::Class::Iterator::Iterator (std::unique_ptr< details::ClassIt > impl)
References LIEF_API.
Iterator() [3/4]
LIEF::objc::Class::Iterator::Iterator (const Iterator &)
References Iterator(), and LIEF_API.
Iterator() [4/4]
LIEF::objc::Class::Iterator::Iterator (Iterator &&) noexcept
References Iterator(), and LIEF_API.
~Iterator()
LIEF::objc::Class::Iterator::~Iterator ()
References Iterator(), and LIEF_API.
Member Function Documentation
operator*()
const Class & LIEF::objc::Class::Iterator::operator* () const
References LIEF::objc::Class::Class(), and LIEF_API.
operator++() [1/2]
Iterator & LIEF::objc::Class::Iterator::operator++ ()
References Iterator(), and LIEF_API.
operator++() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator++ (int) inline
operator--() [1/2]
Iterator & LIEF::objc::Class::Iterator::operator-- ()
References Iterator(), and LIEF_API.
operator--() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator-- (int) inline
operator->()
const Class * LIEF::objc::Class::Iterator::operator-> () const
References LIEF::objc::Class::Class(), and LIEF_API.
operator=() [1/2]
Iterator & LIEF::objc::Class::Iterator::operator= (const Iterator &)
References Iterator(), and LIEF_API.
operator=() [2/2]
Iterator & LIEF::objc::Class::Iterator::operator= (Iterator &&) noexcept
References Iterator(), and LIEF_API.
yield()
std::unique_ptr< Class > LIEF::objc::Class::Iterator::yield ()
Transfer ownership of the class at the current position to the caller. Returns nullptr if the iterator is past-the-end.
References LIEF_API.
The documentation for this class was generated from the following file:
ObjC/Class.hpp