LIEF: Library to Instrument Executable Formats: LIEF::COFF::AuxiliaryFile Class Reference
LIEF::COFF::AuxiliaryFile Class Reference
This auxiliary symbol represents a filename (auxiliary format 4).
#include <AuxiliaryFile.hpp>
Public Member Functions
AuxiliaryFile ()
AuxiliaryFile (std::string file)
AuxiliaryFile (const AuxiliaryFile &)=default
AuxiliaryFile & operator= (const AuxiliaryFile &)=default
AuxiliaryFile (AuxiliaryFile &&)=default
AuxiliaryFile & operator= (AuxiliaryFile &&)=default
std::unique_ptr< AuxiliarySymbol > clone () const override
const std::string & filename () const
The associated filename.
AuxiliaryFile & filename (std::string file)
std::string to_string () const override
~AuxiliaryFile () override=default
Public Member Functions inherited from LIEF::COFF::AuxiliarySymbol
AuxiliarySymbol ()=default
AuxiliarySymbol (std::vector< uint8_t > payload)
AuxiliarySymbol (const AuxiliarySymbol &)=default
AuxiliarySymbol & operator= (const AuxiliarySymbol &)=default
AuxiliarySymbol (AuxiliarySymbol &&)=default
AuxiliarySymbol & operator= (AuxiliarySymbol &&)=default
AuxiliarySymbol (TYPE ty)
TYPE type () const
span< const uint8_t > payload () const
For unknown type only, return the raw representation of this symbol.
span< uint8_t > payload ()
virtual ~AuxiliarySymbol ()=default
template<class T>
const T * as () const
Helper to downcast a AuxiliarySymbol into a concrete implementation.
template<class T>
T * as ()
Static Public Member Functions
static std::unique_ptr< AuxiliaryFile > parse (const std::vector< uint8_t > &payload)
static bool classof (const AuxiliarySymbol *sym)
Static Public Member Functions inherited from LIEF::COFF::AuxiliarySymbol
static std::unique_ptr< AuxiliarySymbol > parse (Symbol &sym, std::vector< uint8_t > payload)
static TYPE get_aux_type (const Symbol &sym)
Additional Inherited Members
Public Types inherited from LIEF::COFF::AuxiliarySymbol
enum class TYPE {
UNKNOWN = 0 , CLR_TOKEN , FUNC_DEF , BF_AND_EF ,
WEAK_EXTERNAL , FILE , SEC_DEF
}
Type discriminator for the subclasses.
Detailed Description
This auxiliary symbol represents a filename (auxiliary format 4).
The Symbol::name itself should start with .file, and this auxiliary record gives the name of a source-code file.
Reference: https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#auxiliary-format-4-files
Constructor & Destructor Documentation
AuxiliaryFile() [1/4]
LIEF::COFF::AuxiliaryFile::AuxiliaryFile () inline
References LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol().
Referenced by AuxiliaryFile(), AuxiliaryFile(), clone(), filename(), operator=(), and operator=().
AuxiliaryFile() [2/4]
LIEF::COFF::AuxiliaryFile::AuxiliaryFile (std::string file) inline
References LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol().
AuxiliaryFile() [3/4]
LIEF::COFF::AuxiliaryFile::AuxiliaryFile (const AuxiliaryFile &) default
References AuxiliaryFile().
AuxiliaryFile() [4/4]
LIEF::COFF::AuxiliaryFile::AuxiliaryFile (AuxiliaryFile &&) default
References AuxiliaryFile().
~AuxiliaryFile()
LIEF::COFF::AuxiliaryFile::~AuxiliaryFile () override default
Member Function Documentation
classof()
bool LIEF::COFF::AuxiliaryFile::classof (const AuxiliarySymbol * sym) inline static
References LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol(), LIEF::COFF::AuxiliarySymbol::FILE, and LIEF::COFF::AuxiliarySymbol::type().
clone()
std::unique_ptr< AuxiliarySymbol > LIEF::COFF::AuxiliaryFile::clone () const inline override virtual
Reimplemented from LIEF::COFF::AuxiliarySymbol.
References AuxiliaryFile().
filename() [1/2]
const std::string & LIEF::COFF::AuxiliaryFile::filename () const inline
The associated filename.
filename() [2/2]
AuxiliaryFile & LIEF::COFF::AuxiliaryFile::filename (std::string file) inline
References AuxiliaryFile().
operator=() [1/2]
AuxiliaryFile & LIEF::COFF::AuxiliaryFile::operator= (AuxiliaryFile &&) default
References AuxiliaryFile().
operator=() [2/2]
AuxiliaryFile & LIEF::COFF::AuxiliaryFile::operator= (const AuxiliaryFile &) default
References AuxiliaryFile().
parse()
std::unique_ptr< AuxiliaryFile > LIEF::COFF::AuxiliaryFile::parse (const std::vector< uint8_t > & payload) static
References LIEF::COFF::AuxiliarySymbol::payload().
to_string()
std::string LIEF::COFF::AuxiliaryFile::to_string () const inline override virtual
Reimplemented from LIEF::COFF::AuxiliarySymbol.
The documentation for this class was generated from the following file:
AuxiliaryFile.hpp