LIEF: Library to Instrument Executable Formats: LIEF::PE::unwind_aarch64::UnpackedFunction Class Reference
LIEF::PE::unwind_aarch64::UnpackedFunction Class Reference
This class represents an unpacked AArch64 exception entry.
#include <UnpackedFunction.hpp>
Classes
struct epilog_scope_t
This structure describes an epilog scope.
Public Types
using epilog_scopes_t = std::vector<epilog_scope_t>
using it_epilog_scopes = ref_iterator<epilog_scopes_t&>
using it_const_epilog_scopes = const_ref_iterator<const epilog_scopes_t&>
Public Types inherited from LIEF::PE::RuntimeFunctionAArch64
enum class PACKED_FLAGS { UNPACKED = 0 , PACKED = 1 , PACKED_FRAGMENT = 2 , RESERVED = 3 }
Public Types inherited from LIEF::PE::ExceptionInfo
enum class ARCH { UNKNOWN = 0 , ARM64 , X86_64 }
Arch discriminator for the subclasses.
Public Member Functions
UnpackedFunction (uint32_t rva, uint32_t length)
UnpackedFunction (const UnpackedFunction &)=default
UnpackedFunction & operator= (const UnpackedFunction &)=default
UnpackedFunction (UnpackedFunction &&)=default
UnpackedFunction & operator= (UnpackedFunction &&)=default
~UnpackedFunction () override=default
std::unique_ptr< ExceptionInfo > clone () const override
std::string to_string () const override
uint32_t xdata_rva () const
RVA where this unpacked data is located (usually pointing in .xdata).
uint32_t version () const
Describes the version of the remaining .xdata.
uint8_t X () const
1-bit field that indicates the presence (1) or absence (0) of exception data.
uint8_t E () const
1-bit field that indicates that information describing a single epilog is packed into the header (1) rather than requiring more scope words later (0).
uint16_t epilog_count () const
If E() == 0, specifies the count of the total number of epilog scopes. Otherwise, return 0
uint16_t epilog_offset () const
If E() == 1, index of the first unwind code that describes the one and only epilog.
uint32_t code_words () const
Number of 32-bit words needed to contain all of the unwind codes.
uint32_t exception_handler () const
Exception handler RVA (if any).
span< const uint8_t > unwind_code () const
Bytes that contain the unwind codes.
span< uint8_t > unwind_code ()
bool is_extended () const
Whether it uses 2-words encoding.
uint64_t epilog_scopes_offset () const
uint64_t unwind_code_offset () const
uint64_t exception_handler_offset () const
it_epilog_scopes epilog_scopes ()
Iterator over the epilog scopes.
it_const_epilog_scopes epilog_scopes () const
UnpackedFunction & xdata_rva (uint32_t value)
UnpackedFunction & version (uint32_t value)
UnpackedFunction & X (uint8_t value)
UnpackedFunction & E (uint8_t value)
UnpackedFunction & epilog_cnt_offset (uint16_t value)
UnpackedFunction & code_words (uint32_t value)
UnpackedFunction & exception_handler (uint32_t value)
UnpackedFunction & epilog_scopes (epilog_scopes_t scopes)
UnpackedFunction & unwind_code (std::vector< uint8_t > code)
UnpackedFunction & is_extended (bool value)
Public Member Functions inherited from LIEF::PE::RuntimeFunctionAArch64
RuntimeFunctionAArch64 (uint64_t RVA, uint32_t length, PACKED_FLAGS flag)
RuntimeFunctionAArch64 (const RuntimeFunctionAArch64 &)=default
RuntimeFunctionAArch64 & operator= (const RuntimeFunctionAArch64 &)=default
RuntimeFunctionAArch64 (RuntimeFunctionAArch64 &&)=default
RuntimeFunctionAArch64 & operator= (RuntimeFunctionAArch64 &&)=default
uint32_t length () const
Length of the function in bytes.
PACKED_FLAGS flag () const
Flag describing the format the unwind data.
uint32_t rva_end () const
Function end address.
~RuntimeFunctionAArch64 ()=default
Public Member Functions inherited from LIEF::PE::ExceptionInfo
ExceptionInfo ()=delete
ExceptionInfo (const ExceptionInfo &)=default
ExceptionInfo & operator= (const ExceptionInfo &)=default
ExceptionInfo (ExceptionInfo &&)=default
ExceptionInfo & operator= (ExceptionInfo &&)=default
ExceptionInfo (ARCH arch, uint64_t rva)
ExceptionInfo (ARCH arch)
ARCH arch () const
Target architecture of this exception.
uint32_t rva_start () const
Function start address.
uint64_t offset () const
Offset in the binary where the raw exception information associated with this entry is defined.
virtual ~ExceptionInfo ()=default
template<class T>
T * as ()
Helper to downcast an ExceptionInfo into a concrete implementation.
template<class T>
const T * as () const
Static Public Member Functions
static std::unique_ptr< UnpackedFunction > parse (Parser &ctx, BinaryStream &strm, uint32_t xdata_rva, uint32_t rva)
static bool classof (const ExceptionInfo *info)
Static Public Member Functions inherited from LIEF::PE::RuntimeFunctionAArch64
static std::unique_ptr< RuntimeFunctionAArch64 > parse (Parser &ctx, BinaryStream &strm)
static bool classof (const ExceptionInfo *info)
Static Public Member Functions inherited from LIEF::PE::ExceptionInfo
static std::unique_ptr< ExceptionInfo > parse (Parser &ctx, BinaryStream &strm)
static std::unique_ptr< ExceptionInfo > parse (Parser &ctx, BinaryStream &strm, Header::MACHINE_TYPES arch)
Detailed Description
This class represents an unpacked AArch64 exception entry.
Reference: https://learn.microsoft.com/en-us/cpp/build/arm64-exception-handling?view=msvc-170#xdata-records
Member Typedef Documentation
epilog_scopes_t
using LIEF::PE::unwind_aarch64::UnpackedFunction::epilog_scopes_t = std::vector<epilog_scope_t>
it_const_epilog_scopes
using LIEF::PE::unwind_aarch64::UnpackedFunction::it_const_epilog_scopes = const_ref_iterator<const epilog_scopes_t&>
it_epilog_scopes
using LIEF::PE::unwind_aarch64::UnpackedFunction::it_epilog_scopes = ref_iterator<epilog_scopes_t&>
Constructor & Destructor Documentation
UnpackedFunction() [1/3]
LIEF::PE::unwind_aarch64::UnpackedFunction::UnpackedFunction (uint32_t rva, uint32_t length) inline
References LIEF::PE::RuntimeFunctionAArch64::length(), and LIEF::PE::RuntimeFunctionAArch64::RuntimeFunctionAArch64().
Referenced by clone(), code_words(), E(), epilog_cnt_offset(), epilog_scopes(), exception_handler(), is_extended(), operator=(), operator=(), UnpackedFunction(), UnpackedFunction(), unwind_code(), version(), X(), and xdata_rva().
UnpackedFunction() [2/3]
LIEF::PE::unwind_aarch64::UnpackedFunction::UnpackedFunction (const UnpackedFunction &) default
References UnpackedFunction().
UnpackedFunction() [3/3]
LIEF::PE::unwind_aarch64::UnpackedFunction::UnpackedFunction (UnpackedFunction &&) default
References UnpackedFunction().
~UnpackedFunction()
LIEF::PE::unwind_aarch64::UnpackedFunction::~UnpackedFunction () override default
Member Function Documentation
classof()
bool LIEF::PE::unwind_aarch64::UnpackedFunction::classof (const ExceptionInfo * info) inline static
References LIEF::PE::RuntimeFunctionAArch64::classof(), LIEF::PE::ExceptionInfo::ExceptionInfo(), LIEF::PE::RuntimeFunctionAArch64::RuntimeFunctionAArch64(), and LIEF::PE::RuntimeFunctionAArch64::UNPACKED.
clone()
std::unique_ptr< ExceptionInfo > LIEF::PE::unwind_aarch64::UnpackedFunction::clone () const inline override virtual
Reimplemented from LIEF::PE::RuntimeFunctionAArch64.
References UnpackedFunction().
code_words() [1/2]
uint32_t LIEF::PE::unwind_aarch64::UnpackedFunction::code_words () const inline
Number of 32-bit words needed to contain all of the unwind codes.
code_words() [2/2]
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::code_words (uint32_t value) inline
References UnpackedFunction().
E() [1/2]
uint8_t LIEF::PE::unwind_aarch64::UnpackedFunction::E () const inline
1-bit field that indicates that information describing a single epilog is packed into the header (1) rather than requiring more scope words later (0).
Referenced by epilog_count(), and epilog_offset().
E() [2/2]
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::E (uint8_t value) inline
References UnpackedFunction().
epilog_cnt_offset()
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::epilog_cnt_offset (uint16_t value) inline
References epilog_offset_, and UnpackedFunction().
epilog_count()
uint16_t LIEF::PE::unwind_aarch64::UnpackedFunction::epilog_count () const inline
If E() == 0, specifies the count of the total number of epilog scopes. Otherwise, return 0
References E(), and epilog_count_.
epilog_offset()
uint16_t LIEF::PE::unwind_aarch64::UnpackedFunction::epilog_offset () const inline
If E() == 1, index of the first unwind code that describes the one and only epilog.
References E(), and epilog_offset_.
epilog_scopes() [1/3]
it_epilog_scopes LIEF::PE::unwind_aarch64::UnpackedFunction::epilog_scopes () inline
Iterator over the epilog scopes.
epilog_scopes() [2/3]
it_const_epilog_scopes LIEF::PE::unwind_aarch64::UnpackedFunction::epilog_scopes () const inline
epilog_scopes() [3/3]
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::epilog_scopes (epilog_scopes_t scopes) inline
References UnpackedFunction().
epilog_scopes_offset()
uint64_t LIEF::PE::unwind_aarch64::UnpackedFunction::epilog_scopes_offset () const inline
exception_handler() [1/2]
uint32_t LIEF::PE::unwind_aarch64::UnpackedFunction::exception_handler () const inline
Exception handler RVA (if any).
exception_handler() [2/2]
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::exception_handler (uint32_t value) inline
References UnpackedFunction().
exception_handler_offset()
uint64_t LIEF::PE::unwind_aarch64::UnpackedFunction::exception_handler_offset () const inline
is_extended() [1/2]
bool LIEF::PE::unwind_aarch64::UnpackedFunction::is_extended () const inline
Whether it uses 2-words encoding.
is_extended() [2/2]
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::is_extended (bool value) inline
References UnpackedFunction().
operator=() [1/2]
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::operator= (const UnpackedFunction &) default
References UnpackedFunction().
operator=() [2/2]
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::operator= (UnpackedFunction &&) default
References UnpackedFunction().
parse()
std::unique_ptr< UnpackedFunction > LIEF::PE::unwind_aarch64::UnpackedFunction::parse (Parser & ctx, BinaryStream & strm, uint32_t xdata_rva, uint32_t rva) static
References xdata_rva().
to_string()
std::string LIEF::PE::unwind_aarch64::UnpackedFunction::to_string () const override virtual
Reimplemented from LIEF::PE::RuntimeFunctionAArch64.
unwind_code() [1/3]
span< uint8_t > LIEF::PE::unwind_aarch64::UnpackedFunction::unwind_code () inline
unwind_code() [2/3]
span< const uint8_t > LIEF::PE::unwind_aarch64::UnpackedFunction::unwind_code () const inline
Bytes that contain the unwind codes.
unwind_code() [3/3]
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::unwind_code (std::vector< uint8_t > code) inline
References UnpackedFunction().
unwind_code_offset()
uint64_t LIEF::PE::unwind_aarch64::UnpackedFunction::unwind_code_offset () const inline
version() [1/2]
uint32_t LIEF::PE::unwind_aarch64::UnpackedFunction::version () const inline
Describes the version of the remaining .xdata.
Currently (2025-01-04), only version 0 is defined, so values of 1-3 aren't permitted.
version() [2/2]
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::version (uint32_t value) inline
References UnpackedFunction().
X() [1/2]
uint8_t LIEF::PE::unwind_aarch64::UnpackedFunction::X () const inline
1-bit field that indicates the presence (1) or absence (0) of exception data.
X() [2/2]
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::X (uint8_t value) inline
References UnpackedFunction().
xdata_rva() [1/2]
uint32_t LIEF::PE::unwind_aarch64::UnpackedFunction::xdata_rva () const inline
RVA where this unpacked data is located (usually pointing in .xdata).
Referenced by parse().
xdata_rva() [2/2]
UnpackedFunction & LIEF::PE::unwind_aarch64::UnpackedFunction::xdata_rva (uint32_t value) inline
References UnpackedFunction().
Member Data Documentation
epilog_count_
uint32_t LIEF::PE::unwind_aarch64::UnpackedFunction::epilog_count_
Referenced by epilog_count().
epilog_offset_
uint32_t LIEF::PE::unwind_aarch64::UnpackedFunction::epilog_offset_ = 0
Referenced by epilog_cnt_offset(), and epilog_offset().
The documentation for this class was generated from the following file:
UnpackedFunction.hpp