LIEF: Library to Instrument Executable Formats: LIEF::PE::PKCS9SigningTime Class Reference
LIEF::PE::PKCS9SigningTime Class Reference
Interface over the structure described by the OID 1.2.840.113549.1.9.5 (PKCS #9).
#include <PKCS9SigningTime.hpp>
Public Types
using time_t = std::array<int32_t, 6>
Time as an array [year, month, day, hour, min, sec].
Public Types inherited from LIEF::PE::Attribute
enum class TYPE {
UNKNOWN = 0 , CONTENT_TYPE , GENERIC_TYPE , SIGNING_CERTIFICATE_V2 ,
SPC_SP_OPUS_INFO , SPC_RELAXED_PE_MARKER_CHECK , MS_COUNTER_SIGN , MS_SPC_NESTED_SIGN ,
MS_SPC_STATEMENT_TYPE , MS_PLATFORM_MANIFEST_BINARY_ID , PKCS9_AT_SEQUENCE_NUMBER , PKCS9_COUNTER_SIGNATURE ,
PKCS9_MESSAGE_DIGEST , PKCS9_SIGNING_TIME
}
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Public Member Functions
PKCS9SigningTime ()=delete
PKCS9SigningTime (time_t time)
PKCS9SigningTime (const PKCS9SigningTime &)=default
PKCS9SigningTime & operator= (const PKCS9SigningTime &)=default
const time_t & time () const
Time as an array [year, month, day, hour, min, sec].
std::string print () const override
Print information about the attribute.
std::unique_ptr< Attribute > clone () const override
void accept (Visitor &visitor) const override
~PKCS9SigningTime () override=default
Public Member Functions inherited from LIEF::PE::Attribute
Attribute ()=delete
Attribute (const Attribute &)=default
Attribute & operator= (const Attribute &)=default
virtual TYPE type () const
Concrete type of the attribute.
~Attribute () override=default
template<class T>
const T * cast () const
template<class T>
T * cast ()
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Static Public Member Functions
static bool classof (const Attribute *attr)
Detailed Description
Interface over the structure described by the OID 1.2.840.113549.1.9.5 (PKCS #9).
The internal structure is described in the RFC #2985: PKCS #9 - Selected Object Classes and Attribute Types Version 2.0
signingTime ATTRIBUTE ::= {
        WITH SYNTAX SigningTime
        EQUALITY MATCHING RULE signingTimeMatch
        SINGLE VALUE TRUE
        ID pkcs-9-at-signingTime
}
SigningTime ::= Time -- imported from ISO/IEC 9594-8
Member Typedef Documentation
time_t
using LIEF::PE::PKCS9SigningTime::time_t = std::array<int32_t, 6>
Time as an array [year, month, day, hour, min, sec].
Constructor & Destructor Documentation
PKCS9SigningTime() [1/3]
LIEF::PE::PKCS9SigningTime::PKCS9SigningTime () delete
Referenced by clone(), operator=(), and PKCS9SigningTime().
PKCS9SigningTime() [2/3]
LIEF::PE::PKCS9SigningTime::PKCS9SigningTime (time_t time) inline
References LIEF::PE::Attribute::Attribute(), and time().
PKCS9SigningTime() [3/3]
LIEF::PE::PKCS9SigningTime::PKCS9SigningTime (const PKCS9SigningTime &) default
References PKCS9SigningTime().
~PKCS9SigningTime()
LIEF::PE::PKCS9SigningTime::~PKCS9SigningTime () override default
Member Function Documentation
accept()
void LIEF::PE::PKCS9SigningTime::accept (Visitor & visitor) const override virtual
Reimplemented from LIEF::PE::Attribute.
classof()
bool LIEF::PE::PKCS9SigningTime::classof (const Attribute * attr) inline static
References LIEF::PE::Attribute::Attribute(), LIEF::PE::Attribute::PKCS9_SIGNING_TIME, and LIEF::PE::Attribute::type().
clone()
std::unique_ptr< Attribute > LIEF::PE::PKCS9SigningTime::clone () const inline override virtual
Implements LIEF::PE::Attribute.
References PKCS9SigningTime().
operator=()
PKCS9SigningTime & LIEF::PE::PKCS9SigningTime::operator= (const PKCS9SigningTime &) default
References PKCS9SigningTime().
print()
std::string LIEF::PE::PKCS9SigningTime::print () const override virtual
Print information about the attribute.
Implements LIEF::PE::Attribute.
time()
const time_t & LIEF::PE::PKCS9SigningTime::time () const inline
Time as an array [year, month, day, hour, min, sec].
Referenced by PKCS9SigningTime().
The documentation for this class was generated from the following file:
PKCS9SigningTime.hpp