LIEF: Library to Instrument Executable Formats: LIEF::OAT::DexFile Class Reference
LIEF::OAT::DexFile Class Reference
#include <DexFile.hpp>
Public Member Functions
DexFile ()
DexFile (const DexFile &)
DexFile & operator= (const DexFile &)
const std::string & location () const
uint32_t checksum () const
uint32_t dex_offset () const
bool has_dex_file () const
const DEX::File * dex_file () const
DEX::File * dex_file ()
void location (const std::string &location)
void checksum (uint32_t checksum)
void dex_offset (uint32_t dex_offset)
const std::vector< uint32_t > & classes_offsets () const
uint32_t lookup_table_offset () const
void class_offsets_offset (uint32_t offset)
void lookup_table_offset (uint32_t offset)
void accept (Visitor &visitor) const override
~DexFile () override
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Additional Inherited Members
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Constructor & Destructor Documentation
DexFile() [1/2]
LIEF::OAT::DexFile::DexFile ()
Referenced by DexFile(), operator<<, and operator=().
DexFile() [2/2]
LIEF::OAT::DexFile::DexFile (const DexFile &)
References DexFile().
~DexFile()
LIEF::OAT::DexFile::~DexFile () override
Member Function Documentation
accept()
void LIEF::OAT::DexFile::accept (Visitor & visitor) const override virtual
Implements LIEF::Object.
checksum() [1/2]
uint32_t LIEF::OAT::DexFile::checksum () const
Referenced by checksum().
checksum() [2/2]
void LIEF::OAT::DexFile::checksum (uint32_t checksum)
References checksum().
class_offsets_offset()
void LIEF::OAT::DexFile::class_offsets_offset (uint32_t offset)
classes_offsets()
const std::vector< uint32_t > & LIEF::OAT::DexFile::classes_offsets () const
dex_file() [1/2]
DEX::File * LIEF::OAT::DexFile::dex_file ()
dex_file() [2/2]
const DEX::File * LIEF::OAT::DexFile::dex_file () const
Referenced by operator<<.
dex_offset() [1/2]
uint32_t LIEF::OAT::DexFile::dex_offset () const
Referenced by dex_offset().
dex_offset() [2/2]
void LIEF::OAT::DexFile::dex_offset (uint32_t dex_offset)
References dex_offset().
has_dex_file()
bool LIEF::OAT::DexFile::has_dex_file () const
location() [1/2]
const std::string & LIEF::OAT::DexFile::location () const
Referenced by location().
location() [2/2]
void LIEF::OAT::DexFile::location (const std::string & location)
References location().
lookup_table_offset() [1/2]
uint32_t LIEF::OAT::DexFile::lookup_table_offset () const
lookup_table_offset() [2/2]
void LIEF::OAT::DexFile::lookup_table_offset (uint32_t offset)
operator=()
DexFile & LIEF::OAT::DexFile::operator= (const DexFile &)
References DexFile().
The documentation for this class was generated from the following file:
DexFile.hpp