LIEF: Library to Instrument Executable Formats: LIEF::COFF::AuxiliarySymbol Class Reference
LIEF::COFF::AuxiliarySymbol Class Reference
Class that represents an auxiliary symbol.
#include <AuxiliarySymbol.hpp>
Public Types
enum class TYPE {
UNKNOWN = 0 , CLR_TOKEN , FUNC_DEF , BF_AND_EF ,
WEAK_EXTERNAL , FILE , SEC_DEF
}
Type discriminator for the subclasses.
Public Member Functions
AuxiliarySymbol ()=default
AuxiliarySymbol (std::vector< uint8_t > payload)
AuxiliarySymbol (const AuxiliarySymbol &)=default
AuxiliarySymbol & operator= (const AuxiliarySymbol &)=default
AuxiliarySymbol (AuxiliarySymbol &&)=default
AuxiliarySymbol & operator= (AuxiliarySymbol &&)=default
virtual std::unique_ptr< AuxiliarySymbol > clone () const
AuxiliarySymbol (TYPE ty)
TYPE type () const
span< const uint8_t > payload () const
For unknown type only, return the raw representation of this symbol.
span< uint8_t > payload ()
virtual std::string to_string () const
virtual ~AuxiliarySymbol ()=default
template<class T>
const T * as () const
Helper to downcast a AuxiliarySymbol into a concrete implementation.
template<class T>
T * as ()
Static Public Member Functions
static std::unique_ptr< AuxiliarySymbol > parse (Symbol &sym, std::vector< uint8_t > payload)
static TYPE get_aux_type (const Symbol &sym)
Detailed Description
Class that represents an auxiliary symbol.
An auxiliary symbol has the same size as a regular LIEF::PE::Symbol (18 bytes) but its content depends on the the parent symbol.
Member Enumeration Documentation
TYPE
enum class LIEF::COFF::AuxiliarySymbol::TYPE strong
Type discriminator for the subclasses.
Enumerator
UNKNOWN
CLR_TOKEN
FUNC_DEF
Auxiliary Format 1 from the PE-COFF documentation.
BF_AND_EF
Auxiliary Format 2: .bf and .ef Symbols from the PE-COFF documentation.
WEAK_EXTERNAL
Auxiliary Format 3: Weak Externals from the PE-COFF documentation.
FILE
Auxiliary Format 4: Files from the PE-COFF documentation.
SEC_DEF
Auxiliary Format 5: Section Definitions from the PE-COFF documentation.
Constructor & Destructor Documentation
AuxiliarySymbol() [1/5]
LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol () default
Referenced by as(), LIEF::COFF::AuxiliarybfAndefSymbol::AuxiliarybfAndefSymbol(), LIEF::COFF::AuxiliaryCLRToken::AuxiliaryCLRToken(), LIEF::COFF::AuxiliaryCLRToken::AuxiliaryCLRToken(), LIEF::COFF::AuxiliaryFile::AuxiliaryFile(), LIEF::COFF::AuxiliaryFile::AuxiliaryFile(), LIEF::COFF::AuxiliaryFunctionDefinition::AuxiliaryFunctionDefinition(), LIEF::COFF::AuxiliaryFunctionDefinition::AuxiliaryFunctionDefinition(), LIEF::COFF::AuxiliarySectionDefinition::AuxiliarySectionDefinition(), LIEF::COFF::AuxiliarySectionDefinition::AuxiliarySectionDefinition(), AuxiliarySymbol(), AuxiliarySymbol(), LIEF::COFF::AuxiliaryWeakExternal::AuxiliaryWeakExternal(), LIEF::COFF::AuxiliaryWeakExternal::AuxiliaryWeakExternal(), LIEF::COFF::AuxiliarybfAndefSymbol::classof(), LIEF::COFF::AuxiliaryCLRToken::classof(), LIEF::COFF::AuxiliaryFile::classof(), LIEF::COFF::AuxiliaryFunctionDefinition::classof(), LIEF::COFF::AuxiliarySectionDefinition::classof(), LIEF::COFF::AuxiliaryWeakExternal::classof(), clone(), operator<<, operator=(), and operator=().
AuxiliarySymbol() [2/5]
LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol (std::vector< uint8_t > payload) inline
References payload().
AuxiliarySymbol() [3/5]
LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol (const AuxiliarySymbol &) default
References AuxiliarySymbol().
AuxiliarySymbol() [4/5]
LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol (AuxiliarySymbol &&) default
References AuxiliarySymbol().
AuxiliarySymbol() [5/5]
LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol (TYPE ty) inline
~AuxiliarySymbol()
virtual LIEF::COFF::AuxiliarySymbol::~AuxiliarySymbol () virtual default
Member Function Documentation
as() [1/2]
template<class T> T * LIEF::COFF::AuxiliarySymbol::as () inline
References AuxiliarySymbol().
as() [2/2]
template<class T> const T * LIEF::COFF::AuxiliarySymbol::as () const inline
Helper to downcast a AuxiliarySymbol into a concrete implementation.
clone()
virtual std::unique_ptr< AuxiliarySymbol > LIEF::COFF::AuxiliarySymbol::clone () const inline virtual
Reimplemented in LIEF::COFF::AuxiliarybfAndefSymbol, LIEF::COFF::AuxiliaryCLRToken, LIEF::COFF::AuxiliaryFile, LIEF::COFF::AuxiliaryFunctionDefinition, LIEF::COFF::AuxiliarySectionDefinition, and LIEF::COFF::AuxiliaryWeakExternal.
References AuxiliarySymbol().
get_aux_type()
TYPE LIEF::COFF::AuxiliarySymbol::get_aux_type (const Symbol & sym) static
operator=() [1/2]
AuxiliarySymbol & LIEF::COFF::AuxiliarySymbol::operator= (AuxiliarySymbol &&) default
References AuxiliarySymbol(), and LIEF_LOCAL.
operator=() [2/2]
AuxiliarySymbol & LIEF::COFF::AuxiliarySymbol::operator= (const AuxiliarySymbol &) default
References AuxiliarySymbol().
parse()
std::unique_ptr< AuxiliarySymbol > LIEF::COFF::AuxiliarySymbol::parse (Symbol & sym, std::vector< uint8_t > payload) static
References payload().
payload() [1/2]
span< uint8_t > LIEF::COFF::AuxiliarySymbol::payload () inline
payload() [2/2]
span< const uint8_t > LIEF::COFF::AuxiliarySymbol::payload () const inline
For unknown type only, return the raw representation of this symbol.
Referenced by AuxiliarySymbol(), LIEF::COFF::AuxiliarybfAndefSymbol::parse(), LIEF::COFF::AuxiliaryCLRToken::parse(), LIEF::COFF::AuxiliaryFile::parse(), LIEF::COFF::AuxiliaryFunctionDefinition::parse(), LIEF::COFF::AuxiliarySectionDefinition::parse(), parse(), and LIEF::COFF::AuxiliaryWeakExternal::parse().
to_string()
virtual std::string LIEF::COFF::AuxiliarySymbol::to_string () const virtual
Reimplemented in LIEF::COFF::AuxiliarybfAndefSymbol, LIEF::COFF::AuxiliaryCLRToken, LIEF::COFF::AuxiliaryFile, LIEF::COFF::AuxiliaryFunctionDefinition, LIEF::COFF::AuxiliarySectionDefinition, and LIEF::COFF::AuxiliaryWeakExternal.
Referenced by operator<<.
type()
TYPE LIEF::COFF::AuxiliarySymbol::type () const inline
Referenced by LIEF::COFF::AuxiliarybfAndefSymbol::classof(), LIEF::COFF::AuxiliaryCLRToken::classof(), LIEF::COFF::AuxiliaryFile::classof(), LIEF::COFF::AuxiliaryFunctionDefinition::classof(), LIEF::COFF::AuxiliarySectionDefinition::classof(), and LIEF::COFF::AuxiliaryWeakExternal::classof().
The documentation for this class was generated from the following file:
AuxiliarySymbol.hpp