LIEF: Library to Instrument Executable Formats: LIEF::pdb::Type::Iterator Class Reference
LIEF::pdb::Type::Iterator Class Reference final
#include <Type.hpp>
Public Types
using implementation = details::TypeIt
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, Type, std::ptrdiff_t, const Type *, const Type & >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Public Member Functions
Iterator ()
Iterator (std::unique_ptr< details::TypeIt > impl)
Iterator (const Iterator &)
Iterator & operator= (const Iterator &)
Iterator (Iterator &&) noexcept
Iterator & operator= (Iterator &&) noexcept
~Iterator ()
Iterator & operator++ ()
const Type & operator* () const
const Type * operator-> () const
std::unique_ptr< Type > yield ()
Transfer ownership of the type at the current position to the caller. Returns nullptr if the iterator is past-the-end.
DerivedT operator++ (int)
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, Type, std::ptrdiff_t, const Type *, const Type & >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Member Typedef Documentation
implementation
using LIEF::pdb::Type::Iterator::implementation = details::TypeIt
Constructor & Destructor Documentation
Iterator() [1/4]
LIEF::pdb::Type::Iterator::Iterator ()
References LIEF_API.
Referenced by Iterator(), Iterator(), operator!=, operator++(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/4]
LIEF::pdb::Type::Iterator::Iterator (std::unique_ptr< details::TypeIt > impl)
References LIEF_API.
Iterator() [3/4]
LIEF::pdb::Type::Iterator::Iterator (const Iterator &)
References Iterator(), and LIEF_API.
Iterator() [4/4]
LIEF::pdb::Type::Iterator::Iterator (Iterator &&) noexcept
References Iterator(), and LIEF_API.
~Iterator()
LIEF::pdb::Type::Iterator::~Iterator ()
References Iterator(), and LIEF_API.
Member Function Documentation
operator*()
const Type & LIEF::pdb::Type::Iterator::operator* () const
References LIEF_API, LIEF_LIFETIMEBOUND, and LIEF::pdb::Type::Type().
operator++() [1/2]
Iterator & LIEF::pdb::Type::Iterator::operator++ ()
References Iterator(), and LIEF_API.
operator++() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator++ (int) inline
operator->()
const Type * LIEF::pdb::Type::Iterator::operator-> () const
References LIEF_API, LIEF_LIFETIMEBOUND, and LIEF::pdb::Type::Type().
operator=() [1/2]
Iterator & LIEF::pdb::Type::Iterator::operator= (const Iterator &)
References Iterator(), and LIEF_API.
operator=() [2/2]
Iterator & LIEF::pdb::Type::Iterator::operator= (Iterator &&) noexcept
References Iterator(), and LIEF_API.
yield()
std::unique_ptr< Type > LIEF::pdb::Type::Iterator::yield ()
Transfer ownership of the type at the current position to the caller. Returns nullptr if the iterator is past-the-end.
References LIEF_API, LIEF::pdb::Type::Type(), and yield().
Referenced by yield().
The documentation for this class was generated from the following file:
PDB/Type.hpp