LIEF: Library to Instrument Executable Formats: LIEF::COFF::AuxiliaryFunctionDefinition Class Reference
LIEF::COFF::AuxiliaryFunctionDefinition Class Reference
This auxiliary symbols marks the beginning of a function definition.
#include <AuxiliaryFunctionDefinition.hpp>
Public Member Functions
AuxiliaryFunctionDefinition ()
AuxiliaryFunctionDefinition (uint32_t tagidx, uint32_t totalsz, uint32_t ptr_line, uint32_t ptr_next_func, uint16_t padding)
AuxiliaryFunctionDefinition (const AuxiliaryFunctionDefinition &)=default
AuxiliaryFunctionDefinition & operator= (const AuxiliaryFunctionDefinition &)=default
AuxiliaryFunctionDefinition (AuxiliaryFunctionDefinition &&)=default
AuxiliaryFunctionDefinition & operator= (AuxiliaryFunctionDefinition &&)=default
std::unique_ptr< AuxiliarySymbol > clone () const override
uint32_t tag_index () const
The symbol-table index of the corresponding .bf (begin function) symbol record.
uint32_t total_size () const
The size of the executable code for the function itself.
uint32_t ptr_to_line_number () const
The file offset of the first COFF line-number entry for the function, or zero if none exists (deprecated).
uint32_t ptr_to_next_func () const
The symbol-table index of the record for the next function. If the function is the last in the symbol table, this field is set to zero.
uint16_t padding () const
Padding value (should be 0).
std::string to_string () const override
~AuxiliaryFunctionDefinition () override=default
Public Member Functions inherited from LIEF::COFF::AuxiliarySymbol
AuxiliarySymbol ()=default
AuxiliarySymbol (std::vector< uint8_t > payload)
AuxiliarySymbol (const AuxiliarySymbol &)=default
AuxiliarySymbol & operator= (const AuxiliarySymbol &)=default
AuxiliarySymbol (AuxiliarySymbol &&)=default
AuxiliarySymbol & operator= (AuxiliarySymbol &&)=default
AuxiliarySymbol (TYPE ty)
TYPE type () const
span< const uint8_t > payload () const
For unknown type only, return the raw representation of this symbol.
span< uint8_t > payload ()
virtual ~AuxiliarySymbol ()=default
template<class T>
const T * as () const
Helper to downcast a AuxiliarySymbol into a concrete implementation.
template<class T>
T * as ()
Static Public Member Functions
static std::unique_ptr< AuxiliaryFunctionDefinition > parse (const std::vector< uint8_t > &payload)
static bool classof (const AuxiliarySymbol *sym)
Static Public Member Functions inherited from LIEF::COFF::AuxiliarySymbol
static std::unique_ptr< AuxiliarySymbol > parse (Symbol &sym, std::vector< uint8_t > payload)
static TYPE get_aux_type (const Symbol &sym)
Additional Inherited Members
Public Types inherited from LIEF::COFF::AuxiliarySymbol
enum class TYPE {
UNKNOWN = 0 , CLR_TOKEN , FUNC_DEF , BF_AND_EF ,
WEAK_EXTERNAL , FILE , SEC_DEF
}
Type discriminator for the subclasses.
Detailed Description
This auxiliary symbols marks the beginning of a function definition.
Reference: https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#auxiliary-format-1-function-definitions
Constructor & Destructor Documentation
AuxiliaryFunctionDefinition() [1/4]
LIEF::COFF::AuxiliaryFunctionDefinition::AuxiliaryFunctionDefinition () inline
References LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol().
Referenced by AuxiliaryFunctionDefinition(), AuxiliaryFunctionDefinition(), clone(), operator=(), and operator=().
AuxiliaryFunctionDefinition() [2/4]
LIEF::COFF::AuxiliaryFunctionDefinition::AuxiliaryFunctionDefinition (uint32_t tagidx, uint32_t totalsz, uint32_t ptr_line, uint32_t ptr_next_func, uint16_t padding) inline
References LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol(), and padding().
AuxiliaryFunctionDefinition() [3/4]
LIEF::COFF::AuxiliaryFunctionDefinition::AuxiliaryFunctionDefinition (const AuxiliaryFunctionDefinition &) default
References AuxiliaryFunctionDefinition().
AuxiliaryFunctionDefinition() [4/4]
LIEF::COFF::AuxiliaryFunctionDefinition::AuxiliaryFunctionDefinition (AuxiliaryFunctionDefinition &&) default
References AuxiliaryFunctionDefinition().
~AuxiliaryFunctionDefinition()
LIEF::COFF::AuxiliaryFunctionDefinition::~AuxiliaryFunctionDefinition () override default
Member Function Documentation
classof()
bool LIEF::COFF::AuxiliaryFunctionDefinition::classof (const AuxiliarySymbol * sym) inline static
References LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol(), LIEF::COFF::AuxiliarySymbol::FUNC_DEF, and LIEF::COFF::AuxiliarySymbol::type().
clone()
std::unique_ptr< AuxiliarySymbol > LIEF::COFF::AuxiliaryFunctionDefinition::clone () const inline override virtual
Reimplemented from LIEF::COFF::AuxiliarySymbol.
References AuxiliaryFunctionDefinition().
operator=() [1/2]
AuxiliaryFunctionDefinition & LIEF::COFF::AuxiliaryFunctionDefinition::operator= (AuxiliaryFunctionDefinition &&) default
References AuxiliaryFunctionDefinition().
operator=() [2/2]
AuxiliaryFunctionDefinition & LIEF::COFF::AuxiliaryFunctionDefinition::operator= (const AuxiliaryFunctionDefinition &) default
References AuxiliaryFunctionDefinition().
padding()
uint16_t LIEF::COFF::AuxiliaryFunctionDefinition::padding () const inline
Padding value (should be 0).
Referenced by AuxiliaryFunctionDefinition().
parse()
std::unique_ptr< AuxiliaryFunctionDefinition > LIEF::COFF::AuxiliaryFunctionDefinition::parse (const std::vector< uint8_t > & payload) static
References LIEF::COFF::AuxiliarySymbol::payload().
ptr_to_line_number()
uint32_t LIEF::COFF::AuxiliaryFunctionDefinition::ptr_to_line_number () const inline
The file offset of the first COFF line-number entry for the function, or zero if none exists (deprecated).
ptr_to_next_func()
uint32_t LIEF::COFF::AuxiliaryFunctionDefinition::ptr_to_next_func () const inline
The symbol-table index of the record for the next function. If the function is the last in the symbol table, this field is set to zero.
tag_index()
uint32_t LIEF::COFF::AuxiliaryFunctionDefinition::tag_index () const inline
The symbol-table index of the corresponding .bf (begin function) symbol record.
to_string()
std::string LIEF::COFF::AuxiliaryFunctionDefinition::to_string () const override virtual
Reimplemented from LIEF::COFF::AuxiliarySymbol.
total_size()
uint32_t LIEF::COFF::AuxiliaryFunctionDefinition::total_size () const inline
The size of the executable code for the function itself.
If the function is in its own section, the SizeOfRawData in the section header is greater or equal to this field, depending on alignment considerations.
The documentation for this class was generated from the following file:
AuxiliaryFunctionDefinition.hpp