LIEF: Library to Instrument Executable Formats: LIEF::PE::DynamicFixupControlTransfer Class Reference
LIEF::PE::DynamicFixupControlTransfer Class Reference
This class wraps fixups associated with the (special) symbol value: IMAGE_DYNAMIC_RELOCATION_GUARD_IMPORT_CONTROL_TRANSFER (3).
#include <DynamicFixupControlTransfer.hpp>
Classes
struct reloc_entry_t
Mirror IMAGE_IMPORT_CONTROL_TRANSFER_DYNAMIC_RELOCATION.
Public Types
using reloc_entries_t = std::vector<reloc_entry_t>
using it_relocations = ref_iterator<reloc_entries_t&>
using it_const_relocations = const_ref_iterator<const reloc_entries_t&>
Public Types inherited from LIEF::PE::DynamicFixup
enum KIND {
UNKNOWN = 0 , GENERIC , ARM64X , FUNCTION_OVERRIDE ,
ARM64_KERNEL_IMPORT_CALL_TRANSFER , GUARD_IMPORT_CONTROL_TRANSFER
}
Public Member Functions
DynamicFixupControlTransfer ()
DynamicFixupControlTransfer (const DynamicFixupControlTransfer &)=default
DynamicFixupControlTransfer & operator= (const DynamicFixupControlTransfer &)=default
DynamicFixupControlTransfer (DynamicFixupControlTransfer &&)=default
DynamicFixupControlTransfer & operator= (DynamicFixupControlTransfer &&)=default
std::unique_ptr< DynamicFixup > clone () const override
std::string to_string () const override
it_relocations relocations ()
Iterator over the relocations.
it_const_relocations relocations () const
~DynamicFixupControlTransfer () override=default
Public Member Functions inherited from LIEF::PE::DynamicFixup
DynamicFixup ()=delete
DynamicFixup (KIND kind)
DynamicFixup (const DynamicFixup &)=default
DynamicFixup & operator= (const DynamicFixup &)=default
DynamicFixup (DynamicFixup &&)=default
DynamicFixup & operator= (DynamicFixup &&)=default
KIND kind () const
Encoding of the fixups.
template<class T>
T * as ()
template<class T>
const T * as () const
virtual ~DynamicFixup ()=default
Static Public Member Functions
static bool classof (const DynamicFixup *fixup)
Static Public Attributes
static constexpr auto NO_IAT_INDEX = 0x7fff
Detailed Description
This class wraps fixups associated with the (special) symbol value: IMAGE_DYNAMIC_RELOCATION_GUARD_IMPORT_CONTROL_TRANSFER (3).
Member Typedef Documentation
it_const_relocations
using LIEF::PE::DynamicFixupControlTransfer::it_const_relocations = const_ref_iterator<const reloc_entries_t&>
it_relocations
using LIEF::PE::DynamicFixupControlTransfer::it_relocations = ref_iterator<reloc_entries_t&>
reloc_entries_t
using LIEF::PE::DynamicFixupControlTransfer::reloc_entries_t = std::vector<reloc_entry_t>
Constructor & Destructor Documentation
DynamicFixupControlTransfer() [1/3]
LIEF::PE::DynamicFixupControlTransfer::DynamicFixupControlTransfer () inline
References LIEF::PE::DynamicFixup::DynamicFixup(), and LIEF::PE::DynamicFixup::GUARD_IMPORT_CONTROL_TRANSFER.
Referenced by clone(), DynamicFixupControlTransfer(), DynamicFixupControlTransfer(), operator=(), and operator=().
DynamicFixupControlTransfer() [2/3]
LIEF::PE::DynamicFixupControlTransfer::DynamicFixupControlTransfer (const DynamicFixupControlTransfer &) default
References DynamicFixupControlTransfer().
DynamicFixupControlTransfer() [3/3]
LIEF::PE::DynamicFixupControlTransfer::DynamicFixupControlTransfer (DynamicFixupControlTransfer &&) default
References DynamicFixupControlTransfer().
~DynamicFixupControlTransfer()
LIEF::PE::DynamicFixupControlTransfer::~DynamicFixupControlTransfer () override default
References LIEF_LOCAL.
Member Function Documentation
classof()
bool LIEF::PE::DynamicFixupControlTransfer::classof (const DynamicFixup * fixup) inline static
References LIEF::PE::DynamicFixup::DynamicFixup(), LIEF::PE::DynamicFixup::GUARD_IMPORT_CONTROL_TRANSFER, and LIEF::PE::DynamicFixup::kind().
clone()
std::unique_ptr< DynamicFixup > LIEF::PE::DynamicFixupControlTransfer::clone () const inline override virtual
Implements LIEF::PE::DynamicFixup.
References DynamicFixupControlTransfer().
operator=() [1/2]
DynamicFixupControlTransfer & LIEF::PE::DynamicFixupControlTransfer::operator= (const DynamicFixupControlTransfer &) default
References DynamicFixupControlTransfer().
operator=() [2/2]
DynamicFixupControlTransfer & LIEF::PE::DynamicFixupControlTransfer::operator= (DynamicFixupControlTransfer &&) default
References DynamicFixupControlTransfer().
relocations() [1/2]
it_relocations LIEF::PE::DynamicFixupControlTransfer::relocations () inline
Iterator over the relocations.
relocations() [2/2]
it_const_relocations LIEF::PE::DynamicFixupControlTransfer::relocations () const inline
to_string()
std::string LIEF::PE::DynamicFixupControlTransfer::to_string () const override virtual
Implements LIEF::PE::DynamicFixup.
Member Data Documentation
NO_IAT_INDEX
auto LIEF::PE::DynamicFixupControlTransfer::NO_IAT_INDEX = 0x7fff static constexpr
The documentation for this class was generated from the following file:
DynamicFixupControlTransfer.hpp