LIEF: Library to Instrument Executable Formats: LIEF::PE::Debug Class Reference
LIEF::PE::Debug Class Reference
This class represents a generic entry in the debug data directory. For known types, this class is extended to provide a dedicated API (see: CodeCodeView).
#include <Debug.hpp>
Public Types
enum class TYPES {
UNKNOWN = 0 , COFF = 1 , CODEVIEW = 2 , FPO = 3 ,
MISC = 4 , EXCEPTION = 5 , FIXUP = 6 , OMAP_TO_SRC = 7 ,
OMAP_FROM_SRC = 8 , BORLAND = 9 , RESERVED10 = 10 , CLSID = 11 ,
VC_FEATURE = 12 , POGO = 13 , ILTCG = 14 , MPX = 15 ,
REPRO = 16 , PDBCHECKSUM = 19 , EX_DLLCHARACTERISTICS = 20
}
The entry types.
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Public Member Functions
Debug ()=default
Debug (TYPES type)
Debug (const details::pe_debug &debug_s, Section *section)
Debug (const Debug &other)=default
Debug & operator= (const Debug &other)=default
Debug (Debug &&)=default
Debug & operator= (Debug &&)=default
~Debug () override=default
virtual std::unique_ptr< Debug > clone () const
uint32_t characteristics () const
Reserved should be 0.
uint32_t timestamp () const
The time and date when the debug data was created.
uint16_t major_version () const
The major version number of the debug data format.
uint16_t minor_version () const
The minor version number of the debug data format.
TYPES type () const
The format DEBUG_TYPES of the debugging information.
uint32_t sizeof_data () const
Size of the debug data.
uint32_t addressof_rawdata () const
Address of the debug data relative to the image base.
uint32_t pointerto_rawdata () const
File offset of the debug data.
const Section * section () const
The section where debug data is located.
Section * section ()
span< uint8_t > payload ()
Debug data associated with this entry.
span< const uint8_t > payload () const
void characteristics (uint32_t characteristics)
void timestamp (uint32_t timestamp)
void major_version (uint16_t major_version)
void minor_version (uint16_t minor_version)
void sizeof_data (uint32_t sizeof_data)
void addressof_rawdata (uint32_t addressof_rawdata)
void pointerto_rawdata (uint32_t pointerto_rawdata)
template<class T>
const T * as () const
template<class T>
T * as ()
void accept (Visitor &visitor) const override
virtual std::string to_string () const
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Static Public Member Functions
static span< uint8_t > get_payload (Section &section, uint32_t rva, uint32_t offset, uint32_t size)
static span< uint8_t > get_payload (Section &section, const details::pe_debug &hdr)
static span< uint8_t > get_payload (Section &section, const Debug &dbg)
Detailed Description
This class represents a generic entry in the debug data directory. For known types, this class is extended to provide a dedicated API (see: CodeCodeView).
Member Enumeration Documentation
TYPES
enum class LIEF::PE::Debug::TYPES strong
The entry types.
Enumerator
UNKNOWN
COFF
COFF Debug information.
CODEVIEW
CodeView debug information that is used to store PDB info.
FPO
Frame pointer omission information.
MISC
Miscellaneous debug information.
EXCEPTION
Debug information that is a copy of the .pdata section.
FIXUP
(Reserved) Debug information used for fixup relocations
OMAP_TO_SRC
The mapping from an RVA in image to an RVA in source image.
OMAP_FROM_SRC
The mapping from an RVA in source image to an RVA in image.
BORLAND
Reserved for Borland.
RESERVED10
Reserved.
CLSID
Reserved.
VC_FEATURE
Visual C++ feature information.
POGO
Profile Guided Optimization metadata.
ILTCG
Incremental Link Time Code Generation metadata.
MPX
REPRO
PE determinism or reproducibility information.
PDBCHECKSUM
Checksum of the PDB file.
EX_DLLCHARACTERISTICS
Extended DLL characteristics.
Constructor & Destructor Documentation
Debug() [1/5]
LIEF::PE::Debug::Debug () default
Referenced by as(), LIEF::PE::CodeView::classof(), LIEF::PE::ExDllCharacteristics::classof(), LIEF::PE::FPO::classof(), LIEF::PE::PDBChecksum::classof(), LIEF::PE::Pogo::classof(), LIEF::PE::Repro::classof(), LIEF::PE::VCFeature::classof(), clone(), LIEF::PE::CodeView::CodeView(), LIEF::PE::CodeView::CodeView(), LIEF::PE::CodeView::CodeView(), Debug(), Debug(), LIEF::PE::ExDllCharacteristics::ExDllCharacteristics(), LIEF::PE::FPO::FPO(), get_payload(), operator<<, operator=(), operator=(), payload(), LIEF::PE::PDBChecksum::PDBChecksum(), LIEF::PE::PDBChecksum::PDBChecksum(), LIEF::PE::Pogo::Pogo(), LIEF::PE::Pogo::Pogo(), LIEF::PE::Repro::Repro(), LIEF::PE::Repro::Repro(), LIEF::PE::Repro::Repro(), LIEF::PE::Repro::Repro(), and LIEF::PE::VCFeature::VCFeature().
Debug() [2/5]
LIEF::PE::Debug::Debug (TYPES type) inline
References type().
Debug() [3/5]
LIEF::PE::Debug::Debug (const details::pe_debug & debug_s, Section * section)
References section().
Debug() [4/5]
LIEF::PE::Debug::Debug (const Debug & other) default
References Debug().
Debug() [5/5]
LIEF::PE::Debug::Debug (Debug &&) default
References Debug().
~Debug()
LIEF::PE::Debug::~Debug () override default
Member Function Documentation
accept()
void LIEF::PE::Debug::accept (Visitor & visitor) const override virtual
Implements LIEF::Object.
Reimplemented in LIEF::PE::Pogo, and LIEF::PE::Repro.
addressof_rawdata() [1/2]
uint32_t LIEF::PE::Debug::addressof_rawdata () const inline
Address of the debug data relative to the image base.
Referenced by addressof_rawdata(), and get_payload().
addressof_rawdata() [2/2]
void LIEF::PE::Debug::addressof_rawdata (uint32_t addressof_rawdata) inline
References addressof_rawdata().
as() [1/2]
template<class T> T * LIEF::PE::Debug::as () inline
References Debug(), and LIEF::PE::T.
as() [2/2]
template<class T> const T * LIEF::PE::Debug::as () const inline
References LIEF::PE::T.
characteristics() [1/2]
uint32_t LIEF::PE::Debug::characteristics () const inline
Reserved should be 0.
Referenced by characteristics().
characteristics() [2/2]
void LIEF::PE::Debug::characteristics (uint32_t characteristics) inline
References characteristics().
clone()
virtual std::unique_ptr< Debug > LIEF::PE::Debug::clone () const inline virtual
Reimplemented in LIEF::PE::CodeView, LIEF::PE::CodeViewPDB, LIEF::PE::ExDllCharacteristics, LIEF::PE::FPO, LIEF::PE::PDBChecksum, LIEF::PE::Pogo, LIEF::PE::Repro, and LIEF::PE::VCFeature.
References Debug().
get_payload() [1/3]
span< uint8_t > LIEF::PE::Debug::get_payload (Section & section, const Debug & dbg) inline static
References addressof_rawdata(), Debug(), get_payload(), pointerto_rawdata(), section(), and sizeof_data().
get_payload() [2/3]
span< uint8_t > LIEF::PE::Debug::get_payload (Section & section, const details::pe_debug & hdr) static
References section().
get_payload() [3/3]
span< uint8_t > LIEF::PE::Debug::get_payload (Section & section, uint32_t rva, uint32_t offset, uint32_t size) static
References section().
Referenced by get_payload().
major_version() [1/2]
uint16_t LIEF::PE::Debug::major_version () const inline
The major version number of the debug data format.
Referenced by major_version().
major_version() [2/2]
void LIEF::PE::Debug::major_version (uint16_t major_version) inline
References major_version().
minor_version() [1/2]
uint16_t LIEF::PE::Debug::minor_version () const inline
The minor version number of the debug data format.
Referenced by minor_version().
minor_version() [2/2]
void LIEF::PE::Debug::minor_version (uint16_t minor_version) inline
References minor_version().
operator=() [1/2]
Debug & LIEF::PE::Debug::operator= (const Debug & other) default
References Debug().
operator=() [2/2]
Debug & LIEF::PE::Debug::operator= (Debug &&) default
References Debug().
payload() [1/2]
span< uint8_t > LIEF::PE::Debug::payload ()
Debug data associated with this entry.
Referenced by LIEF::PE::ExDllCharacteristics::parse(), LIEF::PE::FPO::parse(), LIEF::PE::PDBChecksum::parse(), LIEF::PE::VCFeature::parse(), and payload().
payload() [2/2]
span< const uint8_t > LIEF::PE::Debug::payload () const inline
References Debug(), and payload().
pointerto_rawdata() [1/2]
uint32_t LIEF::PE::Debug::pointerto_rawdata () const inline
File offset of the debug data.
Referenced by get_payload(), and pointerto_rawdata().
pointerto_rawdata() [2/2]
void LIEF::PE::Debug::pointerto_rawdata (uint32_t pointerto_rawdata) inline
References pointerto_rawdata().
section() [1/2]
Section * LIEF::PE::Debug::section () inline
section() [2/2]
const Section * LIEF::PE::Debug::section () const inline
The section where debug data is located.
Referenced by Debug(), LIEF::PE::FPO::FPO(), get_payload(), get_payload(), get_payload(), LIEF::PE::ExDllCharacteristics::parse(), LIEF::PE::FPO::parse(), LIEF::PE::PDBChecksum::parse(), and LIEF::PE::VCFeature::parse().
sizeof_data() [1/2]
uint32_t LIEF::PE::Debug::sizeof_data () const inline
Size of the debug data.
Referenced by get_payload(), and sizeof_data().
sizeof_data() [2/2]
void LIEF::PE::Debug::sizeof_data (uint32_t sizeof_data) inline
References sizeof_data().
timestamp() [1/2]
uint32_t LIEF::PE::Debug::timestamp () const inline
The time and date when the debug data was created.
Referenced by timestamp().
timestamp() [2/2]
void LIEF::PE::Debug::timestamp (uint32_t timestamp) inline
References timestamp().
to_string()
virtual std::string LIEF::PE::Debug::to_string () const virtual
Reimplemented in LIEF::PE::CodeView, LIEF::PE::CodeViewPDB, LIEF::PE::ExDllCharacteristics, LIEF::PE::FPO, LIEF::PE::PDBChecksum, LIEF::PE::Pogo, LIEF::PE::Repro, and LIEF::PE::VCFeature.
References LIEF_API.
Referenced by operator<<.
type()
TYPES LIEF::PE::Debug::type () const inline
The format DEBUG_TYPES of the debugging information.
Referenced by Debug().
The documentation for this class was generated from the following file:
debug/Debug.hpp