LIEF: Library to Instrument Executable Formats: LIEF::dwarf::editor::FunctionType Class Reference
LIEF::dwarf::editor::FunctionType Class Reference
This class represents a function type (DW_TAG_subroutine_type).
#include <FunctionType.hpp>
Classes
class Parameter
This class represents a function's parameter.
Public Member Functions
template<typename... Args, typename = typename std:: enable_if<std::is_constructible<Type, Args&&...>::value>::type>
FunctionType (Args &&... args)
FunctionType & set_return_type (const Type &type)
Set the return type of this function.
std::unique_ptr< Parameter > add_parameter (const Type &type)
Add a parameter.
~FunctionType () override=default
Public Member Functions inherited from LIEF::dwarf::editor::Type
Type ()=delete
Type (std::unique_ptr< details::Type > impl)
std::unique_ptr< PointerType > pointer_to () const
Create a pointer type pointing to this type.
virtual ~Type ()
const details::Type & impl () const
Static Public Member Functions
static bool classof (const Type *type)
Detailed Description
This class represents a function type (DW_TAG_subroutine_type).
Constructor & Destructor Documentation
FunctionType()
template<typename... Args, typename = typename std:: enable_if<std::is_constructible<Type, Args&&...>::value>::type> LIEF::dwarf::editor::FunctionType::FunctionType (Args &&... args) inline
References LIEF::dwarf::editor::Type::Type().
Referenced by set_return_type().
~FunctionType()
LIEF::dwarf::editor::FunctionType::~FunctionType () override default
Member Function Documentation
add_parameter()
std::unique_ptr< Parameter > LIEF::dwarf::editor::FunctionType::add_parameter (const Type & type)
Add a parameter.
References LIEF_LIFETIMEBOUND, and LIEF::dwarf::editor::Type::Type().
classof()
bool LIEF::dwarf::editor::FunctionType::classof (const Type * type) static
References LIEF::dwarf::editor::Type::Type().
set_return_type()
FunctionType & LIEF::dwarf::editor::FunctionType::set_return_type (const Type & type)
Set the return type of this function.
References FunctionType(), LIEF_LIFETIMEBOUND, and LIEF::dwarf::editor::Type::Type().
The documentation for this class was generated from the following file:
FunctionType.hpp