LIEF: Library to Instrument Executable Formats: LIEF::VDEX Namespace Reference
LIEF::VDEX Namespace Reference
Classes
class File
Main class for the VDEX module which represents a VDEX file.
class Hash
class Header
class Parser
Class which parse an VDEX file and transform into a VDEX::File object.
Typedefs
using vdex_version_t = uint32_t
using dex2dex_info_t = std::unordered_map<const DEX::File*, DEX::dex2dex_info_t>
Functions
std::string to_json (const Object &v)
bool is_vdex (const std::string &file)
Check if the given file is an VDEX one.
bool is_vdex (const std::vector< uint8_t > &raw)
Check if the given raw data is an VDEX one.
vdex_version_t version (const std::string &file)
Return the VDEX version of the given file.
vdex_version_t version (const std::vector< uint8_t > &raw)
Return the VDEX version of the raw data.
Android::ANDROID_VERSIONS android_version (vdex_version_t version)
Return the ANDROID_VERSIONS associated with the given VDEX version.
Typedef Documentation
dex2dex_info_t
using LIEF::VDEX::dex2dex_info_t = std::unordered_map<const DEX::File*, DEX::dex2dex_info_t>
vdex_version_t
using LIEF::VDEX::vdex_version_t = uint32_t
Function Documentation
android_version()
Android::ANDROID_VERSIONS LIEF::VDEX::android_version (vdex_version_t version)
Return the ANDROID_VERSIONS associated with the given VDEX version.
References LIEF_API, and version().
is_vdex() [1/2]
bool LIEF::VDEX::is_vdex (const std::string & file)
Check if the given file is an VDEX one.
References LIEF_API.
is_vdex() [2/2]
bool LIEF::VDEX::is_vdex (const std::vector< uint8_t > & raw)
Check if the given raw data is an VDEX one.
References LIEF_API.
to_json()
std::string LIEF::VDEX::to_json (const Object & v)
References LIEF_API.
version() [1/2]
vdex_version_t LIEF::VDEX::version (const std::string & file)
Return the VDEX version of the given file.
References LIEF_API.
Referenced by android_version(), and LIEF::VDEX::Parser::Parser().
version() [2/2]
vdex_version_t LIEF::VDEX::version (const std::vector< uint8_t > & raw)
Return the VDEX version of the raw data.
References LIEF_API.