LIEF: Library to Instrument Executable Formats: LIEF::logging::named Namespace Reference
LIEF::logging::named Namespace Reference
Functions
LEVEL get_level (const char *name)
Get the logging level for the logger with the given name.
void disable (const char *name)
Disable the logger with the given name.
void enable (const char *name)
Enable the logger with the given name.
void set_level (const char *name, LEVEL level)
Set the log level for the logger with the given name.
void set_path (const char *name, const std::string &path)
Change the logger with the given as a file-base logging and set its path.
void log (const char *name, LEVEL level, const std::string &msg)
Log a message with the logger whose name in provided in the first parameter.
void set_logger (const char *name, std::shared_ptr< spdlog::logger > logger)
Set a spdlog sink for the logger with the given name.
spdlog::logger & get_sink (const char *name)
void reset (const char *name)
Reset the logger with the given name.
void enable_debug (const char *name)
Enable debug logging for the logger with the given name.
void debug (const char *name, const std::string &msg)
void info (const char *name, const std::string &msg)
void warn (const char *name, const std::string &msg)
void err (const char *name, const std::string &msg)
void critical (const char *name, const std::string &msg)
Function Documentation
critical()
void LIEF::logging::named::critical (const char * name, const std::string & msg) inline
References LIEF::logging::CRITICAL, and log().
debug()
void LIEF::logging::named::debug (const char * name, const std::string & msg) inline
References LIEF::logging::DEBUG, and log().
disable()
void LIEF::logging::named::disable (const char * name)
Disable the logger with the given name.
References LIEF_API.
enable()
void LIEF::logging::named::enable (const char * name)
Enable the logger with the given name.
References LIEF_API.
enable_debug()
void LIEF::logging::named::enable_debug (const char * name) inline
Enable debug logging for the logger with the given name.
References LIEF::logging::DEBUG, and set_level().
err()
void LIEF::logging::named::err (const char * name, const std::string & msg) inline
References LIEF::logging::ERR, and log().
get_level()
LEVEL LIEF::logging::named::get_level (const char * name)
Get the logging level for the logger with the given name.
References LIEF_API.
get_sink()
spdlog::logger & LIEF::logging::named::get_sink (const char * name)
References LIEF_API.
info()
void LIEF::logging::named::info (const char * name, const std::string & msg) inline
References LIEF::logging::INFO, and log().
log()
void LIEF::logging::named::log (const char * name, LEVEL level, const std::string & msg)
Log a message with the logger whose name in provided in the first parameter.
References LIEF_API.
Referenced by critical(), debug(), err(), info(), and warn().
reset()
void LIEF::logging::named::reset (const char * name)
Reset the logger with the given name.
References LIEF_API.
set_level()
void LIEF::logging::named::set_level (const char * name, LEVEL level)
Set the log level for the logger with the given name.
References LIEF_API.
Referenced by enable_debug().
set_logger()
void LIEF::logging::named::set_logger (const char * name, std::shared_ptr< spdlog::logger > logger)
Set a spdlog sink for the logger with the given name.
References LIEF_API.
set_path()
void LIEF::logging::named::set_path (const char * name, const std::string & path)
Change the logger with the given as a file-base logging and set its path.
References LIEF_API.
warn()
void LIEF::logging::named::warn (const char * name, const std::string & msg) inline
References log(), and LIEF::logging::WARN.