LIEF: Library to Instrument Executable Formats: LIEF Namespace Reference
LIEF Namespace Reference
LIEF namespace.
Namespaces
namespace assembly
Namespace related to assembly/disassembly support.
namespace details
namespace ELF
Namespace related to the LIEF's ELF module.
namespace PE
Namespace related to the LIEF's PE module.
namespace MachO
Namespace related to the LIEF's Mach-O module.
namespace ART
Namespace related to the LIEF's ART module.
namespace COFF
namespace DEX
namespace dwarf
Namespace for the DWARF debug format.
namespace dsc
Namespace related to the dyld shared cache support.
namespace OAT
namespace logging
namespace objc
Namespace related to ObjC metadata.
namespace VDEX
namespace pdb
namespace Android
Classes
class Binary
Generic interface representing a binary executable.
class DebugInfo
This class provides a generic interface for accessing debug information from different formats such as DWARF and PDB.
class Function
Class that represents a function in the binary.
class AbstractHash
class Header
class Parser
Main interface to parse an executable regardless of its format.
class Relocation
Class which represents an abstracted Relocation.
class Section
Class which represents an abstracted section.
class Symbol
This class represents a symbol in an executable format.
class ASN1Reader
class BinaryStream
Class that is used to a read stream of data from different sources.
class ScopedStream
class ToggleEndianness
class FileStream
Stream interface over a std::ifstream.
class MemoryStream
class SpanStream
class VectorStream
struct debug_location_t
This structure holds a debug location (source filename & line).
class result
Wrapper that contains an Object (T) or an error.
struct ok_t
Opaque structure used by ok_error_t.
class ok_error_t
Opaque structure that is used by LIEF to avoid writing result<void> f(...). Instead, it makes the output explicit such as:
class Hash
class vector_iostream
class ScopeOStream
class ref_iterator
Iterator which returns reference on container's values.
class filter_iterator
Iterator which return a ref on container's values given predicates.
class iterator_range
class iterator_facade_base
CRTP base class which implements the entire standard iterator facade in terms of a minimal subset of the interface.
class iterator_adaptor_base
CRTP base class for adapting an iterator to a different type.
struct pointee_iterator
An iterator type that allows iterating over the pointees via some other iterator.
class pointer_iterator
class Object
class optional
struct range_t
struct lief_version_t
class Visitor
Typedefs
template<class T>
using decay_t = typename std::decay<T>::type
template<class T>
using add_const_t = typename std::add_const<T>::type
template<class T>
using remove_const_t = typename std::remove_const<T>::type
template<class T>
using add_lvalue_reference_t = typename std::add_lvalue_reference<T>::type
template<class T, typename U = typename decay_t<T>::value_type, class CT = typename std::add_const<T>::type>
using const_ref_iterator = ref_iterator<CT, U, typename decay_t<CT>::const_iterator>
Iterator which return const ref on container's values.
template<class T, typename U = typename decay_t<T>::value_type, class CT = typename std::add_const<T>::type>
using const_filter_iterator = filter_iterator<CT, U, typename decay_t<CT>::const_iterator>
Iterator which return a const ref on container's values given predicates.
template<typename WrappedIteratorT, typename T1 = typename std::remove_reference<decltype(**std::declval<WrappedIteratorT>())>::type, typename T2 = typename std::add_pointer<T1>::type>
using raw_pointer_iterator
template<typename ElementType, std::size_t Extent = tcb::dynamic_extent>
using span = tcb::span<ElementType, Extent>
Enumerations
enum PLATFORMS {
PLAT_UNKNOWN = 0 , PLAT_LINUX , PLAT_ANDROID , PLAT_WINDOWS ,
PLAT_IOS , PLAT_OSX
}
Functions
const char * to_string (Binary::VA_TYPES e)
const char * to_string (Binary::FORMATS e)
const char * to_string (Function::FLAGS e)
const char * to_string (Header::ARCHITECTURES e)
const char * to_string (Header::OBJECT_TYPES e)
const char * to_string (Header::MODES e)
const char * to_string (Header::ENDIANNESS e)
std::string to_json_from_abstract (const Object &v)
template<typename T>
void swap_endian (T *)
template<typename T>
T get_swapped_endian (const T &other)
template<>
void swap_endian< char > (char *hdr)
template<>
void swap_endian< char16_t > (char16_t *hdr)
template<>
void swap_endian< uint8_t > (uint8_t *hdr)
template<>
void swap_endian< uint16_t > (uint16_t *hdr)
template<>
void swap_endian< uint32_t > (uint32_t *hdr)
template<>
void swap_endian< uint64_t > (uint64_t *hdr)
template<>
void swap_endian< int8_t > (int8_t *hdr)
template<>
void swap_endian< int16_t > (int16_t *hdr)
template<>
void swap_endian< int32_t > (int32_t *hdr)
template<>
void swap_endian< int64_t > (int64_t *hdr)
template<>
void swap_endian< ELF::details::Elf32_Auxv > (ELF::details::Elf32_Auxv *hdr)
template<>
void swap_endian< ELF::details::Elf32_Dyn > (ELF::details::Elf32_Dyn *hdr)
template<>
void swap_endian< ELF::details::Elf32_Ehdr > (ELF::details::Elf32_Ehdr *hdr)
template<>
void swap_endian< ELF::details::Elf32_FileEntry > (ELF::details::Elf32_FileEntry *hdr)
template<>
void swap_endian< ELF::details::Elf32_Phdr > (ELF::details::Elf32_Phdr *hdr)
template<>
void swap_endian< ELF::details::Elf32_Rel > (ELF::details::Elf32_Rel *hdr)
template<>
void swap_endian< ELF::details::Elf32_Rela > (ELF::details::Elf32_Rela *hdr)
template<>
void swap_endian< ELF::details::Elf32_Shdr > (ELF::details::Elf32_Shdr *hdr)
template<>
void swap_endian< ELF::details::Elf32_Sym > (ELF::details::Elf32_Sym *hdr)
template<>
void swap_endian< ELF::details::Elf32_Verdaux > (ELF::details::Elf32_Verdaux *hdr)
template<>
void swap_endian< ELF::details::Elf32_Verdef > (ELF::details::Elf32_Verdef *hdr)
template<>
void swap_endian< ELF::details::Elf32_Vernaux > (ELF::details::Elf32_Vernaux *hdr)
template<>
void swap_endian< ELF::details::Elf32_Verneed > (ELF::details::Elf32_Verneed *hdr)
template<>
void swap_endian< ELF::details::Elf64_Auxv > (ELF::details::Elf64_Auxv *hdr)
template<>
void swap_endian< ELF::details::Elf64_Dyn > (ELF::details::Elf64_Dyn *hdr)
template<>
void swap_endian< ELF::details::Elf64_Ehdr > (ELF::details::Elf64_Ehdr *hdr)
template<>
void swap_endian< ELF::details::Elf64_FileEntry > (ELF::details::Elf64_FileEntry *hdr)
template<>
void swap_endian< ELF::details::Elf64_Phdr > (ELF::details::Elf64_Phdr *hdr)
template<>
void swap_endian< ELF::details::Elf64_Rel > (ELF::details::Elf64_Rel *hdr)
template<>
void swap_endian< ELF::details::Elf64_Rela > (ELF::details::Elf64_Rela *hdr)
template<>
void swap_endian< ELF::details::Elf64_Shdr > (ELF::details::Elf64_Shdr *hdr)
template<>
void swap_endian< ELF::details::Elf64_Sym > (ELF::details::Elf64_Sym *hdr)
template<>
void swap_endian< ELF::details::Elf64_Verdaux > (ELF::details::Elf64_Verdaux *hdr)
template<>
void swap_endian< ELF::details::Elf64_Verdef > (ELF::details::Elf64_Verdef *hdr)
template<>
void swap_endian< ELF::details::Elf64_Vernaux > (ELF::details::Elf64_Vernaux *hdr)
template<>
void swap_endian< ELF::details::Elf64_Verneed > (ELF::details::Elf64_Verneed *hdr)
template<>
void swap_endian< MachO::details::arm_thread_state64_t > (MachO::details::arm_thread_state64_t *hdr)
template<>
void swap_endian< MachO::details::arm_thread_state_t > (MachO::details::arm_thread_state_t *hdr)
template<>
void swap_endian< MachO::details::build_tool_version > (MachO::details::build_tool_version *hdr)
template<>
void swap_endian< MachO::details::build_version_command > (MachO::details::build_version_command *hdr)
template<>
void swap_endian< MachO::details::data_in_code_entry > (MachO::details::data_in_code_entry *hdr)
template<>
void swap_endian< MachO::details::dyld_info_command > (MachO::details::dyld_info_command *hdr)
template<>
void swap_endian< MachO::details::dylib_command > (MachO::details::dylib_command *hdr)
template<>
void swap_endian< MachO::details::dylib_module_32 > (MachO::details::dylib_module_32 *hdr)
template<>
void swap_endian< MachO::details::dylib_module_64 > (MachO::details::dylib_module_64 *hdr)
template<>
void swap_endian< MachO::details::dylib_reference > (MachO::details::dylib_reference *hdr)
template<>
void swap_endian< MachO::details::dylib_table_of_contents > (MachO::details::dylib_table_of_contents *hdr)
template<>
void swap_endian< MachO::details::dylinker_command > (MachO::details::dylinker_command *hdr)
template<>
void swap_endian< MachO::details::dysymtab_command > (MachO::details::dysymtab_command *hdr)
template<>
void swap_endian< MachO::details::encryption_info_command > (MachO::details::encryption_info_command *hdr)
template<>
void swap_endian< MachO::details::entry_point_command > (MachO::details::entry_point_command *hdr)
template<>
void swap_endian< MachO::details::fileset_entry_command > (MachO::details::fileset_entry_command *hdr)
template<>
void swap_endian< MachO::details::fvmfile_command > (MachO::details::fvmfile_command *hdr)
template<>
void swap_endian< MachO::details::ident_command > (MachO::details::ident_command *hdr)
template<>
void swap_endian< MachO::details::linkedit_data_command > (MachO::details::linkedit_data_command *hdr)
template<>
void swap_endian< MachO::details::linker_option_command > (MachO::details::linker_option_command *hdr)
template<>
void swap_endian< MachO::details::load_command > (MachO::details::load_command *hdr)
template<>
void swap_endian< MachO::details::mach_header > (MachO::details::mach_header *hdr)
template<>
void swap_endian< MachO::details::mach_header_64 > (MachO::details::mach_header_64 *hdr)
template<>
void swap_endian< MachO::details::nlist_32 > (MachO::details::nlist_32 *hdr)
template<>
void swap_endian< MachO::details::nlist_64 > (MachO::details::nlist_64 *hdr)
template<>
void swap_endian< MachO::details::prebind_cksum_command > (MachO::details::prebind_cksum_command *hdr)
template<>
void swap_endian< MachO::details::prebound_dylib_command > (MachO::details::prebound_dylib_command *hdr)
template<>
void swap_endian< MachO::details::relocation_info > (MachO::details::relocation_info *hdr)
template<>
void swap_endian< MachO::details::routines_command_32 > (MachO::details::routines_command_32 *hdr)
template<>
void swap_endian< MachO::details::routines_command_64 > (MachO::details::routines_command_64 *hdr)
template<>
void swap_endian< MachO::details::rpath_command > (MachO::details::rpath_command *hdr)
template<>
void swap_endian< MachO::details::scattered_relocation_info > (MachO::details::scattered_relocation_info *hdr)
template<>
void swap_endian< MachO::details::section_32 > (MachO::details::section_32 *hdr)
template<>
void swap_endian< MachO::details::section_64 > (MachO::details::section_64 *hdr)
template<>
void swap_endian< MachO::details::segment_command_32 > (MachO::details::segment_command_32 *hdr)
template<>
void swap_endian< MachO::details::segment_command_64 > (MachO::details::segment_command_64 *hdr)
template<>
void swap_endian< MachO::details::source_version_command > (MachO::details::source_version_command *hdr)
template<>
void swap_endian< MachO::details::sub_client_command > (MachO::details::sub_client_command *hdr)
template<>
void swap_endian< MachO::details::sub_framework_command > (MachO::details::sub_framework_command *hdr)
template<>
void swap_endian< MachO::details::sub_library_command > (MachO::details::sub_library_command *hdr)
template<>
void swap_endian< MachO::details::sub_umbrella_command > (MachO::details::sub_umbrella_command *hdr)
template<>
void swap_endian< MachO::details::symseg_command > (MachO::details::symseg_command *hdr)
template<>
void swap_endian< MachO::details::symtab_command > (MachO::details::symtab_command *hdr)
template<>
void swap_endian< MachO::details::thread_command > (MachO::details::thread_command *hdr)
template<>
void swap_endian< MachO::details::twolevel_hint > (MachO::details::twolevel_hint *hdr)
template<>
void swap_endian< MachO::details::twolevel_hints_command > (MachO::details::twolevel_hints_command *hdr)
template<>
void swap_endian< MachO::details::uuid_command > (MachO::details::uuid_command *hdr)
template<>
void swap_endian< MachO::details::version_min_command > (MachO::details::version_min_command *hdr)
template<>
void swap_endian< MachO::details::x86_thread_state64_t > (MachO::details::x86_thread_state64_t *hdr)
template<>
void swap_endian< MachO::details::x86_thread_state_t > (MachO::details::x86_thread_state_t *hdr)
template<>
void swap_endian< MachO::details::ppc_thread_state64_t > (MachO::details::ppc_thread_state64_t *hdr)
template<>
void swap_endian< MachO::details::ppc_thread_state_t > (MachO::details::ppc_thread_state_t *hdr)
template<class T>
lief_errors get_error (result< T > &err)
Get the error code associated with the result.
template<class T>
lief_errors as_lief_err (result< T > &err)
Return the lief_errors when the provided result<T> is an error.
ok_t ok ()
Return success for function with return type ok_error_t.
bool is_ok (const ok_error_t &val)
bool is_err (const ok_error_t &val)
Hash::value_type hash (const Object &v)
Hash::value_type hash (const std::vector< uint8_t > &raw)
Hash::value_type hash (span< const uint8_t > raw)
template<class T>
iterator_range< T > make_range (T &&x, T &&y)
template<typename RangeT, typename WrappedIteratorT = decltype(std::begin(std::declval<RangeT>()))>
iterator_range< pointee_iterator< WrappedIteratorT > > make_pointee_range (RangeT &&Range)
template<typename RangeT, typename WrappedIteratorT = decltype(std::begin(std::declval<RangeT>()))>
iterator_range< pointer_iterator< WrappedIteratorT > > make_pointer_range (RangeT &&Range)
std::string to_json (const Object &v)
tl::unexpected< lief_errors > nullopt ()
constexpr PLATFORMS current_platform ()
uint64_t align (uint64_t value, uint64_t align_on)
uint64_t align_down (uint64_t value, uint64_t align_on)
uint64_t align_with_offset (uint64_t value, uint64_t align_on, uint64_t offset)
template<typename T>
constexpr T round (T x)
template<>
uint64_t round< uint64_t > (uint64_t x)
constexpr size_t operator""_KB (unsigned long long kbs)
constexpr size_t operator""_MB (unsigned long long mbs)
constexpr size_t operator""_GB (unsigned long long gbs)
std::string u16tou8 (const std::u16string &string, bool remove_null_char=false)
Convert a UTF-16 string to a UTF-8 one.
result< std::u16string > u8tou16 (const std::string &string)
Convert a UTF-8 string to a UTF-16 one.
bool is_extended ()
Whether this version of LIEF includes extended features.
std::string extended_version_info ()
Details about the extended version.
lief_version_t extended_version ()
Return the extended version.
lief_version_t version ()
Return the current version.
result< std::string > demangle (const std::string &mangled)
Demangle the given input.
std::string dump (const uint8_t *buffer, size_t size, const std::string &title="", const std::string &prefix="", size_t limit=0)
Hexdump the provided buffer.
std::string dump (span< const uint8_t > data, const std::string &title="", const std::string &prefix="", size_t limit=0)
std::string dump (const std::vector< uint8_t > &data, const std::string &title="", const std::string &prefix="", size_t limit=0)
Detailed Description
LIEF namespace.
Typedef Documentation
add_const_t
template<class T> using LIEF::add_const_t = typename std::add_const<T>::type
add_lvalue_reference_t
template<class T> using LIEF::add_lvalue_reference_t = typename std::add_lvalue_reference<T>::type
const_filter_iterator
template<class T, typename U = typename decay_t<T>::value_type, class CT = typename std::add_const<T>::type> using LIEF::const_filter_iterator = filter_iterator<CT, U, typename decay_t<CT>::const_iterator>
Iterator which return a const ref on container's values given predicates.
const_ref_iterator
template<class T, typename U = typename decay_t<T>::value_type, class CT = typename std::add_const<T>::type> using LIEF::const_ref_iterator = ref_iterator<CT, U, typename decay_t<CT>::const_iterator>
Iterator which return const ref on container's values.
decay_t
template<class T> using LIEF::decay_t = typename std::decay<T>::type
raw_pointer_iterator
template<typename WrappedIteratorT, typename T1 = typename std::remove_reference<decltype(**std::declval<WrappedIteratorT>())>::type, typename T2 = typename std::add_pointer<T1>::type> using LIEF::raw_pointer_iterator
Initial value:
pointer_iterator<pointee_iterator<WrappedIteratorT, T1>, T2>
remove_const_t
template<class T> using LIEF::remove_const_t = typename std::remove_const<T>::type
span
template<typename ElementType, std::size_t Extent = tcb::dynamic_extent> using LIEF::span = tcb::span<ElementType, Extent>
Enumeration Type Documentation
PLATFORMS
enum LIEF::PLATFORMS
Enumerator
PLAT_UNKNOWN
PLAT_LINUX
PLAT_ANDROID
PLAT_WINDOWS
PLAT_IOS
PLAT_OSX
Function Documentation
align()
uint64_t LIEF::align (uint64_t value, uint64_t align_on) inline
Referenced by align_with_offset(), LIEF::MachO::Section::alignment(), and LIEF::MachO::Binary::virtual_size().
align_down()
uint64_t LIEF::align_down (uint64_t value, uint64_t align_on) inline
align_with_offset()
uint64_t LIEF::align_with_offset (uint64_t value, uint64_t align_on, uint64_t offset) inline
References align().
as_lief_err()
template<class T> lief_errors LIEF::as_lief_err (result< T > & err)
Return the lief_errors when the provided result<T> is an error.
current_platform()
PLATFORMS LIEF::current_platform () constexpr
References PLAT_ANDROID, PLAT_IOS, PLAT_LINUX, PLAT_OSX, PLAT_UNKNOWN, and PLAT_WINDOWS.
demangle()
result< std::string > LIEF::demangle (const std::string & mangled)
Demangle the given input.
This function only works with the extended version of LIEF
References LIEF_API.
dump() [1/3]
std::string LIEF::dump (const std::vector< uint8_t > & data, const std::string & title = "", const std::string & prefix = "", size_t limit = 0) inline
References dump().
dump() [2/3]
std::string LIEF::dump (const uint8_t * buffer, size_t size, const std::string & title = "", const std::string & prefix = "", size_t limit = 0)
Hexdump the provided buffer.
For instance:
+---------------------------------------------------------------------+
| 88 56 05 00 00 00 00 00 00 00 00 00 22 58 05 00  | .V.........."X.. |
| 10 71 02 00 78 55 05 00 00 00 00 00 00 00 00 00  | .q..xU.......... |
| 68 5c 05 00 00 70 02 00 00 00 00 00 00 00 00 00  | h\...p.......... |
| 00 00 00 00 00 00 00 00 00 00 00 00              | ............     |
+---------------------------------------------------------------------+
References LIEF_API.
Referenced by dump(), and dump().
dump() [3/3]
std::string LIEF::dump (span< const uint8_t > data, const std::string & title = "", const std::string & prefix = "", size_t limit = 0) inline
References dump().
extended_version()
lief_version_t LIEF::extended_version ()
Return the extended version.
References LIEF_API.
extended_version_info()
std::string LIEF::extended_version_info ()
Details about the extended version.
References LIEF_API.
get_error()
template<class T> lief_errors LIEF::get_error (result< T > & err)
Get the error code associated with the result.
get_swapped_endian()
template<typename T> T LIEF::get_swapped_endian (const T & other)
References swap_endian().
hash() [1/3]
Hash::value_type LIEF::hash (const Object & v)
References LIEF_API.
Referenced by LIEF::ELF::GnuHash::check(), LIEF::ELF::GnuHash::check_bloom_filter(), LIEF::ELF::GnuHash::check_bucket(), LIEF::PE::x509::check_signature(), and LIEF::Visitor::dispatch().
hash() [2/3]
Hash::value_type LIEF::hash (const std::vector< uint8_t > & raw)
References LIEF_API.
hash() [3/3]
Hash::value_type LIEF::hash (span< const uint8_t > raw)
References LIEF_API.
is_err()
bool LIEF::is_err (const ok_error_t & val) inline
References is_ok().
is_extended()
bool LIEF::is_extended ()
Whether this version of LIEF includes extended features.
References LIEF_API.
is_ok()
bool LIEF::is_ok (const ok_error_t & val) inline
Referenced by is_err().
make_pointee_range()
template<typename RangeT, typename WrappedIteratorT = decltype(std::begin(std::declval<RangeT>()))> iterator_range< pointee_iterator< WrappedIteratorT > > LIEF::make_pointee_range (RangeT && Range)
References make_range().
make_pointer_range()
template<typename RangeT, typename WrappedIteratorT = decltype(std::begin(std::declval<RangeT>()))> iterator_range< pointer_iterator< WrappedIteratorT > > LIEF::make_pointer_range (RangeT && Range)
References make_range().
make_range()
template<class T> iterator_range< T > LIEF::make_range (T && x, T && y)
Referenced by make_pointee_range(), and make_pointer_range().
nullopt()
tl::unexpected< lief_errors > LIEF::nullopt () inline
References make_error_code(), and not_found.
Referenced by LIEF::PE::ResourceStringTable::get(), and LIEF::assembly::AssemblerConfig::resolve_symbol().
ok()
ok_t LIEF::ok () inline
Return success for function with return type ok_error_t.
Referenced by LIEF::BinaryStream::peek_array(), LIEF::BinaryStream::peek_data(), LIEF::BinaryStream::peek_in(), LIEF::FileStream::peek_in(), LIEF::BinaryStream::peek_objects_at(), LIEF::BinaryStream::read_array(), LIEF::BinaryStream::read_data(), and LIEF::BinaryStream::read_objects().
operator""_GB()
size_t LIEF::operator""_GB (unsigned long long gbs) constexpr
operator""_KB()
size_t LIEF::operator""_KB (unsigned long long kbs) constexpr
operator""_MB()
size_t LIEF::operator""_MB (unsigned long long mbs) constexpr
round()
template<typename T> T LIEF::round (T x) inline constexpr
References round< uint64_t >().
round< uint64_t >()
template<> uint64_t LIEF::round< uint64_t > (uint64_t x) inline
Referenced by round().
swap_endian()
template<typename T> void LIEF::swap_endian (T *)
Referenced by get_swapped_endian(), LIEF::BinaryStream::peek(), and LIEF::vector_iostream::write().
swap_endian< char >()
template<> void LIEF::swap_endian< char > (char * hdr)
swap_endian< char16_t >()
template<> void LIEF::swap_endian< char16_t > (char16_t * hdr)
swap_endian< ELF::details::Elf32_Auxv >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Auxv > (ELF::details::Elf32_Auxv * hdr)
swap_endian< ELF::details::Elf32_Dyn >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Dyn > (ELF::details::Elf32_Dyn * hdr)
swap_endian< ELF::details::Elf32_Ehdr >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Ehdr > (ELF::details::Elf32_Ehdr * hdr)
swap_endian< ELF::details::Elf32_FileEntry >()
template<> void LIEF::swap_endian< ELF::details::Elf32_FileEntry > (ELF::details::Elf32_FileEntry * hdr)
swap_endian< ELF::details::Elf32_Phdr >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Phdr > (ELF::details::Elf32_Phdr * hdr)
swap_endian< ELF::details::Elf32_Rel >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Rel > (ELF::details::Elf32_Rel * hdr)
swap_endian< ELF::details::Elf32_Rela >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Rela > (ELF::details::Elf32_Rela * hdr)
swap_endian< ELF::details::Elf32_Shdr >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Shdr > (ELF::details::Elf32_Shdr * hdr)
swap_endian< ELF::details::Elf32_Sym >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Sym > (ELF::details::Elf32_Sym * hdr)
swap_endian< ELF::details::Elf32_Verdaux >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Verdaux > (ELF::details::Elf32_Verdaux * hdr)
swap_endian< ELF::details::Elf32_Verdef >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Verdef > (ELF::details::Elf32_Verdef * hdr)
swap_endian< ELF::details::Elf32_Vernaux >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Vernaux > (ELF::details::Elf32_Vernaux * hdr)
swap_endian< ELF::details::Elf32_Verneed >()
template<> void LIEF::swap_endian< ELF::details::Elf32_Verneed > (ELF::details::Elf32_Verneed * hdr)
swap_endian< ELF::details::Elf64_Auxv >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Auxv > (ELF::details::Elf64_Auxv * hdr)
swap_endian< ELF::details::Elf64_Dyn >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Dyn > (ELF::details::Elf64_Dyn * hdr)
swap_endian< ELF::details::Elf64_Ehdr >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Ehdr > (ELF::details::Elf64_Ehdr * hdr)
swap_endian< ELF::details::Elf64_FileEntry >()
template<> void LIEF::swap_endian< ELF::details::Elf64_FileEntry > (ELF::details::Elf64_FileEntry * hdr)
swap_endian< ELF::details::Elf64_Phdr >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Phdr > (ELF::details::Elf64_Phdr * hdr)
swap_endian< ELF::details::Elf64_Rel >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Rel > (ELF::details::Elf64_Rel * hdr)
swap_endian< ELF::details::Elf64_Rela >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Rela > (ELF::details::Elf64_Rela * hdr)
swap_endian< ELF::details::Elf64_Shdr >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Shdr > (ELF::details::Elf64_Shdr * hdr)
swap_endian< ELF::details::Elf64_Sym >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Sym > (ELF::details::Elf64_Sym * hdr)
swap_endian< ELF::details::Elf64_Verdaux >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Verdaux > (ELF::details::Elf64_Verdaux * hdr)
swap_endian< ELF::details::Elf64_Verdef >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Verdef > (ELF::details::Elf64_Verdef * hdr)
swap_endian< ELF::details::Elf64_Vernaux >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Vernaux > (ELF::details::Elf64_Vernaux * hdr)
swap_endian< ELF::details::Elf64_Verneed >()
template<> void LIEF::swap_endian< ELF::details::Elf64_Verneed > (ELF::details::Elf64_Verneed * hdr)
swap_endian< int16_t >()
template<> void LIEF::swap_endian< int16_t > (int16_t * hdr)
swap_endian< int32_t >()
template<> void LIEF::swap_endian< int32_t > (int32_t * hdr)
swap_endian< int64_t >()
template<> void LIEF::swap_endian< int64_t > (int64_t * hdr)
swap_endian< int8_t >()
template<> void LIEF::swap_endian< int8_t > (int8_t * hdr)
swap_endian< MachO::details::arm_thread_state64_t >()
template<> void LIEF::swap_endian< MachO::details::arm_thread_state64_t > (MachO::details::arm_thread_state64_t * hdr)
swap_endian< MachO::details::arm_thread_state_t >()
template<> void LIEF::swap_endian< MachO::details::arm_thread_state_t > (MachO::details::arm_thread_state_t * hdr)
swap_endian< MachO::details::build_tool_version >()
template<> void LIEF::swap_endian< MachO::details::build_tool_version > (MachO::details::build_tool_version * hdr)
swap_endian< MachO::details::build_version_command >()
template<> void LIEF::swap_endian< MachO::details::build_version_command > (MachO::details::build_version_command * hdr)
swap_endian< MachO::details::data_in_code_entry >()
template<> void LIEF::swap_endian< MachO::details::data_in_code_entry > (MachO::details::data_in_code_entry * hdr)
swap_endian< MachO::details::dyld_info_command >()
template<> void LIEF::swap_endian< MachO::details::dyld_info_command > (MachO::details::dyld_info_command * hdr)
swap_endian< MachO::details::dylib_command >()
template<> void LIEF::swap_endian< MachO::details::dylib_command > (MachO::details::dylib_command * hdr)
swap_endian< MachO::details::dylib_module_32 >()
template<> void LIEF::swap_endian< MachO::details::dylib_module_32 > (MachO::details::dylib_module_32 * hdr)
swap_endian< MachO::details::dylib_module_64 >()
template<> void LIEF::swap_endian< MachO::details::dylib_module_64 > (MachO::details::dylib_module_64 * hdr)
swap_endian< MachO::details::dylib_reference >()
template<> void LIEF::swap_endian< MachO::details::dylib_reference > (MachO::details::dylib_reference * hdr)
swap_endian< MachO::details::dylib_table_of_contents >()
template<> void LIEF::swap_endian< MachO::details::dylib_table_of_contents > (MachO::details::dylib_table_of_contents * hdr)
swap_endian< MachO::details::dylinker_command >()
template<> void LIEF::swap_endian< MachO::details::dylinker_command > (MachO::details::dylinker_command * hdr)
swap_endian< MachO::details::dysymtab_command >()
template<> void LIEF::swap_endian< MachO::details::dysymtab_command > (MachO::details::dysymtab_command * hdr)
swap_endian< MachO::details::encryption_info_command >()
template<> void LIEF::swap_endian< MachO::details::encryption_info_command > (MachO::details::encryption_info_command * hdr)
swap_endian< MachO::details::entry_point_command >()
template<> void LIEF::swap_endian< MachO::details::entry_point_command > (MachO::details::entry_point_command * hdr)
swap_endian< MachO::details::fileset_entry_command >()
template<> void LIEF::swap_endian< MachO::details::fileset_entry_command > (MachO::details::fileset_entry_command * hdr)
swap_endian< MachO::details::fvmfile_command >()
template<> void LIEF::swap_endian< MachO::details::fvmfile_command > (MachO::details::fvmfile_command * hdr)
swap_endian< MachO::details::ident_command >()
template<> void LIEF::swap_endian< MachO::details::ident_command > (MachO::details::ident_command * hdr)
swap_endian< MachO::details::linkedit_data_command >()
template<> void LIEF::swap_endian< MachO::details::linkedit_data_command > (MachO::details::linkedit_data_command * hdr)
swap_endian< MachO::details::linker_option_command >()
template<> void LIEF::swap_endian< MachO::details::linker_option_command > (MachO::details::linker_option_command * hdr)
swap_endian< MachO::details::load_command >()
template<> void LIEF::swap_endian< MachO::details::load_command > (MachO::details::load_command * hdr)
swap_endian< MachO::details::mach_header >()
template<> void LIEF::swap_endian< MachO::details::mach_header > (MachO::details::mach_header * hdr)
swap_endian< MachO::details::mach_header_64 >()
template<> void LIEF::swap_endian< MachO::details::mach_header_64 > (MachO::details::mach_header_64 * hdr)
swap_endian< MachO::details::nlist_32 >()
template<> void LIEF::swap_endian< MachO::details::nlist_32 > (MachO::details::nlist_32 * hdr)
swap_endian< MachO::details::nlist_64 >()
template<> void LIEF::swap_endian< MachO::details::nlist_64 > (MachO::details::nlist_64 * hdr)
swap_endian< MachO::details::ppc_thread_state64_t >()
template<> void LIEF::swap_endian< MachO::details::ppc_thread_state64_t > (MachO::details::ppc_thread_state64_t * hdr)
swap_endian< MachO::details::ppc_thread_state_t >()
template<> void LIEF::swap_endian< MachO::details::ppc_thread_state_t > (MachO::details::ppc_thread_state_t * hdr)
swap_endian< MachO::details::prebind_cksum_command >()
template<> void LIEF::swap_endian< MachO::details::prebind_cksum_command > (MachO::details::prebind_cksum_command * hdr)
swap_endian< MachO::details::prebound_dylib_command >()
template<> void LIEF::swap_endian< MachO::details::prebound_dylib_command > (MachO::details::prebound_dylib_command * hdr)
swap_endian< MachO::details::relocation_info >()
template<> void LIEF::swap_endian< MachO::details::relocation_info > (MachO::details::relocation_info * hdr)
swap_endian< MachO::details::routines_command_32 >()
template<> void LIEF::swap_endian< MachO::details::routines_command_32 > (MachO::details::routines_command_32 * hdr)
swap_endian< MachO::details::routines_command_64 >()
template<> void LIEF::swap_endian< MachO::details::routines_command_64 > (MachO::details::routines_command_64 * hdr)
swap_endian< MachO::details::rpath_command >()
template<> void LIEF::swap_endian< MachO::details::rpath_command > (MachO::details::rpath_command * hdr)
swap_endian< MachO::details::scattered_relocation_info >()
template<> void LIEF::swap_endian< MachO::details::scattered_relocation_info > (MachO::details::scattered_relocation_info * hdr)
swap_endian< MachO::details::section_32 >()
template<> void LIEF::swap_endian< MachO::details::section_32 > (MachO::details::section_32 * hdr)
swap_endian< MachO::details::section_64 >()
template<> void LIEF::swap_endian< MachO::details::section_64 > (MachO::details::section_64 * hdr)
swap_endian< MachO::details::segment_command_32 >()
template<> void LIEF::swap_endian< MachO::details::segment_command_32 > (MachO::details::segment_command_32 * hdr)
swap_endian< MachO::details::segment_command_64 >()
template<> void LIEF::swap_endian< MachO::details::segment_command_64 > (MachO::details::segment_command_64 * hdr)
swap_endian< MachO::details::source_version_command >()
template<> void LIEF::swap_endian< MachO::details::source_version_command > (MachO::details::source_version_command * hdr)
swap_endian< MachO::details::sub_client_command >()
template<> void LIEF::swap_endian< MachO::details::sub_client_command > (MachO::details::sub_client_command * hdr)
swap_endian< MachO::details::sub_framework_command >()
template<> void LIEF::swap_endian< MachO::details::sub_framework_command > (MachO::details::sub_framework_command * hdr)
swap_endian< MachO::details::sub_library_command >()
template<> void LIEF::swap_endian< MachO::details::sub_library_command > (MachO::details::sub_library_command * hdr)
swap_endian< MachO::details::sub_umbrella_command >()
template<> void LIEF::swap_endian< MachO::details::sub_umbrella_command > (MachO::details::sub_umbrella_command * hdr)
swap_endian< MachO::details::symseg_command >()
template<> void LIEF::swap_endian< MachO::details::symseg_command > (MachO::details::symseg_command * hdr)
swap_endian< MachO::details::symtab_command >()
template<> void LIEF::swap_endian< MachO::details::symtab_command > (MachO::details::symtab_command * hdr)
swap_endian< MachO::details::thread_command >()
template<> void LIEF::swap_endian< MachO::details::thread_command > (MachO::details::thread_command * hdr)
swap_endian< MachO::details::twolevel_hint >()
template<> void LIEF::swap_endian< MachO::details::twolevel_hint > (MachO::details::twolevel_hint * hdr)
swap_endian< MachO::details::twolevel_hints_command >()
template<> void LIEF::swap_endian< MachO::details::twolevel_hints_command > (MachO::details::twolevel_hints_command * hdr)
swap_endian< MachO::details::uuid_command >()
template<> void LIEF::swap_endian< MachO::details::uuid_command > (MachO::details::uuid_command * hdr)
swap_endian< MachO::details::version_min_command >()
template<> void LIEF::swap_endian< MachO::details::version_min_command > (MachO::details::version_min_command * hdr)
swap_endian< MachO::details::x86_thread_state64_t >()
template<> void LIEF::swap_endian< MachO::details::x86_thread_state64_t > (MachO::details::x86_thread_state64_t * hdr)
swap_endian< MachO::details::x86_thread_state_t >()
template<> void LIEF::swap_endian< MachO::details::x86_thread_state_t > (MachO::details::x86_thread_state_t * hdr)
swap_endian< uint16_t >()
template<> void LIEF::swap_endian< uint16_t > (uint16_t * hdr)
swap_endian< uint32_t >()
template<> void LIEF::swap_endian< uint32_t > (uint32_t * hdr)
swap_endian< uint64_t >()
template<> void LIEF::swap_endian< uint64_t > (uint64_t * hdr)
swap_endian< uint8_t >()
template<> void LIEF::swap_endian< uint8_t > (uint8_t * hdr)
to_json()
std::string LIEF::to_json (const Object & v)
References LIEF_API.
to_json_from_abstract()
std::string LIEF::to_json_from_abstract (const Object & v)
References LIEF_API.
to_string() [1/7]
const char * LIEF::to_string (Binary::FORMATS e)
References LIEF_API.
to_string() [2/7]
const char * LIEF::to_string (Binary::VA_TYPES e)
References LIEF_API.
to_string() [3/7]
const char * LIEF::to_string (Function::FLAGS e)
References LIEF_API.
to_string() [4/7]
const char * LIEF::to_string (Header::ARCHITECTURES e)
References LIEF_API.
to_string() [5/7]
const char * LIEF::to_string (Header::ENDIANNESS e)
References LIEF_API.
to_string() [6/7]
const char * LIEF::to_string (Header::MODES e)
References LIEF_API.
to_string() [7/7]
const char * LIEF::to_string (Header::OBJECT_TYPES e)
References LIEF_API.
u16tou8()
std::string LIEF::u16tou8 (const std::u16string & string, bool remove_null_char = false)
Convert a UTF-16 string to a UTF-8 one.
References LIEF_API.
u8tou16()
result< std::u16string > LIEF::u8tou16 (const std::string & string)
Convert a UTF-8 string to a UTF-16 one.
References LIEF_API.
version()
lief_version_t LIEF::version ()
Return the current version.
References LIEF_API.
Referenced by LIEF::ELF::Binary::add_dynamic_symbol(), LIEF::Android::code_name(), LIEF::MachO::DylibCommand::compatibility_version(), LIEF::MachO::DylibCommand::current_version(), LIEF::MachO::DyldChainedFixups::fixups_version(), LIEF::ELF::Header::identity_abi_version(), LIEF::ELF::Header::identity_version(), LIEF::MachO::DylibCommand::int2version(), LIEF::MachO::BuildVersion::minos(), LIEF::ELF::Header::object_file_version(), LIEF::lief_version_t::operator<<, LIEF::PE::ResourceVersion::operator<<, LIEF::MachO::Binary::platform(), LIEF::MachO::BuildVersion::sdk(), LIEF::ELF::AndroidIdent::sdk_version(), LIEF::Android::to_string(), LIEF::ELF::to_string(), LIEF::ELF::to_string(), LIEF::MachO::DylibCommand::version2int(), and LIEF::Android::version_string().