LIEF: Library to Instrument Executable Formats: LIEF::PE::ResourceStringTable::entry_t Struct Reference
LIEF::PE::ResourceStringTable::entry_t Struct Reference
An entry in this table which is composed of an UTF-16 key and an UTF-16 value.
#include <ResourceStringTable.hpp>
Public Member Functions
std::string key_u8 () const
Key in utf8 representation.
std::string value_u8 () const
Value in utf8 representation.
bool is_defined () const
operator bool () const
std::string to_string () const
Public Attributes
std::u16string key
std::u16string value
Detailed Description
An entry in this table which is composed of an UTF-16 key and an UTF-16 value.
Member Function Documentation
is_defined()
bool LIEF::PE::ResourceStringTable::entry_t::is_defined () const inline
References key, and value.
Referenced by operator bool().
key_u8()
std::string LIEF::PE::ResourceStringTable::entry_t::key_u8 () const
Key in utf8 representation.
Referenced by to_string().
operator bool()
LIEF::PE::ResourceStringTable::entry_t::operator bool () const inline
References is_defined().
to_string()
std::string LIEF::PE::ResourceStringTable::entry_t::to_string () const inline
References key_u8(), and value_u8().
Referenced by operator<<.
value_u8()
std::string LIEF::PE::ResourceStringTable::entry_t::value_u8 () const
Value in utf8 representation.
Referenced by to_string().
Member Data Documentation
key
std::u16string LIEF::PE::ResourceStringTable::entry_t::key
Referenced by is_defined().
value
std::u16string LIEF::PE::ResourceStringTable::entry_t::value
Referenced by is_defined().
The documentation for this struct was generated from the following file:
ResourceStringTable.hpp