LIEF: Library to Instrument Executable Formats: LIEF::PE::details::arm64_unpacked_t Struct Reference
LIEF::PE::details::arm64_unpacked_t Struct Reference
#include <internal_arm64.hpp>
Public Member Functions
uint32_t function_length () const
uint8_t version () const
bool X () const
uint8_t E () const
uint16_t epilog_count () const
uint8_t code_words () const
bool is_extended () const
Public Attributes
std::array< uint32_t, MAX_WORDS > data = {0}
Static Public Attributes
static constexpr auto MAX_WORDS = 2
Member Function Documentation
code_words()
uint8_t LIEF::PE::details::arm64_unpacked_t::code_words () const inline
References data, and is_extended().
E()
uint8_t LIEF::PE::details::arm64_unpacked_t::E () const inline
References data.
epilog_count()
uint16_t LIEF::PE::details::arm64_unpacked_t::epilog_count () const inline
References data, and is_extended().
function_length()
uint32_t LIEF::PE::details::arm64_unpacked_t::function_length () const inline
References data.
is_extended()
bool LIEF::PE::details::arm64_unpacked_t::is_extended () const inline
References data.
Referenced by code_words(), and epilog_count().
version()
uint8_t LIEF::PE::details::arm64_unpacked_t::version () const inline
References data.
X()
bool LIEF::PE::details::arm64_unpacked_t::X () const inline
References data.
Member Data Documentation
data
std::array<uint32_t, MAX_WORDS> LIEF::PE::details::arm64_unpacked_t::data = {0}
Referenced by code_words(), E(), epilog_count(), function_length(), is_extended(), version(), and X().
MAX_WORDS
auto LIEF::PE::details::arm64_unpacked_t::MAX_WORDS = 2 static constexpr
The documentation for this struct was generated from the following file:
internal_arm64.hpp