LIEF: Library to Instrument Executable Formats: LIEF::PE::ResourceDialog::ordinal_or_str_t Struct Reference
LIEF::PE::ResourceDialog::ordinal_or_str_t Struct Reference
This structure wraps either an ordinal value (uint16_t) or a string. The ordinal value should refer to an existing resource id in the resource tree.
#include <ResourceDialog.hpp>
Public Member Functions
bool is_defined () const
operator bool () const
std::string to_string () const
Public Attributes
result< uint16_t > ordinal = make_error_code(lief_errors::not_found)
std::u16string string
Detailed Description
This structure wraps either an ordinal value (uint16_t) or a string. The ordinal value should refer to an existing resource id in the resource tree.
Member Function Documentation
is_defined()
bool LIEF::PE::ResourceDialog::ordinal_or_str_t::is_defined () const inline
References ordinal.
Referenced by operator bool().
operator bool()
LIEF::PE::ResourceDialog::ordinal_or_str_t::operator bool () const inline
References is_defined().
to_string()
std::string LIEF::PE::ResourceDialog::ordinal_or_str_t::to_string () const
Member Data Documentation
ordinal
result<uint16_t> LIEF::PE::ResourceDialog::ordinal_or_str_t::ordinal = make_error_code(lief_errors::not_found)
Referenced by is_defined().
string
std::u16string LIEF::PE::ResourceDialog::ordinal_or_str_t::string
The documentation for this struct was generated from the following file:
ResourceDialog.hpp