LIEF: Library to Instrument Executable Formats: LIEF::dwarf::Variable::Iterator Class Reference
LIEF::dwarf::Variable::Iterator Class Reference final
#include <Variable.hpp>
Public Types
using implementation = details::VariableIt
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::bidirectional_iterator_tag, Variable, std::ptrdiff_t, const Variable *, const Variable & >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Public Member Functions
Iterator ()
Iterator (std::unique_ptr< details::VariableIt > impl)
Iterator (const Iterator &)
Iterator & operator= (const Iterator &)
Iterator (Iterator &&) noexcept
Iterator & operator= (Iterator &&) noexcept
~Iterator ()
Iterator & operator++ ()
Iterator & operator-- ()
const Variable & operator* () const
const Variable * operator-> () const
std::unique_ptr< Variable > yield ()
Transfer ownership of the variable at the current position to the caller. Returns nullptr if the iterator is past-the-end.
DerivedT operator++ (int)
DerivedT operator-- (int)
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::bidirectional_iterator_tag, Variable, std::ptrdiff_t, const Variable *, const Variable & >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Member Typedef Documentation
implementation
using LIEF::dwarf::Variable::Iterator::implementation = details::VariableIt
Constructor & Destructor Documentation
Iterator() [1/4]
LIEF::dwarf::Variable::Iterator::Iterator ()
References LIEF_API.
Referenced by Iterator(), Iterator(), operator!=, operator++(), operator--(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/4]
LIEF::dwarf::Variable::Iterator::Iterator (std::unique_ptr< details::VariableIt > impl)
References LIEF_API.
Iterator() [3/4]
LIEF::dwarf::Variable::Iterator::Iterator (const Iterator &)
References Iterator(), and LIEF_API.
Iterator() [4/4]
LIEF::dwarf::Variable::Iterator::Iterator (Iterator &&) noexcept
References Iterator(), and LIEF_API.
~Iterator()
LIEF::dwarf::Variable::Iterator::~Iterator ()
References Iterator(), and LIEF_API.
Member Function Documentation
operator*()
const Variable & LIEF::dwarf::Variable::Iterator::operator* () const
References LIEF_API, LIEF_LIFETIMEBOUND, and LIEF::dwarf::Variable::Variable().
operator++() [1/2]
Iterator & LIEF::dwarf::Variable::Iterator::operator++ ()
References Iterator(), and LIEF_API.
operator++() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator++ (int) inline
operator--() [1/2]
Iterator & LIEF::dwarf::Variable::Iterator::operator-- ()
References Iterator(), and LIEF_API.
operator--() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator-- (int) inline
operator->()
const Variable * LIEF::dwarf::Variable::Iterator::operator-> () const
References LIEF_API, LIEF_LIFETIMEBOUND, and LIEF::dwarf::Variable::Variable().
operator=() [1/2]
Iterator & LIEF::dwarf::Variable::Iterator::operator= (const Iterator &)
References Iterator(), and LIEF_API.
operator=() [2/2]
Iterator & LIEF::dwarf::Variable::Iterator::operator= (Iterator &&) noexcept
References Iterator(), and LIEF_API.
yield()
std::unique_ptr< Variable > LIEF::dwarf::Variable::Iterator::yield ()
Transfer ownership of the variable at the current position to the caller. Returns nullptr if the iterator is past-the-end.
References LIEF_API, LIEF::dwarf::Variable::Variable(), and yield().
Referenced by yield().
The documentation for this class was generated from the following file:
Variable.hpp