LIEF: Library to Instrument Executable Formats: LIEF::ELF::NoteGnuProperty::Property Class Reference
LIEF::ELF::NoteGnuProperty::Property Class Reference
This class wraps the different properties that can be used in a NT_GNU_PROPERTY_TYPE_0 note.
#include <NoteGnuProperty.hpp>
Public Types
enum class TYPE {
UNKNOWN = 0 , GENERIC , AARCH64_FEATURES , AARCH64_PAUTH ,
STACK_SIZE , NO_COPY_ON_PROTECTED , X86_ISA , X86_FEATURE ,
NEEDED
}
LIEF's mirror types of the original GNU_PROPERTY_ values.
Public Member Functions
TYPE type () const
Return the LIEF's mirror type of the note.
virtual void dump (std::ostream &os) const
virtual ~Property ()=default
Detailed Description
This class wraps the different properties that can be used in a NT_GNU_PROPERTY_TYPE_0 note.
Member Enumeration Documentation
TYPE
enum class LIEF::ELF::NoteGnuProperty::Property::TYPE strong
LIEF's mirror types of the original GNU_PROPERTY_ values.
Enumerator
UNKNOWN
GENERIC
Property that dont' have special implementation.
AARCH64_FEATURES
Mirror of GNU_PROPERTY_AARCH64_FEATURE_1_AND
AARCH64_PAUTH
Mirror of GNU_PROPERTY_AARCH64_FEATURE_PAUTH
STACK_SIZE
Mirror of GNU_PROPERTY_STACK_SIZE
NO_COPY_ON_PROTECTED
Mirror of GNU_PROPERTY_NO_COPY_ON_PROTECTED
X86_ISA
Mirror of GNU_PROPERTY_X86_ISA_1_* and GNU_PROPERTY_X86_COMPAT_*
X86_FEATURE
Mirror of GNU_PROPERTY_X86_FEATURE_*
NEEDED
Constructor & Destructor Documentation
~Property()
virtual LIEF::ELF::NoteGnuProperty::Property::~Property () virtual default
Member Function Documentation
dump()
virtual void LIEF::ELF::NoteGnuProperty::Property::dump (std::ostream & os) const virtual
Reimplemented in LIEF::ELF::AArch64Feature, LIEF::ELF::AArch64PAuth, LIEF::ELF::StackSize, LIEF::ELF::X86Features, and LIEF::ELF::X86ISA.
Referenced by operator<<.
type()
TYPE LIEF::ELF::NoteGnuProperty::Property::type () const inline
Return the LIEF's mirror type of the note.
Referenced by LIEF::ELF::AArch64Feature::classof(), LIEF::ELF::AArch64PAuth::classof(), LIEF::ELF::Generic::classof(), LIEF::ELF::Needed::classof(), LIEF::ELF::NoteNoCopyOnProtected::classof(), LIEF::ELF::StackSize::classof(), LIEF::ELF::X86Features::classof(), and LIEF::ELF::X86ISA::classof().
The documentation for this class was generated from the following file:
NoteGnuProperty.hpp