LIEF: Library to Instrument Executable Formats: LIEF::pdb::Type Class Reference
LIEF::pdb::Type Class Reference
This is the base class for any PDB type.
#include <Type.hpp>
Classes
class Iterator
Public Types
enum class KIND {
UNKNOWN = 0 , CLASS , POINTER , SIMPLE ,
ENUM , FUNCTION , MODIFIER , BITFIELD ,
ARRAY , UNION , STRUCTURE , INTERFACE
}
Public Member Functions
KIND kind () const
template<class T >
const T * as () const
virtual ~Type ()
Static Public Member Functions
static std::unique_ptr< Type > create (std::unique_ptr< details::Type > impl)
Detailed Description
This is the base class for any PDB type.
Member Enumeration Documentation
KIND
enum class LIEF::pdb::Type::KIND strong
Enumerator
UNKNOWN
CLASS
POINTER
SIMPLE
ENUM
FUNCTION
MODIFIER
BITFIELD
ARRAY
UNION
STRUCTURE
INTERFACE
Constructor & Destructor Documentation
~Type()
virtual LIEF::pdb::Type::~Type () virtual
Member Function Documentation
as()
template<class T > const T * LIEF::pdb::Type::as () const inline
create()
static std::unique_ptr< Type > LIEF::pdb::Type::create (std::unique_ptr< details::Type > impl) static
kind()
KIND LIEF::pdb::Type::kind () const
Referenced by LIEF::pdb::types::Array::classof(), LIEF::pdb::types::BitField::classof(), LIEF::pdb::types::Class::classof(), LIEF::pdb::types::Enum::classof(), LIEF::pdb::types::Function::classof(), LIEF::pdb::types::Interface::classof(), LIEF::pdb::types::Modifier::classof(), LIEF::pdb::types::Pointer::classof(), LIEF::pdb::types::Simple::classof(), LIEF::pdb::types::Structure::classof(), and LIEF::pdb::types::Union::classof().
The documentation for this class was generated from the following file:
PDB/Type.hpp