LIEF: Library to Instrument Executable Formats: LIEF::dsc::Dylib::Iterator Class Reference
LIEF::dsc::Dylib::Iterator Class Reference
Dylib Iterator.
#include <Dylib.hpp>
Public Types
using implementation = details::DylibIt
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::random_access_iterator_tag, std::unique_ptr< Dylib >, std::ptrdiff_t, Dylib *, std::unique_ptr< Dylib > >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Public Member Functions
Iterator (std::unique_ptr< details::DylibIt > impl)
Iterator (const Iterator &)
Iterator & operator= (const Iterator &)
Iterator (Iterator &&) noexcept
Iterator & operator= (Iterator &&) noexcept
~Iterator ()
bool operator< (const Iterator &rhs) const
std::ptrdiff_t operator- (const Iterator &R) const
Iterator & operator+= (std::ptrdiff_t n)
Iterator & operator-= (std::ptrdiff_t n)
std::unique_ptr< Dylib > operator* () const
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::random_access_iterator_tag, std::unique_ptr< Dylib >, std::ptrdiff_t, Dylib *, std::unique_ptr< Dylib > >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Detailed Description
Dylib Iterator.
Member Typedef Documentation
implementation
using LIEF::dsc::Dylib::Iterator::implementation = details::DylibIt
Constructor & Destructor Documentation
Iterator() [1/3]
LIEF::dsc::Dylib::Iterator::Iterator (std::unique_ptr< details::DylibIt > impl)
Referenced by Iterator(), Iterator(), operator!=, operator+=(), operator-(), operator-=(), operator<(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/3]
LIEF::dsc::Dylib::Iterator::Iterator (const Iterator &)
References Iterator().
Iterator() [3/3]
LIEF::dsc::Dylib::Iterator::Iterator (Iterator &&) noexcept
References Iterator().
~Iterator()
LIEF::dsc::Dylib::Iterator::~Iterator ()
References Iterator().
Member Function Documentation
operator*()
std::unique_ptr< Dylib > LIEF::dsc::Dylib::Iterator::operator* () const
operator+=()
Iterator & LIEF::dsc::Dylib::Iterator::operator+= (std::ptrdiff_t n)
References Iterator().
operator-()
std::ptrdiff_t LIEF::dsc::Dylib::Iterator::operator- (const Iterator & R) const
References Iterator().
operator-=()
Iterator & LIEF::dsc::Dylib::Iterator::operator-= (std::ptrdiff_t n)
References Iterator().
operator<()
bool LIEF::dsc::Dylib::Iterator::operator< (const Iterator & rhs) const
References Iterator().
operator=() [1/2]
Iterator & LIEF::dsc::Dylib::Iterator::operator= (const Iterator &)
References Iterator().
operator=() [2/2]
Iterator & LIEF::dsc::Dylib::Iterator::operator= (Iterator &&) noexcept
References Iterator().
The documentation for this class was generated from the following file:
Dylib.hpp