LIEF: Library to Instrument Executable Formats: LIEF::MachO::DyldChainedFixupsCreator Class Reference
LIEF::MachO::DyldChainedFixupsCreator Class Reference
#include <DyldChainedFixupsCreator.hpp>
Classes
struct binding_info_t
struct reloc_info_t
Public Member Functions
DyldChainedFixupsCreator ()=default
DyldChainedFixupsCreator & fixups_version (uint32_t value)
DyldChainedFixupsCreator & imports_format (DYLD_CHAINED_FORMAT fmt)
DyldChainedFixupsCreator & add_relocation (uint64_t address, uint64_t target)
DyldChainedFixupsCreator & add_relocations (const std::vector< reloc_info_t > &relocations)
DyldChainedFixupsCreator & add_binding (uint64_t address, std::string symbol, std::string library, uint64_t addend=0, bool weak=false)
DyldChainedFixupsCreator & add_binding (uint64_t address, std::string symbol, uint64_t addend=0, bool weak=false)
DyldChainedFixupsCreator & add_bindings (const std::vector< binding_info_t > &bindings)
DyldChainedFixups * create (Binary &target)
Static Public Attributes
static constexpr uint32_t MAX_IMPORTS = (uint32_t(1) << 24) - 1
static constexpr uint32_t BIND24_THRESHOLD = (uint32_t(1) << 16) - 1
Constructor & Destructor Documentation
DyldChainedFixupsCreator()
LIEF::MachO::DyldChainedFixupsCreator::DyldChainedFixupsCreator () default
Referenced by add_binding(), add_binding(), add_bindings(), add_relocation(), fixups_version(), and imports_format().
Member Function Documentation
add_binding() [1/2]
DyldChainedFixupsCreator & LIEF::MachO::DyldChainedFixupsCreator::add_binding (uint64_t address, std::string symbol, std::string library, uint64_t addend = 0, bool weak = false)
References DyldChainedFixupsCreator().
Referenced by add_binding().
add_binding() [2/2]
DyldChainedFixupsCreator & LIEF::MachO::DyldChainedFixupsCreator::add_binding (uint64_t address, std::string symbol, uint64_t addend = 0, bool weak = false) inline
References add_binding(), and DyldChainedFixupsCreator().
add_bindings()
DyldChainedFixupsCreator & LIEF::MachO::DyldChainedFixupsCreator::add_bindings (const std::vector< binding_info_t > & bindings) inline
References DyldChainedFixupsCreator().
add_relocation()
DyldChainedFixupsCreator & LIEF::MachO::DyldChainedFixupsCreator::add_relocation (uint64_t address, uint64_t target)
References DyldChainedFixupsCreator().
add_relocations()
DyldChainedFixupsCreator & LIEF::MachO::DyldChainedFixupsCreator::add_relocations (const std::vector< reloc_info_t > & relocations) inline
create()
DyldChainedFixups * LIEF::MachO::DyldChainedFixupsCreator::create (Binary & target)
References LIEF_LOCAL, and LIEF::MachO::UNKNOWN.
fixups_version()
DyldChainedFixupsCreator & LIEF::MachO::DyldChainedFixupsCreator::fixups_version (uint32_t value) inline
References DyldChainedFixupsCreator().
imports_format()
DyldChainedFixupsCreator & LIEF::MachO::DyldChainedFixupsCreator::imports_format (DYLD_CHAINED_FORMAT fmt) inline
References DyldChainedFixupsCreator().
Member Data Documentation
BIND24_THRESHOLD
uint32_t LIEF::MachO::DyldChainedFixupsCreator::BIND24_THRESHOLD = (uint32_t(1) << 16) - 1 static constexpr
MAX_IMPORTS
uint32_t LIEF::MachO::DyldChainedFixupsCreator::MAX_IMPORTS = (uint32_t(1) << 24) - 1 static constexpr
The documentation for this class was generated from the following file:
DyldChainedFixupsCreator.hpp