LIEF: Library to Instrument Executable Formats: LIEF::objc::Category Class Reference
LIEF::objc::Category Class Reference
This class represents an Objective-C category (e.g. @interface NSString (MyAdditions)).
#include <Category.hpp>
Classes
class Iterator
Public Types
using methods_t = iterator_range<Method::Iterator>
Iterator for the category's methods.
using protocols_t = iterator_range<Protocol::Iterator>
Iterator for the protocols adopted by this category.
using properties_t = iterator_range<Property::Iterator>
Iterator for the properties declared by this category.
Public Member Functions
Category (std::unique_ptr< details::Category > impl)
std::string name () const
Name of the category.
std::string class_name () const
(demangled) name of the class extended by this category
methods_t methods () const
Iterator over the different methods defined by this category.
protocols_t protocols () const
Iterator over the different protocols adopted by this category.
properties_t properties () const
Iterator over the properties of this category.
std::string to_decl (const DeclOpt &opt=DeclOpt()) const
Generate a header-like string for this specific category.
~Category ()
Detailed Description
This class represents an Objective-C category (e.g. @interface NSString (MyAdditions)).
Member Typedef Documentation
methods_t
using LIEF::objc::Category::methods_t = iterator_range<Method::Iterator>
Iterator for the category's methods.
properties_t
using LIEF::objc::Category::properties_t = iterator_range<Property::Iterator>
Iterator for the properties declared by this category.
protocols_t
using LIEF::objc::Category::protocols_t = iterator_range<Protocol::Iterator>
Iterator for the protocols adopted by this category.
Constructor & Destructor Documentation
Category()
LIEF::objc::Category::Category (std::unique_ptr< details::Category > impl)
Referenced by LIEF::objc::Category::Iterator::operator*(), LIEF::objc::Category::Iterator::operator->(), and ~Category().
~Category()
LIEF::objc::Category::~Category ()
References Category().
Member Function Documentation
class_name()
std::string LIEF::objc::Category::class_name () const
(demangled) name of the class extended by this category
methods()
methods_t LIEF::objc::Category::methods () const
Iterator over the different methods defined by this category.
References LIEF_LIFETIMEBOUND.
name()
std::string LIEF::objc::Category::name () const
Name of the category.
properties()
properties_t LIEF::objc::Category::properties () const
Iterator over the properties of this category.
References LIEF_LIFETIMEBOUND, and properties().
Referenced by properties().
protocols()
protocols_t LIEF::objc::Category::protocols () const
Iterator over the different protocols adopted by this category.
References LIEF_LIFETIMEBOUND, and protocols().
Referenced by protocols().
to_decl()
std::string LIEF::objc::Category::to_decl (const DeclOpt & opt = DeclOpt()) const
Generate a header-like string for this specific category.
The generated output can be configured with DeclOpt
References to_decl().
Referenced by to_decl().
The documentation for this class was generated from the following file:
Category.hpp