LIEF: Library to Instrument Executable Formats: LIEF::dwarf::editor::StructType Class Reference
LIEF::dwarf::editor::StructType Class Reference
This class represents a struct-like type which can be:
#include <StructType.hpp>
Classes
class Member
This class represents a member of the struct-like.
Public Types
enum class TYPE : uint32_t { CLASS , STRUCT , UNION }
Public Member Functions
StructType & set_size (uint64_t size)
Define the overall size which is equivalent to the sizeof of the current type.
std::unique_ptr< Member > add_member (const std::string &name, const Type &type, int64_t offset=-1)
Adds a member to the current struct-like.
std::unique_ptr< Member > add_bitfield (const std::string &name, const Type &type, uint64_t bitsize, int64_t bitoffset=-1)
Adds a bitfield member to the current structure.
~StructType () override=default
Type ()=delete
Type (std::unique_ptr< details::Type > impl)
Public Member Functions inherited from LIEF::dwarf::editor::Type
Type ()=delete
Type (std::unique_ptr< details::Type > impl)
std::unique_ptr< PointerType > pointer_to () const
Create a pointer type pointing to this type.
virtual ~Type ()
const details::Type & impl () const
Static Public Member Functions
static bool classof (const Type *type)
Detailed Description
This class represents a struct-like type which can be:
DW_TAG_class_type
DW_TAG_structure_type
DW_TAG_union_type
Member Enumeration Documentation
TYPE
enum class LIEF::dwarf::editor::StructType::TYPE : uint32_t strong
Enumerator
CLASS
STRUCT
Discriminant for DW_TAG_class_type.
UNION
Discriminant for DW_TAG_structure_type.
Constructor & Destructor Documentation
~StructType()
LIEF::dwarf::editor::StructType::~StructType () override default
Member Function Documentation
add_bitfield()
std::unique_ptr< Member > LIEF::dwarf::editor::StructType::add_bitfield (const std::string & name, const Type & type, uint64_t bitsize, int64_t bitoffset = -1)
Adds a bitfield member to the current structure.
References Type().
add_member()
std::unique_ptr< Member > LIEF::dwarf::editor::StructType::add_member (const std::string & name, const Type & type, int64_t offset = -1)
Adds a member to the current struct-like.
References Type().
classof()
bool LIEF::dwarf::editor::StructType::classof (const Type * type) static
References Type().
set_size()
StructType & LIEF::dwarf::editor::StructType::set_size (uint64_t size)
Define the overall size which is equivalent to the sizeof of the current type.
This function defines the DW_AT_byte_size attribute
Type() [1/2]
LIEF::dwarf::editor::Type::Type () delete
Referenced by add_bitfield(), add_member(), and classof().
Type() [2/2]
LIEF::dwarf::editor::Type::Type (std::unique_ptr< details::Type > impl)
The documentation for this class was generated from the following file:
StructType.hpp