LIEF: Library to Instrument Executable Formats: LIEF::ScopeOStream Class Reference
LIEF::ScopeOStream Class Reference
#include <iostream.hpp>
Public Member Functions
ScopeOStream (const ScopeOStream &)=delete
ScopeOStream & operator= (const ScopeOStream &)=delete
ScopeOStream (ScopeOStream &&)=delete
ScopeOStream & operator= (ScopeOStream &&)=delete
ScopeOStream (vector_iostream &stream, uint64_t pos)
ScopeOStream (vector_iostream &stream)
~ScopeOStream ()
vector_iostream * operator-> ()
vector_iostream & operator* ()
const vector_iostream & operator* () const
Constructor & Destructor Documentation
ScopeOStream() [1/4]
LIEF::ScopeOStream::ScopeOStream (const ScopeOStream &) delete
References ScopeOStream().
Referenced by operator=(), operator=(), ScopeOStream(), and ScopeOStream().
ScopeOStream() [2/4]
LIEF::ScopeOStream::ScopeOStream (ScopeOStream &&) delete
References ScopeOStream().
ScopeOStream() [3/4]
LIEF::ScopeOStream::ScopeOStream (vector_iostream & stream, uint64_t pos) inline explicit
References LIEF::vector_iostream::seekp().
ScopeOStream() [4/4]
LIEF::ScopeOStream::ScopeOStream (vector_iostream & stream) inline explicit
~ScopeOStream()
LIEF::ScopeOStream::~ScopeOStream () inline
Member Function Documentation
operator*() [1/2]
vector_iostream & LIEF::ScopeOStream::operator* () inline
operator*() [2/2]
const vector_iostream & LIEF::ScopeOStream::operator* () const inline
operator->()
vector_iostream * LIEF::ScopeOStream::operator-> () inline
operator=() [1/2]
ScopeOStream & LIEF::ScopeOStream::operator= (const ScopeOStream &) delete
References ScopeOStream().
operator=() [2/2]
ScopeOStream & LIEF::ScopeOStream::operator= (ScopeOStream &&) delete
References ScopeOStream().
The documentation for this class was generated from the following file:
iostream.hpp