LIEF: Library to Instrument Executable Formats: LIEF::PE::unwind_x64::Code Class Reference
LIEF::PE::unwind_x64::Code Class Reference
Base class for all unwind operations.
#include <UnwindCodeX64.hpp>
Public Types
using OPCODE = RuntimeFunctionX64::UNWIND_OPCODES
using REG = RuntimeFunctionX64::UNWIND_REG
Public Member Functions
Code ()=delete
Code (const Code &)=default
Code & operator= (const Code &)=default
Code (Code &&)=default
Code & operator= (Code &&)=default
virtual ~Code ()=default
Code (OPCODE opcode, uint32_t pos)
Code (OPCODE opcode)
OPCODE opcode () const
The original opcode.
uint32_t position () const
Offset in the prolog.
virtual std::string to_string () const
Pretty representation.
Detailed Description
Base class for all unwind operations.
Member Typedef Documentation
OPCODE
using LIEF::PE::unwind_x64::Code::OPCODE = RuntimeFunctionX64::UNWIND_OPCODES
REG
using LIEF::PE::unwind_x64::Code::REG = RuntimeFunctionX64::UNWIND_REG
Constructor & Destructor Documentation
Code() [1/5]
LIEF::PE::unwind_x64::Code::Code () delete
Referenced by LIEF::PE::unwind_x64::Alloc::Alloc(), LIEF::PE::unwind_x64::Alloc::classof(), LIEF::PE::unwind_x64::Epilog::classof(), LIEF::PE::unwind_x64::PushMachFrame::classof(), LIEF::PE::unwind_x64::PushNonVol::classof(), LIEF::PE::unwind_x64::SaveNonVolatile::classof(), LIEF::PE::unwind_x64::SaveXMM128::classof(), LIEF::PE::unwind_x64::SetFPReg::classof(), LIEF::PE::unwind_x64::Spare::classof(), Code(), Code(), Code(), LIEF::PE::unwind_x64::Epilog::Epilog(), operator<<, operator=(), operator=(), LIEF::PE::unwind_x64::PushMachFrame::PushMachFrame(), LIEF::PE::unwind_x64::PushNonVol::PushNonVol(), LIEF::PE::unwind_x64::SaveNonVolatile::SaveNonVolatile(), LIEF::PE::unwind_x64::SaveXMM128::SaveXMM128(), LIEF::PE::unwind_x64::SetFPReg::SetFPReg(), and LIEF::PE::unwind_x64::Spare::Spare().
Code() [2/5]
LIEF::PE::unwind_x64::Code::Code (const Code &) default
References Code().
Code() [3/5]
LIEF::PE::unwind_x64::Code::Code (Code &&) default
References Code().
~Code()
virtual LIEF::PE::unwind_x64::Code::~Code () virtual default
Code() [4/5]
LIEF::PE::unwind_x64::Code::Code (OPCODE opcode, uint32_t pos) inline
References opcode().
Code() [5/5]
LIEF::PE::unwind_x64::Code::Code (OPCODE opcode) inline
References Code(), and opcode().
Member Function Documentation
opcode()
OPCODE LIEF::PE::unwind_x64::Code::opcode () const inline
The original opcode.
Referenced by LIEF::PE::unwind_x64::Alloc::classof(), LIEF::PE::unwind_x64::Epilog::classof(), LIEF::PE::unwind_x64::PushMachFrame::classof(), LIEF::PE::unwind_x64::PushNonVol::classof(), LIEF::PE::unwind_x64::SaveNonVolatile::classof(), LIEF::PE::unwind_x64::SaveXMM128::classof(), LIEF::PE::unwind_x64::SetFPReg::classof(), LIEF::PE::unwind_x64::Spare::classof(), Code(), and Code().
operator=() [1/2]
Code & LIEF::PE::unwind_x64::Code::operator= (Code &&) default
References Code().
operator=() [2/2]
Code & LIEF::PE::unwind_x64::Code::operator= (const Code &) default
References Code().
position()
uint32_t LIEF::PE::unwind_x64::Code::position () const inline
Offset in the prolog.
to_string()
virtual std::string LIEF::PE::unwind_x64::Code::to_string () const virtual
Pretty representation.
Reimplemented in LIEF::PE::unwind_x64::Alloc, LIEF::PE::unwind_x64::Epilog, LIEF::PE::unwind_x64::PushMachFrame, LIEF::PE::unwind_x64::PushNonVol, LIEF::PE::unwind_x64::SaveNonVolatile, LIEF::PE::unwind_x64::SaveXMM128, LIEF::PE::unwind_x64::SetFPReg, and LIEF::PE::unwind_x64::Spare.
Referenced by operator<<.
The documentation for this class was generated from the following file:
UnwindCodeX64.hpp