LIEF: Library to Instrument Executable Formats: LIEF::PE::DynamicFixupARM64X Class Reference
LIEF::PE::DynamicFixupARM64X Class Reference
This class represents IMAGE_DYNAMIC_RELOCATION_ARM64X.
#include <DynamicFixupARM64X.hpp>
Classes
struct reloc_entry_t
Public Types
enum class FIXUP_TYPE { ZEROFILL = 0 , VALUE = 1 , DELTA = 2 }
using reloc_entries_t = std::vector<reloc_entry_t>
using it_relocations = ref_iterator<reloc_entries_t&>
using it_const_relocations = const_ref_iterator<const reloc_entries_t&>
Public Types inherited from LIEF::PE::DynamicFixup
enum KIND {
UNKNOWN = 0 , GENERIC , ARM64X , FUNCTION_OVERRIDE ,
ARM64_KERNEL_IMPORT_CALL_TRANSFER , GUARD_IMPORT_CONTROL_TRANSFER
}
Public Member Functions
DynamicFixupARM64X ()
DynamicFixupARM64X (const DynamicFixupARM64X &)=default
DynamicFixupARM64X & operator= (const DynamicFixupARM64X &)=default
DynamicFixupARM64X (DynamicFixupARM64X &&)=default
DynamicFixupARM64X & operator= (DynamicFixupARM64X &&)=default
std::unique_ptr< DynamicFixup > clone () const override
std::string to_string () const override
it_relocations relocations ()
Iterator over the different fixup entries.
it_const_relocations relocations () const
~DynamicFixupARM64X () override=default
Public Member Functions inherited from LIEF::PE::DynamicFixup
DynamicFixup ()=delete
DynamicFixup (KIND kind)
DynamicFixup (const DynamicFixup &)=default
DynamicFixup & operator= (const DynamicFixup &)=default
DynamicFixup (DynamicFixup &&)=default
DynamicFixup & operator= (DynamicFixup &&)=default
KIND kind () const
Encoding of the fixups.
template<class T>
T * as ()
template<class T>
const T * as () const
virtual ~DynamicFixup ()=default
Static Public Member Functions
static bool classof (const DynamicFixup *fixup)
Detailed Description
This class represents IMAGE_DYNAMIC_RELOCATION_ARM64X.
Member Typedef Documentation
it_const_relocations
using LIEF::PE::DynamicFixupARM64X::it_const_relocations = const_ref_iterator<const reloc_entries_t&>
it_relocations
using LIEF::PE::DynamicFixupARM64X::it_relocations = ref_iterator<reloc_entries_t&>
reloc_entries_t
using LIEF::PE::DynamicFixupARM64X::reloc_entries_t = std::vector<reloc_entry_t>
Member Enumeration Documentation
FIXUP_TYPE
enum class LIEF::PE::DynamicFixupARM64X::FIXUP_TYPE strong
Enumerator
ZEROFILL
VALUE
DELTA
Constructor & Destructor Documentation
DynamicFixupARM64X() [1/3]
LIEF::PE::DynamicFixupARM64X::DynamicFixupARM64X () inline
References LIEF::PE::DynamicFixup::ARM64X, and LIEF::PE::DynamicFixup::DynamicFixup().
Referenced by clone(), DynamicFixupARM64X(), DynamicFixupARM64X(), operator=(), and operator=().
DynamicFixupARM64X() [2/3]
LIEF::PE::DynamicFixupARM64X::DynamicFixupARM64X (const DynamicFixupARM64X &) default
References DynamicFixupARM64X().
DynamicFixupARM64X() [3/3]
LIEF::PE::DynamicFixupARM64X::DynamicFixupARM64X (DynamicFixupARM64X &&) default
References DynamicFixupARM64X().
~DynamicFixupARM64X()
LIEF::PE::DynamicFixupARM64X::~DynamicFixupARM64X () override default
References LIEF_LOCAL.
Member Function Documentation
classof()
bool LIEF::PE::DynamicFixupARM64X::classof (const DynamicFixup * fixup) inline static
References LIEF::PE::DynamicFixup::ARM64X, LIEF::PE::DynamicFixup::DynamicFixup(), and LIEF::PE::DynamicFixup::kind().
clone()
std::unique_ptr< DynamicFixup > LIEF::PE::DynamicFixupARM64X::clone () const inline override virtual
Implements LIEF::PE::DynamicFixup.
References DynamicFixupARM64X().
operator=() [1/2]
DynamicFixupARM64X & LIEF::PE::DynamicFixupARM64X::operator= (const DynamicFixupARM64X &) default
References DynamicFixupARM64X().
operator=() [2/2]
DynamicFixupARM64X & LIEF::PE::DynamicFixupARM64X::operator= (DynamicFixupARM64X &&) default
References DynamicFixupARM64X().
relocations() [1/2]
it_relocations LIEF::PE::DynamicFixupARM64X::relocations () inline
Iterator over the different fixup entries.
relocations() [2/2]
it_const_relocations LIEF::PE::DynamicFixupARM64X::relocations () const inline
to_string()
std::string LIEF::PE::DynamicFixupARM64X::to_string () const override virtual
Implements LIEF::PE::DynamicFixup.
The documentation for this class was generated from the following file:
DynamicFixupARM64X.hpp