LIEF: Library to Instrument Executable Formats: LIEF::Relocation Class Reference
LIEF::Relocation Class Reference
Class which represents an abstracted Relocation.
#include <Relocation.hpp>
Public Member Functions
Relocation ()=default
Relocation (uint64_t address, uint8_t size)
Constructor from a relocation's address and size.
~Relocation () override=default
Relocation & operator= (const Relocation &)=default
Relocation (const Relocation &)=default
void swap (Relocation &other)
virtual uint64_t address () const
Relocation's address.
virtual size_t size () const
Relocation size in bits.
virtual void address (uint64_t address)
virtual void size (size_t size)
void accept (Visitor &visitor) const override
Method so that the visitor can visit us.
virtual bool operator< (const Relocation &rhs) const
Comparaison based on the Relocation's address.
virtual bool operator<= (const Relocation &rhs) const
Comparaison based on the Relocation's address.
virtual bool operator> (const Relocation &rhs) const
Comparaison based on the Relocation's address.
virtual bool operator>= (const Relocation &rhs) const
Comparaison based on the Relocation's address.
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Additional Inherited Members
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Detailed Description
Class which represents an abstracted Relocation.
Constructor & Destructor Documentation
Relocation() [1/3]
LIEF::Relocation::Relocation () default
Referenced by operator<(), operator<<, operator<=(), operator=(), operator>(), operator>=(), Relocation(), and swap().
Relocation() [2/3]
LIEF::Relocation::Relocation (uint64_t address, uint8_t size) inline
Constructor from a relocation's address and size.
References address(), and size().
~Relocation()
LIEF::Relocation::~Relocation () override default
Relocation() [3/3]
LIEF::Relocation::Relocation (const Relocation &) default
References Relocation().
Member Function Documentation
accept()
void LIEF::Relocation::accept (Visitor & visitor) const override virtual
Method so that the visitor can visit us.
Implements LIEF::Object.
Reimplemented in LIEF::MachO::RelocationDyld, LIEF::MachO::RelocationFixup, LIEF::MachO::RelocationObject, and LIEF::PE::RelocationEntry.
address() [1/2]
virtual uint64_t LIEF::Relocation::address () const inline virtual
Relocation's address.
Reimplemented in LIEF::MachO::Relocation, LIEF::MachO::RelocationFixup, LIEF::MachO::RelocationObject, and LIEF::PE::RelocationEntry.
Referenced by address(), LIEF::MachO::Relocation::BinaryParser, operator<(), operator<=(), operator>(), operator>=(), and Relocation().
address() [2/2]
virtual void LIEF::Relocation::address (uint64_t address) inline virtual
Reimplemented in LIEF::MachO::Relocation, LIEF::MachO::RelocationFixup, and LIEF::PE::RelocationEntry.
References address().
operator<()
virtual bool LIEF::Relocation::operator< (const Relocation & rhs) const inline virtual
Comparaison based on the Relocation's address.
Reimplemented in LIEF::MachO::RelocationDyld.
References address(), and Relocation().
operator<=()
virtual bool LIEF::Relocation::operator<= (const Relocation & rhs) const inline virtual
Comparaison based on the Relocation's address.
Reimplemented in LIEF::MachO::RelocationDyld.
References address(), and Relocation().
operator=()
Relocation & LIEF::Relocation::operator= (const Relocation &) default
References Relocation().
operator>()
virtual bool LIEF::Relocation::operator> (const Relocation & rhs) const inline virtual
Comparaison based on the Relocation's address.
Reimplemented in LIEF::MachO::RelocationDyld.
References address(), and Relocation().
operator>=()
virtual bool LIEF::Relocation::operator>= (const Relocation & rhs) const inline virtual
Comparaison based on the Relocation's address.
Reimplemented in LIEF::MachO::RelocationDyld.
References address(), and Relocation().
size() [1/2]
virtual size_t LIEF::Relocation::size () const inline virtual
Relocation size in bits.
Reimplemented in LIEF::ELF::Relocation, LIEF::MachO::Relocation, LIEF::MachO::RelocationObject, and LIEF::PE::RelocationEntry.
Referenced by LIEF::MachO::Relocation::BinaryParser, Relocation(), and size().
size() [2/2]
virtual void LIEF::Relocation::size (size_t size) inline virtual
Reimplemented in LIEF::MachO::Relocation, LIEF::MachO::RelocationObject, and LIEF::PE::RelocationEntry.
References size().
swap()
void LIEF::Relocation::swap (Relocation & other) inline
References Relocation().
Referenced by LIEF::PE::RelocationEntry::swap().
The documentation for this class was generated from the following file:
Abstract/Relocation.hpp