LIEF: Library to Instrument Executable Formats: LIEF::MachO::FunctionVariants Class Reference
LIEF::MachO::FunctionVariants Class Reference
Class representing the LC_FUNCTION_VARIANTS load command.
#include <FunctionVariants.hpp>
Classes
class RuntimeTableEntry
This class exposes information about a given implementation.
class RuntimeTable
Represents a runtime table of function variants sharing a common namespace (referred to internally as FunctionVariantsRuntimeTable in dyld).
Public Types
using runtime_table_t = std::vector<RuntimeTable>
using it_runtime_table = ref_iterator<runtime_table_t&>
Iterator that outputs RuntimeTable&.
using it_const_runtime_table = const_ref_iterator<const runtime_table_t&>
Iterator that outputs const RuntimeTable&.
Public Types inherited from LIEF::MachO::LoadCommand
enum class TYPE : uint64_t {
UNKNOWN = 0 , SEGMENT = 0x00000001u , SYMTAB = 0x00000002u , SYMSEG = 0x00000003u ,
THREAD = 0x00000004u , UNIXTHREAD = 0x00000005u , LOADFVMLIB = 0x00000006u , IDFVMLIB = 0x00000007u ,
IDENT = 0x00000008u , FVMFILE = 0x00000009u , PREPAGE = 0x0000000Au , DYSYMTAB = 0x0000000Bu ,
LOAD_DYLIB = 0x0000000Cu , ID_DYLIB = 0x0000000Du , LOAD_DYLINKER = 0x0000000Eu , ID_DYLINKER = 0x0000000Fu ,
PREBOUND_DYLIB = 0x00000010u , ROUTINES = 0x00000011u , SUB_FRAMEWORK = 0x00000012u , SUB_UMBRELLA = 0x00000013u ,
SUB_CLIENT = 0x00000014u , SUB_LIBRARY = 0x00000015u , TWOLEVEL_HINTS = 0x00000016u , PREBIND_CKSUM = 0x00000017u ,
LOAD_WEAK_DYLIB = 0x80000018u , SEGMENT_64 = 0x00000019u , ROUTINES_64 = 0x0000001Au , UUID = 0x0000001Bu ,
RPATH = 0x8000001Cu , CODE_SIGNATURE = 0x0000001Du , SEGMENT_SPLIT_INFO = 0x0000001Eu , REEXPORT_DYLIB = 0x8000001Fu ,
LAZY_LOAD_DYLIB = 0x00000020u , ENCRYPTION_INFO = 0x00000021u , DYLD_INFO = 0x00000022u , DYLD_INFO_ONLY = 0x80000022u ,
LOAD_UPWARD_DYLIB = 0x80000023u , VERSION_MIN_MACOSX = 0x00000024u , VERSION_MIN_IPHONEOS = 0x00000025u , FUNCTION_STARTS = 0x00000026u ,
DYLD_ENVIRONMENT = 0x00000027u , MAIN = 0x80000028u , DATA_IN_CODE = 0x00000029u , SOURCE_VERSION = 0x0000002Au ,
DYLIB_CODE_SIGN_DRS = 0x0000002Bu , ENCRYPTION_INFO_64 = 0x0000002Cu , LINKER_OPTION = 0x0000002Du , LINKER_OPTIMIZATION_HINT = 0x0000002Eu ,
VERSION_MIN_TVOS = 0x0000002Fu , VERSION_MIN_WATCHOS = 0x00000030u , NOTE = 0x00000031u , BUILD_VERSION = 0x00000032u ,
DYLD_EXPORTS_TRIE = 0x80000033u , DYLD_CHAINED_FIXUPS = 0x80000034u , FILESET_ENTRY = 0x80000035u , ATOM_INFO = 0x00000036u ,
FUNCTION_VARIANTS = 0x00000037u , FUNCTION_VARIANT_FIXUPS = 0x00000038u , TARGET_TRIPLE = 0x00000039u , LIEF_UNKNOWN = 0xffee0001u
}
using raw_t = std::vector<uint8_t>
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Public Member Functions
FunctionVariants ()=default
FunctionVariants (const details::linkedit_data_command &cmd)
FunctionVariants & operator= (const FunctionVariants &copy)=default
FunctionVariants (const FunctionVariants &copy)=default
std::unique_ptr< LoadCommand > clone () const override
uint32_t data_offset () const
Offset in the __LINKEDIT SegmentCommand where the payload starts.
uint32_t data_size () const
Size of the payload.
void data_offset (uint32_t offset)
void data_size (uint32_t size)
span< const uint8_t > content () const
Return the data slice in the __LINKEDIT segment referenced by data_offset and data_size;.
span< uint8_t > content ()
it_runtime_table runtime_table ()
Iterator over the different RuntimeTable entries located in the content of this __LINKEDIT command.
it_const_runtime_table runtime_table () const
~FunctionVariants () override=default
std::ostream & print (std::ostream &os) const override
Public Member Functions inherited from LIEF::MachO::LoadCommand
LoadCommand ()=default
LoadCommand (const details::load_command &command)
LoadCommand (LoadCommand::TYPE type, uint32_t size)
LoadCommand & operator= (const LoadCommand &copy)=default
LoadCommand (const LoadCommand &copy)=default
void swap (LoadCommand &other) noexcept
~LoadCommand () override=default
LoadCommand::TYPE command () const
Command type.
uint32_t size () const
Size of the command (should be greather than sizeof(load_command)).
span< const uint8_t > data () const
Raw command.
uint64_t command_offset () const
Offset of the command within the Load Command Table.
void data (raw_t data)
void command (LoadCommand::TYPE command)
void size (uint32_t size)
void command_offset (uint64_t offset)
void accept (Visitor &visitor) const override
template<class T>
const T * cast () const
template<class T>
T * cast ()
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Static Public Member Functions
static bool classof (const LoadCommand *cmd)
static std::vector< RuntimeTable > parse_payload (SpanStream &stream)
static result< RuntimeTable > parse_entry (BinaryStream &stream)
Static Public Member Functions inherited from LIEF::MachO::LoadCommand
static bool is_linkedit_data (const LoadCommand &cmd)
Detailed Description
Class representing the LC_FUNCTION_VARIANTS load command.
Introduced publicly in dyld-1284.13 (April 2025), this command supports function multiversioning, the ability to associate multiple implementations of the same function, each optimized for a specific platform, architecture, or runtime context.
At runtime, the system dispatches the most appropriate variant based on hardware capabilities or execution environment.
For example:
FUNCTION_VARIANT_TABLE(my_function,
  { (void*)my_function$Rosetta,  "rosetta" }, // Rosetta translation
  { (void*)my_function$Haswell,  "haswell" }, // Haswell-optimized
  { (void*)my_function$Base,     "default" }  // Default fallback
);
Member Typedef Documentation
it_const_runtime_table
using LIEF::MachO::FunctionVariants::it_const_runtime_table = const_ref_iterator<const runtime_table_t&>
Iterator that outputs const RuntimeTable&.
it_runtime_table
using LIEF::MachO::FunctionVariants::it_runtime_table = ref_iterator<runtime_table_t&>
Iterator that outputs RuntimeTable&.
runtime_table_t
using LIEF::MachO::FunctionVariants::runtime_table_t = std::vector<RuntimeTable>
Constructor & Destructor Documentation
FunctionVariants() [1/3]
LIEF::MachO::FunctionVariants::FunctionVariants () default
Referenced by clone(), FunctionVariants(), and operator=().
FunctionVariants() [2/3]
LIEF::MachO::FunctionVariants::FunctionVariants (const details::linkedit_data_command & cmd)
FunctionVariants() [3/3]
LIEF::MachO::FunctionVariants::FunctionVariants (const FunctionVariants & copy) default
References FunctionVariants().
~FunctionVariants()
LIEF::MachO::FunctionVariants::~FunctionVariants () override default
Member Function Documentation
classof()
bool LIEF::MachO::FunctionVariants::classof (const LoadCommand * cmd) inline static
References LIEF::MachO::LoadCommand::command(), LIEF::MachO::LoadCommand::FUNCTION_VARIANTS, and LIEF::MachO::LoadCommand::LoadCommand().
clone()
std::unique_ptr< LoadCommand > LIEF::MachO::FunctionVariants::clone () const inline override virtual
Reimplemented from LIEF::MachO::LoadCommand.
References FunctionVariants().
content() [1/2]
span< uint8_t > LIEF::MachO::FunctionVariants::content () inline
content() [2/2]
span< const uint8_t > LIEF::MachO::FunctionVariants::content () const inline
Return the data slice in the __LINKEDIT segment referenced by data_offset and data_size;.
data_offset() [1/2]
uint32_t LIEF::MachO::FunctionVariants::data_offset () const inline
Offset in the __LINKEDIT SegmentCommand where the payload starts.
data_offset() [2/2]
void LIEF::MachO::FunctionVariants::data_offset (uint32_t offset) inline
data_size() [1/2]
uint32_t LIEF::MachO::FunctionVariants::data_size () const inline
Size of the payload.
data_size() [2/2]
void LIEF::MachO::FunctionVariants::data_size (uint32_t size) inline
References LIEF::MachO::LoadCommand::size().
operator=()
FunctionVariants & LIEF::MachO::FunctionVariants::operator= (const FunctionVariants & copy) default
References FunctionVariants().
parse_entry()
result< RuntimeTable > LIEF::MachO::FunctionVariants::parse_entry (BinaryStream & stream) static
References LIEF_LOCAL.
parse_payload()
std::vector< RuntimeTable > LIEF::MachO::FunctionVariants::parse_payload (SpanStream & stream) static
References LIEF_LOCAL.
print()
std::ostream & LIEF::MachO::FunctionVariants::print (std::ostream & os) const override virtual
Reimplemented from LIEF::MachO::LoadCommand.
runtime_table() [1/2]
it_runtime_table LIEF::MachO::FunctionVariants::runtime_table () inline
Iterator over the different RuntimeTable entries located in the content of this __LINKEDIT command.
runtime_table() [2/2]
it_const_runtime_table LIEF::MachO::FunctionVariants::runtime_table () const inline
The documentation for this class was generated from the following file:
FunctionVariants.hpp