LIEF: Library to Instrument Executable Formats: LIEF::COFF::Symbol Class Reference
LIEF::COFF::Symbol Class Reference
This class represents a COFF symbol.
#include <Symbol.hpp>
Classes
struct parsing_context_t
Public Types
enum class STORAGE_CLASS : int32_t {
INVALID = 0xFF , END_OF_FUNCTION = -1 , NONE = 0 , AUTOMATIC = 1 ,
EXTERNAL = 2 , STATIC = 3 , REGISTER = 4 , EXTERNAL_DEF = 5 ,
LABEL = 6 , UNDEFINED_LABEL = 7 , MEMBER_OF_STRUCT = 8 , ARGUMENT = 9 ,
STRUCT_TAG = 10 , MEMBER_OF_UNION = 11 , UNION_TAG = 12 , TYPE_DEFINITION = 13 ,
UNDEFINED_STATIC = 14 , ENUM_TAG = 15 , MEMBER_OF_ENUM = 16 , REGISTER_PARAM = 17 ,
BIT_FIELD = 18 , BLOCK = 100 , FUNCTION = 101 , END_OF_STRUCT = 102 ,
FILE = 103 , SECTION = 104 , WEAK_EXTERNAL = 105 , CLR_TOKEN = 107
}
Reference: https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#storage-class.
enum class BASE_TYPE : uint32_t {
TY_NULL = 0 , TY_VOID = 1 , TY_CHAR = 2 , TY_SHORT = 3 ,
TY_INT = 4 , TY_LONG = 5 , TY_FLOAT = 6 , TY_DOUBLE = 7 ,
TY_STRUCT = 8 , TY_UNION = 9 , TY_ENUM = 10 , TY_MOE = 11 ,
TY_BYTE = 12 , TY_WORD = 13 , TY_UINT = 14 , TY_DWORD = 15
}
enum class COMPLEX_TYPE : uint32_t { TY_NULL = 0 , TY_POINTER = 1 , TY_FUNCTION = 2 , TY_ARRAY = 3 }
using auxiliary_symbols_t = std::vector<std::unique_ptr<AuxiliarySymbol>>
using it_auxiliary_symbols_t = ref_iterator<auxiliary_symbols_t&, AuxiliarySymbol*>
using it_const_auxiliary_symbols_t = const_ref_iterator<const auxiliary_symbols_t&, AuxiliarySymbol*>
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Public Member Functions
Symbol ()
Symbol (const Symbol &)
Symbol & operator= (const Symbol &)
Symbol (Symbol &&)
Symbol & operator= (Symbol &&)
uint16_t type () const
The symbol type. The first byte represents the base type (see: base_type()) while the upper byte represents the complex type, if any (see: complex_type()).
STORAGE_CLASS storage_class () const
Storage class of the symbol which indicates what kind of definition a symbol represents.
BASE_TYPE base_type () const
The simple (base) data type.
COMPLEX_TYPE complex_type () const
The complex type (if any).
int16_t section_idx () const
The signed integer that identifies the section, using a one-based index into the section table. Some values have special meaning:
Section * section ()
Section associated with this symbol (if any).
const Section * section () const
bool is_external () const
bool is_weak_external () const
bool is_absolute () const
bool is_undefined () const
bool is_function_line_info () const
bool is_function () const
bool is_file_record () const
it_auxiliary_symbols_t auxiliary_symbols ()
Auxiliary symbols associated with this symbol.
it_const_auxiliary_symbols_t auxiliary_symbols () const
const std::string & name () const override
Name of the symbol. If the symbol does not use a short name, it returns the string pointed by the COFF string offset.
std::string & name () override
const String * coff_name () const
COFF string used to represents the (long) symbol name.
String * coff_name ()
std::string demangled_name () const
Demangled representation of the symbol or an empty string if it can't be demangled.
Symbol & type (uint16_t ty)
Symbol & storage_class (uint8_t value)
Symbol & section_idx (int16_t idx)
AuxiliarySymbol & add_aux (std::unique_ptr< AuxiliarySymbol > sym)
Add a new auxiliary record.
std::string to_string () const
~Symbol () override
Public Member Functions inherited from LIEF::Symbol
Symbol ()=default
Symbol (std::string name)
Symbol (std::string name, uint64_t value)
Symbol (std::string name, uint64_t value, uint64_t size)
Symbol (const Symbol &)=default
Symbol & operator= (const Symbol &)=default
Symbol (Symbol &&)=default
Symbol & operator= (Symbol &&)=default
~Symbol () override=default
void swap (Symbol &other) noexcept
virtual void name (std::string name)
Set symbol name.
virtual uint64_t value () const
virtual void value (uint64_t value)
virtual uint64_t size () const
This size of the symbol (when applicable).
virtual void size (uint64_t value)
void accept (Visitor &visitor) const override
Method so that the visitor can visit us.
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Static Public Member Functions
static std::unique_ptr< Symbol > parse (parsing_context_t &ctx, BinaryStream &stream, size_t *idx)
static constexpr bool is_reversed_sec_idx (int16_t idx)
Check if the given section index is a reserved value.
Static Public Attributes
static constexpr auto SYM_SEC_IDX_DEBUG = -2
The symbol provides general type or debugging information but does not correspond to a section. Microsoft tools use this setting along with .file records.
static constexpr auto SYM_SEC_IDX_ABS = -1
The symbol has an absolute (non-relocatable) value and is not an address.
static constexpr auto SYM_SEC_IDX_UNDEF = 0
The symbol record is not yet assigned a section. A value of zero indicates that a reference to an external symbol is defined elsewhere. A value of non-zero is a common symbol with a size that is specified by the value.
static constexpr auto SYM_COMPLEX_TYPE_SHIFT = 4
Detailed Description
This class represents a COFF symbol.
Member Typedef Documentation
auxiliary_symbols_t
using LIEF::COFF::Symbol::auxiliary_symbols_t = std::vector<std::unique_ptr<AuxiliarySymbol>>
it_auxiliary_symbols_t
using LIEF::COFF::Symbol::it_auxiliary_symbols_t = ref_iterator<auxiliary_symbols_t&, AuxiliarySymbol*>
it_const_auxiliary_symbols_t
using LIEF::COFF::Symbol::it_const_auxiliary_symbols_t = const_ref_iterator<const auxiliary_symbols_t&, AuxiliarySymbol*>
Member Enumeration Documentation
BASE_TYPE
enum class LIEF::COFF::Symbol::BASE_TYPE : uint32_t strong
Enumerator
TY_NULL
No type information or unknown base type.
TY_VOID
Used with void pointers and functions.
TY_CHAR
A character (signed byte).
TY_SHORT
A 2-byte signed integer.
TY_INT
A natural integer type on the target.
TY_LONG
A 4-byte signed integer.
TY_FLOAT
A 4-byte floating-point number.
TY_DOUBLE
An 8-byte floating-point number.
TY_STRUCT
A structure.
TY_UNION
An union.
TY_ENUM
An enumerated type.
TY_MOE
A member of enumeration (a specific value).
TY_BYTE
A byte; unsigned 1-byte integer.
TY_WORD
A word; unsigned 2-byte integer.
TY_UINT
An unsigned integer of natural size.
TY_DWORD
An unsigned 4-byte integer.
COMPLEX_TYPE
enum class LIEF::COFF::Symbol::COMPLEX_TYPE : uint32_t strong
Enumerator
TY_NULL
No complex type; simple scalar variable.
TY_POINTER
A pointer to base type.
TY_FUNCTION
A function that returns a base type.
TY_ARRAY
An array of base type.
STORAGE_CLASS
enum class LIEF::COFF::Symbol::STORAGE_CLASS : int32_t strong
Reference: https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#storage-class.
Enumerator
INVALID
END_OF_FUNCTION
Physical end of function.
NONE
No symbol.
AUTOMATIC
Stack variable.
EXTERNAL
External symbol.
STATIC
Static.
REGISTER
Register variable.
EXTERNAL_DEF
External definition.
LABEL
Label.
UNDEFINED_LABEL
Undefined label.
MEMBER_OF_STRUCT
Member of structure.
ARGUMENT
Function argument.
STRUCT_TAG
Structure tag.
MEMBER_OF_UNION
Member of union.
UNION_TAG
Union tag.
TYPE_DEFINITION
Type definition.
UNDEFINED_STATIC
Undefined static.
ENUM_TAG
Enumeration tag.
MEMBER_OF_ENUM
Member of enumeration.
REGISTER_PARAM
Register parameter.
BIT_FIELD
Bit field.
BLOCK
FUNCTION
END_OF_STRUCT
End of structure.
FILE
File name.
SECTION
WEAK_EXTERNAL
Duplicate tag.
CLR_TOKEN
Constructor & Destructor Documentation
Symbol() [1/3]
LIEF::COFF::Symbol::Symbol ()
Referenced by operator<<, operator=(), operator=(), section_idx(), storage_class(), Symbol(), Symbol(), and type().
Symbol() [2/3]
LIEF::COFF::Symbol::Symbol (const Symbol &)
References Symbol().
Symbol() [3/3]
LIEF::COFF::Symbol::Symbol (Symbol &&)
References Symbol().
~Symbol()
LIEF::COFF::Symbol::~Symbol () override
Member Function Documentation
add_aux()
AuxiliarySymbol & LIEF::COFF::Symbol::add_aux (std::unique_ptr< AuxiliarySymbol > sym)
Add a new auxiliary record.
auxiliary_symbols() [1/2]
it_auxiliary_symbols_t LIEF::COFF::Symbol::auxiliary_symbols () inline
Auxiliary symbols associated with this symbol.
auxiliary_symbols() [2/2]
it_const_auxiliary_symbols_t LIEF::COFF::Symbol::auxiliary_symbols () const inline
base_type()
BASE_TYPE LIEF::COFF::Symbol::base_type () const inline
The simple (base) data type.
coff_name() [1/2]
String * LIEF::COFF::Symbol::coff_name () inline
coff_name() [2/2]
const String * LIEF::COFF::Symbol::coff_name () const inline
COFF string used to represents the (long) symbol name.
complex_type()
COMPLEX_TYPE LIEF::COFF::Symbol::complex_type () const inline
The complex type (if any).
References SYM_COMPLEX_TYPE_SHIFT.
Referenced by is_function().
demangled_name()
std::string LIEF::COFF::Symbol::demangled_name () const
Demangled representation of the symbol or an empty string if it can't be demangled.
is_absolute()
bool LIEF::COFF::Symbol::is_absolute () const inline
References section_idx(), and SYM_SEC_IDX_ABS.
is_external()
bool LIEF::COFF::Symbol::is_external () const inline
References EXTERNAL, and storage_class().
Referenced by is_undefined().
is_file_record()
bool LIEF::COFF::Symbol::is_file_record () const inline
References FILE, and storage_class().
is_function()
bool LIEF::COFF::Symbol::is_function () const inline
References complex_type(), and TY_FUNCTION.
is_function_line_info()
bool LIEF::COFF::Symbol::is_function_line_info () const inline
References FUNCTION, and storage_class().
is_reversed_sec_idx()
constexpr bool LIEF::COFF::Symbol::is_reversed_sec_idx (int16_t idx) inline static constexpr
Check if the given section index is a reserved value.
is_undefined()
bool LIEF::COFF::Symbol::is_undefined () const inline
References is_external(), section_idx(), SYM_SEC_IDX_UNDEF, and LIEF::Symbol::value().
is_weak_external()
bool LIEF::COFF::Symbol::is_weak_external () const inline
References storage_class(), and WEAK_EXTERNAL.
name() [1/2]
const std::string & LIEF::COFF::Symbol::name () const override virtual
Name of the symbol. If the symbol does not use a short name, it returns the string pointed by the COFF string offset.
Reimplemented from LIEF::Symbol.
name() [2/2]
std::string & LIEF::COFF::Symbol::name () override virtual
Reimplemented from LIEF::Symbol.
operator=() [1/2]
Symbol & LIEF::COFF::Symbol::operator= (const Symbol &)
References Symbol().
operator=() [2/2]
Symbol & LIEF::COFF::Symbol::operator= (Symbol &&)
References Symbol().
parse()
std::unique_ptr< Symbol > LIEF::COFF::Symbol::parse (parsing_context_t & ctx, BinaryStream & stream, size_t * idx) static
section() [1/2]
Section * LIEF::COFF::Symbol::section () inline
Section associated with this symbol (if any).
section() [2/2]
const Section * LIEF::COFF::Symbol::section () const inline
section_idx() [1/2]
int16_t LIEF::COFF::Symbol::section_idx () const inline
The signed integer that identifies the section, using a one-based index into the section table. Some values have special meaning:
0: The symbol record is not yet assigned a section. A value of zero indicates that a reference to an external symbol is defined elsewhere. A value of non-zero is a common symbol with a size that is specified by the value.
-1: The symbol has an absolute (non-relocatable) value and is not an address.
-2: The symbol provides general type or debugging information but does not correspond to a section. Microsoft tools use this setting along with .file records
Referenced by is_absolute(), and is_undefined().
section_idx() [2/2]
Symbol & LIEF::COFF::Symbol::section_idx (int16_t idx) inline
References Symbol().
storage_class() [1/2]
STORAGE_CLASS LIEF::COFF::Symbol::storage_class () const inline
Storage class of the symbol which indicates what kind of definition a symbol represents.
Referenced by is_external(), is_file_record(), is_function_line_info(), and is_weak_external().
storage_class() [2/2]
Symbol & LIEF::COFF::Symbol::storage_class (uint8_t value) inline
References Symbol(), and LIEF::Symbol::value().
to_string()
std::string LIEF::COFF::Symbol::to_string () const
References LIEF_API.
Referenced by operator<<.
type() [1/2]
uint16_t LIEF::COFF::Symbol::type () const inline
The symbol type. The first byte represents the base type (see: base_type()) while the upper byte represents the complex type, if any (see: complex_type()).
type() [2/2]
Symbol & LIEF::COFF::Symbol::type (uint16_t ty) inline
References Symbol().
Member Data Documentation
SYM_COMPLEX_TYPE_SHIFT
auto LIEF::COFF::Symbol::SYM_COMPLEX_TYPE_SHIFT = 4 static constexpr
Referenced by complex_type().
SYM_SEC_IDX_ABS
auto LIEF::COFF::Symbol::SYM_SEC_IDX_ABS = -1 static constexpr
The symbol has an absolute (non-relocatable) value and is not an address.
Referenced by is_absolute().
SYM_SEC_IDX_DEBUG
auto LIEF::COFF::Symbol::SYM_SEC_IDX_DEBUG = -2 static constexpr
The symbol provides general type or debugging information but does not correspond to a section. Microsoft tools use this setting along with .file records.
SYM_SEC_IDX_UNDEF
auto LIEF::COFF::Symbol::SYM_SEC_IDX_UNDEF = 0 static constexpr
The symbol record is not yet assigned a section. A value of zero indicates that a reference to an external symbol is defined elsewhere. A value of non-zero is a common symbol with a size that is specified by the value.
Referenced by is_undefined().
The documentation for this class was generated from the following file:
COFF/Symbol.hpp