LIEF: Library to Instrument Executable Formats: LIEF::dwarf::editor::EnumType Class Reference
LIEF::dwarf::editor::EnumType Class Reference
This class represents an editable enum type (DW_TAG_enumeration_type).
#include <EnumType.hpp>
Classes
class Value
This class represents an enum value.
Public Member Functions
EnumType & set_size (uint64_t size)
Define the number of bytes required to hold an instance of the enumeration (DW_AT_byte_size).
EnumType & set_underlying_type (const Type &type)
Set the underlying type that is used to encode this enum.
std::unique_ptr< Value > add_value (const std::string &name, int64_t value)
Add an enum value by specifying its name and its integer value.
~EnumType () override=default
Type ()=delete
Type (std::unique_ptr< details::Type > impl)
Public Member Functions inherited from LIEF::dwarf::editor::Type
Type ()=delete
Type (std::unique_ptr< details::Type > impl)
std::unique_ptr< PointerType > pointer_to () const
Create a pointer type pointing to this type.
virtual ~Type ()
const details::Type & impl () const
Static Public Member Functions
static bool classof (const Type *type)
Detailed Description
This class represents an editable enum type (DW_TAG_enumeration_type).
Constructor & Destructor Documentation
~EnumType()
LIEF::dwarf::editor::EnumType::~EnumType () override default
Member Function Documentation
add_value()
std::unique_ptr< Value > LIEF::dwarf::editor::EnumType::add_value (const std::string & name, int64_t value)
Add an enum value by specifying its name and its integer value.
classof()
bool LIEF::dwarf::editor::EnumType::classof (const Type * type) static
References Type().
set_size()
EnumType & LIEF::dwarf::editor::EnumType::set_size (uint64_t size)
Define the number of bytes required to hold an instance of the enumeration (DW_AT_byte_size).
set_underlying_type()
EnumType & LIEF::dwarf::editor::EnumType::set_underlying_type (const Type & type)
Set the underlying type that is used to encode this enum.
References Type().
Type() [1/2]
LIEF::dwarf::editor::Type::Type () delete
Referenced by classof(), and set_underlying_type().
Type() [2/2]
LIEF::dwarf::editor::Type::Type (std::unique_ptr< details::Type > impl)
The documentation for this class was generated from the following file:
EnumType.hpp