LIEF: Library to Instrument Executable Formats: LIEF::ASN1Reader Class Reference
LIEF::ASN1Reader Class Reference
#include <ASN1Reader.hpp>
Public Member Functions
ASN1Reader ()=delete
ASN1Reader (BinaryStream &stream)
ASN1Reader (const ASN1Reader &)=delete
ASN1Reader & operator= (const ASN1Reader &)=delete
result< bool > is_tag (int tag)
result< size_t > read_tag (int tag)
result< size_t > read_len ()
result< std::string > read_alg ()
result< std::string > read_oid ()
result< bool > read_bool ()
result< int32_t > read_int ()
result< int64_t > read_int64 ()
result< std::vector< uint8_t > > read_large_int ()
result< std::vector< uint8_t > > read_bitstring ()
result< std::vector< uint8_t > > read_octet_string ()
result< std::string > read_utf8_string ()
result< std::unique_ptr< mbedtls_x509_crt > > read_cert ()
result< std::string > x509_read_names ()
result< std::vector< uint8_t > > x509_read_serial ()
result< std::unique_ptr< mbedtls_x509_time > > x509_read_time ()
std::string get_str_tag ()
Static Public Member Functions
static std::string tag2str (int tag)
Constructor & Destructor Documentation
ASN1Reader() [1/3]
LIEF::ASN1Reader::ASN1Reader () delete
Referenced by ASN1Reader(), and operator=().
ASN1Reader() [2/3]
LIEF::ASN1Reader::ASN1Reader (BinaryStream & stream) inline
ASN1Reader() [3/3]
LIEF::ASN1Reader::ASN1Reader (const ASN1Reader &) delete
References ASN1Reader().
Member Function Documentation
get_str_tag()
std::string LIEF::ASN1Reader::get_str_tag ()
is_tag()
result< bool > LIEF::ASN1Reader::is_tag (int tag)
operator=()
ASN1Reader & LIEF::ASN1Reader::operator= (const ASN1Reader &) delete
References ASN1Reader().
read_alg()
result< std::string > LIEF::ASN1Reader::read_alg ()
read_bitstring()
result< std::vector< uint8_t > > LIEF::ASN1Reader::read_bitstring ()
read_bool()
result< bool > LIEF::ASN1Reader::read_bool ()
read_cert()
result< std::unique_ptr< mbedtls_x509_crt > > LIEF::ASN1Reader::read_cert ()
read_int()
result< int32_t > LIEF::ASN1Reader::read_int ()
read_int64()
result< int64_t > LIEF::ASN1Reader::read_int64 ()
read_large_int()
result< std::vector< uint8_t > > LIEF::ASN1Reader::read_large_int ()
read_len()
result< size_t > LIEF::ASN1Reader::read_len ()
read_octet_string()
result< std::vector< uint8_t > > LIEF::ASN1Reader::read_octet_string ()
read_oid()
result< std::string > LIEF::ASN1Reader::read_oid ()
read_tag()
result< size_t > LIEF::ASN1Reader::read_tag (int tag)
read_utf8_string()
result< std::string > LIEF::ASN1Reader::read_utf8_string ()
tag2str()
static std::string LIEF::ASN1Reader::tag2str (int tag) static
x509_read_names()
result< std::string > LIEF::ASN1Reader::x509_read_names ()
x509_read_serial()
result< std::vector< uint8_t > > LIEF::ASN1Reader::x509_read_serial ()
x509_read_time()
result< std::unique_ptr< mbedtls_x509_time > > LIEF::ASN1Reader::x509_read_time ()
The documentation for this class was generated from the following file:
ASN1Reader.hpp