LIEF: Library to Instrument Executable Formats: LIEF::PE::ContentType Class Reference
LIEF::PE::ContentType Class Reference
Interface over the structure described by the OID 1.2.840.113549.1.9.3 (PKCS #9).
#include <ContentType.hpp>
Public Member Functions
ContentType ()
ContentType (oid_t oid)
ContentType (const ContentType &)=default
ContentType & operator= (const ContentType &)=default
const oid_t & oid () const
OID as described in RFC #2985.
std::string print () const override
Print information about the attribute.
std::unique_ptr< Attribute > clone () const override
void accept (Visitor &visitor) const override
~ContentType () override=default
Public Member Functions inherited from LIEF::PE::Attribute
Attribute ()=delete
Attribute (const Attribute &)=default
Attribute & operator= (const Attribute &)=default
virtual TYPE type () const
Concrete type of the attribute.
~Attribute () override=default
template<class T>
const T * cast () const
template<class T>
T * cast ()
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Static Public Member Functions
static bool classof (const Attribute *attr)
Additional Inherited Members
Public Types inherited from LIEF::PE::Attribute
enum class TYPE {
UNKNOWN = 0 , CONTENT_TYPE , GENERIC_TYPE , SIGNING_CERTIFICATE_V2 ,
SPC_SP_OPUS_INFO , SPC_RELAXED_PE_MARKER_CHECK , MS_COUNTER_SIGN , MS_SPC_NESTED_SIGN ,
MS_SPC_STATEMENT_TYPE , MS_PLATFORM_MANIFEST_BINARY_ID , PKCS9_AT_SEQUENCE_NUMBER , PKCS9_COUNTER_SIGNATURE ,
PKCS9_MESSAGE_DIGEST , PKCS9_SIGNING_TIME
}
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Detailed Description
Interface over the structure described by the OID 1.2.840.113549.1.9.3 (PKCS #9).
The internal structure is described in the RFC #2985: PKCS #9 - Selected Object Classes and Attribute Types Version 2.0
ContentType ::= OBJECT IDENTIFIER
Constructor & Destructor Documentation
ContentType() [1/3]
LIEF::PE::ContentType::ContentType () inline
References LIEF::PE::Attribute::Attribute().
Referenced by clone(), ContentType(), and operator=().
ContentType() [2/3]
LIEF::PE::ContentType::ContentType (oid_t oid) inline
References LIEF::PE::Attribute::Attribute(), and oid().
ContentType() [3/3]
LIEF::PE::ContentType::ContentType (const ContentType &) default
References ContentType().
~ContentType()
LIEF::PE::ContentType::~ContentType () override default
Member Function Documentation
accept()
void LIEF::PE::ContentType::accept (Visitor & visitor) const override virtual
Reimplemented from LIEF::PE::Attribute.
classof()
bool LIEF::PE::ContentType::classof (const Attribute * attr) inline static
References LIEF::PE::Attribute::Attribute(), LIEF::PE::Attribute::CONTENT_TYPE, and LIEF::PE::Attribute::type().
clone()
std::unique_ptr< Attribute > LIEF::PE::ContentType::clone () const inline override virtual
Implements LIEF::PE::Attribute.
References ContentType().
oid()
const oid_t & LIEF::PE::ContentType::oid () const inline
OID as described in RFC #2985.
Referenced by ContentType().
operator=()
ContentType & LIEF::PE::ContentType::operator= (const ContentType &) default
References ContentType().
print()
std::string LIEF::PE::ContentType::print () const override virtual
Print information about the attribute.
Implements LIEF::PE::Attribute.
The documentation for this class was generated from the following file:
ContentType.hpp