LIEF: Library to Instrument Executable Formats: LIEF::COFF::AuxiliarybfAndefSymbol Class Reference
LIEF::COFF::AuxiliarybfAndefSymbol Class Reference
#include <AuxiliarybfAndefSymbol.hpp>
Public Member Functions
AuxiliarybfAndefSymbol ()
AuxiliarybfAndefSymbol (const AuxiliarybfAndefSymbol &)=default
AuxiliarybfAndefSymbol & operator= (const AuxiliarybfAndefSymbol &)=default
AuxiliarybfAndefSymbol (AuxiliarybfAndefSymbol &&)=default
AuxiliarybfAndefSymbol & operator= (AuxiliarybfAndefSymbol &&)=default
std::unique_ptr< AuxiliarySymbol > clone () const override
std::string to_string () const override
~AuxiliarybfAndefSymbol () override=default
Public Member Functions inherited from LIEF::COFF::AuxiliarySymbol
AuxiliarySymbol ()=default
AuxiliarySymbol (std::vector< uint8_t > payload)
AuxiliarySymbol (const AuxiliarySymbol &)=default
AuxiliarySymbol & operator= (const AuxiliarySymbol &)=default
AuxiliarySymbol (AuxiliarySymbol &&)=default
AuxiliarySymbol & operator= (AuxiliarySymbol &&)=default
AuxiliarySymbol (TYPE ty)
TYPE type () const
span< const uint8_t > payload () const
For unknown type only, return the raw representation of this symbol.
span< uint8_t > payload ()
virtual ~AuxiliarySymbol ()=default
template<class T>
const T * as () const
Helper to downcast a AuxiliarySymbol into a concrete implementation.
template<class T>
T * as ()
Static Public Member Functions
static std::unique_ptr< AuxiliarybfAndefSymbol > parse (Symbol &sym, const std::vector< uint8_t > &payload)
static bool classof (const AuxiliarySymbol *sym)
Static Public Member Functions inherited from LIEF::COFF::AuxiliarySymbol
static std::unique_ptr< AuxiliarySymbol > parse (Symbol &sym, std::vector< uint8_t > payload)
static TYPE get_aux_type (const Symbol &sym)
Additional Inherited Members
Public Types inherited from LIEF::COFF::AuxiliarySymbol
enum class TYPE {
UNKNOWN = 0 , CLR_TOKEN , FUNC_DEF , BF_AND_EF ,
WEAK_EXTERNAL , FILE , SEC_DEF
}
Type discriminator for the subclasses.
Constructor & Destructor Documentation
AuxiliarybfAndefSymbol() [1/3]
LIEF::COFF::AuxiliarybfAndefSymbol::AuxiliarybfAndefSymbol () inline
References LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol().
Referenced by AuxiliarybfAndefSymbol(), AuxiliarybfAndefSymbol(), clone(), operator=(), and operator=().
AuxiliarybfAndefSymbol() [2/3]
LIEF::COFF::AuxiliarybfAndefSymbol::AuxiliarybfAndefSymbol (const AuxiliarybfAndefSymbol &) default
References AuxiliarybfAndefSymbol().
AuxiliarybfAndefSymbol() [3/3]
LIEF::COFF::AuxiliarybfAndefSymbol::AuxiliarybfAndefSymbol (AuxiliarybfAndefSymbol &&) default
References AuxiliarybfAndefSymbol().
~AuxiliarybfAndefSymbol()
LIEF::COFF::AuxiliarybfAndefSymbol::~AuxiliarybfAndefSymbol () override default
Member Function Documentation
classof()
bool LIEF::COFF::AuxiliarybfAndefSymbol::classof (const AuxiliarySymbol * sym) inline static
References LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol(), LIEF::COFF::AuxiliarySymbol::BF_AND_EF, and LIEF::COFF::AuxiliarySymbol::type().
clone()
std::unique_ptr< AuxiliarySymbol > LIEF::COFF::AuxiliarybfAndefSymbol::clone () const inline override virtual
Reimplemented from LIEF::COFF::AuxiliarySymbol.
References AuxiliarybfAndefSymbol().
operator=() [1/2]
AuxiliarybfAndefSymbol & LIEF::COFF::AuxiliarybfAndefSymbol::operator= (AuxiliarybfAndefSymbol &&) default
References AuxiliarybfAndefSymbol().
operator=() [2/2]
AuxiliarybfAndefSymbol & LIEF::COFF::AuxiliarybfAndefSymbol::operator= (const AuxiliarybfAndefSymbol &) default
References AuxiliarybfAndefSymbol().
parse()
std::unique_ptr< AuxiliarybfAndefSymbol > LIEF::COFF::AuxiliarybfAndefSymbol::parse (Symbol & sym, const std::vector< uint8_t > & payload) static
References LIEF::COFF::AuxiliarySymbol::payload().
to_string()
std::string LIEF::COFF::AuxiliarybfAndefSymbol::to_string () const inline override virtual
Reimplemented from LIEF::COFF::AuxiliarySymbol.
The documentation for this class was generated from the following file:
AuxiliarybfAndefSymbol.hpp