LIEF: Library to Instrument Executable Formats: LIEF::PE::DynamicRelocation Class Reference
LIEF::PE::DynamicRelocation Class Reference abstract
This is the base class for any IMAGE_DYNAMIC_RELOCATION32, IMAGE_DYNAMIC_RELOCATION32_V2, IMAGE_DYNAMIC_RELOCATION64, IMAGE_DYNAMIC_RELOCATION64_V2 dynamic relocations.
#include <DynamicRelocationBase.hpp>
Public Types
enum IMAGE_DYNAMIC_RELOCATION {
RELOCATION_GUARD_RF_PROLOGUE = 1 , RELOCATION_GUARD_RF_EPILOGUE = 2 , RELOCATION_GUARD_IMPORT_CONTROL_TRANSFER = 3 , RELOCATION_GUARD_INDIR_CONTROL_TRANSFER = 4 ,
RELOCATION_GUARD_SWITCHTABLE_BRANCH = 5 , RELOCATION_ARM64X = 6 , RELOCATION_FUNCTION_OVERRIDE = 7 , RELOCATION_ARM64_KERNEL_IMPORT_CALL_TRANSFER = 8 ,
_RELOC_LAST_ENTRY
}
Special symbol values as defined in link.exe - GetDVRTSpecialSymbolName.
Public Member Functions
DynamicRelocation ()=delete
DynamicRelocation (uint32_t version)
DynamicRelocation (const DynamicRelocation &)
DynamicRelocation & operator= (const DynamicRelocation &)
DynamicRelocation (DynamicRelocation &&)
DynamicRelocation & operator= (DynamicRelocation &&)
virtual std::unique_ptr< DynamicRelocation > clone () const =0
uint32_t version () const
Version of the structure.
uint64_t symbol () const
Symbol address. Some values have a special meaning (c.f. IMAGE_DYNAMIC_RELOCATION) and define how fixups are encoded.
const DynamicFixup * fixups () const
DynamicFixup * fixups ()
Return fixups information, where the interpretation may depend on the symbol's value.
DynamicRelocation & symbol (uint64_t value)
DynamicRelocation & fixups (std::unique_ptr< DynamicFixup > F)
virtual std::string to_string () const =0
template<class T>
T * as ()
template<class T>
const T * as () const
virtual ~DynamicRelocation ()
Detailed Description
This is the base class for any IMAGE_DYNAMIC_RELOCATION32, IMAGE_DYNAMIC_RELOCATION32_V2, IMAGE_DYNAMIC_RELOCATION64, IMAGE_DYNAMIC_RELOCATION64_V2 dynamic relocations.
Member Enumeration Documentation
IMAGE_DYNAMIC_RELOCATION
enum LIEF::PE::DynamicRelocation::IMAGE_DYNAMIC_RELOCATION
Special symbol values as defined in link.exe - GetDVRTSpecialSymbolName.
Enumerator
RELOCATION_GUARD_RF_PROLOGUE
Mirror IMAGE_DYNAMIC_RELOCATION_GUARD_RF_PROLOGUE.
RELOCATION_GUARD_RF_EPILOGUE
Mirror IMAGE_DYNAMIC_RELOCATION_GUARD_RF_EPILOGUE.
RELOCATION_GUARD_IMPORT_CONTROL_TRANSFER
Mirror IMAGE_DYNAMIC_RELOCATION_GUARD_IMPORT_CONTROL_TRANSFER.
RELOCATION_GUARD_INDIR_CONTROL_TRANSFER
Mirror IMAGE_DYNAMIC_RELOCATION_GUARD_INDIR_CONTROL_TRANSFER.
RELOCATION_GUARD_SWITCHTABLE_BRANCH
Mirror IMAGE_DYNAMIC_RELOCATION_GUARD_SWITCHTABLE_BRANCH.
RELOCATION_ARM64X
Mirror IMAGE_DYNAMIC_RELOCATION_ARM64X.
RELOCATION_FUNCTION_OVERRIDE
Mirror IMAGE_DYNAMIC_RELOCATION_FUNCTION_OVERRIDE.
RELOCATION_ARM64_KERNEL_IMPORT_CALL_TRANSFER
Mirror IMAGE_DYNAMIC_RELOCATION_ARM64_KERNEL_IMPORT_CALL_TRANSFER.
_RELOC_LAST_ENTRY
Constructor & Destructor Documentation
DynamicRelocation() [1/4]
LIEF::PE::DynamicRelocation::DynamicRelocation () delete
Referenced by as(), LIEF::PE::DynamicRelocationV1::classof(), LIEF::PE::DynamicRelocationV2::classof(), DynamicRelocation(), DynamicRelocation(), LIEF::PE::DynamicRelocationV1::DynamicRelocationV1(), LIEF::PE::DynamicRelocationV2::DynamicRelocationV2(), fixups(), operator<<, operator=(), operator=(), and symbol().
DynamicRelocation() [2/4]
LIEF::PE::DynamicRelocation::DynamicRelocation (uint32_t version)
References version().
DynamicRelocation() [3/4]
LIEF::PE::DynamicRelocation::DynamicRelocation (const DynamicRelocation &)
References DynamicRelocation().
DynamicRelocation() [4/4]
LIEF::PE::DynamicRelocation::DynamicRelocation (DynamicRelocation &&)
References DynamicRelocation().
~DynamicRelocation()
virtual LIEF::PE::DynamicRelocation::~DynamicRelocation () virtual
Member Function Documentation
as() [1/2]
template<class T> T * LIEF::PE::DynamicRelocation::as () inline
References LIEF::PE::T.
Referenced by as().
as() [2/2]
template<class T> const T * LIEF::PE::DynamicRelocation::as () const inline
References as(), DynamicRelocation(), and LIEF::PE::T.
clone()
virtual std::unique_ptr< DynamicRelocation > LIEF::PE::DynamicRelocation::clone () const pure virtual
Implemented in LIEF::PE::DynamicRelocationV1, and LIEF::PE::DynamicRelocationV2.
fixups() [1/3]
DynamicFixup * LIEF::PE::DynamicRelocation::fixups () inline
Return fixups information, where the interpretation may depend on the symbol's value.
fixups() [2/3]
const DynamicFixup * LIEF::PE::DynamicRelocation::fixups () const inline
fixups() [3/3]
DynamicRelocation & LIEF::PE::DynamicRelocation::fixups (std::unique_ptr< DynamicFixup > F)
References DynamicRelocation().
operator=() [1/2]
DynamicRelocation & LIEF::PE::DynamicRelocation::operator= (const DynamicRelocation &)
References DynamicRelocation().
operator=() [2/2]
DynamicRelocation & LIEF::PE::DynamicRelocation::operator= (DynamicRelocation &&)
References DynamicRelocation().
symbol() [1/2]
uint64_t LIEF::PE::DynamicRelocation::symbol () const inline
Symbol address. Some values have a special meaning (c.f. IMAGE_DYNAMIC_RELOCATION) and define how fixups are encoded.
symbol() [2/2]
DynamicRelocation & LIEF::PE::DynamicRelocation::symbol (uint64_t value) inline
References DynamicRelocation().
to_string()
virtual std::string LIEF::PE::DynamicRelocation::to_string () const pure virtual
Implemented in LIEF::PE::DynamicRelocationV1, and LIEF::PE::DynamicRelocationV2.
Referenced by operator<<.
version()
uint32_t LIEF::PE::DynamicRelocation::version () const inline
Version of the structure.
Referenced by LIEF::PE::DynamicRelocationV1::classof(), LIEF::PE::DynamicRelocationV2::classof(), and DynamicRelocation().
The documentation for this class was generated from the following file:
DynamicRelocationBase.hpp