LIEF: Library to Instrument Executable Formats: LIEF::dwarf::Parameter Class Reference
LIEF::dwarf::Parameter Class Reference
This class represents a DWARF parameter which can be either:
#include <Parameter.hpp>
Classes
class Location
This class exposes information about the location of a parameter.
class RegisterLoc
This class represents a register location.
Public Types
enum class KIND { UNKNOWN = 0 , TEMPLATE_TYPE , TEMPLATE_VALUE , FORMAL }
Public Member Functions
Parameter ()=delete
Parameter (Parameter &&other)
Parameter & operator= (Parameter &&other)
Parameter & operator= (const Parameter &)=delete
Parameter (const Parameter &)=delete
KIND kind () const
std::string name () const
Name of the parameter.
std::unique_ptr< Type > type () const
Type of this parameter.
std::unique_ptr< Location > location () const
Location of this parameter. For instance it can be a specific register that is not following the calling convention.
template<class T>
const T * as () const
virtual ~Parameter ()
Static Public Member Functions
static std::unique_ptr< Parameter > create (std::unique_ptr< details::Parameter > impl)
Detailed Description
This class represents a DWARF parameter which can be either:
A regular function parameter (see: parameters::Formal)
A template type parameter (see: parameters::TemplateType)
A template value parameter (see: parameters::TemplateValue)
Member Enumeration Documentation
KIND
enum class LIEF::dwarf::Parameter::KIND strong
Enumerator
UNKNOWN
TEMPLATE_TYPE
DW_TAG_template_type_parameter.
TEMPLATE_VALUE
DW_TAG_template_value_parameter.
FORMAL
DW_TAG_formal_parameter.
Constructor & Destructor Documentation
Parameter() [1/3]
LIEF::dwarf::Parameter::Parameter () delete
Referenced by create(), operator=(), operator=(), Parameter(), and Parameter().
Parameter() [2/3]
LIEF::dwarf::Parameter::Parameter (Parameter && other)
References Parameter().
Parameter() [3/3]
LIEF::dwarf::Parameter::Parameter (const Parameter &) delete
References Parameter().
~Parameter()
virtual LIEF::dwarf::Parameter::~Parameter () virtual
References LIEF_LOCAL.
Member Function Documentation
as()
template<class T> const T * LIEF::dwarf::Parameter::as () const inline
create()
std::unique_ptr< Parameter > LIEF::dwarf::Parameter::create (std::unique_ptr< details::Parameter > impl) static
References Parameter().
kind()
KIND LIEF::dwarf::Parameter::kind () const
location()
std::unique_ptr< Location > LIEF::dwarf::Parameter::location () const
Location of this parameter. For instance it can be a specific register that is not following the calling convention.
name()
std::string LIEF::dwarf::Parameter::name () const
Name of the parameter.
operator=() [1/2]
Parameter & LIEF::dwarf::Parameter::operator= (const Parameter &) delete
References Parameter().
operator=() [2/2]
Parameter & LIEF::dwarf::Parameter::operator= (Parameter && other)
References Parameter().
type()
std::unique_ptr< Type > LIEF::dwarf::Parameter::type () const
Type of this parameter.
The documentation for this class was generated from the following file:
Parameter.hpp