LIEF: Library to Instrument Executable Formats: LIEF::PE::DynamicFixupARM64Kernel Class Reference
LIEF::PE::DynamicFixupARM64Kernel Class Reference
This class wraps fixups associated with the (special) symbol value: IMAGE_DYNAMIC_RELOCATION_ARM64_KERNEL_IMPORT_CALL_TRANSFER (8).
#include <DynamicFixupARM64Kernel.hpp>
Classes
struct reloc_entry_t
Mirror IMAGE_IMPORT_CONTROL_TRANSFER_ARM64_RELOCATION.
Public Types
enum class IMPORT_TYPE : uint8_t { STATIC = 0 , DELAYED = 1 }
using reloc_entries_t = std::vector<reloc_entry_t>
using it_relocations = ref_iterator<reloc_entries_t&>
using it_const_relocations = const_ref_iterator<const reloc_entries_t&>
Public Types inherited from LIEF::PE::DynamicFixup
enum KIND {
UNKNOWN = 0 , GENERIC , ARM64X , FUNCTION_OVERRIDE ,
ARM64_KERNEL_IMPORT_CALL_TRANSFER , GUARD_IMPORT_CONTROL_TRANSFER
}
Public Member Functions
DynamicFixupARM64Kernel ()
DynamicFixupARM64Kernel (const DynamicFixupARM64Kernel &)=default
DynamicFixupARM64Kernel & operator= (const DynamicFixupARM64Kernel &)=default
DynamicFixupARM64Kernel (DynamicFixupARM64Kernel &&)=default
DynamicFixupARM64Kernel & operator= (DynamicFixupARM64Kernel &&)=default
std::unique_ptr< DynamicFixup > clone () const override
std::string to_string () const override
it_relocations relocations ()
Iterator over the relocations.
it_const_relocations relocations () const
~DynamicFixupARM64Kernel () override=default
Public Member Functions inherited from LIEF::PE::DynamicFixup
DynamicFixup ()=delete
DynamicFixup (KIND kind)
DynamicFixup (const DynamicFixup &)=default
DynamicFixup & operator= (const DynamicFixup &)=default
DynamicFixup (DynamicFixup &&)=default
DynamicFixup & operator= (DynamicFixup &&)=default
KIND kind () const
Encoding of the fixups.
template<class T>
T * as ()
template<class T>
const T * as () const
virtual ~DynamicFixup ()=default
Static Public Member Functions
static bool classof (const DynamicFixup *fixup)
Static Public Attributes
static constexpr auto NO_IAT_INDEX = 0x7fff
Detailed Description
This class wraps fixups associated with the (special) symbol value: IMAGE_DYNAMIC_RELOCATION_ARM64_KERNEL_IMPORT_CALL_TRANSFER (8).
Member Typedef Documentation
it_const_relocations
using LIEF::PE::DynamicFixupARM64Kernel::it_const_relocations = const_ref_iterator<const reloc_entries_t&>
it_relocations
using LIEF::PE::DynamicFixupARM64Kernel::it_relocations = ref_iterator<reloc_entries_t&>
reloc_entries_t
using LIEF::PE::DynamicFixupARM64Kernel::reloc_entries_t = std::vector<reloc_entry_t>
Member Enumeration Documentation
IMPORT_TYPE
enum class LIEF::PE::DynamicFixupARM64Kernel::IMPORT_TYPE : uint8_t strong
Enumerator
STATIC
DELAYED
Constructor & Destructor Documentation
DynamicFixupARM64Kernel() [1/3]
LIEF::PE::DynamicFixupARM64Kernel::DynamicFixupARM64Kernel () inline
References LIEF::PE::DynamicFixup::ARM64_KERNEL_IMPORT_CALL_TRANSFER, and LIEF::PE::DynamicFixup::DynamicFixup().
Referenced by clone(), DynamicFixupARM64Kernel(), DynamicFixupARM64Kernel(), operator=(), and operator=().
DynamicFixupARM64Kernel() [2/3]
LIEF::PE::DynamicFixupARM64Kernel::DynamicFixupARM64Kernel (const DynamicFixupARM64Kernel &) default
References DynamicFixupARM64Kernel().
DynamicFixupARM64Kernel() [3/3]
LIEF::PE::DynamicFixupARM64Kernel::DynamicFixupARM64Kernel (DynamicFixupARM64Kernel &&) default
References DynamicFixupARM64Kernel().
~DynamicFixupARM64Kernel()
LIEF::PE::DynamicFixupARM64Kernel::~DynamicFixupARM64Kernel () override default
References LIEF_LOCAL.
Member Function Documentation
classof()
bool LIEF::PE::DynamicFixupARM64Kernel::classof (const DynamicFixup * fixup) inline static
References LIEF::PE::DynamicFixup::ARM64_KERNEL_IMPORT_CALL_TRANSFER, LIEF::PE::DynamicFixup::DynamicFixup(), and LIEF::PE::DynamicFixup::kind().
clone()
std::unique_ptr< DynamicFixup > LIEF::PE::DynamicFixupARM64Kernel::clone () const inline override virtual
Implements LIEF::PE::DynamicFixup.
References DynamicFixupARM64Kernel().
operator=() [1/2]
DynamicFixupARM64Kernel & LIEF::PE::DynamicFixupARM64Kernel::operator= (const DynamicFixupARM64Kernel &) default
References DynamicFixupARM64Kernel().
operator=() [2/2]
DynamicFixupARM64Kernel & LIEF::PE::DynamicFixupARM64Kernel::operator= (DynamicFixupARM64Kernel &&) default
References DynamicFixupARM64Kernel().
relocations() [1/2]
it_relocations LIEF::PE::DynamicFixupARM64Kernel::relocations () inline
Iterator over the relocations.
relocations() [2/2]
it_const_relocations LIEF::PE::DynamicFixupARM64Kernel::relocations () const inline
to_string()
std::string LIEF::PE::DynamicFixupARM64Kernel::to_string () const override virtual
Implements LIEF::PE::DynamicFixup.
Member Data Documentation
NO_IAT_INDEX
auto LIEF::PE::DynamicFixupARM64Kernel::NO_IAT_INDEX = 0x7fff static constexpr
The documentation for this class was generated from the following file:
DynamicFixupARM64Kernel.hpp