LIEF: Library to Instrument Executable Formats: LIEF::ToggleEndianness Class Reference
LIEF::ToggleEndianness Class Reference
#include <BinaryStream.hpp>
Public Member Functions
ToggleEndianness (const ToggleEndianness &)=delete
ToggleEndianness & operator= (const ToggleEndianness &)=delete
ToggleEndianness (ToggleEndianness &&)=delete
ToggleEndianness & operator= (ToggleEndianness &&)=delete
ToggleEndianness (BinaryStream &stream, bool value)
ToggleEndianness (BinaryStream &stream)
~ToggleEndianness ()
BinaryStream * operator-> ()
BinaryStream & operator* ()
const BinaryStream & operator* () const
Constructor & Destructor Documentation
ToggleEndianness() [1/4]
LIEF::ToggleEndianness::ToggleEndianness (const ToggleEndianness &) delete
References ToggleEndianness().
Referenced by operator=(), operator=(), ToggleEndianness(), and ToggleEndianness().
ToggleEndianness() [2/4]
LIEF::ToggleEndianness::ToggleEndianness (ToggleEndianness &&) delete
References ToggleEndianness().
ToggleEndianness() [3/4]
LIEF::ToggleEndianness::ToggleEndianness (BinaryStream & stream, bool value) inline explicit
References LIEF::BinaryStream::set_endian_swap().
ToggleEndianness() [4/4]
LIEF::ToggleEndianness::ToggleEndianness (BinaryStream & stream) inline explicit
References LIEF::BinaryStream::set_endian_swap().
~ToggleEndianness()
LIEF::ToggleEndianness::~ToggleEndianness () inline
Member Function Documentation
operator*() [1/2]
BinaryStream & LIEF::ToggleEndianness::operator* () inline
operator*() [2/2]
const BinaryStream & LIEF::ToggleEndianness::operator* () const inline
operator->()
BinaryStream * LIEF::ToggleEndianness::operator-> () inline
operator=() [1/2]
ToggleEndianness & LIEF::ToggleEndianness::operator= (const ToggleEndianness &) delete
References ToggleEndianness().
operator=() [2/2]
ToggleEndianness & LIEF::ToggleEndianness::operator= (ToggleEndianness &&) delete
References ToggleEndianness().
The documentation for this class was generated from the following file:
BinaryStream.hpp