LIEF: Library to Instrument Executable Formats: LIEF::pdb::types::Simple Class Reference
LIEF::pdb::types::Simple Class Reference
This class represents a primitive types (int, float, ...) which are also named simple types in the PDB format.
#include <Simple.hpp>
Public Types
enum class TYPES {
UNKNOWN = 0 , VOID_ = 0x0003 , SCHAR = 0x0010 , UCHAR = 0x0020 ,
RCHAR = 0x0070 , WCHAR = 0x0071 , CHAR16 = 0x007a , CHAR32 = 0x007b ,
CHAR8 = 0x007c , SBYTE = 0x0068 , UBYTE = 0x0069 , SSHORT = 0x0011 ,
USHORT = 0x0021 , SINT16 = 0x0072 , UINT16 = 0x0073 , SLONG = 0x0012 ,
ULONG = 0x0022 , SINT32 = 0x0074 , UINT32 = 0x0075 , SQUAD = 0x0013 ,
UQUAD = 0x0023 , SINT64 = 0x0076 , UINT64 = 0x0077 , SOCTA = 0x0014 ,
UOCTA = 0x0024 , SINT128 = 0x0078 , UINT128 = 0x0079 , FLOAT16 = 0x0046 ,
FLOAT32 = 0x0040 , FLOAT32_PARTIAL_PRECISION = 0x45 , FLOAT48 = 0x0044 , FLOAT64 = 0x0041 ,
FLOAT80 = 0x0042 , FLOAT128 = 0x0043 , COMPLEX16 = 0x0056 , COMPLEX32 = 0x0050 ,
COMPLEX32_PARTIAL_PRECISION = 0x0055 , COMPLEX48 = 0x0054 , COMPLEX64 = 0x0051 , COMPLEX80 = 0x0052 ,
COMPLEX128 = 0x0053 , BOOL8 = 0x0030 , BOOL16 = 0x0031 , BOOL32 = 0x0032 ,
BOOL64 = 0x0033 , BOOL128 = 0x0034
}
Identifier of the primitive type.
enum class MODES : uint32_t {
DIRECT = 0x00000000 , FAR_POINTER = 0x00000200 , HUGE_POINTER = 0x00000300 , NEAR_POINTER32 = 0x00000400 ,
FAR_POINTER32 = 0x00000500 , NEAR_POINTER64 = 0x00000600 , NEAR_POINTER128 = 0x00000700
}
Modifier applied to the underlying type.
Public Types inherited from LIEF::pdb::Type
enum class KIND {
UNKNOWN = 0 , CLASS , POINTER , SIMPLE ,
ENUM , FUNCTION , MODIFIER , BITFIELD ,
ARRAY , UNION , STRUCTURE , INTERFACE
}
Public Member Functions
TYPES type () const
Returns the underlying primitive type.
MODES modes () const
Returns the mode (pointer type) of this Simple type.
bool is_pointer () const
Check if this simple type is a pointer.
bool is_signed () const
Check if the underlying type is signed.
~Simple () override
Public Member Functions inherited from LIEF::pdb::Type
KIND kind () const
optional< uint64_t > size () const
Size of the type. This size should match the value of sizeof(...) applied to this type.
optional< std::string > name () const
Type's name (if present).
std::string to_decl (const DeclOpt &opt=DeclOpt()) const
Generates a C/C++ definition for this type.
template<class T>
const T * as () const
virtual ~Type ()
Static Public Member Functions
static bool classof (const Type *type)
Static Public Member Functions inherited from LIEF::pdb::Type
static std::unique_ptr< Type > create (std::unique_ptr< details::Type > impl)
Detailed Description
This class represents a primitive types (int, float, ...) which are also named simple types in the PDB format.
Member Enumeration Documentation
MODES
enum class LIEF::pdb::types::Simple::MODES : uint32_t strong
Modifier applied to the underlying type.
In the PDB Simple Type encoding, these represent pointer attributes.
Enumerator
DIRECT
Not a pointer (direct access).
FAR_POINTER
Far pointer.
HUGE_POINTER
Huge pointer.
NEAR_POINTER32
32-bit Near pointer
FAR_POINTER32
32-bit Far pointer
NEAR_POINTER64
64-bit Near pointer
NEAR_POINTER128
128-bit Near pointer
TYPES
enum class LIEF::pdb::types::Simple::TYPES strong
Identifier of the primitive type.
These values correspond to the low bits of the CodeView Type Index.
Enumerator
UNKNOWN
VOID_
SCHAR
Signed Character.
UCHAR
Unsigned Character.
RCHAR
"Real" Character (char)
WCHAR
Wide Character (wchar_t).
CHAR16
16-bit Character (char16_t)
CHAR32
32-bit Character (char32_t)
CHAR8
8-bit Character (char8_t)
SBYTE
Signed Byte.
UBYTE
Unsigned Byte.
SSHORT
Signed Short.
USHORT
Unsigned Short.
SINT16
Explicit Signed 16-bit Integer.
UINT16
Explicit Unsigned 16-bit Integer.
SLONG
Signed Long.
ULONG
Unsigned Long.
SINT32
Explicit Signed 32-bit Integer.
UINT32
Explicit Unsigned 32-bit Integer.
SQUAD
Signed Quadword.
UQUAD
Unsigned Quadword.
SINT64
Explicit Signed 64-bit Integer.
UINT64
Explicit Unsigned 64-bit Integer.
SOCTA
Signed Octaword.
UOCTA
Unsigned Octaword.
SINT128
Explicit Signed 128-bit Integer.
UINT128
Explicit Unsigned 128-bit Integer.
FLOAT16
16-bit Floating point
FLOAT32
32-bit Floating point (float)
FLOAT32_PARTIAL_PRECISION
FLOAT48
48-bit Floating point
FLOAT64
64-bit Floating point (double)
FLOAT80
80-bit Floating point
FLOAT128
128-bit Floating point
COMPLEX16
COMPLEX32
COMPLEX32_PARTIAL_PRECISION
COMPLEX48
COMPLEX64
COMPLEX80
COMPLEX128
BOOL8
8-bit Boolean
BOOL16
16-bit Boolean
BOOL32
32-bit Boolean
BOOL64
64-bit Boolean
BOOL128
128-bit Boolean
Constructor & Destructor Documentation
~Simple()
LIEF::pdb::types::Simple::~Simple () override
Member Function Documentation
classof()
bool LIEF::pdb::types::Simple::classof (const Type * type) inline static
References LIEF::pdb::Type::SIMPLE, and type().
is_pointer()
bool LIEF::pdb::types::Simple::is_pointer () const inline
Check if this simple type is a pointer.
References DIRECT, and modes().
is_signed()
bool LIEF::pdb::types::Simple::is_signed () const inline
Check if the underlying type is signed.
References SBYTE, SCHAR, SINT128, SINT16, SINT32, SINT64, SLONG, SOCTA, SQUAD, SSHORT, and type().
modes()
MODES LIEF::pdb::types::Simple::modes () const
Returns the mode (pointer type) of this Simple type.
Referenced by is_pointer().
type()
TYPES LIEF::pdb::types::Simple::type () const
Returns the underlying primitive type.
Referenced by classof(), and is_signed().
The documentation for this class was generated from the following file:
Simple.hpp