LIEF: Library to Instrument Executable Formats: LIEF::dwarf::editor::Function::LexicalBlock Class Reference
LIEF::dwarf::editor::Function::LexicalBlock Class Reference
This class mirrors the DW_TAG_lexical_block DWARF tag.
#include <Function.hpp>
Public Member Functions
LexicalBlock ()=delete
LexicalBlock (std::unique_ptr< details::FunctionLexicalBlock > impl)
std::unique_ptr< LexicalBlock > add_block (uint64_t start, uint64_t end)
Create a sub-block with the given low/high addresses.
std::unique_ptr< LexicalBlock > add_block (const std::vector< range_t > &range)
Create a sub-block with the given range of addresses.
LexicalBlock & add_description (const std::string &description)
Create a DW_AT_description entry with the description provided in parameter.
LexicalBlock & add_name (const std::string &name)
Create a DW_AT_name entry to associate a name to this entry.
~LexicalBlock ()
Detailed Description
This class mirrors the DW_TAG_lexical_block DWARF tag.
Constructor & Destructor Documentation
LexicalBlock() [1/2]
LIEF::dwarf::editor::Function::LexicalBlock::LexicalBlock () delete
Referenced by add_description(), and add_name().
LexicalBlock() [2/2]
LIEF::dwarf::editor::Function::LexicalBlock::LexicalBlock (std::unique_ptr< details::FunctionLexicalBlock > impl)
~LexicalBlock()
LIEF::dwarf::editor::Function::LexicalBlock::~LexicalBlock ()
Member Function Documentation
add_block() [1/2]
std::unique_ptr< LexicalBlock > LIEF::dwarf::editor::Function::LexicalBlock::add_block (const std::vector< range_t > & range)
Create a sub-block with the given range of addresses.
add_block() [2/2]
std::unique_ptr< LexicalBlock > LIEF::dwarf::editor::Function::LexicalBlock::add_block (uint64_t start, uint64_t end)
Create a sub-block with the given low/high addresses.
add_description()
LexicalBlock & LIEF::dwarf::editor::Function::LexicalBlock::add_description (const std::string & description)
Create a DW_AT_description entry with the description provided in parameter.
References LexicalBlock().
add_name()
LexicalBlock & LIEF::dwarf::editor::Function::LexicalBlock::add_name (const std::string & name)
Create a DW_AT_name entry to associate a name to this entry.
References LexicalBlock().
The documentation for this class was generated from the following file:
DWARF/editor/Function.hpp