LIEF: Library to Instrument Executable Formats: LIEF::PE::ResourceDialogExtended::Item Class Reference
LIEF::PE::ResourceDialogExtended::Item Class Reference
This class represents a DLGTEMPLATEEX item (DLGITEMTEMPLATEEX).
#include <ResourceDialogExtended.hpp>
Public Member Functions
Item ()=default
Item (const Item &)=default
Item & operator= (const Item &)=default
Item (Item &&)=default
Item & operator= (Item &&)=default
std::string to_string () const override
uint32_t help_id () const
The help context identifier for the control. When the system sends a WM_HELP message, it passes the helpID value in the dwContextId member of the HELPINFO structure.
Item & help_id (uint32_t value)
~Item () override=default
Public Member Functions inherited from LIEF::PE::ResourceDialog::Item
Item ()=default
Item (const Item &)=default
Item & operator= (const Item &)=default
Item (Item &&)=default
Item & operator= (Item &&)=default
uint32_t style () const
The style of the control. This can be a combination of WINDOW_STYLES or CONTROL_STYLES.
uint32_t extended_style () const
The extended styles for a window. This member is not used to create controls in dialog boxes, but applications that use dialog box templates can use it to create other types of windows.
int32_t id () const
The control identifier.
bool has (WINDOW_STYLES style) const
Check if this item has the given WINDOW_STYLES.
bool has (CONTROL_STYLES style) const
Check if this item has the given CONTROL_STYLES.
std::vector< WINDOW_STYLES > window_styles () const
List of WINDOW_STYLES used by this item.
std::vector< CONTROL_STYLES > control_styles () const
List of CONTROL_STYLES used by this item.
int16_t x () const
The x-coordinate, in dialog box units, of the upper-left corner of the control. This coordinate is always relative to the upper-left corner of the dialog box's client area.
int16_t y () const
The y-coordinate, in dialog box units, of the upper-left corner of the control. This coordinate is always relative to the upper-left corner of the dialog box's client area.
int16_t cx () const
The width, in dialog box units, of the control.
int16_t cy () const
The height, in dialog box units, of the control.
Item & style (uint32_t value)
Item & extended_style (uint32_t value)
Item & x (int16_t value)
Item & y (int16_t value)
Item & cx (int16_t value)
Item & cy (int16_t value)
Item & id (int32_t value)
Item & data (std::vector< uint8_t > creation_data)
Item & clazz (std::u16string title)
Item & clazz (uint16_t ord)
Item & title (std::u16string value)
Item & title (uint16_t ord)
const ordinal_or_str_t & clazz () const
Window class of the control. This can be either: a string that specifies the name of a registered window class or an ordinal value of a predefined system class.
const ordinal_or_str_t & title () const
Title of the item which can be either: a string that specifies the initial text or an ordinal value of a resource, such as an icon, in an executable file.
span< const uint8_t > creation_data () const
Creation data that is passed to the control's window procedure.
span< uint8_t > creation_data ()
Static Public Member Functions
static result< Item > parse (BinaryStream &stream)
Additional Inherited Members
Public Types inherited from LIEF::PE::ResourceDialog::Item
enum class WINDOW_CLASS : uint32_t {
BUTTON = 0x0080 , EDIT = 0x0081 , STATIC = 0x0082 , LIST_BOX = 0x0083 ,
SCROLL_BAR = 0x0084 , COMBO_BOX = 0x0085
}
Detailed Description
This class represents a DLGTEMPLATEEX item (DLGITEMTEMPLATEEX).
See: https://learn.microsoft.com/en-us/windows/win32/dlgbox/dlgitemtemplateex
Constructor & Destructor Documentation
Item() [1/3]
LIEF::PE::ResourceDialogExtended::Item::Item () default
Referenced by help_id(), Item(), Item(), operator=(), and operator=().
Item() [2/3]
LIEF::PE::ResourceDialogExtended::Item::Item (const Item &) default
References Item().
Item() [3/3]
LIEF::PE::ResourceDialogExtended::Item::Item (Item &&) default
References Item().
~Item()
LIEF::PE::ResourceDialogExtended::Item::~Item () override virtual default
Reimplemented from LIEF::PE::ResourceDialog::Item.
Member Function Documentation
help_id() [1/2]
uint32_t LIEF::PE::ResourceDialogExtended::Item::help_id () const inline
The help context identifier for the control. When the system sends a WM_HELP message, it passes the helpID value in the dwContextId member of the HELPINFO structure.
help_id() [2/2]
Item & LIEF::PE::ResourceDialogExtended::Item::help_id (uint32_t value) inline
References Item().
operator=() [1/2]
Item & LIEF::PE::ResourceDialogExtended::Item::operator= (const Item &) default
References Item().
operator=() [2/2]
Item & LIEF::PE::ResourceDialogExtended::Item::operator= (Item &&) default
References Item().
parse()
result< Item > LIEF::PE::ResourceDialogExtended::Item::parse (BinaryStream & stream) static
to_string()
std::string LIEF::PE::ResourceDialogExtended::Item::to_string () const override virtual
Implements LIEF::PE::ResourceDialog::Item.
The documentation for this class was generated from the following file:
ResourceDialogExtended.hpp