LIEF: Library to Instrument Executable Formats: LIEF::dwarf::LexicalBlock::Iterator Class Reference
LIEF::dwarf::LexicalBlock::Iterator Class Reference final
#include <LexicalBlock.hpp>
Public Types
using implementation = details::LexicalBlockIt
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::bidirectional_iterator_tag, LexicalBlock, std::ptrdiff_t, const LexicalBlock *, const LexicalBlock & >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Public Member Functions
Iterator ()
Iterator (std::unique_ptr< details::LexicalBlockIt > impl)
Iterator (const Iterator &)
Iterator & operator= (const Iterator &)
Iterator (Iterator &&) noexcept
Iterator & operator= (Iterator &&) noexcept
~Iterator ()
Iterator & operator++ ()
Iterator & operator-- ()
const LexicalBlock & operator* () const
const LexicalBlock * operator-> () const
std::unique_ptr< LexicalBlock > yield ()
Transfer ownership of the lexical block at the current position to the caller. Returns nullptr if the iterator is past-the-end.
DerivedT operator++ (int)
DerivedT operator-- (int)
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::bidirectional_iterator_tag, LexicalBlock, std::ptrdiff_t, const LexicalBlock *, const LexicalBlock & >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Member Typedef Documentation
implementation
using LIEF::dwarf::LexicalBlock::Iterator::implementation = details::LexicalBlockIt
Constructor & Destructor Documentation
Iterator() [1/4]
LIEF::dwarf::LexicalBlock::Iterator::Iterator ()
References LIEF_API.
Referenced by Iterator(), Iterator(), operator!=, operator++(), operator--(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/4]
LIEF::dwarf::LexicalBlock::Iterator::Iterator (std::unique_ptr< details::LexicalBlockIt > impl)
References LIEF_API.
Iterator() [3/4]
LIEF::dwarf::LexicalBlock::Iterator::Iterator (const Iterator &)
References Iterator(), and LIEF_API.
Iterator() [4/4]
LIEF::dwarf::LexicalBlock::Iterator::Iterator (Iterator &&) noexcept
References Iterator(), and LIEF_API.
~Iterator()
LIEF::dwarf::LexicalBlock::Iterator::~Iterator ()
References Iterator(), and LIEF_API.
Member Function Documentation
operator*()
const LexicalBlock & LIEF::dwarf::LexicalBlock::Iterator::operator* () const
References LIEF::dwarf::LexicalBlock::LexicalBlock(), LIEF_API, and LIEF_LIFETIMEBOUND.
operator++() [1/2]
Iterator & LIEF::dwarf::LexicalBlock::Iterator::operator++ ()
References Iterator(), and LIEF_API.
operator++() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator++ (int) inline
operator--() [1/2]
Iterator & LIEF::dwarf::LexicalBlock::Iterator::operator-- ()
References Iterator(), and LIEF_API.
operator--() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator-- (int) inline
operator->()
const LexicalBlock * LIEF::dwarf::LexicalBlock::Iterator::operator-> () const
References LIEF::dwarf::LexicalBlock::LexicalBlock(), LIEF_API, and LIEF_LIFETIMEBOUND.
operator=() [1/2]
Iterator & LIEF::dwarf::LexicalBlock::Iterator::operator= (const Iterator &)
References Iterator(), and LIEF_API.
operator=() [2/2]
Iterator & LIEF::dwarf::LexicalBlock::Iterator::operator= (Iterator &&) noexcept
References Iterator(), and LIEF_API.
yield()
std::unique_ptr< LexicalBlock > LIEF::dwarf::LexicalBlock::Iterator::yield ()
Transfer ownership of the lexical block at the current position to the caller. Returns nullptr if the iterator is past-the-end.
References LIEF::dwarf::LexicalBlock::LexicalBlock(), LIEF_API, and yield().
Referenced by yield().
The documentation for this class was generated from the following file:
LexicalBlock.hpp