LIEF: Library to Instrument Executable Formats: LIEF::assembly::Instruction::Iterator Class Reference
LIEF::assembly::Instruction::Iterator Class Reference final
Lazy-forward iterator that outputs Instruction
#include <Instruction.hpp>
Public Types
using implementation = details::InstructionIt
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, std::unique_ptr< Instruction >, std::ptrdiff_t, Instruction *, std::unique_ptr< Instruction > >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Public Member Functions
Iterator ()
Iterator (std::unique_ptr< details::InstructionIt > impl)
Iterator (const Iterator &)
Iterator & operator= (const Iterator &)
Iterator (Iterator &&) noexcept
Iterator & operator= (Iterator &&) noexcept
~Iterator ()
Iterator & operator++ ()
std::unique_ptr< Instruction > operator* () const
Disassemble and output an Instruction at the current iterator's position.
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, std::unique_ptr< Instruction >, std::ptrdiff_t, Instruction *, std::unique_ptr< Instruction > >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Detailed Description
Lazy-forward iterator that outputs Instruction
Member Typedef Documentation
implementation
using LIEF::assembly::Instruction::Iterator::implementation = details::InstructionIt
Constructor & Destructor Documentation
Iterator() [1/4]
LIEF::assembly::Instruction::Iterator::Iterator ()
References LIEF_API.
Referenced by Iterator(), Iterator(), operator!=, operator++(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/4]
LIEF::assembly::Instruction::Iterator::Iterator (std::unique_ptr< details::InstructionIt > impl)
References LIEF_API.
Iterator() [3/4]
LIEF::assembly::Instruction::Iterator::Iterator (const Iterator &)
References Iterator(), and LIEF_API.
Iterator() [4/4]
LIEF::assembly::Instruction::Iterator::Iterator (Iterator &&) noexcept
References Iterator(), and LIEF_API.
~Iterator()
LIEF::assembly::Instruction::Iterator::~Iterator ()
References Iterator(), and LIEF_API.
Member Function Documentation
operator*()
std::unique_ptr< Instruction > LIEF::assembly::Instruction::Iterator::operator* () const
Disassemble and output an Instruction at the current iterator's position.
References LIEF_API.
operator++()
Iterator & LIEF::assembly::Instruction::Iterator::operator++ ()
References Iterator(), and LIEF_API.
operator=() [1/2]
Iterator & LIEF::assembly::Instruction::Iterator::operator= (const Iterator &)
References Iterator(), and LIEF_API.
operator=() [2/2]
Iterator & LIEF::assembly::Instruction::Iterator::operator= (Iterator &&) noexcept
References Iterator(), and LIEF_API.
The documentation for this class was generated from the following file:
Instruction.hpp