LIEF: Library to Instrument Executable Formats: LIEF::PE::DynamicFixup Class Reference
LIEF::PE::DynamicFixup Class Reference abstract
This is the base class for any fixups located in DynamicRelocation.
#include <DynamicFixup.hpp>
Public Types
enum KIND {
UNKNOWN = 0 , GENERIC , ARM64X , FUNCTION_OVERRIDE ,
ARM64_KERNEL_IMPORT_CALL_TRANSFER , GUARD_IMPORT_CONTROL_TRANSFER
}
Public Member Functions
DynamicFixup ()=delete
DynamicFixup (KIND kind)
DynamicFixup (const DynamicFixup &)=default
DynamicFixup & operator= (const DynamicFixup &)=default
DynamicFixup (DynamicFixup &&)=default
DynamicFixup & operator= (DynamicFixup &&)=default
virtual std::unique_ptr< DynamicFixup > clone () const =0
virtual std::string to_string () const =0
KIND kind () const
Encoding of the fixups.
template<class T >
T * as ()
template<class T >
const T * as () const
virtual ~DynamicFixup ()=default
Detailed Description
This is the base class for any fixups located in DynamicRelocation.
Member Enumeration Documentation
KIND
enum LIEF::PE::DynamicFixup::KIND
Enumerator
UNKNOWN
If DynamicRelocation::symbol is a special value that is not supported by LIEF.
GENERIC
If DynamicRelocation::symbol is not a special value.
ARM64X
If DynamicRelocation::symbol is set to IMAGE_DYNAMIC_RELOCATION_ARM64X
FUNCTION_OVERRIDE
If DynamicRelocation::symbol is set to IMAGE_DYNAMIC_RELOCATION_FUNCTION_OVERRIDE
ARM64_KERNEL_IMPORT_CALL_TRANSFER
If DynamicRelocation::symbol is set to IMAGE_DYNAMIC_RELOCATION_ARM64_KERNEL_IMPORT_CALL_TRANSFER
GUARD_IMPORT_CONTROL_TRANSFER
If DynamicRelocation::symbol is set to IMAGE_DYNAMIC_RELOCATION_GUARD_IMPORT_CONTROL_TRANSFER
Constructor & Destructor Documentation
DynamicFixup() [1/4]
LIEF::PE::DynamicFixup::DynamicFixup () delete
DynamicFixup() [2/4]
LIEF::PE::DynamicFixup::DynamicFixup (KIND kind) inline
DynamicFixup() [3/4]
LIEF::PE::DynamicFixup::DynamicFixup (const DynamicFixup &) default
DynamicFixup() [4/4]
LIEF::PE::DynamicFixup::DynamicFixup (DynamicFixup &&) default
~DynamicFixup()
virtual LIEF::PE::DynamicFixup::~DynamicFixup () virtual default
Member Function Documentation
as() [1/2]
template<class T > T * LIEF::PE::DynamicFixup::as () inline
References LIEF::PE::T.
as() [2/2]
template<class T > const T * LIEF::PE::DynamicFixup::as () const inline
References LIEF::PE::T.
clone()
virtual std::unique_ptr< DynamicFixup > LIEF::PE::DynamicFixup::clone () const pure virtual
Implemented in LIEF::PE::DynamicFixupARM64Kernel, LIEF::PE::DynamicFixupARM64X, LIEF::PE::DynamicFixupControlTransfer, LIEF::PE::DynamicFixupGeneric, LIEF::PE::DynamicFixupUnknown, and LIEF::PE::FunctionOverride.
kind()
KIND LIEF::PE::DynamicFixup::kind () const inline
Encoding of the fixups.
Referenced by LIEF::PE::DynamicFixupARM64Kernel::classof(), LIEF::PE::DynamicFixupARM64X::classof(), LIEF::PE::DynamicFixupControlTransfer::classof(), LIEF::PE::DynamicFixupGeneric::classof(), LIEF::PE::DynamicFixupUnknown::classof(), and LIEF::PE::FunctionOverride::classof().
operator=() [1/2]
DynamicFixup & LIEF::PE::DynamicFixup::operator= (const DynamicFixup &) default
operator=() [2/2]
DynamicFixup & LIEF::PE::DynamicFixup::operator= (DynamicFixup &&) default
to_string()
virtual std::string LIEF::PE::DynamicFixup::to_string () const pure virtual
Implemented in LIEF::PE::DynamicFixupARM64Kernel, LIEF::PE::DynamicFixupARM64X, LIEF::PE::DynamicFixupControlTransfer, LIEF::PE::DynamicFixupGeneric, LIEF::PE::DynamicFixupUnknown, and LIEF::PE::FunctionOverride.
Referenced by operator<<.
The documentation for this class was generated from the following file:
DynamicFixup.hpp