LIEF: Library to Instrument Executable Formats: LIEF::dwarf::types::Enum::Entry Class Reference
LIEF::dwarf::types::Enum::Entry Class Reference
This class represents an enum entry which is essentially composed of a name and its value (integer).
#include <Enum.hpp>
Public Member Functions
Entry (std::unique_ptr< details::EnumEntry > impl)
Entry (Entry &&other) noexcept
Entry & operator= (Entry &&other) noexcept
std::string name () const
Enum entry's name.
optional< int64_t > value () const
Enum entry's value (if any).
~Entry ()
Detailed Description
This class represents an enum entry which is essentially composed of a name and its value (integer).
Constructor & Destructor Documentation
Entry() [1/2]
LIEF::dwarf::types::Enum::Entry::Entry (std::unique_ptr< details::EnumEntry > impl)
Referenced by Entry(), and operator=().
Entry() [2/2]
LIEF::dwarf::types::Enum::Entry::Entry (Entry && other) noexcept
References Entry().
~Entry()
LIEF::dwarf::types::Enum::Entry::~Entry ()
Member Function Documentation
name()
std::string LIEF::dwarf::types::Enum::Entry::name () const
Enum entry's name.
operator=()
Entry & LIEF::dwarf::types::Enum::Entry::operator= (Entry && other) noexcept
References Entry().
value()
optional< int64_t > LIEF::dwarf::types::Enum::Entry::value () const
Enum entry's value (if any).
The documentation for this class was generated from the following file:
DWARF/types/Enum.hpp