LIEF: Library to Instrument Executable Formats: LIEF::PE::ResourcesManager Class Reference
LIEF::PE::ResourcesManager Class Reference
The Resource Manager provides an enhanced API to manipulate the resource tree.
#include <ResourcesManager.hpp>
Classes
struct string_entry_t
This structure represent an entry in the string table (RT_STRING).
Public Types
enum class TYPE {
CURSOR = 1 , BITMAP = 2 , ICON = 3 , MENU = 4 ,
DIALOG = 5 , STRING = 6 , FONTDIR = 7 , FONT = 8 ,
ACCELERATOR = 9 , RCDATA = 10 , MESSAGETABLE = 11 , GROUP_CURSOR = 12 ,
GROUP_ICON = 14 , VERSION = 16 , DLGINCLUDE = 17 , PLUGPLAY = 19 ,
VXD = 20 , ANICURSOR = 21 , ANIICON = 22 , HTML = 23 ,
MANIFEST = 24
}
The different types of resources From https://learn.microsoft.com/en-us/windows/win32/menurc/resource-types.
using dialogs_t = ResourceDialog::dialogs_t
using it_const_dialogs = const_ref_iterator<const dialogs_t&, const ResourceDialog*>
using icons_t = std::vector<ResourceIcon>
using it_const_icons = const_ref_iterator<icons_t>
using accelerators_t = std::vector<ResourceAccelerator>
using it_const_accelerators = const_ref_iterator<accelerators_t>
using strings_table_t = std::vector<string_entry_t>
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Public Member Functions
ResourcesManager ()=delete
ResourcesManager (ResourceNode &rsrc)
ResourcesManager (const ResourcesManager &other)
ResourcesManager & operator= (const ResourcesManager &other)
ResourcesManager (ResourcesManager &&)=default
ResourcesManager & operator= (ResourcesManager &&)=default
~ResourcesManager () override=default
ResourceNode * get_node_type (TYPE type)
Return the ResourceNode associated with the given TYPE or a nullptr if not found;.
const ResourceNode * get_node_type (TYPE type) const
std::vector< TYPE > get_types () const
List of TYPE present in the resources.
bool has_type (TYPE type) const
true if the resource has the given TYPE node
bool has_manifest () const
true if resources contain the Manifest element
std::string manifest () const
Return the manifest as a std::string or an empty string if not found or corrupted.
void manifest (const std::string &manifest)
Change or set the manifest. If the manifest node path does not exist, all required nodes are created.
bool has_version () const
true if resources a LIEF::PE::ResourceVersion
std::vector< ResourceVersion > version () const
Return a list of verison info (VS_VERSIONINFO).
bool has_icons () const
true if resources contain a LIEF::PE::ResourceIcon
it_const_icons icons () const
Return the list of the icons present in the resources.
void add_icon (const ResourceIcon &icon)
Add an icon to the resources.
void change_icon (const ResourceIcon &original, const ResourceIcon &newone)
bool has_dialogs () const
true if resources contain dialogs
it_const_dialogs dialogs () const
Return the list of the dialogs present in the resource.
bool has_string_table () const
true if the resources contain a string table
strings_table_t string_table () const
Return the list of the strings embedded in the string table (RT_STRING).
bool has_html () const
true if the resources contain html
std::vector< std::string > html () const
Return the list of the html resources.
bool has_accelerator () const
true if the resources contain accelerator info
it_const_accelerators accelerator () const
Return the list of the accelerator in the resource.
std::string print (uint32_t depth=0) const
Print the resource tree to the given depth.
void accept (Visitor &visitor) const override
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Detailed Description
The Resource Manager provides an enhanced API to manipulate the resource tree.
Member Typedef Documentation
accelerators_t
using LIEF::PE::ResourcesManager::accelerators_t = std::vector<ResourceAccelerator>
dialogs_t
using LIEF::PE::ResourcesManager::dialogs_t = ResourceDialog::dialogs_t
icons_t
using LIEF::PE::ResourcesManager::icons_t = std::vector<ResourceIcon>
it_const_accelerators
using LIEF::PE::ResourcesManager::it_const_accelerators = const_ref_iterator<accelerators_t>
it_const_dialogs
using LIEF::PE::ResourcesManager::it_const_dialogs = const_ref_iterator<const dialogs_t&, const ResourceDialog*>
it_const_icons
using LIEF::PE::ResourcesManager::it_const_icons = const_ref_iterator<icons_t>
strings_table_t
using LIEF::PE::ResourcesManager::strings_table_t = std::vector<string_entry_t>
Member Enumeration Documentation
TYPE
enum class LIEF::PE::ResourcesManager::TYPE strong
The different types of resources From https://learn.microsoft.com/en-us/windows/win32/menurc/resource-types.
Enumerator
CURSOR
BITMAP
ICON
MENU
DIALOG
STRING
FONTDIR
FONT
ACCELERATOR
RCDATA
MESSAGETABLE
GROUP_CURSOR
GROUP_ICON
VERSION
DLGINCLUDE
PLUGPLAY
VXD
ANICURSOR
ANIICON
HTML
MANIFEST
Constructor & Destructor Documentation
ResourcesManager() [1/4]
LIEF::PE::ResourcesManager::ResourcesManager () delete
Referenced by get_node_type(), operator<<, operator=(), operator=(), ResourcesManager(), and ResourcesManager().
ResourcesManager() [2/4]
LIEF::PE::ResourcesManager::ResourcesManager (ResourceNode & rsrc) inline
ResourcesManager() [3/4]
LIEF::PE::ResourcesManager::ResourcesManager (const ResourcesManager & other) inline
References LIEF::Object::Object(), and ResourcesManager().
ResourcesManager() [4/4]
LIEF::PE::ResourcesManager::ResourcesManager (ResourcesManager &&) default
References ResourcesManager().
~ResourcesManager()
LIEF::PE::ResourcesManager::~ResourcesManager () override default
Member Function Documentation
accelerator()
it_const_accelerators LIEF::PE::ResourcesManager::accelerator () const
Return the list of the accelerator in the resource.
accept()
void LIEF::PE::ResourcesManager::accept (Visitor & visitor) const override virtual
Implements LIEF::Object.
add_icon()
void LIEF::PE::ResourcesManager::add_icon (const ResourceIcon & icon)
Add an icon to the resources.
change_icon()
void LIEF::PE::ResourcesManager::change_icon (const ResourceIcon & original, const ResourceIcon & newone)
dialogs()
it_const_dialogs LIEF::PE::ResourcesManager::dialogs () const
Return the list of the dialogs present in the resource.
get_node_type() [1/2]
ResourceNode * LIEF::PE::ResourcesManager::get_node_type (TYPE type) inline
Return the ResourceNode associated with the given TYPE or a nullptr if not found;.
References ResourcesManager().
Referenced by has_accelerator(), has_dialogs(), has_html(), has_icons(), has_manifest(), has_string_table(), has_type(), and has_version().
get_node_type() [2/2]
const ResourceNode * LIEF::PE::ResourcesManager::get_node_type (TYPE type) const
get_types()
std::vector< TYPE > LIEF::PE::ResourcesManager::get_types () const
List of TYPE present in the resources.
has_accelerator()
bool LIEF::PE::ResourcesManager::has_accelerator () const inline
true if the resources contain accelerator info
References ACCELERATOR, and get_node_type().
has_dialogs()
bool LIEF::PE::ResourcesManager::has_dialogs () const inline
true if resources contain dialogs
References DIALOG, and get_node_type().
has_html()
bool LIEF::PE::ResourcesManager::has_html () const inline
true if the resources contain html
References get_node_type(), and HTML.
has_icons()
bool LIEF::PE::ResourcesManager::has_icons () const inline
true if resources contain a LIEF::PE::ResourceIcon
References get_node_type(), GROUP_ICON, and ICON.
has_manifest()
bool LIEF::PE::ResourcesManager::has_manifest () const inline
true if resources contain the Manifest element
References get_node_type(), and MANIFEST.
has_string_table()
bool LIEF::PE::ResourcesManager::has_string_table () const inline
true if the resources contain a string table
References get_node_type(), and STRING.
has_type()
bool LIEF::PE::ResourcesManager::has_type (TYPE type) const inline
true if the resource has the given TYPE node
References get_node_type().
has_version()
bool LIEF::PE::ResourcesManager::has_version () const inline
true if resources a LIEF::PE::ResourceVersion
References get_node_type(), and VERSION.
html()
std::vector< std::string > LIEF::PE::ResourcesManager::html () const
Return the list of the html resources.
icons()
it_const_icons LIEF::PE::ResourcesManager::icons () const
Return the list of the icons present in the resources.
manifest() [1/2]
std::string LIEF::PE::ResourcesManager::manifest () const
Return the manifest as a std::string or an empty string if not found or corrupted.
Referenced by manifest().
manifest() [2/2]
void LIEF::PE::ResourcesManager::manifest (const std::string & manifest)
Change or set the manifest. If the manifest node path does not exist, all required nodes are created.
References manifest().
operator=() [1/2]
ResourcesManager & LIEF::PE::ResourcesManager::operator= (const ResourcesManager & other) inline
References LIEF::Object::operator=(), and ResourcesManager().
operator=() [2/2]
ResourcesManager & LIEF::PE::ResourcesManager::operator= (ResourcesManager &&) default
References ResourcesManager().
print()
std::string LIEF::PE::ResourcesManager::print (uint32_t depth = 0) const
Print the resource tree to the given depth.
string_table()
strings_table_t LIEF::PE::ResourcesManager::string_table () const
Return the list of the strings embedded in the string table (RT_STRING).
version()
std::vector< ResourceVersion > LIEF::PE::ResourcesManager::version () const
Return a list of verison info (VS_VERSIONINFO).
The documentation for this class was generated from the following file:
ResourcesManager.hpp