LIEF: Library to Instrument Executable Formats: LIEF::ScopedStream Class Reference
LIEF::ScopedStream Class Reference
#include <BinaryStream.hpp>
Public Member Functions
ScopedStream (const ScopedStream &)=delete
ScopedStream & operator= (const ScopedStream &)=delete
ScopedStream (ScopedStream &&)=delete
ScopedStream & operator= (ScopedStream &&)=delete
ScopedStream (BinaryStream &stream, uint64_t pos)
ScopedStream (BinaryStream &stream)
~ScopedStream ()
BinaryStream * operator-> ()
BinaryStream & operator* ()
const BinaryStream & operator* () const
Constructor & Destructor Documentation
ScopedStream() [1/4]
LIEF::ScopedStream::ScopedStream (const ScopedStream &) delete
References ScopedStream().
Referenced by operator=(), operator=(), ScopedStream(), and ScopedStream().
ScopedStream() [2/4]
LIEF::ScopedStream::ScopedStream (ScopedStream &&) delete
References ScopedStream().
ScopedStream() [3/4]
LIEF::ScopedStream::ScopedStream (BinaryStream & stream, uint64_t pos) inline explicit
References LIEF::BinaryStream::setpos().
ScopedStream() [4/4]
LIEF::ScopedStream::ScopedStream (BinaryStream & stream) inline explicit
~ScopedStream()
LIEF::ScopedStream::~ScopedStream () inline
Member Function Documentation
operator*() [1/2]
BinaryStream & LIEF::ScopedStream::operator* () inline
operator*() [2/2]
const BinaryStream & LIEF::ScopedStream::operator* () const inline
operator->()
BinaryStream * LIEF::ScopedStream::operator-> () inline
operator=() [1/2]
ScopedStream & LIEF::ScopedStream::operator= (const ScopedStream &) delete
References ScopedStream().
operator=() [2/2]
ScopedStream & LIEF::ScopedStream::operator= (ScopedStream &&) delete
References ScopedStream().
The documentation for this class was generated from the following file:
BinaryStream.hpp