LIEF: Library to Instrument Executable Formats: LIEF::dwarf::editor::Function::Parameter Class Reference
LIEF::dwarf::editor::Function::Parameter Class Reference
This class represents a parameter of the current function (DW_TAG_formal_parameter).
#include <Function.hpp>
Public Member Functions
Parameter ()=delete
Parameter (std::unique_ptr< details::FunctionParameter > impl)
~Parameter ()
Parameter & assign_register (const std::string &name)
Assign this parameter to a specific named register.
Parameter & assign_register (uint64_t reg)
Assign this parameter to the given DWARF register id (e.g. DW_OP_reg0).
Detailed Description
This class represents a parameter of the current function (DW_TAG_formal_parameter).
Constructor & Destructor Documentation
Parameter() [1/2]
LIEF::dwarf::editor::Function::Parameter::Parameter () delete
Referenced by assign_register(), and assign_register().
Parameter() [2/2]
LIEF::dwarf::editor::Function::Parameter::Parameter (std::unique_ptr< details::FunctionParameter > impl)
~Parameter()
LIEF::dwarf::editor::Function::Parameter::~Parameter ()
Member Function Documentation
assign_register() [1/2]
Parameter & LIEF::dwarf::editor::Function::Parameter::assign_register (const std::string & name)
Assign this parameter to a specific named register.
References Parameter().
assign_register() [2/2]
Parameter & LIEF::dwarf::editor::Function::Parameter::assign_register (uint64_t reg)
Assign this parameter to the given DWARF register id (e.g. DW_OP_reg0).
References Parameter().
The documentation for this class was generated from the following file:
DWARF/editor/Function.hpp