LIEF: Library to Instrument Executable Formats: LIEF::PE::ResourceDialog::Item Class Reference
LIEF::PE::ResourceDialog::Item Class Reference abstract
This class represents an element of the dialog. It can be for instance, a button, or a caption.
#include <ResourceDialog.hpp>
Public Types
enum class WINDOW_CLASS : uint32_t {
BUTTON = 0x0080 , EDIT = 0x0081 , STATIC = 0x0082 , LIST_BOX = 0x0083 ,
SCROLL_BAR = 0x0084 , COMBO_BOX = 0x0085
}
Public Member Functions
Item ()=default
Item (const Item &)=default
Item & operator= (const Item &)=default
Item (Item &&)=default
Item & operator= (Item &&)=default
uint32_t style () const
The style of the control. This can be a combination of WINDOW_STYLES or CONTROL_STYLES.
uint32_t extended_style () const
The extended styles for a window. This member is not used to create controls in dialog boxes, but applications that use dialog box templates can use it to create other types of windows.
int32_t id () const
The control identifier.
bool has (WINDOW_STYLES style) const
Check if this item has the given WINDOW_STYLES.
bool has (CONTROL_STYLES style) const
Check if this item has the given CONTROL_STYLES.
std::vector< WINDOW_STYLES > window_styles () const
List of WINDOW_STYLES used by this item.
std::vector< CONTROL_STYLES > control_styles () const
List of CONTROL_STYLES used by this item.
int16_t x () const
The x-coordinate, in dialog box units, of the upper-left corner of the control. This coordinate is always relative to the upper-left corner of the dialog box's client area.
int16_t y () const
The y-coordinate, in dialog box units, of the upper-left corner of the control. This coordinate is always relative to the upper-left corner of the dialog box's client area.
int16_t cx () const
The width, in dialog box units, of the control.
int16_t cy () const
The height, in dialog box units, of the control.
Item & style (uint32_t value)
Item & extended_style (uint32_t value)
Item & x (int16_t value)
Item & y (int16_t value)
Item & cx (int16_t value)
Item & cy (int16_t value)
Item & id (int32_t value)
Item & data (std::vector< uint8_t > creation_data)
Item & clazz (std::u16string title)
Item & clazz (uint16_t ord)
Item & title (std::u16string value)
Item & title (uint16_t ord)
const ordinal_or_str_t & clazz () const
Window class of the control. This can be either: a string that specifies the name of a registered window class or an ordinal value of a predefined system class.
const ordinal_or_str_t & title () const
Title of the item which can be either: a string that specifies the initial text or an ordinal value of a resource, such as an icon, in an executable file.
span< const uint8_t > creation_data () const
Creation data that is passed to the control's window procedure.
span< uint8_t > creation_data ()
virtual ~Item ()=default
virtual std::string to_string () const =0
Detailed Description
This class represents an element of the dialog. It can be for instance, a button, or a caption.
This class is inherited by the regular or extended dialog's item:
ResourceDialogRegular::Item
ResourceDialogExtended::Item
Member Enumeration Documentation
WINDOW_CLASS
enum class LIEF::PE::ResourceDialog::Item::WINDOW_CLASS : uint32_t strong
Enumerator
BUTTON
EDIT
STATIC
LIST_BOX
SCROLL_BAR
COMBO_BOX
Constructor & Destructor Documentation
Item() [1/3]
LIEF::PE::ResourceDialog::Item::Item () default
Referenced by clazz(), clazz(), cx(), cy(), data(), extended_style(), id(), Item(), Item(), operator<<, operator=(), operator=(), style(), title(), title(), x(), and y().
Item() [2/3]
LIEF::PE::ResourceDialog::Item::Item (const Item &) default
References Item().
Item() [3/3]
LIEF::PE::ResourceDialog::Item::Item (Item &&) default
References Item().
~Item()
virtual LIEF::PE::ResourceDialog::Item::~Item () virtual default
Reimplemented in LIEF::PE::ResourceDialogExtended::Item, and LIEF::PE::ResourceDialogRegular::Item.
Member Function Documentation
clazz() [1/3]
const ordinal_or_str_t & LIEF::PE::ResourceDialog::Item::clazz () const inline
Window class of the control. This can be either: a string that specifies the name of a registered window class or an ordinal value of a predefined system class.
clazz() [2/3]
Item & LIEF::PE::ResourceDialog::Item::clazz (std::u16string title) inline
References Item(), make_error_code(), not_found, and title().
clazz() [3/3]
Item & LIEF::PE::ResourceDialog::Item::clazz (uint16_t ord) inline
References Item().
control_styles()
std::vector< CONTROL_STYLES > LIEF::PE::ResourceDialog::Item::control_styles () const
List of CONTROL_STYLES used by this item.
creation_data() [1/2]
span< uint8_t > LIEF::PE::ResourceDialog::Item::creation_data () inline
creation_data() [2/2]
span< const uint8_t > LIEF::PE::ResourceDialog::Item::creation_data () const inline
Creation data that is passed to the control's window procedure.
Referenced by data().
cx() [1/2]
int16_t LIEF::PE::ResourceDialog::Item::cx () const inline
The width, in dialog box units, of the control.
cx() [2/2]
Item & LIEF::PE::ResourceDialog::Item::cx (int16_t value) inline
References Item().
cy() [1/2]
int16_t LIEF::PE::ResourceDialog::Item::cy () const inline
The height, in dialog box units, of the control.
cy() [2/2]
Item & LIEF::PE::ResourceDialog::Item::cy (int16_t value) inline
References Item().
data()
Item & LIEF::PE::ResourceDialog::Item::data (std::vector< uint8_t > creation_data) inline
References creation_data(), and Item().
extended_style() [1/2]
uint32_t LIEF::PE::ResourceDialog::Item::extended_style () const inline
The extended styles for a window. This member is not used to create controls in dialog boxes, but applications that use dialog box templates can use it to create other types of windows.
It can take a combination of WINDOW_EXTENDED_STYLES
extended_style() [2/2]
Item & LIEF::PE::ResourceDialog::Item::extended_style (uint32_t value) inline
References Item().
has() [1/2]
bool LIEF::PE::ResourceDialog::Item::has (CONTROL_STYLES style) const inline
Check if this item has the given CONTROL_STYLES.
References style().
has() [2/2]
bool LIEF::PE::ResourceDialog::Item::has (WINDOW_STYLES style) const inline
Check if this item has the given WINDOW_STYLES.
References style().
id() [1/2]
int32_t LIEF::PE::ResourceDialog::Item::id () const inline
The control identifier.
id() [2/2]
Item & LIEF::PE::ResourceDialog::Item::id (int32_t value) inline
References Item().
operator=() [1/2]
Item & LIEF::PE::ResourceDialog::Item::operator= (const Item &) default
References Item().
operator=() [2/2]
Item & LIEF::PE::ResourceDialog::Item::operator= (Item &&) default
References Item().
style() [1/2]
uint32_t LIEF::PE::ResourceDialog::Item::style () const inline
The style of the control. This can be a combination of WINDOW_STYLES or CONTROL_STYLES.
Referenced by has(), and has().
style() [2/2]
Item & LIEF::PE::ResourceDialog::Item::style (uint32_t value) inline
References Item().
title() [1/3]
const ordinal_or_str_t & LIEF::PE::ResourceDialog::Item::title () const inline
Title of the item which can be either: a string that specifies the initial text or an ordinal value of a resource, such as an icon, in an executable file.
title() [2/3]
Item & LIEF::PE::ResourceDialog::Item::title (std::u16string value) inline
References Item(), make_error_code(), and not_found.
Referenced by clazz().
title() [3/3]
Item & LIEF::PE::ResourceDialog::Item::title (uint16_t ord) inline
References Item().
to_string()
virtual std::string LIEF::PE::ResourceDialog::Item::to_string () const pure virtual
Implemented in LIEF::PE::ResourceDialogExtended::Item, and LIEF::PE::ResourceDialogRegular::Item.
Referenced by operator<<.
window_styles()
std::vector< WINDOW_STYLES > LIEF::PE::ResourceDialog::Item::window_styles () const
List of WINDOW_STYLES used by this item.
x() [1/2]
int16_t LIEF::PE::ResourceDialog::Item::x () const inline
The x-coordinate, in dialog box units, of the upper-left corner of the control. This coordinate is always relative to the upper-left corner of the dialog box's client area.
x() [2/2]
Item & LIEF::PE::ResourceDialog::Item::x (int16_t value) inline
References Item().
y() [1/2]
int16_t LIEF::PE::ResourceDialog::Item::y () const inline
The y-coordinate, in dialog box units, of the upper-left corner of the control. This coordinate is always relative to the upper-left corner of the dialog box's client area.
y() [2/2]
Item & LIEF::PE::ResourceDialog::Item::y (int16_t value) inline
References Item().
The documentation for this class was generated from the following file:
ResourceDialog.hpp