LIEF: Library to Instrument Executable Formats: LIEF::dwarf::editor::Function Class Reference
LIEF::dwarf::editor::Function Class Reference
This class represents an editable DWARF function (DW_TAG_subprogram).
#include <Function.hpp>
Classes
struct range_t
class Parameter
This class represents a parameter of the current function (DW_TAG_formal_parameter).
class LexicalBlock
This class mirrors the DW_TAG_lexical_block DWARF tag.
class Label
This class mirrors the DW_TAG_label DWARF tag.
Public Member Functions
Function ()=delete
Function (std::unique_ptr< details::Function > impl)
Function & set_address (uint64_t addr)
Set the address of this function by defining DW_AT_entry_pc.
Function & set_low_high (uint64_t low, uint64_t high)
Set the upper and lower bound addresses for this function. This assumes that the function is contiguous between low and high.
Function & set_ranges (const std::vector< range_t > &ranges)
Set the ranges of addresses owned by the implementation of this function by setting the DW_AT_ranges attribute.
Function & set_external ()
Set the function as external by defining DW_AT_external to true. This means that the function is imported by the current compilation unit.
Function & set_return_type (const Type &type)
Set the return type of this function.
std::unique_ptr< Parameter > add_parameter (const std::string &name, const Type &type)
Add a parameter to the current function.
std::unique_ptr< Variable > create_stack_variable (const std::string &name)
Create a stack-based variable owned by the current function.
std::unique_ptr< LexicalBlock > add_lexical_block (uint64_t start, uint64_t end)
Add a lexical block with the given range.
std::unique_ptr< Label > add_label (uint64_t addr, const std::string &label)
Add a label at the given address.
Function & add_description (const std::string &description)
Create a DW_AT_description entry with the description provided in parameter.
~Function ()
Detailed Description
This class represents an editable DWARF function (DW_TAG_subprogram).
Constructor & Destructor Documentation
Function() [1/2]
LIEF::dwarf::editor::Function::Function () delete
Referenced by add_description(), set_address(), set_external(), set_low_high(), set_ranges(), and set_return_type().
Function() [2/2]
LIEF::dwarf::editor::Function::Function (std::unique_ptr< details::Function > impl)
~Function()
LIEF::dwarf::editor::Function::~Function ()
Member Function Documentation
add_description()
Function & LIEF::dwarf::editor::Function::add_description (const std::string & description)
Create a DW_AT_description entry with the description provided in parameter.
References Function().
add_label()
std::unique_ptr< Label > LIEF::dwarf::editor::Function::add_label (uint64_t addr, const std::string & label)
Add a label at the given address.
add_lexical_block()
std::unique_ptr< LexicalBlock > LIEF::dwarf::editor::Function::add_lexical_block (uint64_t start, uint64_t end)
Add a lexical block with the given range.
add_parameter()
std::unique_ptr< Parameter > LIEF::dwarf::editor::Function::add_parameter (const std::string & name, const Type & type)
Add a parameter to the current function.
create_stack_variable()
std::unique_ptr< Variable > LIEF::dwarf::editor::Function::create_stack_variable (const std::string & name)
Create a stack-based variable owned by the current function.
set_address()
Function & LIEF::dwarf::editor::Function::set_address (uint64_t addr)
Set the address of this function by defining DW_AT_entry_pc.
References Function().
set_external()
Function & LIEF::dwarf::editor::Function::set_external ()
Set the function as external by defining DW_AT_external to true. This means that the function is imported by the current compilation unit.
References Function().
set_low_high()
Function & LIEF::dwarf::editor::Function::set_low_high (uint64_t low, uint64_t high)
Set the upper and lower bound addresses for this function. This assumes that the function is contiguous between low and high.
Underneath, the function defines DW_AT_low_pc and DW_AT_high_pc
References Function().
set_ranges()
Function & LIEF::dwarf::editor::Function::set_ranges (const std::vector< range_t > & ranges)
Set the ranges of addresses owned by the implementation of this function by setting the DW_AT_ranges attribute.
This setter should be used for non-contiguous function.
References Function().
set_return_type()
Function & LIEF::dwarf::editor::Function::set_return_type (const Type & type)
Set the return type of this function.
References Function().
The documentation for this class was generated from the following file:
DWARF/editor/Function.hpp