LIEF: Library to Instrument Executable Formats: LIEF::COFF::ParserConfig Class Reference
LIEF::COFF::ParserConfig Class Reference
Class used to configure the COFF parser.
#include <ParserConfig.hpp>
Static Public Member Functions
static const ParserConfig & default_conf ()
static const ParserConfig & all ()
Detailed Description
Class used to configure the COFF parser.
Member Function Documentation
all()
const ParserConfig & LIEF::COFF::ParserConfig::all () inline static
References default_conf().
default_conf()
const ParserConfig & LIEF::COFF::ParserConfig::default_conf () inline static
Referenced by all(), LIEF::COFF::Parser::parse(), and LIEF::COFF::Parser::parse().
The documentation for this class was generated from the following file:
COFF/ParserConfig.hpp