LIEF: Library to Instrument Executable Formats: LIEF::MachO::ThreadLocalVariables::Iterator Class Reference
LIEF::MachO::ThreadLocalVariables::Iterator Class Reference
Random-access iterator that materializes Thunk values on the fly from the raw section content.
#include <ThreadLocalVariables.hpp>
Public Member Functions
Iterator ()=default
Iterator (const ThreadLocalVariables &parent, size_t pos)
Iterator (const Iterator &)=default
Iterator & operator= (const Iterator &)=default
Iterator (Iterator &&) noexcept=default
Iterator & operator= (Iterator &&) noexcept=default
~Iterator ()=default
bool operator< (const Iterator &rhs) const
std::ptrdiff_t operator- (const Iterator &R) const
Iterator & operator+= (std::ptrdiff_t n)
Iterator & operator-= (std::ptrdiff_t n)
Thunk operator* () const
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::random_access_iterator_tag, const Thunk >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::random_access_iterator_tag, const Thunk >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Detailed Description
Random-access iterator that materializes Thunk values on the fly from the raw section content.
Constructor & Destructor Documentation
Iterator() [1/4]
LIEF::MachO::ThreadLocalVariables::Iterator::Iterator () default
Referenced by Iterator(), Iterator(), operator!=, operator+=(), operator-(), operator-=(), operator<(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/4]
LIEF::MachO::ThreadLocalVariables::Iterator::Iterator (const ThreadLocalVariables & parent, size_t pos) inline
References LIEF::MachO::ThreadLocalVariables::ThreadLocalVariables().
Iterator() [3/4]
LIEF::MachO::ThreadLocalVariables::Iterator::Iterator (const Iterator &) default
References Iterator().
Iterator() [4/4]
LIEF::MachO::ThreadLocalVariables::Iterator::Iterator (Iterator &&) default noexcept
References Iterator().
~Iterator()
LIEF::MachO::ThreadLocalVariables::Iterator::~Iterator () default
References Iterator().
Member Function Documentation
operator*()
Thunk LIEF::MachO::ThreadLocalVariables::Iterator::operator* () const inline
operator+=()
Iterator & LIEF::MachO::ThreadLocalVariables::Iterator::operator+= (std::ptrdiff_t n) inline
References Iterator().
operator-()
std::ptrdiff_t LIEF::MachO::ThreadLocalVariables::Iterator::operator- (const Iterator & R) const inline
References Iterator().
operator-=()
Iterator & LIEF::MachO::ThreadLocalVariables::Iterator::operator-= (std::ptrdiff_t n) inline
References Iterator().
operator<()
bool LIEF::MachO::ThreadLocalVariables::Iterator::operator< (const Iterator & rhs) const inline
References Iterator().
operator=() [1/2]
Iterator & LIEF::MachO::ThreadLocalVariables::Iterator::operator= (const Iterator &) default
References Iterator().
operator=() [2/2]
Iterator & LIEF::MachO::ThreadLocalVariables::Iterator::operator= (Iterator &&) default noexcept
References Iterator().
The documentation for this class was generated from the following file:
ThreadLocalVariables.hpp