LIEF: Library to Instrument Executable Formats: LIEF::dwarf::Type Class Reference
LIEF::dwarf::Type Class Reference
This class represents a DWARF Type which includes:
#include <Type.hpp>
Classes
class Iterator
Public Types
enum class KIND {
UNKNOWN = 0 , UNSPECIFIED , BASE , CONST_KIND ,
CLASS , ARRAY , POINTER , STRUCT ,
UNION , TYPEDEF , REF , SET_TYPE ,
STRING , SUBROUTINE , POINTER_MEMBER , PACKED ,
FILE , THROWN , VOLATILE , RESTRICT ,
INTERFACE , SHARED , RVALREF , TEMPLATE_ALIAS ,
COARRAY , DYNAMIC , ATOMIC , IMMUTABLE ,
ENUM
}
Public Member Functions
Type (std::unique_ptr< details::Type > impl)
Type (details::Type &impl)
Type (const Type &)=delete
Type & operator= (const Type &)=delete
Type (Type &&) noexcept
Type & operator= (Type &&) noexcept
virtual ~Type ()
KIND kind () const
bool is_unspecified () const
Whether this type is a DW_TAG_unspecified_type.
result< std::string > name () const
Return the type's name using either DW_AT_name or DW_AT_picture_string (if any).
result< uint64_t > size () const
Return the size of the type or an error if it can't be computed.
debug_location_t location () const
Return the debug location where this type is defined.
std::unique_ptr< Scope > scope () const
Return the scope in which this type is defined.
std::string to_decl (const DeclOpt &opt=DeclOpt()) const
Generates a C/C++ definition for this type.
template<class T>
const T * as () const
Static Public Member Functions
static std::unique_ptr< Type > create (std::unique_ptr< details::Type > impl)
Detailed Description
This class represents a DWARF Type which includes:
DW_TAG_array_type
DW_TAG_atomic_type
DW_TAG_base_type
DW_TAG_class_type
DW_TAG_coarray_type
DW_TAG_const_type
DW_TAG_dynamic_type
DW_TAG_enumeration_type
DW_TAG_file_type
DW_TAG_immutable_type
DW_TAG_interface_type
DW_TAG_packed_type
DW_TAG_pointer_type
DW_TAG_ptr_to_member_type
DW_TAG_reference_type
DW_TAG_restrict_type
DW_TAG_rvalue_reference_type
DW_TAG_set_type
DW_TAG_shared_type
DW_TAG_string_type
DW_TAG_structure_type
DW_TAG_subroutine_type
DW_TAG_template_alias
DW_TAG_thrown_type
DW_TAG_typedef
DW_TAG_union_type
DW_TAG_unspecified_type
DW_TAG_volatile_type
Member Enumeration Documentation
KIND
enum class LIEF::dwarf::Type::KIND strong
Enumerator
UNKNOWN
UNSPECIFIED
BASE
CONST_KIND
CLASS
ARRAY
POINTER
STRUCT
UNION
TYPEDEF
REF
SET_TYPE
STRING
SUBROUTINE
POINTER_MEMBER
PACKED
FILE
THROWN
VOLATILE
RESTRICT
INTERFACE
SHARED
RVALREF
TEMPLATE_ALIAS
COARRAY
DYNAMIC
ATOMIC
IMMUTABLE
ENUM
Constructor & Destructor Documentation
Type() [1/4]
LIEF::dwarf::Type::Type (std::unique_ptr< details::Type > impl)
References LIEF_LOCAL.
Referenced by LIEF::dwarf::types::Array::Array(), LIEF::dwarf::types::Atomic::Atomic(), LIEF::dwarf::types::Base::Base(), LIEF::dwarf::types::ClassLike::ClassLike(), LIEF::dwarf::types::Array::classof(), LIEF::dwarf::types::Atomic::classof(), LIEF::dwarf::types::Base::classof(), LIEF::dwarf::types::Class::classof(), LIEF::dwarf::types::ClassLike::classof(), LIEF::dwarf::types::Coarray::classof(), LIEF::dwarf::types::Const::classof(), LIEF::dwarf::types::Dynamic::classof(), LIEF::dwarf::types::Enum::classof(), LIEF::dwarf::types::File::classof(), LIEF::dwarf::types::Immutable::classof(), LIEF::dwarf::types::Interface::classof(), LIEF::dwarf::types::Packed::classof(), LIEF::dwarf::types::Pointer::classof(), LIEF::dwarf::types::PointerToMember::classof(), LIEF::dwarf::types::Reference::classof(), LIEF::dwarf::types::Restrict::classof(), LIEF::dwarf::types::RValueReference::classof(), LIEF::dwarf::types::SetTy::classof(), LIEF::dwarf::types::Shared::classof(), LIEF::dwarf::types::StringTy::classof(), LIEF::dwarf::types::Structure::classof(), LIEF::dwarf::types::Subroutine::classof(), LIEF::dwarf::types::TemplateAlias::classof(), LIEF::dwarf::types::Thrown::classof(), LIEF::dwarf::types::Typedef::classof(), LIEF::dwarf::types::Union::classof(), LIEF::dwarf::types::Volatile::classof(), LIEF::dwarf::types::Coarray::Coarray(), LIEF::dwarf::types::Const::Const(), LIEF::dwarf::types::Dynamic::Dynamic(), LIEF::dwarf::types::Enum::Enum(), LIEF::dwarf::types::File::File(), LIEF::dwarf::types::Immutable::Immutable(), LIEF::dwarf::types::Interface::Interface(), LIEF::dwarf::Type::Iterator::operator*(), LIEF::dwarf::types::Array::operator*(), LIEF::dwarf::types::Atomic::operator*(), LIEF::dwarf::types::Const::operator*(), LIEF::dwarf::types::Immutable::operator*(), LIEF::dwarf::types::Pointer::operator*(), LIEF::dwarf::types::PointerToMember::operator*(), LIEF::dwarf::types::Reference::operator*(), LIEF::dwarf::types::Restrict::operator*(), LIEF::dwarf::types::RValueReference::operator*(), LIEF::dwarf::types::SetTy::operator*(), LIEF::dwarf::types::Shared::operator*(), LIEF::dwarf::types::TemplateAlias::operator*(), LIEF::dwarf::types::Thrown::operator*(), LIEF::dwarf::types::Typedef::operator*(), LIEF::dwarf::types::Volatile::operator*(), LIEF::dwarf::Type::Iterator::operator->(), LIEF::dwarf::types::Array::operator->(), LIEF::dwarf::types::Atomic::operator->(), LIEF::dwarf::types::Const::operator->(), LIEF::dwarf::types::Immutable::operator->(), LIEF::dwarf::types::Pointer::operator->(), LIEF::dwarf::types::PointerToMember::operator->(), LIEF::dwarf::types::Reference::operator->(), LIEF::dwarf::types::Restrict::operator->(), LIEF::dwarf::types::RValueReference::operator->(), LIEF::dwarf::types::SetTy::operator->(), LIEF::dwarf::types::Shared::operator->(), LIEF::dwarf::types::TemplateAlias::operator->(), LIEF::dwarf::types::Thrown::operator->(), LIEF::dwarf::types::Typedef::operator->(), LIEF::dwarf::types::Volatile::operator->(), operator=(), operator=(), LIEF::dwarf::types::Pointer::Pointer(), LIEF::dwarf::types::PointerToMember::PointerToMember(), LIEF::dwarf::types::Reference::Reference(), LIEF::dwarf::types::Restrict::Restrict(), LIEF::dwarf::types::Subroutine::return_type(), LIEF::dwarf::types::RValueReference::RValueReference(), LIEF::dwarf::types::SetTy::SetTy(), LIEF::dwarf::types::Shared::Shared(), LIEF::dwarf::types::StringTy::StringTy(), LIEF::dwarf::types::Subroutine::Subroutine(), LIEF::dwarf::types::TemplateAlias::TemplateAlias(), LIEF::dwarf::types::Thrown::Thrown(), Type(), Type(), LIEF::dwarf::types::Typedef::Typedef(), LIEF::dwarf::types::Array::underlying_type(), LIEF::dwarf::types::Atomic::underlying_type(), LIEF::dwarf::types::Const::underlying_type(), LIEF::dwarf::types::Enum::underlying_type(), LIEF::dwarf::types::Immutable::underlying_type(), LIEF::dwarf::types::Pointer::underlying_type(), LIEF::dwarf::types::PointerToMember::underlying_type(), LIEF::dwarf::types::Reference::underlying_type(), LIEF::dwarf::types::Restrict::underlying_type(), LIEF::dwarf::types::RValueReference::underlying_type(), LIEF::dwarf::types::SetTy::underlying_type(), LIEF::dwarf::types::Shared::underlying_type(), LIEF::dwarf::types::TemplateAlias::underlying_type(), LIEF::dwarf::types::Thrown::underlying_type(), LIEF::dwarf::types::Typedef::underlying_type(), LIEF::dwarf::types::Volatile::underlying_type(), LIEF::dwarf::types::Volatile::Volatile(), and ~Type().
Type() [2/4]
LIEF::dwarf::Type::Type (details::Type & impl)
References LIEF_LOCAL.
Type() [3/4]
LIEF::dwarf::Type::Type (const Type &) delete
References Type().
Type() [4/4]
LIEF::dwarf::Type::Type (Type &&) noexcept
References Type().
~Type()
virtual LIEF::dwarf::Type::~Type () virtual
References Type().
Member Function Documentation
as()
template<class T> const T * LIEF::dwarf::Type::as () const inline
create()
std::unique_ptr< Type > LIEF::dwarf::Type::create (std::unique_ptr< details::Type > impl) static
is_unspecified()
bool LIEF::dwarf::Type::is_unspecified () const inline
Whether this type is a DW_TAG_unspecified_type.
References kind(), and UNSPECIFIED.
kind()
KIND LIEF::dwarf::Type::kind () const
Referenced by LIEF::dwarf::types::Array::classof(), LIEF::dwarf::types::ClassLike::classof(), LIEF::dwarf::types::TemplateAlias::classof(), LIEF::dwarf::types::Thrown::classof(), LIEF::dwarf::types::Typedef::classof(), LIEF::dwarf::types::Volatile::classof(), and is_unspecified().
location()
debug_location_t LIEF::dwarf::Type::location () const
Return the debug location where this type is defined.
name()
result< std::string > LIEF::dwarf::Type::name () const
Return the type's name using either DW_AT_name or DW_AT_picture_string (if any).
operator=() [1/2]
Type & LIEF::dwarf::Type::operator= (const Type &) delete
References Type().
operator=() [2/2]
Type & LIEF::dwarf::Type::operator= (Type &&) noexcept
References Type().
scope()
std::unique_ptr< Scope > LIEF::dwarf::Type::scope () const
Return the scope in which this type is defined.
size()
result< uint64_t > LIEF::dwarf::Type::size () const
Return the size of the type or an error if it can't be computed.
This size should match the equivalent of sizeof(Type).
to_decl()
std::string LIEF::dwarf::Type::to_decl (const DeclOpt & opt = DeclOpt()) const
Generates a C/C++ definition for this type.
The documentation for this class was generated from the following file:
DWARF/Type.hpp