LIEF: Library to Instrument Executable Formats: LIEF::PE::ResourceStringFileInfo Class Reference
LIEF::PE::ResourceStringFileInfo Class Reference
Representation of the StringFileInfo structure.
#include <ResourceStringFileInfo.hpp>
Public Types
using elements_t = std::vector<ResourceStringTable>
using it_const_elements = const_ref_iterator<const elements_t&>
using it_elements = ref_iterator<elements_t&>
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Public Member Functions
ResourceStringFileInfo ()=default
ResourceStringFileInfo (const ResourceStringFileInfo &)=default
ResourceStringFileInfo & operator= (const ResourceStringFileInfo &)=default
ResourceStringFileInfo (ResourceStringFileInfo &&)=default
ResourceStringFileInfo & operator= (ResourceStringFileInfo &&)=default
~ResourceStringFileInfo () override=default
uint16_t type () const
The type of data in the version resource.
const std::u16string & key () const
Signature of the structure. Must be the unicode string "StringFileInfo".
it_const_elements children () const
Iterator over the children values.
it_elements children ()
std::string key_u8 () const
The key as an utf8 string.
ResourceStringFileInfo & type (uint16_t type)
ResourceStringFileInfo & key (std::u16string key)
void add_child (ResourceStringTable table)
void accept (Visitor &visitor) const override
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Static Public Member Functions
static result< ResourceStringFileInfo > parse (BinaryStream &stream)
Detailed Description
Representation of the StringFileInfo structure.
It contains version information that can be displayed for a particular language and code page.
See: https://learn.microsoft.com/en-us/windows/win32/menurc/stringfileinfo
Member Typedef Documentation
elements_t
using LIEF::PE::ResourceStringFileInfo::elements_t = std::vector<ResourceStringTable>
it_const_elements
using LIEF::PE::ResourceStringFileInfo::it_const_elements = const_ref_iterator<const elements_t&>
it_elements
using LIEF::PE::ResourceStringFileInfo::it_elements = ref_iterator<elements_t&>
Constructor & Destructor Documentation
ResourceStringFileInfo() [1/3]
LIEF::PE::ResourceStringFileInfo::ResourceStringFileInfo () default
Referenced by key(), operator<<, operator=(), operator=(), ResourceStringFileInfo(), ResourceStringFileInfo(), and type().
ResourceStringFileInfo() [2/3]
LIEF::PE::ResourceStringFileInfo::ResourceStringFileInfo (const ResourceStringFileInfo &) default
References ResourceStringFileInfo().
ResourceStringFileInfo() [3/3]
LIEF::PE::ResourceStringFileInfo::ResourceStringFileInfo (ResourceStringFileInfo &&) default
References ResourceStringFileInfo().
~ResourceStringFileInfo()
LIEF::PE::ResourceStringFileInfo::~ResourceStringFileInfo () override default
Member Function Documentation
accept()
void LIEF::PE::ResourceStringFileInfo::accept (Visitor & visitor) const override virtual
Implements LIEF::Object.
References LIEF_API.
add_child()
void LIEF::PE::ResourceStringFileInfo::add_child (ResourceStringTable table) inline
children() [1/2]
it_elements LIEF::PE::ResourceStringFileInfo::children () inline
children() [2/2]
it_const_elements LIEF::PE::ResourceStringFileInfo::children () const inline
Iterator over the children values.
key() [1/2]
const std::u16string & LIEF::PE::ResourceStringFileInfo::key () const inline
Signature of the structure. Must be the unicode string "StringFileInfo".
Referenced by key().
key() [2/2]
ResourceStringFileInfo & LIEF::PE::ResourceStringFileInfo::key (std::u16string key) inline
References key(), and ResourceStringFileInfo().
key_u8()
std::string LIEF::PE::ResourceStringFileInfo::key_u8 () const
The key as an utf8 string.
operator=() [1/2]
ResourceStringFileInfo & LIEF::PE::ResourceStringFileInfo::operator= (const ResourceStringFileInfo &) default
References ResourceStringFileInfo().
operator=() [2/2]
ResourceStringFileInfo & LIEF::PE::ResourceStringFileInfo::operator= (ResourceStringFileInfo &&) default
References ResourceStringFileInfo().
parse()
result< ResourceStringFileInfo > LIEF::PE::ResourceStringFileInfo::parse (BinaryStream & stream) static
type() [1/2]
uint16_t LIEF::PE::ResourceStringFileInfo::type () const inline
The type of data in the version resource.
1 if it contains text data
0 if it contains binary data
Referenced by type().
type() [2/2]
ResourceStringFileInfo & LIEF::PE::ResourceStringFileInfo::type (uint16_t type) inline
References ResourceStringFileInfo(), and type().
The documentation for this class was generated from the following file:
ResourceStringFileInfo.hpp