LIEF: Library to Instrument Executable Formats: LIEF::assembly::powerpc::Operand::Iterator Class Reference
LIEF::assembly::powerpc::Operand::Iterator Class Reference final
Forward iterator that lazily disassembles powerpc Operand.
#include <Operand.hpp>
Public Types
using implementation = details::OperandIt
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, Operand, std::ptrdiff_t, const Operand *, const Operand & >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Public Member Functions
Iterator ()
Iterator (std::unique_ptr< details::OperandIt > impl)
Iterator (const Iterator &)
Iterator & operator= (const Iterator &)
Iterator (Iterator &&) noexcept
Iterator & operator= (Iterator &&) noexcept
~Iterator ()
Iterator & operator++ ()
const Operand & operator* () const
const Operand * operator-> () const
std::unique_ptr< Operand > yield ()
Transfer ownership of the operand at the current position to the caller. Returns nullptr if the iterator is past-the-end.
DerivedT operator++ (int)
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, Operand, std::ptrdiff_t, const Operand *, const Operand & >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Detailed Description
Forward iterator that lazily disassembles powerpc Operand.
Member Typedef Documentation
implementation
using LIEF::assembly::powerpc::Operand::Iterator::implementation = details::OperandIt
Constructor & Destructor Documentation
Iterator() [1/4]
LIEF::assembly::powerpc::Operand::Iterator::Iterator ()
References LIEF_API.
Referenced by Iterator(), Iterator(), operator!=, operator++(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/4]
LIEF::assembly::powerpc::Operand::Iterator::Iterator (std::unique_ptr< details::OperandIt > impl)
References LIEF_API.
Iterator() [3/4]
LIEF::assembly::powerpc::Operand::Iterator::Iterator (const Iterator &)
References Iterator(), and LIEF_API.
Iterator() [4/4]
LIEF::assembly::powerpc::Operand::Iterator::Iterator (Iterator &&) noexcept
References Iterator(), and LIEF_API.
~Iterator()
LIEF::assembly::powerpc::Operand::Iterator::~Iterator ()
References Iterator(), and LIEF_API.
Member Function Documentation
operator*()
const Operand & LIEF::assembly::powerpc::Operand::Iterator::operator* () const
References LIEF_API, and LIEF_LIFETIMEBOUND.
operator++() [1/2]
Iterator & LIEF::assembly::powerpc::Operand::Iterator::operator++ ()
References Iterator(), LIEF_API, and LIEF_LIFETIMEBOUND.
operator++() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator++ (int) inline
operator->()
const Operand * LIEF::assembly::powerpc::Operand::Iterator::operator-> () const
References LIEF_API, and LIEF_LIFETIMEBOUND.
operator=() [1/2]
Iterator & LIEF::assembly::powerpc::Operand::Iterator::operator= (const Iterator &)
References Iterator(), and LIEF_API.
operator=() [2/2]
Iterator & LIEF::assembly::powerpc::Operand::Iterator::operator= (Iterator &&) noexcept
References Iterator(), and LIEF_API.
yield()
std::unique_ptr< Operand > LIEF::assembly::powerpc::Operand::Iterator::yield ()
Transfer ownership of the operand at the current position to the caller. Returns nullptr if the iterator is past-the-end.
References LIEF_API, and yield().
Referenced by yield().
The documentation for this class was generated from the following file:
powerpc/Operand.hpp