LIEF: Library to Instrument Executable Formats: LIEF::pdb::types::Attribute::Iterator Class Reference
LIEF::pdb::types::Attribute::Iterator Class Reference final
#include <Attribute.hpp>
Public Types
using implementation = details::AttributeIt
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, Attribute, std::ptrdiff_t, const Attribute *, const Attribute & >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Public Member Functions
Iterator ()
Iterator (std::unique_ptr< details::AttributeIt > impl)
Iterator (const Iterator &)
Iterator & operator= (const Iterator &)
Iterator (Iterator &&) noexcept
Iterator & operator= (Iterator &&) noexcept
~Iterator ()
Iterator & operator++ ()
const Attribute & operator* () const
const Attribute * operator-> () const
std::unique_ptr< Attribute > yield ()
Transfer ownership of the attribute at the current position to the caller. Returns nullptr if the iterator is past-the-end.
DerivedT operator++ (int)
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::forward_iterator_tag, Attribute, std::ptrdiff_t, const Attribute *, const Attribute & >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Member Typedef Documentation
implementation
using LIEF::pdb::types::Attribute::Iterator::implementation = details::AttributeIt
Constructor & Destructor Documentation
Iterator() [1/4]
LIEF::pdb::types::Attribute::Iterator::Iterator ()
References LIEF_API.
Referenced by Iterator(), Iterator(), operator!=, operator++(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/4]
LIEF::pdb::types::Attribute::Iterator::Iterator (std::unique_ptr< details::AttributeIt > impl)
References LIEF_API.
Iterator() [3/4]
LIEF::pdb::types::Attribute::Iterator::Iterator (const Iterator &)
References Iterator(), and LIEF_API.
Iterator() [4/4]
LIEF::pdb::types::Attribute::Iterator::Iterator (Iterator &&) noexcept
References Iterator(), and LIEF_API.
~Iterator()
LIEF::pdb::types::Attribute::Iterator::~Iterator ()
References Iterator(), and LIEF_API.
Member Function Documentation
operator*()
const Attribute & LIEF::pdb::types::Attribute::Iterator::operator* () const
References LIEF::pdb::types::Attribute::Attribute(), LIEF_API, and LIEF_LIFETIMEBOUND.
operator++() [1/2]
Iterator & LIEF::pdb::types::Attribute::Iterator::operator++ ()
References Iterator(), and LIEF_API.
operator++() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator++ (int) inline
operator->()
const Attribute * LIEF::pdb::types::Attribute::Iterator::operator-> () const
References LIEF::pdb::types::Attribute::Attribute(), LIEF_API, and LIEF_LIFETIMEBOUND.
operator=() [1/2]
Iterator & LIEF::pdb::types::Attribute::Iterator::operator= (const Iterator &)
References Iterator(), and LIEF_API.
operator=() [2/2]
Iterator & LIEF::pdb::types::Attribute::Iterator::operator= (Iterator &&) noexcept
References Iterator(), and LIEF_API.
yield()
std::unique_ptr< Attribute > LIEF::pdb::types::Attribute::Iterator::yield ()
Transfer ownership of the attribute at the current position to the caller. Returns nullptr if the iterator is past-the-end.
References LIEF::pdb::types::Attribute::Attribute(), LIEF_API, and yield().
Referenced by yield().
The documentation for this class was generated from the following file:
PDB/types/Attribute.hpp