LIEF: Library to Instrument Executable Formats: LIEF::details::canbe_unique< T > Class Template Reference
LIEF::details::canbe_unique< T > Class Template Reference
#include <canbe_unique.hpp>
Public Member Functions
canbe_unique ()=default
canbe_unique (const canbe_unique &)=delete
canbe_unique & operator= (const canbe_unique &)=delete
canbe_unique & operator= (std::nullptr_t)
canbe_unique (canbe_unique &&other) noexcept
canbe_unique & operator= (canbe_unique &&other) noexcept
canbe_unique (T &ptr)
canbe_unique (const T &ptr)
canbe_unique (std::unique_ptr< T > unique_ptr)
T * get ()
const T * get () const
T * operator-> ()
const T * operator-> () const
T & operator* ()
const T & operator* () const
void reset ()
operator bool () const
~canbe_unique ()
Constructor & Destructor Documentation
canbe_unique() [1/6]
template<class T > LIEF::details::canbe_unique< T >::canbe_unique () default
Referenced by canbe_unique(), canbe_unique(), operator=(), operator=(), and operator=().
canbe_unique() [2/6]
template<class T > LIEF::details::canbe_unique< T >::canbe_unique (const canbe_unique< T > &) delete
References canbe_unique().
canbe_unique() [3/6]
template<class T > LIEF::details::canbe_unique< T >::canbe_unique (canbe_unique< T > && other) inline noexcept
References canbe_unique().
canbe_unique() [4/6]
template<class T > LIEF::details::canbe_unique< T >::canbe_unique (T & ptr) inline
canbe_unique() [5/6]
template<class T > LIEF::details::canbe_unique< T >::canbe_unique (const T & ptr) inline
canbe_unique() [6/6]
template<class T > LIEF::details::canbe_unique< T >::canbe_unique (std::unique_ptr< T > unique_ptr) inline
~canbe_unique()
template<class T > LIEF::details::canbe_unique< T >::~canbe_unique () inline
References reset().
Member Function Documentation
get() [1/2]
template<class T > T * LIEF::details::canbe_unique< T >::get () inline
get() [2/2]
template<class T > const T * LIEF::details::canbe_unique< T >::get () const inline
operator bool()
template<class T > LIEF::details::canbe_unique< T >::operator bool () const inline
operator*() [1/2]
template<class T > T & LIEF::details::canbe_unique< T >::operator* () inline
operator*() [2/2]
template<class T > const T & LIEF::details::canbe_unique< T >::operator* () const inline
operator->() [1/2]
template<class T > T * LIEF::details::canbe_unique< T >::operator-> () inline
operator->() [2/2]
template<class T > const T * LIEF::details::canbe_unique< T >::operator-> () const inline
operator=() [1/3]
template<class T > canbe_unique & LIEF::details::canbe_unique< T >::operator= (canbe_unique< T > && other) inline noexcept
References canbe_unique().
operator=() [2/3]
template<class T > canbe_unique & LIEF::details::canbe_unique< T >::operator= (const canbe_unique< T > &) delete
References canbe_unique().
operator=() [3/3]
template<class T > canbe_unique & LIEF::details::canbe_unique< T >::operator= (std::nullptr_t) inline
References canbe_unique(), and reset().
reset()
template<class T > void LIEF::details::canbe_unique< T >::reset () inline
Referenced by operator=(), and ~canbe_unique().
The documentation for this class was generated from the following file:
canbe_unique.hpp