LIEF: Library to Instrument Executable Formats: LIEF::PE::SpcIndirectData Class Reference
LIEF::PE::SpcIndirectData Class Reference
#include <SpcIndirectData.hpp>
Public Member Functions
SpcIndirectData ()
SpcIndirectData (const SpcIndirectData &)=default
SpcIndirectData & operator= (const SpcIndirectData &)=default
std::unique_ptr< Content > clone () const override
ALGORITHMS digest_algorithm () const
Digest used to hash the file.
span< const uint8_t > digest () const
PE's authentihash.
const std::string & file () const
const std::string & url () const
void print (std::ostream &os) const override
void accept (Visitor &visitor) const override
~SpcIndirectData () override=default
Public Member Functions inherited from LIEF::PE::ContentInfo::Content
Content (oid_t oid)
const oid_t & content_type () const
template<class T>
const T * cast () const
template<class T>
T * cast ()
~Content () override=default
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Static Public Member Functions
static bool classof (const ContentInfo::Content *content)
Static Public Attributes
static constexpr auto SPC_INDIRECT_DATA_OBJID = "1.3.6.1.4.1.311.2.1.4"
Additional Inherited Members
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Constructor & Destructor Documentation
SpcIndirectData() [1/2]
LIEF::PE::SpcIndirectData::SpcIndirectData () inline
References LIEF::PE::ContentInfo::Content::Content(), and SPC_INDIRECT_DATA_OBJID.
Referenced by clone(), operator<<, operator=(), and SpcIndirectData().
SpcIndirectData() [2/2]
LIEF::PE::SpcIndirectData::SpcIndirectData (const SpcIndirectData &) default
References SpcIndirectData().
~SpcIndirectData()
LIEF::PE::SpcIndirectData::~SpcIndirectData () override default
Member Function Documentation
accept()
void LIEF::PE::SpcIndirectData::accept (Visitor & visitor) const override virtual
Implements LIEF::Object.
classof()
bool LIEF::PE::SpcIndirectData::classof (const ContentInfo::Content * content) inline static
References LIEF::PE::ContentInfo::Content::content_type(), and SPC_INDIRECT_DATA_OBJID.
clone()
std::unique_ptr< Content > LIEF::PE::SpcIndirectData::clone () const inline override virtual
Implements LIEF::PE::ContentInfo::Content.
References SpcIndirectData().
digest()
span< const uint8_t > LIEF::PE::SpcIndirectData::digest () const inline
PE's authentihash.
See also
LIEF::PE::Binary::authentihash
digest_algorithm()
ALGORITHMS LIEF::PE::SpcIndirectData::digest_algorithm () const inline
Digest used to hash the file.
It should match LIEF::PE::SignerInfo::digest_algorithm
file()
const std::string & LIEF::PE::SpcIndirectData::file () const inline
operator=()
SpcIndirectData & LIEF::PE::SpcIndirectData::operator= (const SpcIndirectData &) default
References SpcIndirectData().
print()
void LIEF::PE::SpcIndirectData::print (std::ostream & os) const override virtual
Implements LIEF::PE::ContentInfo::Content.
Referenced by operator<<.
url()
const std::string & LIEF::PE::SpcIndirectData::url () const inline
Member Data Documentation
SPC_INDIRECT_DATA_OBJID
auto LIEF::PE::SpcIndirectData::SPC_INDIRECT_DATA_OBJID = "1.3.6.1.4.1.311.2.1.4" static constexpr
Referenced by classof(), and SpcIndirectData().
The documentation for this class was generated from the following file:
SpcIndirectData.hpp