LIEF: Library to Instrument Executable Formats: LIEF::PE::DynamicFixupUnknown Class Reference
LIEF::PE::DynamicFixupUnknown Class Reference
This class represents an special dynamic relocation where the format of the fixups is not supported by LIEF.
#include <DynamicFixupUnknown.hpp>
Public Member Functions
DynamicFixupUnknown (std::vector< uint8_t > payload)
DynamicFixupUnknown (const DynamicFixupUnknown &)=default
DynamicFixupUnknown & operator= (const DynamicFixupUnknown &)=default
DynamicFixupUnknown (DynamicFixupUnknown &&)=default
DynamicFixupUnknown & operator= (DynamicFixupUnknown &&)=default
std::unique_ptr< DynamicFixup > clone () const override
std::string to_string () const override
span< const uint8_t > payload () const
Raw fixups.
span< uint8_t > payload ()
~DynamicFixupUnknown () override=default
Public Member Functions inherited from LIEF::PE::DynamicFixup
DynamicFixup ()=delete
DynamicFixup (KIND kind)
DynamicFixup (const DynamicFixup &)=default
DynamicFixup & operator= (const DynamicFixup &)=default
DynamicFixup (DynamicFixup &&)=default
DynamicFixup & operator= (DynamicFixup &&)=default
KIND kind () const
Encoding of the fixups.
template<class T>
T * as ()
template<class T>
const T * as () const
virtual ~DynamicFixup ()=default
Static Public Member Functions
static bool classof (const DynamicFixup *fixup)
Additional Inherited Members
Public Types inherited from LIEF::PE::DynamicFixup
enum KIND {
UNKNOWN = 0 , GENERIC , ARM64X , FUNCTION_OVERRIDE ,
ARM64_KERNEL_IMPORT_CALL_TRANSFER , GUARD_IMPORT_CONTROL_TRANSFER
}
Detailed Description
This class represents an special dynamic relocation where the format of the fixups is not supported by LIEF.
Constructor & Destructor Documentation
DynamicFixupUnknown() [1/3]
LIEF::PE::DynamicFixupUnknown::DynamicFixupUnknown (std::vector< uint8_t > payload) inline
References LIEF::PE::DynamicFixup::DynamicFixup(), payload(), and LIEF::PE::DynamicFixup::UNKNOWN.
Referenced by clone(), DynamicFixupUnknown(), DynamicFixupUnknown(), operator=(), and operator=().
DynamicFixupUnknown() [2/3]
LIEF::PE::DynamicFixupUnknown::DynamicFixupUnknown (const DynamicFixupUnknown &) default
References DynamicFixupUnknown().
DynamicFixupUnknown() [3/3]
LIEF::PE::DynamicFixupUnknown::DynamicFixupUnknown (DynamicFixupUnknown &&) default
References DynamicFixupUnknown().
~DynamicFixupUnknown()
LIEF::PE::DynamicFixupUnknown::~DynamicFixupUnknown () override default
Member Function Documentation
classof()
bool LIEF::PE::DynamicFixupUnknown::classof (const DynamicFixup * fixup) inline static
References LIEF::PE::DynamicFixup::DynamicFixup(), LIEF::PE::DynamicFixup::kind(), and LIEF::PE::DynamicFixup::UNKNOWN.
clone()
std::unique_ptr< DynamicFixup > LIEF::PE::DynamicFixupUnknown::clone () const inline override virtual
Implements LIEF::PE::DynamicFixup.
References DynamicFixupUnknown().
operator=() [1/2]
DynamicFixupUnknown & LIEF::PE::DynamicFixupUnknown::operator= (const DynamicFixupUnknown &) default
References DynamicFixupUnknown().
operator=() [2/2]
DynamicFixupUnknown & LIEF::PE::DynamicFixupUnknown::operator= (DynamicFixupUnknown &&) default
References DynamicFixupUnknown().
payload() [1/2]
span< uint8_t > LIEF::PE::DynamicFixupUnknown::payload () inline
payload() [2/2]
span< const uint8_t > LIEF::PE::DynamicFixupUnknown::payload () const inline
Raw fixups.
Referenced by DynamicFixupUnknown().
to_string()
std::string LIEF::PE::DynamicFixupUnknown::to_string () const inline override virtual
Implements LIEF::PE::DynamicFixup.
The documentation for this class was generated from the following file:
DynamicFixupUnknown.hpp