LIEF: Library to Instrument Executable Formats: LIEF::COFF::AuxiliaryCLRToken Class Reference
LIEF::COFF::AuxiliaryCLRToken Class Reference
Auxiliary symbol associated with the CLR_TOKEN storage class.
#include <AuxiliaryCLRToken.hpp>
Public Member Functions
AuxiliaryCLRToken ()
AuxiliaryCLRToken (uint8_t aux_type, uint8_t reserved, uint32_t symbol_idx, std::vector< uint8_t > rgb_reserved)
AuxiliaryCLRToken (const AuxiliaryCLRToken &)=default
AuxiliaryCLRToken & operator= (const AuxiliaryCLRToken &)=default
AuxiliaryCLRToken (AuxiliaryCLRToken &&)=default
AuxiliaryCLRToken & operator= (AuxiliaryCLRToken &&)=default
std::unique_ptr< AuxiliarySymbol > clone () const override
uint8_t aux_type () const
IMAGE_AUX_SYMBOL_TYPE which should be IMAGE_AUX_SYMBOL_TYPE_TOKEN_DEF (1)
uint8_t reserved () const
Reserved value (should be 0).
uint32_t symbol_idx () const
Index in the symbol table.
const Symbol * symbol () const
Symbol referenced by symbol_idx() (if resolved).
Symbol * symbol ()
span< const uint8_t > rgb_reserved () const
Reserved (padding) values. Should be 0.
std::string to_string () const override
~AuxiliaryCLRToken () override=default
Public Member Functions inherited from LIEF::COFF::AuxiliarySymbol
AuxiliarySymbol ()=default
AuxiliarySymbol (std::vector< uint8_t > payload)
AuxiliarySymbol (const AuxiliarySymbol &)=default
AuxiliarySymbol & operator= (const AuxiliarySymbol &)=default
AuxiliarySymbol (AuxiliarySymbol &&)=default
AuxiliarySymbol & operator= (AuxiliarySymbol &&)=default
AuxiliarySymbol (TYPE ty)
TYPE type () const
span< const uint8_t > payload () const
For unknown type only, return the raw representation of this symbol.
span< uint8_t > payload ()
virtual ~AuxiliarySymbol ()=default
template<class T>
const T * as () const
Helper to downcast a AuxiliarySymbol into a concrete implementation.
template<class T>
T * as ()
Static Public Member Functions
static std::unique_ptr< AuxiliaryCLRToken > parse (const std::vector< uint8_t > &payload)
static bool classof (const AuxiliarySymbol *sym)
Static Public Member Functions inherited from LIEF::COFF::AuxiliarySymbol
static std::unique_ptr< AuxiliarySymbol > parse (Symbol &sym, std::vector< uint8_t > payload)
static TYPE get_aux_type (const Symbol &sym)
Additional Inherited Members
Public Types inherited from LIEF::COFF::AuxiliarySymbol
enum class TYPE {
UNKNOWN = 0 , CLR_TOKEN , FUNC_DEF , BF_AND_EF ,
WEAK_EXTERNAL , FILE , SEC_DEF
}
Type discriminator for the subclasses.
Detailed Description
Auxiliary symbol associated with the CLR_TOKEN storage class.
Constructor & Destructor Documentation
AuxiliaryCLRToken() [1/4]
LIEF::COFF::AuxiliaryCLRToken::AuxiliaryCLRToken () inline
References LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol().
Referenced by AuxiliaryCLRToken(), AuxiliaryCLRToken(), clone(), operator=(), and operator=().
AuxiliaryCLRToken() [2/4]
LIEF::COFF::AuxiliaryCLRToken::AuxiliaryCLRToken (uint8_t aux_type, uint8_t reserved, uint32_t symbol_idx, std::vector< uint8_t > rgb_reserved) inline
References aux_type(), LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol(), reserved(), rgb_reserved(), and symbol_idx().
AuxiliaryCLRToken() [3/4]
LIEF::COFF::AuxiliaryCLRToken::AuxiliaryCLRToken (const AuxiliaryCLRToken &) default
References AuxiliaryCLRToken().
AuxiliaryCLRToken() [4/4]
LIEF::COFF::AuxiliaryCLRToken::AuxiliaryCLRToken (AuxiliaryCLRToken &&) default
References AuxiliaryCLRToken().
~AuxiliaryCLRToken()
LIEF::COFF::AuxiliaryCLRToken::~AuxiliaryCLRToken () override default
Member Function Documentation
aux_type()
uint8_t LIEF::COFF::AuxiliaryCLRToken::aux_type () const inline
IMAGE_AUX_SYMBOL_TYPE which should be IMAGE_AUX_SYMBOL_TYPE_TOKEN_DEF (1)
Referenced by AuxiliaryCLRToken().
classof()
bool LIEF::COFF::AuxiliaryCLRToken::classof (const AuxiliarySymbol * sym) inline static
References LIEF::COFF::AuxiliarySymbol::AuxiliarySymbol(), LIEF::COFF::AuxiliarySymbol::CLR_TOKEN, and LIEF::COFF::AuxiliarySymbol::type().
clone()
std::unique_ptr< AuxiliarySymbol > LIEF::COFF::AuxiliaryCLRToken::clone () const inline override virtual
Reimplemented from LIEF::COFF::AuxiliarySymbol.
References AuxiliaryCLRToken().
operator=() [1/2]
AuxiliaryCLRToken & LIEF::COFF::AuxiliaryCLRToken::operator= (AuxiliaryCLRToken &&) default
References AuxiliaryCLRToken().
operator=() [2/2]
AuxiliaryCLRToken & LIEF::COFF::AuxiliaryCLRToken::operator= (const AuxiliaryCLRToken &) default
References AuxiliaryCLRToken().
parse()
std::unique_ptr< AuxiliaryCLRToken > LIEF::COFF::AuxiliaryCLRToken::parse (const std::vector< uint8_t > & payload) static
References LIEF::COFF::AuxiliarySymbol::payload().
reserved()
uint8_t LIEF::COFF::AuxiliaryCLRToken::reserved () const inline
Reserved value (should be 0).
Referenced by AuxiliaryCLRToken().
rgb_reserved()
span< const uint8_t > LIEF::COFF::AuxiliaryCLRToken::rgb_reserved () const inline
Reserved (padding) values. Should be 0.
Referenced by AuxiliaryCLRToken().
symbol() [1/2]
Symbol * LIEF::COFF::AuxiliaryCLRToken::symbol () inline
symbol() [2/2]
const Symbol * LIEF::COFF::AuxiliaryCLRToken::symbol () const inline
Symbol referenced by symbol_idx() (if resolved).
symbol_idx()
uint32_t LIEF::COFF::AuxiliaryCLRToken::symbol_idx () const inline
Index in the symbol table.
Referenced by AuxiliaryCLRToken().
to_string()
std::string LIEF::COFF::AuxiliaryCLRToken::to_string () const override virtual
Reimplemented from LIEF::COFF::AuxiliarySymbol.
The documentation for this class was generated from the following file:
AuxiliaryCLRToken.hpp