LIEF: Library to Instrument Executable Formats: LIEF::PE::Relocation Class Reference
LIEF::PE::Relocation Class Reference
Class which represents the Base Relocation Block We usually find this structure in the .reloc section.
#include <Relocation.hpp>
Public Types
using entries_t = std::vector<std::unique_ptr<RelocationEntry>>
using it_entries = ref_iterator<entries_t&, RelocationEntry*>
using it_const_entries = const_ref_iterator<const entries_t&, RelocationEntry*>
using relocations_t = std::vector<std::unique_ptr<Relocation>>
Public Types inherited from LIEF::Object
template<class T>
using output_t = add_pointer_t<decay_t<T>>
template<class T>
using output_const_t = add_pointer_t<add_const_t<decay_t<T>>>
Public Member Functions
Relocation ()
Relocation (uint32_t base, uint32_t block_size)
Relocation (uint32_t base)
Relocation (const Relocation &other)
Relocation & operator= (Relocation other)
Relocation (Relocation &&)
Relocation & operator= (Relocation &&other)
Relocation (const details::pe_base_relocation_block &header)
~Relocation () override
void swap (Relocation &other)
uint32_t virtual_address () const
The RVA for which the offset of the relocation entries (RelocationEntry) is added.
uint32_t block_size () const
The total number of bytes in the base relocation block.
it_const_entries entries () const
Iterator over the RelocationEntry.
it_entries entries ()
void virtual_address (uint32_t virtual_address)
void block_size (uint32_t block_size)
RelocationEntry & add_entry (const RelocationEntry &entry)
void accept (Visitor &visitor) const override
Public Member Functions inherited from LIEF::Object
Object ()
Object (const Object &other)
Object & operator= (const Object &other)
Object (Object &&other) noexcept=default
Object & operator= (Object &&other) noexcept=default
template<class T>
output_t< T > as ()
template<class T>
output_const_t< T > as () const
virtual bool operator== (const Object &other) const
virtual bool operator!= (const Object &other) const
virtual ~Object ()
Static Public Member Functions
static relocations_t parse (Parser &ctx, BinaryStream &stream)
Detailed Description
Class which represents the Base Relocation Block We usually find this structure in the .reloc section.
Member Typedef Documentation
entries_t
using LIEF::PE::Relocation::entries_t = std::vector<std::unique_ptr<RelocationEntry>>
it_const_entries
using LIEF::PE::Relocation::it_const_entries = const_ref_iterator<const entries_t&, RelocationEntry*>
it_entries
using LIEF::PE::Relocation::it_entries = ref_iterator<entries_t&, RelocationEntry*>
relocations_t
using LIEF::PE::Relocation::relocations_t = std::vector<std::unique_ptr<Relocation>>
Constructor & Destructor Documentation
Relocation() [1/6]
LIEF::PE::Relocation::Relocation ()
Referenced by operator<<, operator=(), operator=(), Relocation(), Relocation(), and swap().
Relocation() [2/6]
LIEF::PE::Relocation::Relocation (uint32_t base, uint32_t block_size)
References block_size().
Relocation() [3/6]
LIEF::PE::Relocation::Relocation (uint32_t base)
Relocation() [4/6]
LIEF::PE::Relocation::Relocation (const Relocation & other)
References Relocation().
Relocation() [5/6]
LIEF::PE::Relocation::Relocation (Relocation &&)
References Relocation().
Relocation() [6/6]
LIEF::PE::Relocation::Relocation (const details::pe_base_relocation_block & header)
~Relocation()
LIEF::PE::Relocation::~Relocation () override
Member Function Documentation
accept()
void LIEF::PE::Relocation::accept (Visitor & visitor) const override virtual
Implements LIEF::Object.
add_entry()
RelocationEntry & LIEF::PE::Relocation::add_entry (const RelocationEntry & entry)
block_size() [1/2]
uint32_t LIEF::PE::Relocation::block_size () const inline
The total number of bytes in the base relocation block.
block_size = sizeof(BaseRelocationBlock) +
             nb_of_relocs * sizeof(uint16_t = RelocationEntry)
Referenced by block_size(), and Relocation().
block_size() [2/2]
void LIEF::PE::Relocation::block_size (uint32_t block_size) inline
References block_size().
entries() [1/2]
it_entries LIEF::PE::Relocation::entries () inline
entries() [2/2]
it_const_entries LIEF::PE::Relocation::entries () const inline
Iterator over the RelocationEntry.
operator=() [1/2]
Relocation & LIEF::PE::Relocation::operator= (Relocation && other)
References Relocation().
operator=() [2/2]
Relocation & LIEF::PE::Relocation::operator= (Relocation other)
References Relocation().
parse()
relocations_t LIEF::PE::Relocation::parse (Parser & ctx, BinaryStream & stream) static
References LIEF_LOCAL, and Parser.
swap()
void LIEF::PE::Relocation::swap (Relocation & other)
References Relocation().
virtual_address() [1/2]
uint32_t LIEF::PE::Relocation::virtual_address () const inline
The RVA for which the offset of the relocation entries (RelocationEntry) is added.
Referenced by virtual_address().
virtual_address() [2/2]
void LIEF::PE::Relocation::virtual_address (uint32_t virtual_address) inline
References virtual_address().
The documentation for this class was generated from the following file:
PE/Relocation.hpp