LIEF: Library to Instrument Executable Formats: LIEF::DEX::Parser Class Reference
LIEF::DEX::Parser Class Reference
Class which parses a DEX file to produce a DEX::File object.
#include <Parser.hpp>
Public Member Functions
Parser & operator= (const Parser &copy)=delete
Parser (const Parser &copy)=delete
Static Public Member Functions
static std::unique_ptr< File > parse (const std::string &file)
Parse the DEX file from the file path given in parameter.
static std::unique_ptr< File > parse (std::vector< uint8_t > data, const std::string &name="")
Detailed Description
Class which parses a DEX file to produce a DEX::File object.
Constructor & Destructor Documentation
Parser()
LIEF::DEX::Parser::Parser (const Parser & copy) delete
References Parser(), and LIEF::DEX::version().
Referenced by operator=(), and Parser().
Member Function Documentation
operator=()
Parser & LIEF::DEX::Parser::operator= (const Parser & copy) delete
References Parser().
parse() [1/2]
std::unique_ptr< File > LIEF::DEX::Parser::parse (const std::string & file) static
Parse the DEX file from the file path given in parameter.
parse() [2/2]
std::unique_ptr< File > LIEF::DEX::Parser::parse (std::vector< uint8_t > data, const std::string & name = "") static
The documentation for this class was generated from the following file:
DEX/Parser.hpp