LIEF: Library to Instrument Executable Formats: LIEF::objc::IVar::Iterator Class Reference
LIEF::objc::IVar::Iterator Class Reference final
#include <IVar.hpp>
Public Types
using implementation = details::IVarIt
Public Types inherited from LIEF::iterator_facade_base< Iterator, std::bidirectional_iterator_tag, IVar, std::ptrdiff_t, const IVar *, const IVar & >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Public Member Functions
Iterator ()
Iterator (std::unique_ptr< details::IVarIt > impl)
Iterator (const Iterator &)
Iterator & operator= (const Iterator &)
Iterator (Iterator &&) noexcept
Iterator & operator= (Iterator &&) noexcept
~Iterator ()
Iterator & operator++ ()
Iterator & operator-- ()
const IVar & operator* () const
const IVar * operator-> () const
std::unique_ptr< IVar > yield ()
Transfer ownership of the ivar at the current position to the caller. Returns nullptr if the iterator is past-the-end.
DerivedT operator++ (int)
DerivedT operator-- (int)
Public Member Functions inherited from LIEF::iterator_facade_base< Iterator, std::bidirectional_iterator_tag, IVar, std::ptrdiff_t, const IVar *, const IVar & >
Iterator operator+ (std::ptrdiff_t n) const
Iterator operator- (std::ptrdiff_t n) const
Iterator & operator++ ()
Iterator & operator-- ()
bool operator!= (const Iterator &RHS) const
bool operator> (const Iterator &RHS) const
bool operator<= (const Iterator &RHS) const
bool operator>= (const Iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Member Typedef Documentation
implementation
using LIEF::objc::IVar::Iterator::implementation = details::IVarIt
Constructor & Destructor Documentation
Iterator() [1/4]
LIEF::objc::IVar::Iterator::Iterator ()
References LIEF_API.
Referenced by Iterator(), Iterator(), operator!=, operator++(), operator--(), operator=(), operator=(), operator==, and ~Iterator().
Iterator() [2/4]
LIEF::objc::IVar::Iterator::Iterator (std::unique_ptr< details::IVarIt > impl)
References LIEF_API.
Iterator() [3/4]
LIEF::objc::IVar::Iterator::Iterator (const Iterator &)
References Iterator(), and LIEF_API.
Iterator() [4/4]
LIEF::objc::IVar::Iterator::Iterator (Iterator &&) noexcept
References Iterator(), and LIEF_API.
~Iterator()
LIEF::objc::IVar::Iterator::~Iterator ()
References Iterator(), and LIEF_API.
Member Function Documentation
operator*()
const IVar & LIEF::objc::IVar::Iterator::operator* () const
References LIEF::objc::IVar::IVar(), and LIEF_API.
operator++() [1/2]
Iterator & LIEF::objc::IVar::Iterator::operator++ ()
References Iterator(), and LIEF_API.
operator++() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator++ (int) inline
operator--() [1/2]
Iterator & LIEF::objc::IVar::Iterator::operator-- ()
References Iterator(), and LIEF_API.
operator--() [2/2]
DerivedT LIEF::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator-- (int) inline
operator->()
const IVar * LIEF::objc::IVar::Iterator::operator-> () const
References LIEF::objc::IVar::IVar(), and LIEF_API.
operator=() [1/2]
Iterator & LIEF::objc::IVar::Iterator::operator= (const Iterator &)
References Iterator(), and LIEF_API.
operator=() [2/2]
Iterator & LIEF::objc::IVar::Iterator::operator= (Iterator &&) noexcept
References Iterator(), and LIEF_API.
yield()
std::unique_ptr< IVar > LIEF::objc::IVar::Iterator::yield ()
Transfer ownership of the ivar at the current position to the caller. Returns nullptr if the iterator is past-the-end.
References LIEF_API.
The documentation for this class was generated from the following file:
IVar.hpp