LIEF: Library to Instrument Executable Formats: errors.hpp File Reference
errors.hpp File Reference
#include <cstdint>
#include <LIEF/third-party/expected.hpp>
Classes
struct LIEF::ok_t
Opaque structure used by ok_error_t.
Namespaces
namespace LIEF
LIEF namespace.
Typedefs
template<typename T >
using LIEF::result = tl::expected<T, lief_errors>
Wrapper that contains an Object (T) or an error.
using LIEF::ok_error_t = result<ok_t>
Opaque structure that is used by LIEF to avoid writing result<void> f(...). Instead, it makes the output explicit such as:
Enumerations
enum class lief_errors : uint32_t {
read_error = 1 , not_found , not_implemented , not_supported ,
corrupted , conversion_error , read_out_of_bound , asn1_bad_tag ,
file_error , file_format_error , parsing_error , build_error ,
data_too_large , require_extended_version
}
LIEF error codes definition.
Functions
const char * to_string (lief_errors err)
tl::unexpected< lief_errors > make_error_code (lief_errors e)
Create an standard error code from lief_errors.
template<class T >
lief_errors LIEF::get_error (result< T > &err)
Get the error code associated with the result.
template<class T >
lief_errors LIEF::as_lief_err (result< T > &err)
Return the lief_errors when the provided result<T> is an error.
ok_t LIEF::ok ()
Return success for function with return type ok_error_t.
bool LIEF::is_ok (const ok_error_t &val)
bool LIEF::is_err (const ok_error_t &val)
Enumeration Type Documentation
lief_errors
enum class lief_errors : uint32_t strong
LIEF error codes definition.
Enumerator
read_error
not_found
not_implemented
not_supported
corrupted
conversion_error
read_out_of_bound
asn1_bad_tag
file_error
file_format_error
parsing_error
build_error
data_too_large
require_extended_version
Function Documentation
make_error_code()
tl::unexpected< lief_errors > make_error_code (lief_errors e) inline
Create an standard error code from lief_errors.
Referenced by LIEF::PE::ResourceDialog::Item::clazz(), LIEF::Binary::get_int_from_virtual_address(), LIEF::ELF::Binary::get_section_idx(), LIEF::ELF::Binary::get_section_idx(), LIEF::PE::ResourceDialog::menu(), LIEF::nullopt(), LIEF::BinaryStream::peek(), LIEF::BinaryStream::peek_array(), LIEF::BinaryStream::peek_data(), LIEF::BinaryStream::peek_in(), LIEF::FileStream::peek_in(), LIEF::BinaryStream::peek_objects_at(), LIEF::BinaryStream::read_array(), LIEF::FileStream::read_at(), LIEF::BinaryStream::read_data(), LIEF::BinaryStream::read_objects(), LIEF::SpanStream::slice(), LIEF::SpanStream::slice(), LIEF::PE::ResourceDialog::Item::title(), LIEF::PE::ResourceDialog::window_class(), and LIEF::SpanStream::~SpanStream().
to_string()
const char * to_string (lief_errors err)
Referenced by LIEF::PE::ResourceAccelerator::ansi_str().