LIEF: Library to Instrument Executable Formats: LIEF::ELF::ParserConfig Struct Reference
LIEF::ELF::ParserConfig Struct Reference
This structure is used to tweak the ELF Parser (ELF::Parser).
#include <ParserConfig.hpp>
Public Types
enum class DYNSYM_COUNT { AUTO = 0 , SECTION = 1 , HASH = 2 , RELOCATIONS = 3 }
Static Public Member Functions
static ParserConfig all ()
This returns a ParserConfig object configured to process all the ELF elements.
Public Attributes
bool parse_relocations = true
Whether relocations (including plt-like relocations) should be parsed.
bool parse_dyn_symbols = true
Whether dynamic symbols (those from .dynsym) should be parsed.
bool parse_symtab_symbols = true
Whether debug symbols (those from .symtab) should be parsed.
bool parse_symbol_versions = true
Whether versioning symbols should be parsed.
bool parse_notes = true
Whether ELF notes information should be parsed.
bool parse_overlay = true
Whether the overlay data should be parsed.
DYNSYM_COUNT count_mtd = DYNSYM_COUNT::AUTO
uint64_t page_size = 0
Memory page size if the binary uses a non-standard value.
Detailed Description
This structure is used to tweak the ELF Parser (ELF::Parser).
Member Enumeration Documentation
DYNSYM_COUNT
enum class LIEF::ELF::ParserConfig::DYNSYM_COUNT strong
Methods that can be used by the LIEF::ELF::Parser to count the number of dynamic symbols
Enumerator
AUTO
Automatic detection
SECTION
Count based on sections (not very reliable)
HASH
Count based on hash table (reliable)
RELOCATIONS
Count based on PLT/GOT relocations (very reliable but not accurate)
Member Function Documentation
all()
ParserConfig LIEF::ELF::ParserConfig::all () inline static
This returns a ParserConfig object configured to process all the ELF elements.
Referenced by LIEF::ELF::Parser::parse(), LIEF::ELF::Parser::parse(), and LIEF::ELF::Parser::parse().
Member Data Documentation
count_mtd
DYNSYM_COUNT LIEF::ELF::ParserConfig::count_mtd = DYNSYM_COUNT::AUTO
The method used to count the number of dynamic symbols
page_size
uint64_t LIEF::ELF::ParserConfig::page_size = 0
Memory page size if the binary uses a non-standard value.
For instance, SPARCV9 binary can use page size from 0x2000 to 0x100000.
parse_dyn_symbols
bool LIEF::ELF::ParserConfig::parse_dyn_symbols = true
Whether dynamic symbols (those from .dynsym) should be parsed.
parse_notes
bool LIEF::ELF::ParserConfig::parse_notes = true
Whether ELF notes information should be parsed.
parse_overlay
bool LIEF::ELF::ParserConfig::parse_overlay = true
Whether the overlay data should be parsed.
parse_relocations
bool LIEF::ELF::ParserConfig::parse_relocations = true
Whether relocations (including plt-like relocations) should be parsed.
parse_symbol_versions
bool LIEF::ELF::ParserConfig::parse_symbol_versions = true
Whether versioning symbols should be parsed.
parse_symtab_symbols
bool LIEF::ELF::ParserConfig::parse_symtab_symbols = true
Whether debug symbols (those from .symtab) should be parsed.
The documentation for this struct was generated from the following file:
ELF/ParserConfig.hpp