LIEF: Library to Instrument Executable Formats: LIEF::runtime::windows::Host::version_t Struct Reference
LIEF::runtime::windows::Host::version_t Struct Reference
#include <Host.hpp>
Public Member Functions
version_t ()=default
version_t (uint32_t major, uint32_t minor, uint32_t build_number)
bool operator<= (const version_t &rhs) const
bool operator> (const version_t &rhs) const
bool operator>= (const version_t &rhs) const
bool operator< (const version_t &rhs) const
bool operator== (const version_t &other) const
bool operator!= (const version_t &other) const
std::string to_string () const
Public Attributes
uint32_t major = 0
uint32_t minor = 0
uint32_t build_number = 0
Constructor & Destructor Documentation
version_t() [1/2]
LIEF::runtime::windows::Host::version_t::version_t () default
Referenced by operator!=(), operator<(), operator<<, operator<=(), operator==(), operator>(), and operator>=().
version_t() [2/2]
LIEF::runtime::windows::Host::version_t::version_t (uint32_t major, uint32_t minor, uint32_t build_number) inline
References build_number, major, and minor.
Member Function Documentation
operator!=()
bool LIEF::runtime::windows::Host::version_t::operator!= (const version_t & other) const inline
References version_t().
operator<()
bool LIEF::runtime::windows::Host::version_t::operator< (const version_t & rhs) const inline
References version_t().
operator<=()
bool LIEF::runtime::windows::Host::version_t::operator<= (const version_t & rhs) const
References version_t().
operator==()
bool LIEF::runtime::windows::Host::version_t::operator== (const version_t & other) const
References version_t().
operator>()
bool LIEF::runtime::windows::Host::version_t::operator> (const version_t & rhs) const inline
References version_t().
operator>=()
bool LIEF::runtime::windows::Host::version_t::operator>= (const version_t & rhs) const
References version_t().
to_string()
std::string LIEF::runtime::windows::Host::version_t::to_string () const
Member Data Documentation
build_number
uint32_t LIEF::runtime::windows::Host::version_t::build_number = 0
Referenced by version_t().
major
uint32_t LIEF::runtime::windows::Host::version_t::major = 0
Referenced by version_t().
minor
uint32_t LIEF::runtime::windows::Host::version_t::minor = 0
Referenced by version_t().
The documentation for this struct was generated from the following file:
windows/Host.hpp