LIEF: Library to Instrument Executable Formats: LIEF::runtime::osx::Host::version_t Struct Reference
LIEF::runtime::osx::Host::version_t Struct Reference
#include <Host.hpp>
Public Member Functions
version_t (uint32_t major, uint32_t minor, uint32_t patch)
bool operator<= (const version_t &rhs) const
bool operator> (const version_t &rhs) const
bool operator>= (const version_t &rhs) const
bool operator< (const version_t &rhs) const
bool operator== (const version_t &other) const
bool operator!= (const version_t &other) const
std::string to_string () const
Static Public Member Functions
static const version_t & BigSur ()
static const version_t & Monterey ()
static const version_t & Ventura ()
static const version_t & Sonoma ()
static const version_t & Sequoia ()
static const version_t & Tahoe ()
Public Attributes
uint32_t major = 0
uint32_t minor = 0
uint32_t patch = 0
Constructor & Destructor Documentation
version_t()
LIEF::runtime::osx::Host::version_t::version_t (uint32_t major, uint32_t minor, uint32_t patch) inline
References major, minor, and patch.
Referenced by BigSur(), Monterey(), operator!=(), operator<(), operator<<, operator<=(), operator==(), operator>(), operator>=(), Sequoia(), Sonoma(), Tahoe(), and Ventura().
Member Function Documentation
BigSur()
const version_t & LIEF::runtime::osx::Host::version_t::BigSur () static
References version_t().
Monterey()
const version_t & LIEF::runtime::osx::Host::version_t::Monterey () static
References version_t().
operator!=()
bool LIEF::runtime::osx::Host::version_t::operator!= (const version_t & other) const inline
References version_t().
operator<()
bool LIEF::runtime::osx::Host::version_t::operator< (const version_t & rhs) const inline
References version_t().
operator<=()
bool LIEF::runtime::osx::Host::version_t::operator<= (const version_t & rhs) const
References version_t().
operator==()
bool LIEF::runtime::osx::Host::version_t::operator== (const version_t & other) const
References version_t().
operator>()
bool LIEF::runtime::osx::Host::version_t::operator> (const version_t & rhs) const inline
References version_t().
operator>=()
bool LIEF::runtime::osx::Host::version_t::operator>= (const version_t & rhs) const
References version_t().
Sequoia()
const version_t & LIEF::runtime::osx::Host::version_t::Sequoia () static
References version_t().
Sonoma()
const version_t & LIEF::runtime::osx::Host::version_t::Sonoma () static
References version_t().
Tahoe()
const version_t & LIEF::runtime::osx::Host::version_t::Tahoe () static
References version_t().
to_string()
std::string LIEF::runtime::osx::Host::version_t::to_string () const
Ventura()
const version_t & LIEF::runtime::osx::Host::version_t::Ventura () static
References version_t().
Member Data Documentation
major
uint32_t LIEF::runtime::osx::Host::version_t::major = 0
Referenced by version_t().
minor
uint32_t LIEF::runtime::osx::Host::version_t::minor = 0
Referenced by version_t().
patch
uint32_t LIEF::runtime::osx::Host::version_t::patch = 0
Referenced by version_t().
The documentation for this struct was generated from the following file:
osx/Host.hpp